ICT290 Assignment 1: C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/dependencies/SDL2/include/SDL.h File Reference
SDL.h File Reference
#include "SDL_main.h"
#include "SDL_stdinc.h"
#include "SDL_assert.h"
#include "SDL_atomic.h"
#include "SDL_audio.h"
#include "SDL_clipboard.h"
#include "SDL_cpuinfo.h"
#include "SDL_endian.h"
#include "SDL_error.h"
#include "SDL_events.h"
#include "SDL_filesystem.h"
#include "SDL_gamecontroller.h"
#include "SDL_haptic.h"
#include "SDL_hints.h"
#include "SDL_joystick.h"
#include "SDL_loadso.h"
#include "SDL_log.h"
#include "SDL_messagebox.h"
#include "SDL_metal.h"
#include "SDL_mutex.h"
#include "SDL_power.h"
#include "SDL_render.h"
#include "SDL_rwops.h"
#include "SDL_sensor.h"
#include "SDL_shape.h"
#include "SDL_system.h"
#include "SDL_thread.h"
#include "SDL_timer.h"
#include "SDL_version.h"
#include "SDL_video.h"
#include "begin_code.h"
#include "close_code.h"
SDL_INIT_*
These are the flags which may be passed to SDL_Init(). You should specify the subsystems which you will be using in your application.
#define SDL_INIT_TIMER 0x00000001u
#define SDL_INIT_AUDIO 0x00000010u
#define SDL_INIT_VIDEO 0x00000020u
#define SDL_INIT_JOYSTICK 0x00000200u
#define SDL_INIT_HAPTIC 0x00001000u
#define SDL_INIT_GAMECONTROLLER 0x00002000u
#define SDL_INIT_EVENTS 0x00004000u
#define SDL_INIT_SENSOR 0x00008000u
#define SDL_INIT_NOPARACHUTE 0x00100000u
#define SDL_INIT_EVERYTHING
DECLSPEC int SDLCALL SDL_Init (Uint32 flags)
DECLSPEC int SDLCALL SDL_InitSubSystem (Uint32 flags)
DECLSPEC void SDLCALL SDL_QuitSubSystem (Uint32 flags)
DECLSPEC Uint32 SDLCALL SDL_WasInit (Uint32 flags)
DECLSPEC void SDLCALL SDL_Quit (void)
Detailed Description
Main include header for the SDL library
Definition in file SDL.h.
Macro Definition Documentation
SDL_INIT_AUDIO
#define SDL_INIT_AUDIO 0x00000010u
Definition at line 79 of file SDL.h.
SDL_INIT_EVENTS
#define SDL_INIT_EVENTS 0x00004000u
Definition at line 84 of file SDL.h.
SDL_INIT_EVERYTHING
#define SDL_INIT_EVERYTHING
Value:
                ( \
                SDL_INIT_TIMER | SDL_INIT_AUDIO | SDL_INIT_VIDEO | SDL_INIT_EVENTS | \
                SDL_INIT_JOYSTICK | SDL_INIT_HAPTIC | SDL_INIT_GAMECONTROLLER | SDL_INIT_SENSOR \
            )
Definition at line 87 of file SDL.h.
SDL_INIT_GAMECONTROLLER
#define SDL_INIT_GAMECONTROLLER 0x00002000u
SDL_INIT_GAMECONTROLLER implies SDL_INIT_JOYSTICK
Definition at line 83 of file SDL.h.
SDL_INIT_HAPTIC
#define SDL_INIT_HAPTIC 0x00001000u
Definition at line 82 of file SDL.h.
SDL_INIT_JOYSTICK
#define SDL_INIT_JOYSTICK 0x00000200u
SDL_INIT_JOYSTICK implies SDL_INIT_EVENTS
Definition at line 81 of file SDL.h.
SDL_INIT_NOPARACHUTE
#define SDL_INIT_NOPARACHUTE 0x00100000u
compatibility; this flag is ignored.
Definition at line 86 of file SDL.h.
SDL_INIT_SENSOR
#define SDL_INIT_SENSOR 0x00008000u
Definition at line 85 of file SDL.h.
SDL_INIT_TIMER
#define SDL_INIT_TIMER 0x00000001u
Definition at line 78 of file SDL.h.
SDL_INIT_VIDEO
#define SDL_INIT_VIDEO 0x00000020u
SDL_INIT_VIDEO implies SDL_INIT_EVENTS
Definition at line 80 of file SDL.h.
Function Documentation
SDL_Init()
DECLSPEC int SDLCALL SDL_Init (Uint32 flags)
This function initializes the subsystems specified by flags
Referenced by CEasySound::CEasySound().
SDL_InitSubSystem()
DECLSPEC int SDLCALL SDL_InitSubSystem (Uint32 flags)
This function initializes specific SDL subsystems
Subsystem initialization is ref-counted, you must call SDL_QuitSubSystem() for each SDL_InitSubSystem() to correctly shutdown a subsystem manually (or call SDL_Quit() to force shutdown). If a subsystem is already loaded then this call will increase the ref-count and return.
SDL_Quit()
DECLSPEC void SDLCALL SDL_Quit (void)
This function cleans up all initialized subsystems. You should call it upon all exit conditions.
Referenced by CEasySound::CEasySound(), and CEasySound::~CEasySound().
SDL_QuitSubSystem()
DECLSPEC void SDLCALL SDL_QuitSubSystem (Uint32 flags)
This function cleans up specific SDL subsystems
SDL_WasInit()
DECLSPEC Uint32 SDLCALL SDL_WasInit (Uint32 flags)
This function returns a mask of the specified subsystems which have previously been initialized.
If flags is 0, it returns a mask of all initialized subsystems.