ICT290 Assignment 1: C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/dependencies/SDL2/include/SDL_opengl.h File Reference
SDL_opengl.h File Reference
#include "SDL_config.h"
#include "SDL_opengl_glext.h"
Macros
#define __gl_h_
#define GLAPI extern
#define GLAPIENTRY
#define APIENTRY GLAPIENTRY
#define APIENTRYP APIENTRY *
#define GLAPIENTRYP GLAPIENTRY *
#define GL_VERSION_1_1 1
#define GL_VERSION_1_2 1
#define GL_VERSION_1_3 1
#define GL_ARB_imaging 1
#define GL_FALSE 0
#define GL_TRUE 1
#define GL_BYTE 0x1400
#define GL_UNSIGNED_BYTE 0x1401
#define GL_SHORT 0x1402
#define GL_UNSIGNED_SHORT 0x1403
#define GL_INT 0x1404
#define GL_UNSIGNED_INT 0x1405
#define GL_FLOAT 0x1406
#define GL_2_BYTES 0x1407
#define GL_3_BYTES 0x1408
#define GL_4_BYTES 0x1409
#define GL_DOUBLE 0x140A
#define GL_POINTS 0x0000
#define GL_LINES 0x0001
#define GL_LINE_LOOP 0x0002
#define GL_LINE_STRIP 0x0003
#define GL_TRIANGLES 0x0004
#define GL_TRIANGLE_STRIP 0x0005
#define GL_TRIANGLE_FAN 0x0006
#define GL_QUADS 0x0007
#define GL_QUAD_STRIP 0x0008
#define GL_POLYGON 0x0009
#define GL_VERTEX_ARRAY 0x8074
#define GL_NORMAL_ARRAY 0x8075
#define GL_COLOR_ARRAY 0x8076
#define GL_INDEX_ARRAY 0x8077
#define GL_TEXTURE_COORD_ARRAY 0x8078
#define GL_EDGE_FLAG_ARRAY 0x8079
#define GL_VERTEX_ARRAY_SIZE 0x807A
#define GL_VERTEX_ARRAY_TYPE 0x807B
#define GL_VERTEX_ARRAY_STRIDE 0x807C
#define GL_NORMAL_ARRAY_TYPE 0x807E
#define GL_NORMAL_ARRAY_STRIDE 0x807F
#define GL_COLOR_ARRAY_SIZE 0x8081
#define GL_COLOR_ARRAY_TYPE 0x8082
#define GL_COLOR_ARRAY_STRIDE 0x8083
#define GL_INDEX_ARRAY_TYPE 0x8085
#define GL_INDEX_ARRAY_STRIDE 0x8086
#define GL_TEXTURE_COORD_ARRAY_SIZE 0x8088
#define GL_TEXTURE_COORD_ARRAY_TYPE 0x8089
#define GL_TEXTURE_COORD_ARRAY_STRIDE 0x808A
#define GL_EDGE_FLAG_ARRAY_STRIDE 0x808C
#define GL_VERTEX_ARRAY_POINTER 0x808E
#define GL_NORMAL_ARRAY_POINTER 0x808F
#define GL_COLOR_ARRAY_POINTER 0x8090
#define GL_INDEX_ARRAY_POINTER 0x8091
#define GL_TEXTURE_COORD_ARRAY_POINTER 0x8092
#define GL_EDGE_FLAG_ARRAY_POINTER 0x8093
#define GL_V2F 0x2A20
#define GL_V3F 0x2A21
#define GL_C4UB_V2F 0x2A22
#define GL_C4UB_V3F 0x2A23
#define GL_C3F_V3F 0x2A24
#define GL_N3F_V3F 0x2A25
#define GL_C4F_N3F_V3F 0x2A26
#define GL_T2F_V3F 0x2A27
#define GL_T4F_V4F 0x2A28
#define GL_T2F_C4UB_V3F 0x2A29
#define GL_T2F_C3F_V3F 0x2A2A
#define GL_T2F_N3F_V3F 0x2A2B
#define GL_T2F_C4F_N3F_V3F 0x2A2C
#define GL_T4F_C4F_N3F_V4F 0x2A2D
#define GL_MATRIX_MODE 0x0BA0
#define GL_MODELVIEW 0x1700
#define GL_PROJECTION 0x1701
#define GL_TEXTURE 0x1702
#define GL_POINT_SMOOTH 0x0B10
#define GL_POINT_SIZE 0x0B11
#define GL_POINT_SIZE_GRANULARITY 0x0B13
#define GL_POINT_SIZE_RANGE 0x0B12
#define GL_LINE_SMOOTH 0x0B20
#define GL_LINE_STIPPLE 0x0B24
#define GL_LINE_STIPPLE_PATTERN 0x0B25
#define GL_LINE_STIPPLE_REPEAT 0x0B26
#define GL_LINE_WIDTH 0x0B21
#define GL_LINE_WIDTH_GRANULARITY 0x0B23
#define GL_LINE_WIDTH_RANGE 0x0B22
#define GL_POINT 0x1B00
#define GL_LINE 0x1B01
#define GL_FILL 0x1B02
#define GL_CW 0x0900
#define GL_CCW 0x0901
#define GL_FRONT 0x0404
#define GL_BACK 0x0405
#define GL_POLYGON_MODE 0x0B40
#define GL_POLYGON_SMOOTH 0x0B41
#define GL_POLYGON_STIPPLE 0x0B42
#define GL_EDGE_FLAG 0x0B43
#define GL_CULL_FACE 0x0B44
#define GL_CULL_FACE_MODE 0x0B45
#define GL_FRONT_FACE 0x0B46
#define GL_POLYGON_OFFSET_FACTOR 0x8038
#define GL_POLYGON_OFFSET_UNITS 0x2A00
#define GL_POLYGON_OFFSET_POINT 0x2A01
#define GL_POLYGON_OFFSET_LINE 0x2A02
#define GL_POLYGON_OFFSET_FILL 0x8037
#define GL_COMPILE 0x1300
#define GL_COMPILE_AND_EXECUTE 0x1301
#define GL_LIST_BASE 0x0B32
#define GL_LIST_INDEX 0x0B33
#define GL_LIST_MODE 0x0B30
#define GL_NEVER 0x0200
#define GL_LESS 0x0201
#define GL_EQUAL 0x0202
#define GL_LEQUAL 0x0203
#define GL_GREATER 0x0204
#define GL_NOTEQUAL 0x0205
#define GL_GEQUAL 0x0206
#define GL_ALWAYS 0x0207
#define GL_DEPTH_TEST 0x0B71
#define GL_DEPTH_BITS 0x0D56
#define GL_DEPTH_CLEAR_VALUE 0x0B73
#define GL_DEPTH_FUNC 0x0B74
#define GL_DEPTH_RANGE 0x0B70
#define GL_DEPTH_WRITEMASK 0x0B72
#define GL_DEPTH_COMPONENT 0x1902
#define GL_LIGHTING 0x0B50
#define GL_LIGHT0 0x4000
#define GL_LIGHT1 0x4001
#define GL_LIGHT2 0x4002
#define GL_LIGHT3 0x4003
#define GL_LIGHT4 0x4004
#define GL_LIGHT5 0x4005
#define GL_LIGHT6 0x4006
#define GL_LIGHT7 0x4007
#define GL_SPOT_EXPONENT 0x1205
#define GL_SPOT_CUTOFF 0x1206
#define GL_CONSTANT_ATTENUATION 0x1207
#define GL_LINEAR_ATTENUATION 0x1208
#define GL_QUADRATIC_ATTENUATION 0x1209
#define GL_AMBIENT 0x1200
#define GL_DIFFUSE 0x1201
#define GL_SPECULAR 0x1202
#define GL_SHININESS 0x1601
#define GL_EMISSION 0x1600
#define GL_POSITION 0x1203
#define GL_SPOT_DIRECTION 0x1204
#define GL_AMBIENT_AND_DIFFUSE 0x1602
#define GL_COLOR_INDEXES 0x1603
#define GL_LIGHT_MODEL_TWO_SIDE 0x0B52
#define GL_LIGHT_MODEL_LOCAL_VIEWER 0x0B51
#define GL_LIGHT_MODEL_AMBIENT 0x0B53
#define GL_FRONT_AND_BACK 0x0408
#define GL_SHADE_MODEL 0x0B54
#define GL_FLAT 0x1D00
#define GL_SMOOTH 0x1D01
#define GL_COLOR_MATERIAL 0x0B57
#define GL_COLOR_MATERIAL_FACE 0x0B55
#define GL_COLOR_MATERIAL_PARAMETER 0x0B56
#define GL_NORMALIZE 0x0BA1
#define GL_CLIP_PLANE0 0x3000
#define GL_CLIP_PLANE1 0x3001
#define GL_CLIP_PLANE2 0x3002
#define GL_CLIP_PLANE3 0x3003
#define GL_CLIP_PLANE4 0x3004
#define GL_CLIP_PLANE5 0x3005
#define GL_ACCUM_RED_BITS 0x0D58
#define GL_ACCUM_GREEN_BITS 0x0D59
#define GL_ACCUM_BLUE_BITS 0x0D5A
#define GL_ACCUM_ALPHA_BITS 0x0D5B
#define GL_ACCUM_CLEAR_VALUE 0x0B80
#define GL_ACCUM 0x0100
#define GL_ADD 0x0104
#define GL_LOAD 0x0101
#define GL_MULT 0x0103
#define GL_RETURN 0x0102
#define GL_ALPHA_TEST 0x0BC0
#define GL_ALPHA_TEST_REF 0x0BC2
#define GL_ALPHA_TEST_FUNC 0x0BC1
#define GL_BLEND 0x0BE2
#define GL_BLEND_SRC 0x0BE1
#define GL_BLEND_DST 0x0BE0
#define GL_ZERO 0
#define GL_ONE 1
#define GL_SRC_COLOR 0x0300
#define GL_ONE_MINUS_SRC_COLOR 0x0301
#define GL_SRC_ALPHA 0x0302
#define GL_ONE_MINUS_SRC_ALPHA 0x0303
#define GL_DST_ALPHA 0x0304
#define GL_ONE_MINUS_DST_ALPHA 0x0305
#define GL_DST_COLOR 0x0306
#define GL_ONE_MINUS_DST_COLOR 0x0307
#define GL_SRC_ALPHA_SATURATE 0x0308
#define GL_FEEDBACK 0x1C01
#define GL_RENDER 0x1C00
#define GL_SELECT 0x1C02
#define GL_2D 0x0600
#define GL_3D 0x0601
#define GL_3D_COLOR 0x0602
#define GL_3D_COLOR_TEXTURE 0x0603
#define GL_4D_COLOR_TEXTURE 0x0604
#define GL_POINT_TOKEN 0x0701
#define GL_LINE_TOKEN 0x0702
#define GL_LINE_RESET_TOKEN 0x0707
#define GL_POLYGON_TOKEN 0x0703
#define GL_BITMAP_TOKEN 0x0704
#define GL_DRAW_PIXEL_TOKEN 0x0705
#define GL_COPY_PIXEL_TOKEN 0x0706
#define GL_PASS_THROUGH_TOKEN 0x0700
#define GL_FEEDBACK_BUFFER_POINTER 0x0DF0
#define GL_FEEDBACK_BUFFER_SIZE 0x0DF1
#define GL_FEEDBACK_BUFFER_TYPE 0x0DF2
#define GL_SELECTION_BUFFER_POINTER 0x0DF3
#define GL_SELECTION_BUFFER_SIZE 0x0DF4
#define GL_FOG 0x0B60
#define GL_FOG_MODE 0x0B65
#define GL_FOG_DENSITY 0x0B62
#define GL_FOG_COLOR 0x0B66
#define GL_FOG_INDEX 0x0B61
#define GL_FOG_START 0x0B63
#define GL_FOG_END 0x0B64
#define GL_LINEAR 0x2601
#define GL_EXP 0x0800
#define GL_EXP2 0x0801
#define GL_LOGIC_OP 0x0BF1
#define GL_INDEX_LOGIC_OP 0x0BF1
#define GL_COLOR_LOGIC_OP 0x0BF2
#define GL_LOGIC_OP_MODE 0x0BF0
#define GL_CLEAR 0x1500
#define GL_SET 0x150F
#define GL_COPY 0x1503
#define GL_COPY_INVERTED 0x150C
#define GL_NOOP 0x1505
#define GL_INVERT 0x150A
#define GL_AND 0x1501
#define GL_NAND 0x150E
#define GL_OR 0x1507
#define GL_NOR 0x1508
#define GL_XOR 0x1506
#define GL_EQUIV 0x1509
#define GL_AND_REVERSE 0x1502
#define GL_AND_INVERTED 0x1504
#define GL_OR_REVERSE 0x150B
#define GL_OR_INVERTED 0x150D
#define GL_STENCIL_BITS 0x0D57
#define GL_STENCIL_TEST 0x0B90
#define GL_STENCIL_CLEAR_VALUE 0x0B91
#define GL_STENCIL_FUNC 0x0B92
#define GL_STENCIL_VALUE_MASK 0x0B93
#define GL_STENCIL_FAIL 0x0B94
#define GL_STENCIL_PASS_DEPTH_FAIL 0x0B95
#define GL_STENCIL_PASS_DEPTH_PASS 0x0B96
#define GL_STENCIL_REF 0x0B97
#define GL_STENCIL_WRITEMASK 0x0B98
#define GL_STENCIL_INDEX 0x1901
#define GL_KEEP 0x1E00
#define GL_REPLACE 0x1E01
#define GL_INCR 0x1E02
#define GL_DECR 0x1E03
#define GL_NONE 0
#define GL_LEFT 0x0406
#define GL_RIGHT 0x0407
#define GL_FRONT_LEFT 0x0400
#define GL_FRONT_RIGHT 0x0401
#define GL_BACK_LEFT 0x0402
#define GL_BACK_RIGHT 0x0403
#define GL_AUX0 0x0409
#define GL_AUX1 0x040A
#define GL_AUX2 0x040B
#define GL_AUX3 0x040C
#define GL_COLOR_INDEX 0x1900
#define GL_RED 0x1903
#define GL_GREEN 0x1904
#define GL_BLUE 0x1905
#define GL_ALPHA 0x1906
#define GL_LUMINANCE 0x1909
#define GL_LUMINANCE_ALPHA 0x190A
#define GL_ALPHA_BITS 0x0D55
#define GL_RED_BITS 0x0D52
#define GL_GREEN_BITS 0x0D53
#define GL_BLUE_BITS 0x0D54
#define GL_INDEX_BITS 0x0D51
#define GL_SUBPIXEL_BITS 0x0D50
#define GL_AUX_BUFFERS 0x0C00
#define GL_READ_BUFFER 0x0C02
#define GL_DRAW_BUFFER 0x0C01
#define GL_DOUBLEBUFFER 0x0C32
#define GL_STEREO 0x0C33
#define GL_BITMAP 0x1A00
#define GL_COLOR 0x1800
#define GL_DEPTH 0x1801
#define GL_STENCIL 0x1802
#define GL_DITHER 0x0BD0
#define GL_RGB 0x1907
#define GL_RGBA 0x1908
#define GL_MAX_LIST_NESTING 0x0B31
#define GL_MAX_EVAL_ORDER 0x0D30
#define GL_MAX_LIGHTS 0x0D31
#define GL_MAX_CLIP_PLANES 0x0D32
#define GL_MAX_TEXTURE_SIZE 0x0D33
#define GL_MAX_PIXEL_MAP_TABLE 0x0D34
#define GL_MAX_ATTRIB_STACK_DEPTH 0x0D35
#define GL_MAX_MODELVIEW_STACK_DEPTH 0x0D36
#define GL_MAX_NAME_STACK_DEPTH 0x0D37
#define GL_MAX_PROJECTION_STACK_DEPTH 0x0D38
#define GL_MAX_TEXTURE_STACK_DEPTH 0x0D39
#define GL_MAX_VIEWPORT_DIMS 0x0D3A
#define GL_MAX_CLIENT_ATTRIB_STACK_DEPTH 0x0D3B
#define GL_ATTRIB_STACK_DEPTH 0x0BB0
#define GL_CLIENT_ATTRIB_STACK_DEPTH 0x0BB1
#define GL_COLOR_CLEAR_VALUE 0x0C22
#define GL_COLOR_WRITEMASK 0x0C23
#define GL_CURRENT_INDEX 0x0B01
#define GL_CURRENT_COLOR 0x0B00
#define GL_CURRENT_NORMAL 0x0B02
#define GL_CURRENT_RASTER_COLOR 0x0B04
#define GL_CURRENT_RASTER_DISTANCE 0x0B09
#define GL_CURRENT_RASTER_INDEX 0x0B05
#define GL_CURRENT_RASTER_POSITION 0x0B07
#define GL_CURRENT_RASTER_TEXTURE_COORDS 0x0B06
#define GL_CURRENT_RASTER_POSITION_VALID 0x0B08
#define GL_CURRENT_TEXTURE_COORDS 0x0B03
#define GL_INDEX_CLEAR_VALUE 0x0C20
#define GL_INDEX_MODE 0x0C30
#define GL_INDEX_WRITEMASK 0x0C21
#define GL_MODELVIEW_MATRIX 0x0BA6
#define GL_MODELVIEW_STACK_DEPTH 0x0BA3
#define GL_NAME_STACK_DEPTH 0x0D70
#define GL_PROJECTION_MATRIX 0x0BA7
#define GL_PROJECTION_STACK_DEPTH 0x0BA4
#define GL_RENDER_MODE 0x0C40
#define GL_RGBA_MODE 0x0C31
#define GL_TEXTURE_MATRIX 0x0BA8
#define GL_TEXTURE_STACK_DEPTH 0x0BA5
#define GL_VIEWPORT 0x0BA2
#define GL_AUTO_NORMAL 0x0D80
#define GL_MAP1_COLOR_4 0x0D90
#define GL_MAP1_INDEX 0x0D91
#define GL_MAP1_NORMAL 0x0D92
#define GL_MAP1_TEXTURE_COORD_1 0x0D93
#define GL_MAP1_TEXTURE_COORD_2 0x0D94
#define GL_MAP1_TEXTURE_COORD_3 0x0D95
#define GL_MAP1_TEXTURE_COORD_4 0x0D96
#define GL_MAP1_VERTEX_3 0x0D97
#define GL_MAP1_VERTEX_4 0x0D98
#define GL_MAP2_COLOR_4 0x0DB0
#define GL_MAP2_INDEX 0x0DB1
#define GL_MAP2_NORMAL 0x0DB2
#define GL_MAP2_TEXTURE_COORD_1 0x0DB3
#define GL_MAP2_TEXTURE_COORD_2 0x0DB4
#define GL_MAP2_TEXTURE_COORD_3 0x0DB5
#define GL_MAP2_TEXTURE_COORD_4 0x0DB6
#define GL_MAP2_VERTEX_3 0x0DB7
#define GL_MAP2_VERTEX_4 0x0DB8
#define GL_MAP1_GRID_DOMAIN 0x0DD0
#define GL_MAP1_GRID_SEGMENTS 0x0DD1
#define GL_MAP2_GRID_DOMAIN 0x0DD2
#define GL_MAP2_GRID_SEGMENTS 0x0DD3
#define GL_COEFF 0x0A00
#define GL_ORDER 0x0A01
#define GL_DOMAIN 0x0A02
#define GL_PERSPECTIVE_CORRECTION_HINT 0x0C50
#define GL_POINT_SMOOTH_HINT 0x0C51
#define GL_LINE_SMOOTH_HINT 0x0C52
#define GL_POLYGON_SMOOTH_HINT 0x0C53
#define GL_FOG_HINT 0x0C54
#define GL_DONT_CARE 0x1100
#define GL_FASTEST 0x1101
#define GL_NICEST 0x1102
#define GL_SCISSOR_BOX 0x0C10
#define GL_SCISSOR_TEST 0x0C11
#define GL_MAP_COLOR 0x0D10
#define GL_MAP_STENCIL 0x0D11
#define GL_INDEX_SHIFT 0x0D12
#define GL_INDEX_OFFSET 0x0D13
#define GL_RED_SCALE 0x0D14
#define GL_RED_BIAS 0x0D15
#define GL_GREEN_SCALE 0x0D18
#define GL_GREEN_BIAS 0x0D19
#define GL_BLUE_SCALE 0x0D1A
#define GL_BLUE_BIAS 0x0D1B
#define GL_ALPHA_SCALE 0x0D1C
#define GL_ALPHA_BIAS 0x0D1D
#define GL_DEPTH_SCALE 0x0D1E
#define GL_DEPTH_BIAS 0x0D1F
#define GL_PIXEL_MAP_S_TO_S_SIZE 0x0CB1
#define GL_PIXEL_MAP_I_TO_I_SIZE 0x0CB0
#define GL_PIXEL_MAP_I_TO_R_SIZE 0x0CB2
#define GL_PIXEL_MAP_I_TO_G_SIZE 0x0CB3
#define GL_PIXEL_MAP_I_TO_B_SIZE 0x0CB4
#define GL_PIXEL_MAP_I_TO_A_SIZE 0x0CB5
#define GL_PIXEL_MAP_R_TO_R_SIZE 0x0CB6
#define GL_PIXEL_MAP_G_TO_G_SIZE 0x0CB7
#define GL_PIXEL_MAP_B_TO_B_SIZE 0x0CB8
#define GL_PIXEL_MAP_A_TO_A_SIZE 0x0CB9
#define GL_PIXEL_MAP_S_TO_S 0x0C71
#define GL_PIXEL_MAP_I_TO_I 0x0C70
#define GL_PIXEL_MAP_I_TO_R 0x0C72
#define GL_PIXEL_MAP_I_TO_G 0x0C73
#define GL_PIXEL_MAP_I_TO_B 0x0C74
#define GL_PIXEL_MAP_I_TO_A 0x0C75
#define GL_PIXEL_MAP_R_TO_R 0x0C76
#define GL_PIXEL_MAP_G_TO_G 0x0C77
#define GL_PIXEL_MAP_B_TO_B 0x0C78
#define GL_PIXEL_MAP_A_TO_A 0x0C79
#define GL_PACK_ALIGNMENT 0x0D05
#define GL_PACK_LSB_FIRST 0x0D01
#define GL_PACK_ROW_LENGTH 0x0D02
#define GL_PACK_SKIP_PIXELS 0x0D04
#define GL_PACK_SKIP_ROWS 0x0D03
#define GL_PACK_SWAP_BYTES 0x0D00
#define GL_UNPACK_ALIGNMENT 0x0CF5
#define GL_UNPACK_LSB_FIRST 0x0CF1
#define GL_UNPACK_ROW_LENGTH 0x0CF2
#define GL_UNPACK_SKIP_PIXELS 0x0CF4
#define GL_UNPACK_SKIP_ROWS 0x0CF3
#define GL_UNPACK_SWAP_BYTES 0x0CF0
#define GL_ZOOM_X 0x0D16
#define GL_ZOOM_Y 0x0D17
#define GL_TEXTURE_ENV 0x2300
#define GL_TEXTURE_ENV_MODE 0x2200
#define GL_TEXTURE_1D 0x0DE0
#define GL_TEXTURE_2D 0x0DE1
#define GL_TEXTURE_WRAP_S 0x2802
#define GL_TEXTURE_WRAP_T 0x2803
#define GL_TEXTURE_MAG_FILTER 0x2800
#define GL_TEXTURE_MIN_FILTER 0x2801
#define GL_TEXTURE_ENV_COLOR 0x2201
#define GL_TEXTURE_GEN_S 0x0C60
#define GL_TEXTURE_GEN_T 0x0C61
#define GL_TEXTURE_GEN_R 0x0C62
#define GL_TEXTURE_GEN_Q 0x0C63
#define GL_TEXTURE_GEN_MODE 0x2500
#define GL_TEXTURE_BORDER_COLOR 0x1004
#define GL_TEXTURE_WIDTH 0x1000
#define GL_TEXTURE_HEIGHT 0x1001
#define GL_TEXTURE_BORDER 0x1005
#define GL_TEXTURE_COMPONENTS 0x1003
#define GL_TEXTURE_RED_SIZE 0x805C
#define GL_TEXTURE_GREEN_SIZE 0x805D
#define GL_TEXTURE_BLUE_SIZE 0x805E
#define GL_TEXTURE_ALPHA_SIZE 0x805F
#define GL_TEXTURE_LUMINANCE_SIZE 0x8060
#define GL_TEXTURE_INTENSITY_SIZE 0x8061
#define GL_NEAREST_MIPMAP_NEAREST 0x2700
#define GL_NEAREST_MIPMAP_LINEAR 0x2702
#define GL_LINEAR_MIPMAP_NEAREST 0x2701
#define GL_LINEAR_MIPMAP_LINEAR 0x2703
#define GL_OBJECT_LINEAR 0x2401
#define GL_OBJECT_PLANE 0x2501
#define GL_EYE_LINEAR 0x2400
#define GL_EYE_PLANE 0x2502
#define GL_SPHERE_MAP 0x2402
#define GL_DECAL 0x2101
#define GL_MODULATE 0x2100
#define GL_NEAREST 0x2600
#define GL_REPEAT 0x2901
#define GL_CLAMP 0x2900
#define GL_S 0x2000
#define GL_T 0x2001
#define GL_R 0x2002
#define GL_Q 0x2003
#define GL_VENDOR 0x1F00
#define GL_RENDERER 0x1F01
#define GL_VERSION 0x1F02
#define GL_EXTENSIONS 0x1F03
#define GL_NO_ERROR 0
#define GL_INVALID_ENUM 0x0500
#define GL_INVALID_VALUE 0x0501
#define GL_INVALID_OPERATION 0x0502
#define GL_STACK_OVERFLOW 0x0503
#define GL_STACK_UNDERFLOW 0x0504
#define GL_OUT_OF_MEMORY 0x0505
#define GL_CURRENT_BIT 0x00000001
#define GL_POINT_BIT 0x00000002
#define GL_LINE_BIT 0x00000004
#define GL_POLYGON_BIT 0x00000008
#define GL_POLYGON_STIPPLE_BIT 0x00000010
#define GL_PIXEL_MODE_BIT 0x00000020
#define GL_LIGHTING_BIT 0x00000040
#define GL_FOG_BIT 0x00000080
#define GL_DEPTH_BUFFER_BIT 0x00000100
#define GL_ACCUM_BUFFER_BIT 0x00000200
#define GL_STENCIL_BUFFER_BIT 0x00000400
#define GL_VIEWPORT_BIT 0x00000800
#define GL_TRANSFORM_BIT 0x00001000
#define GL_ENABLE_BIT 0x00002000
#define GL_COLOR_BUFFER_BIT 0x00004000
#define GL_HINT_BIT 0x00008000
#define GL_EVAL_BIT 0x00010000
#define GL_LIST_BIT 0x00020000
#define GL_TEXTURE_BIT 0x00040000
#define GL_SCISSOR_BIT 0x00080000
#define GL_ALL_ATTRIB_BITS 0x000FFFFF
#define GL_PROXY_TEXTURE_1D 0x8063
#define GL_PROXY_TEXTURE_2D 0x8064
#define GL_TEXTURE_PRIORITY 0x8066
#define GL_TEXTURE_RESIDENT 0x8067
#define GL_TEXTURE_BINDING_1D 0x8068
#define GL_TEXTURE_BINDING_2D 0x8069
#define GL_TEXTURE_INTERNAL_FORMAT 0x1003
#define GL_ALPHA4 0x803B
#define GL_ALPHA8 0x803C
#define GL_ALPHA12 0x803D
#define GL_ALPHA16 0x803E
#define GL_LUMINANCE4 0x803F
#define GL_LUMINANCE8 0x8040
#define GL_LUMINANCE12 0x8041
#define GL_LUMINANCE16 0x8042
#define GL_LUMINANCE4_ALPHA4 0x8043
#define GL_LUMINANCE6_ALPHA2 0x8044
#define GL_LUMINANCE8_ALPHA8 0x8045
#define GL_LUMINANCE12_ALPHA4 0x8046
#define GL_LUMINANCE12_ALPHA12 0x8047
#define GL_LUMINANCE16_ALPHA16 0x8048
#define GL_INTENSITY 0x8049
#define GL_INTENSITY4 0x804A
#define GL_INTENSITY8 0x804B
#define GL_INTENSITY12 0x804C
#define GL_INTENSITY16 0x804D
#define GL_R3_G3_B2 0x2A10
#define GL_RGB4 0x804F
#define GL_RGB5 0x8050
#define GL_RGB8 0x8051
#define GL_RGB10 0x8052
#define GL_RGB12 0x8053
#define GL_RGB16 0x8054
#define GL_RGBA2 0x8055
#define GL_RGBA4 0x8056
#define GL_RGB5_A1 0x8057
#define GL_RGBA8 0x8058
#define GL_RGB10_A2 0x8059
#define GL_RGBA12 0x805A
#define GL_RGBA16 0x805B
#define GL_CLIENT_PIXEL_STORE_BIT 0x00000001
#define GL_CLIENT_VERTEX_ARRAY_BIT 0x00000002
#define GL_ALL_CLIENT_ATTRIB_BITS 0xFFFFFFFF
#define GL_CLIENT_ALL_ATTRIB_BITS 0xFFFFFFFF
#define GL_RESCALE_NORMAL 0x803A
#define GL_CLAMP_TO_EDGE 0x812F
#define GL_MAX_ELEMENTS_VERTICES 0x80E8
#define GL_MAX_ELEMENTS_INDICES 0x80E9
#define GL_BGR 0x80E0
#define GL_BGRA 0x80E1
#define GL_UNSIGNED_BYTE_3_3_2 0x8032
#define GL_UNSIGNED_BYTE_2_3_3_REV 0x8362
#define GL_UNSIGNED_SHORT_5_6_5 0x8363
#define GL_UNSIGNED_SHORT_5_6_5_REV 0x8364
#define GL_UNSIGNED_SHORT_4_4_4_4 0x8033
#define GL_UNSIGNED_SHORT_4_4_4_4_REV 0x8365
#define GL_UNSIGNED_SHORT_5_5_5_1 0x8034
#define GL_UNSIGNED_SHORT_1_5_5_5_REV 0x8366
#define GL_UNSIGNED_INT_8_8_8_8 0x8035
#define GL_UNSIGNED_INT_8_8_8_8_REV 0x8367
#define GL_UNSIGNED_INT_10_10_10_2 0x8036
#define GL_UNSIGNED_INT_2_10_10_10_REV 0x8368
#define GL_LIGHT_MODEL_COLOR_CONTROL 0x81F8
#define GL_SINGLE_COLOR 0x81F9
#define GL_SEPARATE_SPECULAR_COLOR 0x81FA
#define GL_TEXTURE_MIN_LOD 0x813A
#define GL_TEXTURE_MAX_LOD 0x813B
#define GL_TEXTURE_BASE_LEVEL 0x813C
#define GL_TEXTURE_MAX_LEVEL 0x813D
#define GL_SMOOTH_POINT_SIZE_RANGE 0x0B12
#define GL_SMOOTH_POINT_SIZE_GRANULARITY 0x0B13
#define GL_SMOOTH_LINE_WIDTH_RANGE 0x0B22
#define GL_SMOOTH_LINE_WIDTH_GRANULARITY 0x0B23
#define GL_ALIASED_POINT_SIZE_RANGE 0x846D
#define GL_ALIASED_LINE_WIDTH_RANGE 0x846E
#define GL_PACK_SKIP_IMAGES 0x806B
#define GL_PACK_IMAGE_HEIGHT 0x806C
#define GL_UNPACK_SKIP_IMAGES 0x806D
#define GL_UNPACK_IMAGE_HEIGHT 0x806E
#define GL_TEXTURE_3D 0x806F
#define GL_PROXY_TEXTURE_3D 0x8070
#define GL_TEXTURE_DEPTH 0x8071
#define GL_TEXTURE_WRAP_R 0x8072
#define GL_MAX_3D_TEXTURE_SIZE 0x8073
#define GL_TEXTURE_BINDING_3D 0x806A
#define GL_CONSTANT_COLOR 0x8001
#define GL_ONE_MINUS_CONSTANT_COLOR 0x8002
#define GL_CONSTANT_ALPHA 0x8003
#define GL_ONE_MINUS_CONSTANT_ALPHA 0x8004
#define GL_COLOR_TABLE 0x80D0
#define GL_POST_CONVOLUTION_COLOR_TABLE 0x80D1
#define GL_POST_COLOR_MATRIX_COLOR_TABLE 0x80D2
#define GL_PROXY_COLOR_TABLE 0x80D3
#define GL_PROXY_POST_CONVOLUTION_COLOR_TABLE 0x80D4
#define GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE 0x80D5
#define GL_COLOR_TABLE_SCALE 0x80D6
#define GL_COLOR_TABLE_BIAS 0x80D7
#define GL_COLOR_TABLE_FORMAT 0x80D8
#define GL_COLOR_TABLE_WIDTH 0x80D9
#define GL_COLOR_TABLE_RED_SIZE 0x80DA
#define GL_COLOR_TABLE_GREEN_SIZE 0x80DB
#define GL_COLOR_TABLE_BLUE_SIZE 0x80DC
#define GL_COLOR_TABLE_ALPHA_SIZE 0x80DD
#define GL_COLOR_TABLE_LUMINANCE_SIZE 0x80DE
#define GL_COLOR_TABLE_INTENSITY_SIZE 0x80DF
#define GL_CONVOLUTION_1D 0x8010
#define GL_CONVOLUTION_2D 0x8011
#define GL_SEPARABLE_2D 0x8012
#define GL_CONVOLUTION_BORDER_MODE 0x8013
#define GL_CONVOLUTION_FILTER_SCALE 0x8014
#define GL_CONVOLUTION_FILTER_BIAS 0x8015
#define GL_REDUCE 0x8016
#define GL_CONVOLUTION_FORMAT 0x8017
#define GL_CONVOLUTION_WIDTH 0x8018
#define GL_CONVOLUTION_HEIGHT 0x8019
#define GL_MAX_CONVOLUTION_WIDTH 0x801A
#define GL_MAX_CONVOLUTION_HEIGHT 0x801B
#define GL_POST_CONVOLUTION_RED_SCALE 0x801C
#define GL_POST_CONVOLUTION_GREEN_SCALE 0x801D
#define GL_POST_CONVOLUTION_BLUE_SCALE 0x801E
#define GL_POST_CONVOLUTION_ALPHA_SCALE 0x801F
#define GL_POST_CONVOLUTION_RED_BIAS 0x8020
#define GL_POST_CONVOLUTION_GREEN_BIAS 0x8021
#define GL_POST_CONVOLUTION_BLUE_BIAS 0x8022
#define GL_POST_CONVOLUTION_ALPHA_BIAS 0x8023
#define GL_CONSTANT_BORDER 0x8151
#define GL_REPLICATE_BORDER 0x8153
#define GL_CONVOLUTION_BORDER_COLOR 0x8154
#define GL_COLOR_MATRIX 0x80B1
#define GL_COLOR_MATRIX_STACK_DEPTH 0x80B2
#define GL_MAX_COLOR_MATRIX_STACK_DEPTH 0x80B3
#define GL_POST_COLOR_MATRIX_RED_SCALE 0x80B4
#define GL_POST_COLOR_MATRIX_GREEN_SCALE 0x80B5
#define GL_POST_COLOR_MATRIX_BLUE_SCALE 0x80B6
#define GL_POST_COLOR_MATRIX_ALPHA_SCALE 0x80B7
#define GL_POST_COLOR_MATRIX_RED_BIAS 0x80B8
#define GL_POST_COLOR_MATRIX_GREEN_BIAS 0x80B9
#define GL_POST_COLOR_MATRIX_BLUE_BIAS 0x80BA
#define GL_POST_COLOR_MATRIX_ALPHA_BIAS 0x80BB
#define GL_HISTOGRAM 0x8024
#define GL_PROXY_HISTOGRAM 0x8025
#define GL_HISTOGRAM_WIDTH 0x8026
#define GL_HISTOGRAM_FORMAT 0x8027
#define GL_HISTOGRAM_RED_SIZE 0x8028
#define GL_HISTOGRAM_GREEN_SIZE 0x8029
#define GL_HISTOGRAM_BLUE_SIZE 0x802A
#define GL_HISTOGRAM_ALPHA_SIZE 0x802B
#define GL_HISTOGRAM_LUMINANCE_SIZE 0x802C
#define GL_HISTOGRAM_SINK 0x802D
#define GL_MINMAX 0x802E
#define GL_MINMAX_FORMAT 0x802F
#define GL_MINMAX_SINK 0x8030
#define GL_TABLE_TOO_LARGE 0x8031
#define GL_BLEND_EQUATION 0x8009
#define GL_MIN 0x8007
#define GL_MAX 0x8008
#define GL_FUNC_ADD 0x8006
#define GL_FUNC_SUBTRACT 0x800A
#define GL_FUNC_REVERSE_SUBTRACT 0x800B
#define GL_BLEND_COLOR 0x8005
#define GL_TEXTURE0 0x84C0
#define GL_TEXTURE1 0x84C1
#define GL_TEXTURE2 0x84C2
#define GL_TEXTURE3 0x84C3
#define GL_TEXTURE4 0x84C4
#define GL_TEXTURE5 0x84C5
#define GL_TEXTURE6 0x84C6
#define GL_TEXTURE7 0x84C7
#define GL_TEXTURE8 0x84C8
#define GL_TEXTURE9 0x84C9
#define GL_TEXTURE10 0x84CA
#define GL_TEXTURE11 0x84CB
#define GL_TEXTURE12 0x84CC
#define GL_TEXTURE13 0x84CD
#define GL_TEXTURE14 0x84CE
#define GL_TEXTURE15 0x84CF
#define GL_TEXTURE16 0x84D0
#define GL_TEXTURE17 0x84D1
#define GL_TEXTURE18 0x84D2
#define GL_TEXTURE19 0x84D3
#define GL_TEXTURE20 0x84D4
#define GL_TEXTURE21 0x84D5
#define GL_TEXTURE22 0x84D6
#define GL_TEXTURE23 0x84D7
#define GL_TEXTURE24 0x84D8
#define GL_TEXTURE25 0x84D9
#define GL_TEXTURE26 0x84DA
#define GL_TEXTURE27 0x84DB
#define GL_TEXTURE28 0x84DC
#define GL_TEXTURE29 0x84DD
#define GL_TEXTURE30 0x84DE
#define GL_TEXTURE31 0x84DF
#define GL_ACTIVE_TEXTURE 0x84E0
#define GL_CLIENT_ACTIVE_TEXTURE 0x84E1
#define GL_MAX_TEXTURE_UNITS 0x84E2
#define GL_NORMAL_MAP 0x8511
#define GL_REFLECTION_MAP 0x8512
#define GL_TEXTURE_CUBE_MAP 0x8513
#define GL_TEXTURE_BINDING_CUBE_MAP 0x8514
#define GL_TEXTURE_CUBE_MAP_POSITIVE_X 0x8515
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_X 0x8516
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Y 0x8517
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 0x8518
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Z 0x8519
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 0x851A
#define GL_PROXY_TEXTURE_CUBE_MAP 0x851B
#define GL_MAX_CUBE_MAP_TEXTURE_SIZE 0x851C
#define GL_COMPRESSED_ALPHA 0x84E9
#define GL_COMPRESSED_LUMINANCE 0x84EA
#define GL_COMPRESSED_LUMINANCE_ALPHA 0x84EB
#define GL_COMPRESSED_INTENSITY 0x84EC
#define GL_COMPRESSED_RGB 0x84ED
#define GL_COMPRESSED_RGBA 0x84EE
#define GL_TEXTURE_COMPRESSION_HINT 0x84EF
#define GL_TEXTURE_COMPRESSED_IMAGE_SIZE 0x86A0
#define GL_TEXTURE_COMPRESSED 0x86A1
#define GL_NUM_COMPRESSED_TEXTURE_FORMATS 0x86A2
#define GL_COMPRESSED_TEXTURE_FORMATS 0x86A3
#define GL_MULTISAMPLE 0x809D
#define GL_SAMPLE_ALPHA_TO_COVERAGE 0x809E
#define GL_SAMPLE_ALPHA_TO_ONE 0x809F
#define GL_SAMPLE_COVERAGE 0x80A0
#define GL_SAMPLE_BUFFERS 0x80A8
#define GL_SAMPLES 0x80A9
#define GL_SAMPLE_COVERAGE_VALUE 0x80AA
#define GL_SAMPLE_COVERAGE_INVERT 0x80AB
#define GL_MULTISAMPLE_BIT 0x20000000
#define GL_TRANSPOSE_MODELVIEW_MATRIX 0x84E3
#define GL_TRANSPOSE_PROJECTION_MATRIX 0x84E4
#define GL_TRANSPOSE_TEXTURE_MATRIX 0x84E5
#define GL_TRANSPOSE_COLOR_MATRIX 0x84E6
#define GL_COMBINE 0x8570
#define GL_COMBINE_RGB 0x8571
#define GL_COMBINE_ALPHA 0x8572
#define GL_SOURCE0_RGB 0x8580
#define GL_SOURCE1_RGB 0x8581
#define GL_SOURCE2_RGB 0x8582
#define GL_SOURCE0_ALPHA 0x8588
#define GL_SOURCE1_ALPHA 0x8589
#define GL_SOURCE2_ALPHA 0x858A
#define GL_OPERAND0_RGB 0x8590
#define GL_OPERAND1_RGB 0x8591
#define GL_OPERAND2_RGB 0x8592
#define GL_OPERAND0_ALPHA 0x8598
#define GL_OPERAND1_ALPHA 0x8599
#define GL_OPERAND2_ALPHA 0x859A
#define GL_RGB_SCALE 0x8573
#define GL_ADD_SIGNED 0x8574
#define GL_INTERPOLATE 0x8575
#define GL_SUBTRACT 0x84E7
#define GL_CONSTANT 0x8576
#define GL_PRIMARY_COLOR 0x8577
#define GL_PREVIOUS 0x8578
#define GL_DOT3_RGB 0x86AE
#define GL_DOT3_RGBA 0x86AF
#define GL_CLAMP_TO_BORDER 0x812D
#define GL_ARB_multitexture 1
#define GL_TEXTURE0_ARB 0x84C0
#define GL_TEXTURE1_ARB 0x84C1
#define GL_TEXTURE2_ARB 0x84C2
#define GL_TEXTURE3_ARB 0x84C3
#define GL_TEXTURE4_ARB 0x84C4
#define GL_TEXTURE5_ARB 0x84C5
#define GL_TEXTURE6_ARB 0x84C6
#define GL_TEXTURE7_ARB 0x84C7
#define GL_TEXTURE8_ARB 0x84C8
#define GL_TEXTURE9_ARB 0x84C9
#define GL_TEXTURE10_ARB 0x84CA
#define GL_TEXTURE11_ARB 0x84CB
#define GL_TEXTURE12_ARB 0x84CC
#define GL_TEXTURE13_ARB 0x84CD
#define GL_TEXTURE14_ARB 0x84CE
#define GL_TEXTURE15_ARB 0x84CF
#define GL_TEXTURE16_ARB 0x84D0
#define GL_TEXTURE17_ARB 0x84D1
#define GL_TEXTURE18_ARB 0x84D2
#define GL_TEXTURE19_ARB 0x84D3
#define GL_TEXTURE20_ARB 0x84D4
#define GL_TEXTURE21_ARB 0x84D5
#define GL_TEXTURE22_ARB 0x84D6
#define GL_TEXTURE23_ARB 0x84D7
#define GL_TEXTURE24_ARB 0x84D8
#define GL_TEXTURE25_ARB 0x84D9
#define GL_TEXTURE26_ARB 0x84DA
#define GL_TEXTURE27_ARB 0x84DB
#define GL_TEXTURE28_ARB 0x84DC
#define GL_TEXTURE29_ARB 0x84DD
#define GL_TEXTURE30_ARB 0x84DE
#define GL_TEXTURE31_ARB 0x84DF
#define GL_ACTIVE_TEXTURE_ARB 0x84E0
#define GL_CLIENT_ACTIVE_TEXTURE_ARB 0x84E1
#define GL_MAX_TEXTURE_UNITS_ARB 0x84E2
#define GL_MESA_packed_depth_stencil 1
#define GL_DEPTH_STENCIL_MESA 0x8750
#define GL_UNSIGNED_INT_24_8_MESA 0x8751
#define GL_UNSIGNED_INT_8_24_REV_MESA 0x8752
#define GL_UNSIGNED_SHORT_15_1_MESA 0x8753
#define GL_UNSIGNED_SHORT_1_15_REV_MESA 0x8754
#define GL_ATI_blend_equation_separate 1
#define GL_ALPHA_BLEND_EQUATION_ATI 0x883D
#define GL_OES_EGL_image 1
Typedefs
typedef unsigned int GLenum
typedef unsigned char GLboolean
typedef unsigned int GLbitfield
typedef void GLvoid
typedef signed char GLbyte
typedef short GLshort
typedef int GLint
typedef unsigned char GLubyte
typedef unsigned short GLushort
typedef unsigned int GLuint
typedef int GLsizei
typedef float GLfloat
typedef float GLclampf
typedef double GLdouble
typedef double GLclampd
typedef GLuint start
typedef GLuint GLuint end
typedef GLuint GLuint GLsizei count
typedef GLuint GLuint GLsizei GLenum type
typedef GLuint GLuint GLsizei GLenum const GLvoid * indices
typedef GLint level
typedef GLint GLint internalformat
typedef GLint GLint GLsizei width
typedef GLint GLint GLsizei GLsizei height
typedef GLint GLint GLsizei GLsizei GLsizei depth
typedef GLint GLint GLsizei GLsizei GLsizei GLint border
typedef GLint GLint GLsizei GLsizei GLsizei GLint GLenum format
typedef GLint GLint GLsizei GLsizei GLsizei GLint GLenum GLenum const GLvoid * pixels
typedef GLint GLint xoffset
typedef GLint GLint GLint yoffset
typedef GLint GLint GLint GLint zoffset
typedef GLint GLint GLint GLint GLint x
typedef GLint GLint GLint GLint GLint GLint y
typedef GLboolean invert
typedef GLint GLenum GLsizei GLsizei GLsizei GLint GLsizei imageSize
typedef GLint GLenum GLsizei GLsizei GLsizei GLint GLsizei const GLvoid * data
typedef GLint GLvoid * img
typedef GLdouble s
typedef const GLdouble * v
typedef GLdouble GLdouble t
typedef GLdouble GLdouble GLdouble r
typedef GLdouble GLdouble GLdouble GLdouble q
typedef GLenum modeA
typedef void * GLeglImageOES
typedef GLeglImageOES image
Functions
GLAPI void GLAPIENTRY glClearIndex (GLfloat c)
GLAPI void GLAPIENTRY glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GLAPI void GLAPIENTRY glClear (GLbitfield mask)
GLAPI void GLAPIENTRY glIndexMask (GLuint mask)
GLAPI void GLAPIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
GLAPI void GLAPIENTRY glAlphaFunc (GLenum func, GLclampf ref)
GLAPI void GLAPIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor)
GLAPI void GLAPIENTRY glLogicOp (GLenum opcode)
GLAPI void GLAPIENTRY glCullFace (GLenum mode)
GLAPI void GLAPIENTRY glFrontFace (GLenum mode)
GLAPI void GLAPIENTRY glPointSize (GLfloat size)
GLAPI void GLAPIENTRY glLineWidth (GLfloat width)
GLAPI void GLAPIENTRY glLineStipple (GLint factor, GLushort pattern)
GLAPI void GLAPIENTRY glPolygonMode (GLenum face, GLenum mode)
GLAPI void GLAPIENTRY glPolygonOffset (GLfloat factor, GLfloat units)
GLAPI void GLAPIENTRY glPolygonStipple (const GLubyte *mask)
GLAPI void GLAPIENTRY glGetPolygonStipple (GLubyte *mask)
GLAPI void GLAPIENTRY glEdgeFlag (GLboolean flag)
GLAPI void GLAPIENTRY glEdgeFlagv (const GLboolean *flag)
GLAPI void GLAPIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height)
GLAPI void GLAPIENTRY glClipPlane (GLenum plane, const GLdouble *equation)
GLAPI void GLAPIENTRY glGetClipPlane (GLenum plane, GLdouble *equation)
GLAPI void GLAPIENTRY glDrawBuffer (GLenum mode)
GLAPI void GLAPIENTRY glReadBuffer (GLenum mode)
GLAPI void GLAPIENTRY glEnable (GLenum cap)
GLAPI void GLAPIENTRY glDisable (GLenum cap)
GLAPI GLboolean GLAPIENTRY glIsEnabled (GLenum cap)
GLAPI void GLAPIENTRY glEnableClientState (GLenum cap)
GLAPI void GLAPIENTRY glDisableClientState (GLenum cap)
GLAPI void GLAPIENTRY glGetBooleanv (GLenum pname, GLboolean *params)
GLAPI void GLAPIENTRY glGetDoublev (GLenum pname, GLdouble *params)
GLAPI void GLAPIENTRY glGetFloatv (GLenum pname, GLfloat *params)
GLAPI void GLAPIENTRY glGetIntegerv (GLenum pname, GLint *params)
GLAPI void GLAPIENTRY glPushAttrib (GLbitfield mask)
GLAPI void GLAPIENTRY glPopAttrib (void)
GLAPI void GLAPIENTRY glPushClientAttrib (GLbitfield mask)
GLAPI void GLAPIENTRY glPopClientAttrib (void)
GLAPI GLint GLAPIENTRY glRenderMode (GLenum mode)
GLAPI GLenum GLAPIENTRY glGetError (void)
const GLAPI GLubyte *GLAPIENTRY glGetString (GLenum name)
GLAPI void GLAPIENTRY glFinish (void)
GLAPI void GLAPIENTRY glFlush (void)
GLAPI void GLAPIENTRY glHint (GLenum target, GLenum mode)
GLAPI void GLAPIENTRY glClearDepth (GLclampd depth)
GLAPI void GLAPIENTRY glDepthFunc (GLenum func)
GLAPI void GLAPIENTRY glDepthMask (GLboolean flag)
GLAPI void GLAPIENTRY glDepthRange (GLclampd near_val, GLclampd far_val)
GLAPI void GLAPIENTRY glClearAccum (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
GLAPI void GLAPIENTRY glAccum (GLenum op, GLfloat value)
GLAPI void GLAPIENTRY glMatrixMode (GLenum mode)
GLAPI void GLAPIENTRY glOrtho (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val)
GLAPI void GLAPIENTRY glFrustum (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val)
GLAPI void GLAPIENTRY glViewport (GLint x, GLint y, GLsizei width, GLsizei height)
GLAPI void GLAPIENTRY glPushMatrix (void)
GLAPI void GLAPIENTRY glPopMatrix (void)
GLAPI void GLAPIENTRY glLoadIdentity (void)
GLAPI void GLAPIENTRY glLoadMatrixd (const GLdouble *m)
GLAPI void GLAPIENTRY glLoadMatrixf (const GLfloat *m)
GLAPI void GLAPIENTRY glMultMatrixd (const GLdouble *m)
GLAPI void GLAPIENTRY glMultMatrixf (const GLfloat *m)
GLAPI void GLAPIENTRY glRotated (GLdouble angle, GLdouble x, GLdouble y, GLdouble z)
GLAPI void GLAPIENTRY glRotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
GLAPI void GLAPIENTRY glScaled (GLdouble x, GLdouble y, GLdouble z)
GLAPI void GLAPIENTRY glScalef (GLfloat x, GLfloat y, GLfloat z)
GLAPI void GLAPIENTRY glTranslated (GLdouble x, GLdouble y, GLdouble z)
GLAPI void GLAPIENTRY glTranslatef (GLfloat x, GLfloat y, GLfloat z)
GLAPI GLboolean GLAPIENTRY glIsList (GLuint list)
GLAPI void GLAPIENTRY glDeleteLists (GLuint list, GLsizei range)
GLAPI GLuint GLAPIENTRY glGenLists (GLsizei range)
GLAPI void GLAPIENTRY glNewList (GLuint list, GLenum mode)
GLAPI void GLAPIENTRY glEndList (void)
GLAPI void GLAPIENTRY glCallList (GLuint list)
GLAPI void GLAPIENTRY glCallLists (GLsizei n, GLenum type, const GLvoid *lists)
GLAPI void GLAPIENTRY glListBase (GLuint base)
GLAPI void GLAPIENTRY glBegin (GLenum mode)
GLAPI void GLAPIENTRY glEnd (void)
GLAPI void GLAPIENTRY glVertex2d (GLdouble x, GLdouble y)
GLAPI void GLAPIENTRY glVertex2f (GLfloat x, GLfloat y)
GLAPI void GLAPIENTRY glVertex2i (GLint x, GLint y)
GLAPI void GLAPIENTRY glVertex2s (GLshort x, GLshort y)
GLAPI void GLAPIENTRY glVertex3d (GLdouble x, GLdouble y, GLdouble z)
GLAPI void GLAPIENTRY glVertex3f (GLfloat x, GLfloat y, GLfloat z)
GLAPI void GLAPIENTRY glVertex3i (GLint x, GLint y, GLint z)
GLAPI void GLAPIENTRY glVertex3s (GLshort x, GLshort y, GLshort z)
GLAPI void GLAPIENTRY glVertex4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
GLAPI void GLAPIENTRY glVertex4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
GLAPI void GLAPIENTRY glVertex4i (GLint x, GLint y, GLint z, GLint w)
GLAPI void GLAPIENTRY glVertex4s (GLshort x, GLshort y, GLshort z, GLshort w)
GLAPI void GLAPIENTRY glVertex2dv (const GLdouble *v)
GLAPI void GLAPIENTRY glVertex2fv (const GLfloat *v)
GLAPI void GLAPIENTRY glVertex2iv (const GLint *v)
GLAPI void GLAPIENTRY glVertex2sv (const GLshort *v)
GLAPI void GLAPIENTRY glVertex3dv (const GLdouble *v)
GLAPI void GLAPIENTRY glVertex3fv (const GLfloat *v)
GLAPI void GLAPIENTRY glVertex3iv (const GLint *v)
GLAPI void GLAPIENTRY glVertex3sv (const GLshort *v)
GLAPI void GLAPIENTRY glVertex4dv (const GLdouble *v)
GLAPI void GLAPIENTRY glVertex4fv (const GLfloat *v)
GLAPI void GLAPIENTRY glVertex4iv (const GLint *v)
GLAPI void GLAPIENTRY glVertex4sv (const GLshort *v)
GLAPI void GLAPIENTRY glNormal3b (GLbyte nx, GLbyte ny, GLbyte nz)
GLAPI void GLAPIENTRY glNormal3d (GLdouble nx, GLdouble ny, GLdouble nz)
GLAPI void GLAPIENTRY glNormal3f (GLfloat nx, GLfloat ny, GLfloat nz)
GLAPI void GLAPIENTRY glNormal3i (GLint nx, GLint ny, GLint nz)
GLAPI void GLAPIENTRY glNormal3s (GLshort nx, GLshort ny, GLshort nz)
GLAPI void GLAPIENTRY glNormal3bv (const GLbyte *v)
GLAPI void GLAPIENTRY glNormal3dv (const GLdouble *v)
GLAPI void GLAPIENTRY glNormal3fv (const GLfloat *v)
GLAPI void GLAPIENTRY glNormal3iv (const GLint *v)
GLAPI void GLAPIENTRY glNormal3sv (const GLshort *v)
GLAPI void GLAPIENTRY glIndexd (GLdouble c)
GLAPI void GLAPIENTRY glIndexf (GLfloat c)
GLAPI void GLAPIENTRY glIndexi (GLint c)
GLAPI void GLAPIENTRY glIndexs (GLshort c)
GLAPI void GLAPIENTRY glIndexub (GLubyte c)
GLAPI void GLAPIENTRY glIndexdv (const GLdouble *c)
GLAPI void GLAPIENTRY glIndexfv (const GLfloat *c)
GLAPI void GLAPIENTRY glIndexiv (const GLint *c)
GLAPI void GLAPIENTRY glIndexsv (const GLshort *c)
GLAPI void GLAPIENTRY glIndexubv (const GLubyte *c)
GLAPI void GLAPIENTRY glColor3b (GLbyte red, GLbyte green, GLbyte blue)
GLAPI void GLAPIENTRY glColor3d (GLdouble red, GLdouble green, GLdouble blue)
GLAPI void GLAPIENTRY glColor3f (GLfloat red, GLfloat green, GLfloat blue)
GLAPI void GLAPIENTRY glColor3i (GLint red, GLint green, GLint blue)
GLAPI void GLAPIENTRY glColor3s (GLshort red, GLshort green, GLshort blue)
GLAPI void GLAPIENTRY glColor3ub (GLubyte red, GLubyte green, GLubyte blue)
GLAPI void GLAPIENTRY glColor3ui (GLuint red, GLuint green, GLuint blue)
GLAPI void GLAPIENTRY glColor3us (GLushort red, GLushort green, GLushort blue)
GLAPI void GLAPIENTRY glColor4b (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha)
GLAPI void GLAPIENTRY glColor4d (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha)
GLAPI void GLAPIENTRY glColor4f (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
GLAPI void GLAPIENTRY glColor4i (GLint red, GLint green, GLint blue, GLint alpha)
GLAPI void GLAPIENTRY glColor4s (GLshort red, GLshort green, GLshort blue, GLshort alpha)
GLAPI void GLAPIENTRY glColor4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
GLAPI void GLAPIENTRY glColor4ui (GLuint red, GLuint green, GLuint blue, GLuint alpha)
GLAPI void GLAPIENTRY glColor4us (GLushort red, GLushort green, GLushort blue, GLushort alpha)
GLAPI void GLAPIENTRY glColor3bv (const GLbyte *v)
GLAPI void GLAPIENTRY glColor3dv (const GLdouble *v)
GLAPI void GLAPIENTRY glColor3fv (const GLfloat *v)
GLAPI void GLAPIENTRY glColor3iv (const GLint *v)
GLAPI void GLAPIENTRY glColor3sv (const GLshort *v)
GLAPI void GLAPIENTRY glColor3ubv (const GLubyte *v)
GLAPI void GLAPIENTRY glColor3uiv (const GLuint *v)
GLAPI void GLAPIENTRY glColor3usv (const GLushort *v)
GLAPI void GLAPIENTRY glColor4bv (const GLbyte *v)
GLAPI void GLAPIENTRY glColor4dv (const GLdouble *v)
GLAPI void GLAPIENTRY glColor4fv (const GLfloat *v)
GLAPI void GLAPIENTRY glColor4iv (const GLint *v)
GLAPI void GLAPIENTRY glColor4sv (const GLshort *v)
GLAPI void GLAPIENTRY glColor4ubv (const GLubyte *v)
GLAPI void GLAPIENTRY glColor4uiv (const GLuint *v)
GLAPI void GLAPIENTRY glColor4usv (const GLushort *v)
GLAPI void GLAPIENTRY glTexCoord1d (GLdouble s)
GLAPI void GLAPIENTRY glTexCoord1f (GLfloat s)
GLAPI void GLAPIENTRY glTexCoord1i (GLint s)
GLAPI void GLAPIENTRY glTexCoord1s (GLshort s)
GLAPI void GLAPIENTRY glTexCoord2d (GLdouble s, GLdouble t)
GLAPI void GLAPIENTRY glTexCoord2f (GLfloat s, GLfloat t)
GLAPI void GLAPIENTRY glTexCoord2i (GLint s, GLint t)
GLAPI void GLAPIENTRY glTexCoord2s (GLshort s, GLshort t)
GLAPI void GLAPIENTRY glTexCoord3d (GLdouble s, GLdouble t, GLdouble r)
GLAPI void GLAPIENTRY glTexCoord3f (GLfloat s, GLfloat t, GLfloat r)
GLAPI void GLAPIENTRY glTexCoord3i (GLint s, GLint t, GLint r)
GLAPI void GLAPIENTRY glTexCoord3s (GLshort s, GLshort t, GLshort r)
GLAPI void GLAPIENTRY glTexCoord4d (GLdouble s, GLdouble t, GLdouble r, GLdouble q)
GLAPI void GLAPIENTRY glTexCoord4f (GLfloat s, GLfloat t, GLfloat r, GLfloat q)
GLAPI void GLAPIENTRY glTexCoord4i (GLint s, GLint t, GLint r, GLint q)
GLAPI void GLAPIENTRY glTexCoord4s (GLshort s, GLshort t, GLshort r, GLshort q)
GLAPI void GLAPIENTRY glTexCoord1dv (const GLdouble *v)
GLAPI void GLAPIENTRY glTexCoord1fv (const GLfloat *v)
GLAPI void GLAPIENTRY glTexCoord1iv (const GLint *v)
GLAPI void GLAPIENTRY glTexCoord1sv (const GLshort *v)
GLAPI void GLAPIENTRY glTexCoord2dv (const GLdouble *v)
GLAPI void GLAPIENTRY glTexCoord2fv (const GLfloat *v)
GLAPI void GLAPIENTRY glTexCoord2iv (const GLint *v)
GLAPI void GLAPIENTRY glTexCoord2sv (const GLshort *v)
GLAPI void GLAPIENTRY glTexCoord3dv (const GLdouble *v)
GLAPI void GLAPIENTRY glTexCoord3fv (const GLfloat *v)
GLAPI void GLAPIENTRY glTexCoord3iv (const GLint *v)
GLAPI void GLAPIENTRY glTexCoord3sv (const GLshort *v)
GLAPI void GLAPIENTRY glTexCoord4dv (const GLdouble *v)
GLAPI void GLAPIENTRY glTexCoord4fv (const GLfloat *v)
GLAPI void GLAPIENTRY glTexCoord4iv (const GLint *v)
GLAPI void GLAPIENTRY glTexCoord4sv (const GLshort *v)
GLAPI void GLAPIENTRY glRasterPos2d (GLdouble x, GLdouble y)
GLAPI void GLAPIENTRY glRasterPos2f (GLfloat x, GLfloat y)
GLAPI void GLAPIENTRY glRasterPos2i (GLint x, GLint y)
GLAPI void GLAPIENTRY glRasterPos2s (GLshort x, GLshort y)
GLAPI void GLAPIENTRY glRasterPos3d (GLdouble x, GLdouble y, GLdouble z)
GLAPI void GLAPIENTRY glRasterPos3f (GLfloat x, GLfloat y, GLfloat z)
GLAPI void GLAPIENTRY glRasterPos3i (GLint x, GLint y, GLint z)
GLAPI void GLAPIENTRY glRasterPos3s (GLshort x, GLshort y, GLshort z)
GLAPI void GLAPIENTRY glRasterPos4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
GLAPI void GLAPIENTRY glRasterPos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
GLAPI void GLAPIENTRY glRasterPos4i (GLint x, GLint y, GLint z, GLint w)
GLAPI void GLAPIENTRY glRasterPos4s (GLshort x, GLshort y, GLshort z, GLshort w)
GLAPI void GLAPIENTRY glRasterPos2dv (const GLdouble *v)
GLAPI void GLAPIENTRY glRasterPos2fv (const GLfloat *v)
GLAPI void GLAPIENTRY glRasterPos2iv (const GLint *v)
GLAPI void GLAPIENTRY glRasterPos2sv (const GLshort *v)
GLAPI void GLAPIENTRY glRasterPos3dv (const GLdouble *v)
GLAPI void GLAPIENTRY glRasterPos3fv (const GLfloat *v)
GLAPI void GLAPIENTRY glRasterPos3iv (const GLint *v)
GLAPI void GLAPIENTRY glRasterPos3sv (const GLshort *v)
GLAPI void GLAPIENTRY glRasterPos4dv (const GLdouble *v)
GLAPI void GLAPIENTRY glRasterPos4fv (const GLfloat *v)
GLAPI void GLAPIENTRY glRasterPos4iv (const GLint *v)
GLAPI void GLAPIENTRY glRasterPos4sv (const GLshort *v)
GLAPI void GLAPIENTRY glRectd (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2)
GLAPI void GLAPIENTRY glRectf (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2)
GLAPI void GLAPIENTRY glRecti (GLint x1, GLint y1, GLint x2, GLint y2)
GLAPI void GLAPIENTRY glRects (GLshort x1, GLshort y1, GLshort x2, GLshort y2)
GLAPI void GLAPIENTRY glRectdv (const GLdouble *v1, const GLdouble *v2)
GLAPI void GLAPIENTRY glRectfv (const GLfloat *v1, const GLfloat *v2)
GLAPI void GLAPIENTRY glRectiv (const GLint *v1, const GLint *v2)
GLAPI void GLAPIENTRY glRectsv (const GLshort *v1, const GLshort *v2)
GLAPI void GLAPIENTRY glVertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
GLAPI void GLAPIENTRY glNormalPointer (GLenum type, GLsizei stride, const GLvoid *ptr)
GLAPI void GLAPIENTRY glColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
GLAPI void GLAPIENTRY glIndexPointer (GLenum type, GLsizei stride, const GLvoid *ptr)
GLAPI void GLAPIENTRY glTexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid *ptr)
GLAPI void GLAPIENTRY glEdgeFlagPointer (GLsizei stride, const GLvoid *ptr)
GLAPI void GLAPIENTRY glGetPointerv (GLenum pname, GLvoid **params)
GLAPI void GLAPIENTRY glArrayElement (GLint i)
GLAPI void GLAPIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count)
GLAPI void GLAPIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid *indices)
GLAPI void GLAPIENTRY glInterleavedArrays (GLenum format, GLsizei stride, const GLvoid *pointer)
GLAPI void GLAPIENTRY glShadeModel (GLenum mode)
GLAPI void GLAPIENTRY glLightf (GLenum light, GLenum pname, GLfloat param)
GLAPI void GLAPIENTRY glLighti (GLenum light, GLenum pname, GLint param)
GLAPI void GLAPIENTRY glLightfv (GLenum light, GLenum pname, const GLfloat *params)
GLAPI void GLAPIENTRY glLightiv (GLenum light, GLenum pname, const GLint *params)
GLAPI void GLAPIENTRY glGetLightfv (GLenum light, GLenum pname, GLfloat *params)
GLAPI void GLAPIENTRY glGetLightiv (GLenum light, GLenum pname, GLint *params)
GLAPI void GLAPIENTRY glLightModelf (GLenum pname, GLfloat param)
GLAPI void GLAPIENTRY glLightModeli (GLenum pname, GLint param)
GLAPI void GLAPIENTRY glLightModelfv (GLenum pname, const GLfloat *params)
GLAPI void GLAPIENTRY glLightModeliv (GLenum pname, const GLint *params)
GLAPI void GLAPIENTRY glMaterialf (GLenum face, GLenum pname, GLfloat param)
GLAPI void GLAPIENTRY glMateriali (GLenum face, GLenum pname, GLint param)
GLAPI void GLAPIENTRY glMaterialfv (GLenum face, GLenum pname, const GLfloat *params)
GLAPI void GLAPIENTRY glMaterialiv (GLenum face, GLenum pname, const GLint *params)
GLAPI void GLAPIENTRY glGetMaterialfv (GLenum face, GLenum pname, GLfloat *params)
GLAPI void GLAPIENTRY glGetMaterialiv (GLenum face, GLenum pname, GLint *params)
GLAPI void GLAPIENTRY glColorMaterial (GLenum face, GLenum mode)
GLAPI void GLAPIENTRY glPixelZoom (GLfloat xfactor, GLfloat yfactor)
GLAPI void GLAPIENTRY glPixelStoref (GLenum pname, GLfloat param)
GLAPI void GLAPIENTRY glPixelStorei (GLenum pname, GLint param)
GLAPI void GLAPIENTRY glPixelTransferf (GLenum pname, GLfloat param)
GLAPI void GLAPIENTRY glPixelTransferi (GLenum pname, GLint param)
GLAPI void GLAPIENTRY glPixelMapfv (GLenum map, GLsizei mapsize, const GLfloat *values)
GLAPI void GLAPIENTRY glPixelMapuiv (GLenum map, GLsizei mapsize, const GLuint *values)
GLAPI void GLAPIENTRY glPixelMapusv (GLenum map, GLsizei mapsize, const GLushort *values)
GLAPI void GLAPIENTRY glGetPixelMapfv (GLenum map, GLfloat *values)
GLAPI void GLAPIENTRY glGetPixelMapuiv (GLenum map, GLuint *values)
GLAPI void GLAPIENTRY glGetPixelMapusv (GLenum map, GLushort *values)
GLAPI void GLAPIENTRY glBitmap (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte *bitmap)
GLAPI void GLAPIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid *pixels)
GLAPI void GLAPIENTRY glDrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
GLAPI void GLAPIENTRY glCopyPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type)
GLAPI void GLAPIENTRY glStencilFunc (GLenum func, GLint ref, GLuint mask)
GLAPI void GLAPIENTRY glStencilMask (GLuint mask)
GLAPI void GLAPIENTRY glStencilOp (GLenum fail, GLenum zfail, GLenum zpass)
GLAPI void GLAPIENTRY glClearStencil (GLint s)
GLAPI void GLAPIENTRY glTexGend (GLenum coord, GLenum pname, GLdouble param)
GLAPI void GLAPIENTRY glTexGenf (GLenum coord, GLenum pname, GLfloat param)
GLAPI void GLAPIENTRY glTexGeni (GLenum coord, GLenum pname, GLint param)
GLAPI void GLAPIENTRY glTexGendv (GLenum coord, GLenum pname, const GLdouble *params)
GLAPI void GLAPIENTRY glTexGenfv (GLenum coord, GLenum pname, const GLfloat *params)
GLAPI void GLAPIENTRY glTexGeniv (GLenum coord, GLenum pname, const GLint *params)
GLAPI void GLAPIENTRY glGetTexGendv (GLenum coord, GLenum pname, GLdouble *params)
GLAPI void GLAPIENTRY glGetTexGenfv (GLenum coord, GLenum pname, GLfloat *params)
GLAPI void GLAPIENTRY glGetTexGeniv (GLenum coord, GLenum pname, GLint *params)
GLAPI void GLAPIENTRY glTexEnvf (GLenum target, GLenum pname, GLfloat param)
GLAPI void GLAPIENTRY glTexEnvi (GLenum target, GLenum pname, GLint param)
GLAPI void GLAPIENTRY glTexEnvfv (GLenum target, GLenum pname, const GLfloat *params)
GLAPI void GLAPIENTRY glTexEnviv (GLenum target, GLenum pname, const GLint *params)
GLAPI void GLAPIENTRY glGetTexEnvfv (GLenum target, GLenum pname, GLfloat *params)
GLAPI void GLAPIENTRY glGetTexEnviv (GLenum target, GLenum pname, GLint *params)
GLAPI void GLAPIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param)
GLAPI void GLAPIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param)
GLAPI void GLAPIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat *params)
GLAPI void GLAPIENTRY glTexParameteriv (GLenum target, GLenum pname, const GLint *params)
GLAPI void GLAPIENTRY glGetTexParameterfv (GLenum target, GLenum pname, GLfloat *params)
GLAPI void GLAPIENTRY glGetTexParameteriv (GLenum target, GLenum pname, GLint *params)
GLAPI void GLAPIENTRY glGetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat *params)
GLAPI void GLAPIENTRY glGetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint *params)
GLAPI void GLAPIENTRY glTexImage1D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
GLAPI void GLAPIENTRY glTexImage2D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
GLAPI void GLAPIENTRY glGetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid *pixels)
GLAPI void GLAPIENTRY glGenTextures (GLsizei n, GLuint *textures)
GLAPI void GLAPIENTRY glDeleteTextures (GLsizei n, const GLuint *textures)
GLAPI void GLAPIENTRY glBindTexture (GLenum target, GLuint texture)
GLAPI void GLAPIENTRY glPrioritizeTextures (GLsizei n, const GLuint *textures, const GLclampf *priorities)
GLAPI GLboolean GLAPIENTRY glAreTexturesResident (GLsizei n, const GLuint *textures, GLboolean *residences)
GLAPI GLboolean GLAPIENTRY glIsTexture (GLuint texture)
GLAPI void GLAPIENTRY glTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid *pixels)
GLAPI void GLAPIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *pixels)
GLAPI void GLAPIENTRY glCopyTexImage1D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border)
GLAPI void GLAPIENTRY glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
GLAPI void GLAPIENTRY glCopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
GLAPI void GLAPIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
GLAPI void GLAPIENTRY glMap1d (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble *points)
GLAPI void GLAPIENTRY glMap1f (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat *points)
GLAPI void GLAPIENTRY glMap2d (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble *points)
GLAPI void GLAPIENTRY glMap2f (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat *points)
GLAPI void GLAPIENTRY glGetMapdv (GLenum target, GLenum query, GLdouble *v)
GLAPI void GLAPIENTRY glGetMapfv (GLenum target, GLenum query, GLfloat *v)
GLAPI void GLAPIENTRY glGetMapiv (GLenum target, GLenum query, GLint *v)
GLAPI void GLAPIENTRY glEvalCoord1d (GLdouble u)
GLAPI void GLAPIENTRY glEvalCoord1f (GLfloat u)
GLAPI void GLAPIENTRY glEvalCoord1dv (const GLdouble *u)
GLAPI void GLAPIENTRY glEvalCoord1fv (const GLfloat *u)
GLAPI void GLAPIENTRY glEvalCoord2d (GLdouble u, GLdouble v)
GLAPI void GLAPIENTRY glEvalCoord2f (GLfloat u, GLfloat v)
GLAPI void GLAPIENTRY glEvalCoord2dv (const GLdouble *u)
GLAPI void GLAPIENTRY glEvalCoord2fv (const GLfloat *u)
GLAPI void GLAPIENTRY glMapGrid1d (GLint un, GLdouble u1, GLdouble u2)
GLAPI void GLAPIENTRY glMapGrid1f (GLint un, GLfloat u1, GLfloat u2)
GLAPI void GLAPIENTRY glMapGrid2d (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2)
GLAPI void GLAPIENTRY glMapGrid2f (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2)
GLAPI void GLAPIENTRY glEvalPoint1 (GLint i)
GLAPI void GLAPIENTRY glEvalPoint2 (GLint i, GLint j)
GLAPI void GLAPIENTRY glEvalMesh1 (GLenum mode, GLint i1, GLint i2)
GLAPI void GLAPIENTRY glEvalMesh2 (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2)
GLAPI void GLAPIENTRY glFogf (GLenum pname, GLfloat param)
GLAPI void GLAPIENTRY glFogi (GLenum pname, GLint param)
GLAPI void GLAPIENTRY glFogfv (GLenum pname, const GLfloat *params)
GLAPI void GLAPIENTRY glFogiv (GLenum pname, const GLint *params)
GLAPI void GLAPIENTRY glFeedbackBuffer (GLsizei size, GLenum type, GLfloat *buffer)
GLAPI void GLAPIENTRY glPassThrough (GLfloat token)
GLAPI void GLAPIENTRY glSelectBuffer (GLsizei size, GLuint *buffer)
GLAPI void GLAPIENTRY glInitNames (void)
GLAPI void GLAPIENTRY glLoadName (GLuint name)
GLAPI void GLAPIENTRY glPushName (GLuint name)
GLAPI void GLAPIENTRY glPopName (void)
GLAPI void GLAPIENTRY glDrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid *indices)
GLAPI void GLAPIENTRY glTexImage3D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid *pixels)
GLAPI void GLAPIENTRY glTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid *pixels)
GLAPI void GLAPIENTRY glCopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
typedef void (APIENTRYP PFNGLDRAWRANGEELEMENTSPROC)(GLenum mode
GLAPI void GLAPIENTRY glColorTable (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *table)
GLAPI void GLAPIENTRY glColorSubTable (GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid *data)
GLAPI void GLAPIENTRY glColorTableParameteriv (GLenum target, GLenum pname, const GLint *params)
GLAPI void GLAPIENTRY glColorTableParameterfv (GLenum target, GLenum pname, const GLfloat *params)
GLAPI void GLAPIENTRY glCopyColorSubTable (GLenum target, GLsizei start, GLint x, GLint y, GLsizei width)
GLAPI void GLAPIENTRY glCopyColorTable (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
GLAPI void GLAPIENTRY glGetColorTable (GLenum target, GLenum format, GLenum type, GLvoid *table)
GLAPI void GLAPIENTRY glGetColorTableParameterfv (GLenum target, GLenum pname, GLfloat *params)
GLAPI void GLAPIENTRY glGetColorTableParameteriv (GLenum target, GLenum pname, GLint *params)
GLAPI void GLAPIENTRY glBlendEquation (GLenum mode)
GLAPI void GLAPIENTRY glBlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
GLAPI void GLAPIENTRY glHistogram (GLenum target, GLsizei width, GLenum internalformat, GLboolean sink)
GLAPI void GLAPIENTRY glResetHistogram (GLenum target)
GLAPI void GLAPIENTRY glGetHistogram (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid *values)
GLAPI void GLAPIENTRY glGetHistogramParameterfv (GLenum target, GLenum pname, GLfloat *params)
GLAPI void GLAPIENTRY glGetHistogramParameteriv (GLenum target, GLenum pname, GLint *params)
GLAPI void GLAPIENTRY glMinmax (GLenum target, GLenum internalformat, GLboolean sink)
GLAPI void GLAPIENTRY glResetMinmax (GLenum target)
GLAPI void GLAPIENTRY glGetMinmax (GLenum target, GLboolean reset, GLenum format, GLenum types, GLvoid *values)
GLAPI void GLAPIENTRY glGetMinmaxParameterfv (GLenum target, GLenum pname, GLfloat *params)
GLAPI void GLAPIENTRY glGetMinmaxParameteriv (GLenum target, GLenum pname, GLint *params)
GLAPI void GLAPIENTRY glConvolutionFilter1D (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid *image)
GLAPI void GLAPIENTRY glConvolutionFilter2D (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *image)
GLAPI void GLAPIENTRY glConvolutionParameterf (GLenum target, GLenum pname, GLfloat params)
GLAPI void GLAPIENTRY glConvolutionParameterfv (GLenum target, GLenum pname, const GLfloat *params)
GLAPI void GLAPIENTRY glConvolutionParameteri (GLenum target, GLenum pname, GLint params)
GLAPI void GLAPIENTRY glConvolutionParameteriv (GLenum target, GLenum pname, const GLint *params)
GLAPI void GLAPIENTRY glCopyConvolutionFilter1D (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
GLAPI void GLAPIENTRY glCopyConvolutionFilter2D (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height)
GLAPI void GLAPIENTRY glGetConvolutionFilter (GLenum target, GLenum format, GLenum type, GLvoid *image)
GLAPI void GLAPIENTRY glGetConvolutionParameterfv (GLenum target, GLenum pname, GLfloat *params)
GLAPI void GLAPIENTRY glGetConvolutionParameteriv (GLenum target, GLenum pname, GLint *params)
GLAPI void GLAPIENTRY glSeparableFilter2D (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid *row, const GLvoid *column)
GLAPI void GLAPIENTRY glGetSeparableFilter (GLenum target, GLenum format, GLenum type, GLvoid *row, GLvoid *column, GLvoid *span)
GLAPI void GLAPIENTRY glActiveTexture (GLenum texture)
GLAPI void GLAPIENTRY glClientActiveTexture (GLenum texture)
GLAPI void GLAPIENTRY glCompressedTexImage1D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid *data)
GLAPI void GLAPIENTRY glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid *data)
GLAPI void GLAPIENTRY glCompressedTexImage3D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid *data)
GLAPI void GLAPIENTRY glCompressedTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid *data)
GLAPI void GLAPIENTRY glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid *data)
GLAPI void GLAPIENTRY glCompressedTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid *data)
GLAPI void GLAPIENTRY glGetCompressedTexImage (GLenum target, GLint lod, GLvoid *img)
GLAPI void GLAPIENTRY glMultiTexCoord1d (GLenum target, GLdouble s)
GLAPI void GLAPIENTRY glMultiTexCoord1dv (GLenum target, const GLdouble *v)
GLAPI void GLAPIENTRY glMultiTexCoord1f (GLenum target, GLfloat s)
GLAPI void GLAPIENTRY glMultiTexCoord1fv (GLenum target, const GLfloat *v)
GLAPI void GLAPIENTRY glMultiTexCoord1i (GLenum target, GLint s)
GLAPI void GLAPIENTRY glMultiTexCoord1iv (GLenum target, const GLint *v)
GLAPI void GLAPIENTRY glMultiTexCoord1s (GLenum target, GLshort s)
GLAPI void GLAPIENTRY glMultiTexCoord1sv (GLenum target, const GLshort *v)
GLAPI void GLAPIENTRY glMultiTexCoord2d (GLenum target, GLdouble s, GLdouble t)
GLAPI void GLAPIENTRY glMultiTexCoord2dv (GLenum target, const GLdouble *v)
GLAPI void GLAPIENTRY glMultiTexCoord2f (GLenum target, GLfloat s, GLfloat t)
GLAPI void GLAPIENTRY glMultiTexCoord2fv (GLenum target, const GLfloat *v)
GLAPI void GLAPIENTRY glMultiTexCoord2i (GLenum target, GLint s, GLint t)
GLAPI void GLAPIENTRY glMultiTexCoord2iv (GLenum target, const GLint *v)
GLAPI void GLAPIENTRY glMultiTexCoord2s (GLenum target, GLshort s, GLshort t)
GLAPI void GLAPIENTRY glMultiTexCoord2sv (GLenum target, const GLshort *v)
GLAPI void GLAPIENTRY glMultiTexCoord3d (GLenum target, GLdouble s, GLdouble t, GLdouble r)
GLAPI void GLAPIENTRY glMultiTexCoord3dv (GLenum target, const GLdouble *v)
GLAPI void GLAPIENTRY glMultiTexCoord3f (GLenum target, GLfloat s, GLfloat t, GLfloat r)
GLAPI void GLAPIENTRY glMultiTexCoord3fv (GLenum target, const GLfloat *v)
GLAPI void GLAPIENTRY glMultiTexCoord3i (GLenum target, GLint s, GLint t, GLint r)
GLAPI void GLAPIENTRY glMultiTexCoord3iv (GLenum target, const GLint *v)
GLAPI void GLAPIENTRY glMultiTexCoord3s (GLenum target, GLshort s, GLshort t, GLshort r)
GLAPI void GLAPIENTRY glMultiTexCoord3sv (GLenum target, const GLshort *v)
GLAPI void GLAPIENTRY glMultiTexCoord4d (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
GLAPI void GLAPIENTRY glMultiTexCoord4dv (GLenum target, const GLdouble *v)
GLAPI void GLAPIENTRY glMultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
GLAPI void GLAPIENTRY glMultiTexCoord4fv (GLenum target, const GLfloat *v)
GLAPI void GLAPIENTRY glMultiTexCoord4i (GLenum target, GLint s, GLint t, GLint r, GLint q)
GLAPI void GLAPIENTRY glMultiTexCoord4iv (GLenum target, const GLint *v)
GLAPI void GLAPIENTRY glMultiTexCoord4s (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
GLAPI void GLAPIENTRY glMultiTexCoord4sv (GLenum target, const GLshort *v)
GLAPI void GLAPIENTRY glLoadTransposeMatrixd (const GLdouble m[16])
GLAPI void GLAPIENTRY glLoadTransposeMatrixf (const GLfloat m[16])
GLAPI void GLAPIENTRY glMultTransposeMatrixd (const GLdouble m[16])
GLAPI void GLAPIENTRY glMultTransposeMatrixf (const GLfloat m[16])
GLAPI void GLAPIENTRY glSampleCoverage (GLclampf value, GLboolean invert)
GLAPI void GLAPIENTRY glActiveTextureARB (GLenum texture)
GLAPI void GLAPIENTRY glClientActiveTextureARB (GLenum texture)
GLAPI void GLAPIENTRY glMultiTexCoord1dARB (GLenum target, GLdouble s)
GLAPI void GLAPIENTRY glMultiTexCoord1dvARB (GLenum target, const GLdouble *v)
GLAPI void GLAPIENTRY glMultiTexCoord1fARB (GLenum target, GLfloat s)
GLAPI void GLAPIENTRY glMultiTexCoord1fvARB (GLenum target, const GLfloat *v)
GLAPI void GLAPIENTRY glMultiTexCoord1iARB (GLenum target, GLint s)
GLAPI void GLAPIENTRY glMultiTexCoord1ivARB (GLenum target, const GLint *v)
GLAPI void GLAPIENTRY glMultiTexCoord1sARB (GLenum target, GLshort s)
GLAPI void GLAPIENTRY glMultiTexCoord1svARB (GLenum target, const GLshort *v)
GLAPI void GLAPIENTRY glMultiTexCoord2dARB (GLenum target, GLdouble s, GLdouble t)
GLAPI void GLAPIENTRY glMultiTexCoord2dvARB (GLenum target, const GLdouble *v)
GLAPI void GLAPIENTRY glMultiTexCoord2fARB (GLenum target, GLfloat s, GLfloat t)
GLAPI void GLAPIENTRY glMultiTexCoord2fvARB (GLenum target, const GLfloat *v)
GLAPI void GLAPIENTRY glMultiTexCoord2iARB (GLenum target, GLint s, GLint t)
GLAPI void GLAPIENTRY glMultiTexCoord2ivARB (GLenum target, const GLint *v)
GLAPI void GLAPIENTRY glMultiTexCoord2sARB (GLenum target, GLshort s, GLshort t)
GLAPI void GLAPIENTRY glMultiTexCoord2svARB (GLenum target, const GLshort *v)
GLAPI void GLAPIENTRY glMultiTexCoord3dARB (GLenum target, GLdouble s, GLdouble t, GLdouble r)
GLAPI void GLAPIENTRY glMultiTexCoord3dvARB (GLenum target, const GLdouble *v)
GLAPI void GLAPIENTRY glMultiTexCoord3fARB (GLenum target, GLfloat s, GLfloat t, GLfloat r)
GLAPI void GLAPIENTRY glMultiTexCoord3fvARB (GLenum target, const GLfloat *v)
GLAPI void GLAPIENTRY glMultiTexCoord3iARB (GLenum target, GLint s, GLint t, GLint r)
GLAPI void GLAPIENTRY glMultiTexCoord3ivARB (GLenum target, const GLint *v)
GLAPI void GLAPIENTRY glMultiTexCoord3sARB (GLenum target, GLshort s, GLshort t, GLshort r)
GLAPI void GLAPIENTRY glMultiTexCoord3svARB (GLenum target, const GLshort *v)
GLAPI void GLAPIENTRY glMultiTexCoord4dARB (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
GLAPI void GLAPIENTRY glMultiTexCoord4dvARB (GLenum target, const GLdouble *v)
GLAPI void GLAPIENTRY glMultiTexCoord4fARB (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
GLAPI void GLAPIENTRY glMultiTexCoord4fvARB (GLenum target, const GLfloat *v)
GLAPI void GLAPIENTRY glMultiTexCoord4iARB (GLenum target, GLint s, GLint t, GLint r, GLint q)
GLAPI void GLAPIENTRY glMultiTexCoord4ivARB (GLenum target, const GLint *v)
GLAPI void GLAPIENTRY glMultiTexCoord4sARB (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
GLAPI void GLAPIENTRY glMultiTexCoord4svARB (GLenum target, const GLshort *v)
GLAPI void GLAPIENTRY glBlendEquationSeparateATI (GLenum modeRGB, GLenum modeA)
Detailed Description
This is a simple file to encapsulate the OpenGL API headers.
Definition in file SDL_opengl.h.
Macro Definition Documentation
__gl_h_
#define __gl_h_
Definition at line 69 of file SDL_opengl.h.
APIENTRY
#define APIENTRY GLAPIENTRY
Definition at line 139 of file SDL_opengl.h.
APIENTRYP
#define APIENTRYP APIENTRY *
Definition at line 144 of file SDL_opengl.h.
GL_2_BYTES
#define GL_2_BYTES 0x1407
Definition at line 210 of file SDL_opengl.h.
GL_2D
#define GL_2D 0x0600
Definition at line 418 of file SDL_opengl.h.
GL_3_BYTES
#define GL_3_BYTES 0x1408
Definition at line 211 of file SDL_opengl.h.
GL_3D
#define GL_3D 0x0601
Definition at line 419 of file SDL_opengl.h.
GL_3D_COLOR
#define GL_3D_COLOR 0x0602
Definition at line 420 of file SDL_opengl.h.
GL_3D_COLOR_TEXTURE
#define GL_3D_COLOR_TEXTURE 0x0603
Definition at line 421 of file SDL_opengl.h.
GL_4_BYTES
#define GL_4_BYTES 0x1409
Definition at line 212 of file SDL_opengl.h.
GL_4D_COLOR_TEXTURE
#define GL_4D_COLOR_TEXTURE 0x0604
Definition at line 422 of file SDL_opengl.h.
GL_ACCUM
#define GL_ACCUM 0x0100
Definition at line 385 of file SDL_opengl.h.
GL_ACCUM_ALPHA_BITS
#define GL_ACCUM_ALPHA_BITS 0x0D5B
Definition at line 383 of file SDL_opengl.h.
GL_ACCUM_BLUE_BITS
#define GL_ACCUM_BLUE_BITS 0x0D5A
Definition at line 382 of file SDL_opengl.h.
GL_ACCUM_BUFFER_BIT
#define GL_ACCUM_BUFFER_BIT 0x00000200
Definition at line 737 of file SDL_opengl.h.
GL_ACCUM_CLEAR_VALUE
#define GL_ACCUM_CLEAR_VALUE 0x0B80
Definition at line 384 of file SDL_opengl.h.
GL_ACCUM_GREEN_BITS
#define GL_ACCUM_GREEN_BITS 0x0D59
Definition at line 381 of file SDL_opengl.h.
GL_ACCUM_RED_BITS
#define GL_ACCUM_RED_BITS 0x0D58
Definition at line 380 of file SDL_opengl.h.
GL_ACTIVE_TEXTURE
#define GL_ACTIVE_TEXTURE 0x84E0
Definition at line 1806 of file SDL_opengl.h.
GL_ACTIVE_TEXTURE_ARB
#define GL_ACTIVE_TEXTURE_ARB 0x84E0
Definition at line 2022 of file SDL_opengl.h.
GL_ADD
#define GL_ADD 0x0104
Definition at line 386 of file SDL_opengl.h.
GL_ADD_SIGNED
#define GL_ADD_SIGNED 0x8574
Definition at line 1866 of file SDL_opengl.h.
GL_ALIASED_LINE_WIDTH_RANGE
#define GL_ALIASED_LINE_WIDTH_RANGE 0x846E
Definition at line 1536 of file SDL_opengl.h.
GL_ALIASED_POINT_SIZE_RANGE
#define GL_ALIASED_POINT_SIZE_RANGE 0x846D
Definition at line 1535 of file SDL_opengl.h.
GL_ALL_ATTRIB_BITS
#define GL_ALL_ATTRIB_BITS 0x000FFFFF
Definition at line 748 of file SDL_opengl.h.
GL_ALL_CLIENT_ATTRIB_BITS
#define GL_ALL_CLIENT_ATTRIB_BITS 0xFFFFFFFF
Definition at line 794 of file SDL_opengl.h.
GL_ALPHA
#define GL_ALPHA 0x1906
Definition at line 509 of file SDL_opengl.h.
GL_ALPHA12
#define GL_ALPHA12 0x803D
Definition at line 761 of file SDL_opengl.h.
GL_ALPHA16
#define GL_ALPHA16 0x803E
Definition at line 762 of file SDL_opengl.h.
GL_ALPHA4
#define GL_ALPHA4 0x803B
Definition at line 759 of file SDL_opengl.h.
GL_ALPHA8
#define GL_ALPHA8 0x803C
Definition at line 760 of file SDL_opengl.h.
GL_ALPHA_BIAS
#define GL_ALPHA_BIAS 0x0D1D
Definition at line 629 of file SDL_opengl.h.
GL_ALPHA_BITS
#define GL_ALPHA_BITS 0x0D55
Definition at line 512 of file SDL_opengl.h.
GL_ALPHA_BLEND_EQUATION_ATI
#define GL_ALPHA_BLEND_EQUATION_ATI 0x883D
Definition at line 2129 of file SDL_opengl.h.
GL_ALPHA_SCALE
#define GL_ALPHA_SCALE 0x0D1C
Definition at line 628 of file SDL_opengl.h.
GL_ALPHA_TEST
#define GL_ALPHA_TEST 0x0BC0
Definition at line 392 of file SDL_opengl.h.
GL_ALPHA_TEST_FUNC
#define GL_ALPHA_TEST_FUNC 0x0BC1
Definition at line 394 of file SDL_opengl.h.
GL_ALPHA_TEST_REF
#define GL_ALPHA_TEST_REF 0x0BC2
Definition at line 393 of file SDL_opengl.h.
GL_ALWAYS
#define GL_ALWAYS 0x0207
Definition at line 326 of file SDL_opengl.h.
GL_AMBIENT
#define GL_AMBIENT 0x1200
Definition at line 350 of file SDL_opengl.h.
GL_AMBIENT_AND_DIFFUSE
#define GL_AMBIENT_AND_DIFFUSE 0x1602
Definition at line 357 of file SDL_opengl.h.
GL_AND
#define GL_AND 0x1501
Definition at line 462 of file SDL_opengl.h.
GL_AND_INVERTED
#define GL_AND_INVERTED 0x1504
Definition at line 469 of file SDL_opengl.h.
GL_AND_REVERSE
#define GL_AND_REVERSE 0x1502
Definition at line 468 of file SDL_opengl.h.
GL_ARB_imaging
#define GL_ARB_imaging 1
Definition at line 170 of file SDL_opengl.h.
GL_ARB_multitexture
#define GL_ARB_multitexture 1
Definition at line 1988 of file SDL_opengl.h.
GL_ATI_blend_equation_separate
#define GL_ATI_blend_equation_separate 1
Definition at line 2127 of file SDL_opengl.h.
GL_ATTRIB_STACK_DEPTH
#define GL_ATTRIB_STACK_DEPTH 0x0BB0
Definition at line 547 of file SDL_opengl.h.
GL_AUTO_NORMAL
#define GL_AUTO_NORMAL 0x0D80
Definition at line 576 of file SDL_opengl.h.
GL_AUX0
#define GL_AUX0 0x0409
Definition at line 501 of file SDL_opengl.h.
GL_AUX1
#define GL_AUX1 0x040A
Definition at line 502 of file SDL_opengl.h.
GL_AUX2
#define GL_AUX2 0x040B
Definition at line 503 of file SDL_opengl.h.
GL_AUX3
#define GL_AUX3 0x040C
Definition at line 504 of file SDL_opengl.h.
GL_AUX_BUFFERS
#define GL_AUX_BUFFERS 0x0C00
Definition at line 518 of file SDL_opengl.h.
GL_BACK
#define GL_BACK 0x0405
Definition at line 297 of file SDL_opengl.h.
GL_BACK_LEFT
#define GL_BACK_LEFT 0x0402
Definition at line 499 of file SDL_opengl.h.
GL_BACK_RIGHT
#define GL_BACK_RIGHT 0x0403
Definition at line 500 of file SDL_opengl.h.
GL_BGR
#define GL_BGR 0x80E0
Definition at line 1510 of file SDL_opengl.h.
GL_BGRA
#define GL_BGRA 0x80E1
Definition at line 1511 of file SDL_opengl.h.
GL_BITMAP
#define GL_BITMAP 0x1A00
Definition at line 523 of file SDL_opengl.h.
GL_BITMAP_TOKEN
#define GL_BITMAP_TOKEN 0x0704
Definition at line 427 of file SDL_opengl.h.
GL_BLEND
#define GL_BLEND 0x0BE2
Definition at line 397 of file SDL_opengl.h.
GL_BLEND_COLOR
#define GL_BLEND_COLOR 0x8005
Definition at line 1655 of file SDL_opengl.h.
GL_BLEND_DST
#define GL_BLEND_DST 0x0BE0
Definition at line 399 of file SDL_opengl.h.
GL_BLEND_EQUATION
#define GL_BLEND_EQUATION 0x8009
Definition at line 1649 of file SDL_opengl.h.
GL_BLEND_SRC
#define GL_BLEND_SRC 0x0BE1
Definition at line 398 of file SDL_opengl.h.
GL_BLUE
#define GL_BLUE 0x1905
Definition at line 508 of file SDL_opengl.h.
GL_BLUE_BIAS
#define GL_BLUE_BIAS 0x0D1B
Definition at line 627 of file SDL_opengl.h.
GL_BLUE_BITS
#define GL_BLUE_BITS 0x0D54
Definition at line 515 of file SDL_opengl.h.
GL_BLUE_SCALE
#define GL_BLUE_SCALE 0x0D1A
Definition at line 626 of file SDL_opengl.h.
GL_BYTE
#define GL_BYTE 0x1400
Definition at line 203 of file SDL_opengl.h.
GL_C3F_V3F
#define GL_C3F_V3F 0x2A24
Definition at line 258 of file SDL_opengl.h.
GL_C4F_N3F_V3F
#define GL_C4F_N3F_V3F 0x2A26
Definition at line 260 of file SDL_opengl.h.
GL_C4UB_V2F
#define GL_C4UB_V2F 0x2A22
Definition at line 256 of file SDL_opengl.h.
GL_C4UB_V3F
#define GL_C4UB_V3F 0x2A23
Definition at line 257 of file SDL_opengl.h.
GL_CCW
#define GL_CCW 0x0901
Definition at line 295 of file SDL_opengl.h.
GL_CLAMP
#define GL_CLAMP 0x2900
Definition at line 706 of file SDL_opengl.h.
GL_CLAMP_TO_BORDER
#define GL_CLAMP_TO_BORDER 0x812D
Definition at line 1876 of file SDL_opengl.h.
GL_CLAMP_TO_EDGE
#define GL_CLAMP_TO_EDGE 0x812F
Definition at line 1507 of file SDL_opengl.h.
GL_CLEAR
#define GL_CLEAR 0x1500
Definition at line 456 of file SDL_opengl.h.
GL_CLIENT_ACTIVE_TEXTURE
#define GL_CLIENT_ACTIVE_TEXTURE 0x84E1
Definition at line 1807 of file SDL_opengl.h.
GL_CLIENT_ACTIVE_TEXTURE_ARB
#define GL_CLIENT_ACTIVE_TEXTURE_ARB 0x84E1
Definition at line 2023 of file SDL_opengl.h.
GL_CLIENT_ALL_ATTRIB_BITS
#define GL_CLIENT_ALL_ATTRIB_BITS 0xFFFFFFFF
Definition at line 795 of file SDL_opengl.h.
GL_CLIENT_ATTRIB_STACK_DEPTH
#define GL_CLIENT_ATTRIB_STACK_DEPTH 0x0BB1
Definition at line 548 of file SDL_opengl.h.
GL_CLIENT_PIXEL_STORE_BIT
#define GL_CLIENT_PIXEL_STORE_BIT 0x00000001
Definition at line 792 of file SDL_opengl.h.
GL_CLIENT_VERTEX_ARRAY_BIT
#define GL_CLIENT_VERTEX_ARRAY_BIT 0x00000002
Definition at line 793 of file SDL_opengl.h.
GL_CLIP_PLANE0
#define GL_CLIP_PLANE0 0x3000
Definition at line 372 of file SDL_opengl.h.
GL_CLIP_PLANE1
#define GL_CLIP_PLANE1 0x3001
Definition at line 373 of file SDL_opengl.h.
GL_CLIP_PLANE2
#define GL_CLIP_PLANE2 0x3002
Definition at line 374 of file SDL_opengl.h.
GL_CLIP_PLANE3
#define GL_CLIP_PLANE3 0x3003
Definition at line 375 of file SDL_opengl.h.
GL_CLIP_PLANE4
#define GL_CLIP_PLANE4 0x3004
Definition at line 376 of file SDL_opengl.h.
GL_CLIP_PLANE5
#define GL_CLIP_PLANE5 0x3005
Definition at line 377 of file SDL_opengl.h.
GL_COEFF
#define GL_COEFF 0x0A00
Definition at line 599 of file SDL_opengl.h.
GL_COLOR
#define GL_COLOR 0x1800
Definition at line 524 of file SDL_opengl.h.
GL_COLOR_ARRAY
#define GL_COLOR_ARRAY 0x8076
Definition at line 230 of file SDL_opengl.h.
GL_COLOR_ARRAY_POINTER
#define GL_COLOR_ARRAY_POINTER 0x8090
Definition at line 250 of file SDL_opengl.h.
GL_COLOR_ARRAY_SIZE
#define GL_COLOR_ARRAY_SIZE 0x8081
Definition at line 239 of file SDL_opengl.h.
GL_COLOR_ARRAY_STRIDE
#define GL_COLOR_ARRAY_STRIDE 0x8083
Definition at line 241 of file SDL_opengl.h.
GL_COLOR_ARRAY_TYPE
#define GL_COLOR_ARRAY_TYPE 0x8082
Definition at line 240 of file SDL_opengl.h.
GL_COLOR_BUFFER_BIT
#define GL_COLOR_BUFFER_BIT 0x00004000
Definition at line 742 of file SDL_opengl.h.
GL_COLOR_CLEAR_VALUE
#define GL_COLOR_CLEAR_VALUE 0x0C22
Definition at line 549 of file SDL_opengl.h.
GL_COLOR_INDEX
#define GL_COLOR_INDEX 0x1900
Definition at line 505 of file SDL_opengl.h.
GL_COLOR_INDEXES
#define GL_COLOR_INDEXES 0x1603
Definition at line 358 of file SDL_opengl.h.
GL_COLOR_LOGIC_OP
#define GL_COLOR_LOGIC_OP 0x0BF2
Definition at line 454 of file SDL_opengl.h.
GL_COLOR_MATERIAL
#define GL_COLOR_MATERIAL 0x0B57
Definition at line 366 of file SDL_opengl.h.
GL_COLOR_MATERIAL_FACE
#define GL_COLOR_MATERIAL_FACE 0x0B55
Definition at line 367 of file SDL_opengl.h.
GL_COLOR_MATERIAL_PARAMETER
#define GL_COLOR_MATERIAL_PARAMETER 0x0B56
Definition at line 368 of file SDL_opengl.h.
GL_COLOR_MATRIX
#define GL_COLOR_MATRIX 0x80B1
Definition at line 1624 of file SDL_opengl.h.
GL_COLOR_MATRIX_STACK_DEPTH
#define GL_COLOR_MATRIX_STACK_DEPTH 0x80B2
Definition at line 1625 of file SDL_opengl.h.
GL_COLOR_TABLE
#define GL_COLOR_TABLE 0x80D0
Definition at line 1585 of file SDL_opengl.h.
GL_COLOR_TABLE_ALPHA_SIZE
#define GL_COLOR_TABLE_ALPHA_SIZE 0x80DD
Definition at line 1598 of file SDL_opengl.h.
GL_COLOR_TABLE_BIAS
#define GL_COLOR_TABLE_BIAS 0x80D7
Definition at line 1592 of file SDL_opengl.h.
GL_COLOR_TABLE_BLUE_SIZE
#define GL_COLOR_TABLE_BLUE_SIZE 0x80DC
Definition at line 1597 of file SDL_opengl.h.
GL_COLOR_TABLE_FORMAT
#define GL_COLOR_TABLE_FORMAT 0x80D8
Definition at line 1593 of file SDL_opengl.h.
GL_COLOR_TABLE_GREEN_SIZE
#define GL_COLOR_TABLE_GREEN_SIZE 0x80DB
Definition at line 1596 of file SDL_opengl.h.
GL_COLOR_TABLE_INTENSITY_SIZE
#define GL_COLOR_TABLE_INTENSITY_SIZE 0x80DF
Definition at line 1600 of file SDL_opengl.h.
GL_COLOR_TABLE_LUMINANCE_SIZE
#define GL_COLOR_TABLE_LUMINANCE_SIZE 0x80DE
Definition at line 1599 of file SDL_opengl.h.
GL_COLOR_TABLE_RED_SIZE
#define GL_COLOR_TABLE_RED_SIZE 0x80DA
Definition at line 1595 of file SDL_opengl.h.
GL_COLOR_TABLE_SCALE
#define GL_COLOR_TABLE_SCALE 0x80D6
Definition at line 1591 of file SDL_opengl.h.
GL_COLOR_TABLE_WIDTH
#define GL_COLOR_TABLE_WIDTH 0x80D9
Definition at line 1594 of file SDL_opengl.h.
GL_COLOR_WRITEMASK
#define GL_COLOR_WRITEMASK 0x0C23
Definition at line 550 of file SDL_opengl.h.
GL_COMBINE
#define GL_COMBINE 0x8570
Definition at line 1850 of file SDL_opengl.h.
GL_COMBINE_ALPHA
#define GL_COMBINE_ALPHA 0x8572
Definition at line 1852 of file SDL_opengl.h.
GL_COMBINE_RGB
#define GL_COMBINE_RGB 0x8571
Definition at line 1851 of file SDL_opengl.h.
GL_COMPILE
#define GL_COMPILE 0x1300
Definition at line 312 of file SDL_opengl.h.
GL_COMPILE_AND_EXECUTE
#define GL_COMPILE_AND_EXECUTE 0x1301
Definition at line 313 of file SDL_opengl.h.
GL_COMPRESSED_ALPHA
#define GL_COMPRESSED_ALPHA 0x84E9
Definition at line 1823 of file SDL_opengl.h.
GL_COMPRESSED_INTENSITY
#define GL_COMPRESSED_INTENSITY 0x84EC
Definition at line 1826 of file SDL_opengl.h.
GL_COMPRESSED_LUMINANCE
#define GL_COMPRESSED_LUMINANCE 0x84EA
Definition at line 1824 of file SDL_opengl.h.
GL_COMPRESSED_LUMINANCE_ALPHA
#define GL_COMPRESSED_LUMINANCE_ALPHA 0x84EB
Definition at line 1825 of file SDL_opengl.h.
GL_COMPRESSED_RGB
#define GL_COMPRESSED_RGB 0x84ED
Definition at line 1827 of file SDL_opengl.h.
GL_COMPRESSED_RGBA
#define GL_COMPRESSED_RGBA 0x84EE
Definition at line 1828 of file SDL_opengl.h.
GL_COMPRESSED_TEXTURE_FORMATS
#define GL_COMPRESSED_TEXTURE_FORMATS 0x86A3
Definition at line 1833 of file SDL_opengl.h.
GL_CONSTANT
#define GL_CONSTANT 0x8576
Definition at line 1869 of file SDL_opengl.h.
GL_CONSTANT_ALPHA
#define GL_CONSTANT_ALPHA 0x8003
Definition at line 1583 of file SDL_opengl.h.
GL_CONSTANT_ATTENUATION
#define GL_CONSTANT_ATTENUATION 0x1207
Definition at line 347 of file SDL_opengl.h.
GL_CONSTANT_BORDER
#define GL_CONSTANT_BORDER 0x8151
Definition at line 1621 of file SDL_opengl.h.
GL_CONSTANT_COLOR
#define GL_CONSTANT_COLOR 0x8001
Definition at line 1581 of file SDL_opengl.h.
GL_CONVOLUTION_1D
#define GL_CONVOLUTION_1D 0x8010
Definition at line 1601 of file SDL_opengl.h.
GL_CONVOLUTION_2D
#define GL_CONVOLUTION_2D 0x8011
Definition at line 1602 of file SDL_opengl.h.
GL_CONVOLUTION_BORDER_COLOR
#define GL_CONVOLUTION_BORDER_COLOR 0x8154
Definition at line 1623 of file SDL_opengl.h.
GL_CONVOLUTION_BORDER_MODE
#define GL_CONVOLUTION_BORDER_MODE 0x8013
Definition at line 1604 of file SDL_opengl.h.
GL_CONVOLUTION_FILTER_BIAS
#define GL_CONVOLUTION_FILTER_BIAS 0x8015
Definition at line 1606 of file SDL_opengl.h.
GL_CONVOLUTION_FILTER_SCALE
#define GL_CONVOLUTION_FILTER_SCALE 0x8014
Definition at line 1605 of file SDL_opengl.h.
GL_CONVOLUTION_FORMAT
#define GL_CONVOLUTION_FORMAT 0x8017
Definition at line 1608 of file SDL_opengl.h.
GL_CONVOLUTION_HEIGHT
#define GL_CONVOLUTION_HEIGHT 0x8019
Definition at line 1610 of file SDL_opengl.h.
GL_CONVOLUTION_WIDTH
#define GL_CONVOLUTION_WIDTH 0x8018
Definition at line 1609 of file SDL_opengl.h.
GL_COPY
#define GL_COPY 0x1503
Definition at line 458 of file SDL_opengl.h.
GL_COPY_INVERTED
#define GL_COPY_INVERTED 0x150C
Definition at line 459 of file SDL_opengl.h.
GL_COPY_PIXEL_TOKEN
#define GL_COPY_PIXEL_TOKEN 0x0706
Definition at line 429 of file SDL_opengl.h.
GL_CULL_FACE
#define GL_CULL_FACE 0x0B44
Definition at line 302 of file SDL_opengl.h.
GL_CULL_FACE_MODE
#define GL_CULL_FACE_MODE 0x0B45
Definition at line 303 of file SDL_opengl.h.
GL_CURRENT_BIT
#define GL_CURRENT_BIT 0x00000001
Definition at line 728 of file SDL_opengl.h.
GL_CURRENT_COLOR
#define GL_CURRENT_COLOR 0x0B00
Definition at line 552 of file SDL_opengl.h.
GL_CURRENT_INDEX
#define GL_CURRENT_INDEX 0x0B01
Definition at line 551 of file SDL_opengl.h.
GL_CURRENT_NORMAL
#define GL_CURRENT_NORMAL 0x0B02
Definition at line 553 of file SDL_opengl.h.
GL_CURRENT_RASTER_COLOR
#define GL_CURRENT_RASTER_COLOR 0x0B04
Definition at line 554 of file SDL_opengl.h.
GL_CURRENT_RASTER_DISTANCE
#define GL_CURRENT_RASTER_DISTANCE 0x0B09
Definition at line 555 of file SDL_opengl.h.
GL_CURRENT_RASTER_INDEX
#define GL_CURRENT_RASTER_INDEX 0x0B05
Definition at line 556 of file SDL_opengl.h.
GL_CURRENT_RASTER_POSITION
#define GL_CURRENT_RASTER_POSITION 0x0B07
Definition at line 557 of file SDL_opengl.h.
GL_CURRENT_RASTER_POSITION_VALID
#define GL_CURRENT_RASTER_POSITION_VALID 0x0B08
Definition at line 559 of file SDL_opengl.h.
GL_CURRENT_RASTER_TEXTURE_COORDS
#define GL_CURRENT_RASTER_TEXTURE_COORDS 0x0B06
Definition at line 558 of file SDL_opengl.h.
GL_CURRENT_TEXTURE_COORDS
#define GL_CURRENT_TEXTURE_COORDS 0x0B03
Definition at line 560 of file SDL_opengl.h.
GL_CW
#define GL_CW 0x0900
Definition at line 294 of file SDL_opengl.h.
GL_DECAL
#define GL_DECAL 0x2101
Definition at line 702 of file SDL_opengl.h.
GL_DECR
#define GL_DECR 0x1E03
Definition at line 488 of file SDL_opengl.h.
GL_DEPTH
#define GL_DEPTH 0x1801
Definition at line 525 of file SDL_opengl.h.
GL_DEPTH_BIAS
#define GL_DEPTH_BIAS 0x0D1F
Definition at line 631 of file SDL_opengl.h.
GL_DEPTH_BITS
#define GL_DEPTH_BITS 0x0D56
Definition at line 328 of file SDL_opengl.h.
GL_DEPTH_BUFFER_BIT
#define GL_DEPTH_BUFFER_BIT 0x00000100
Definition at line 736 of file SDL_opengl.h.
GL_DEPTH_CLEAR_VALUE
#define GL_DEPTH_CLEAR_VALUE 0x0B73
Definition at line 329 of file SDL_opengl.h.
GL_DEPTH_COMPONENT
#define GL_DEPTH_COMPONENT 0x1902
Definition at line 333 of file SDL_opengl.h.
GL_DEPTH_FUNC
#define GL_DEPTH_FUNC 0x0B74
Definition at line 330 of file SDL_opengl.h.
GL_DEPTH_RANGE
#define GL_DEPTH_RANGE 0x0B70
Definition at line 331 of file SDL_opengl.h.
GL_DEPTH_SCALE
#define GL_DEPTH_SCALE 0x0D1E
Definition at line 630 of file SDL_opengl.h.
GL_DEPTH_STENCIL_MESA
#define GL_DEPTH_STENCIL_MESA 0x8750
Definition at line 2117 of file SDL_opengl.h.
GL_DEPTH_TEST
#define GL_DEPTH_TEST 0x0B71
Definition at line 327 of file SDL_opengl.h.
GL_DEPTH_WRITEMASK
#define GL_DEPTH_WRITEMASK 0x0B72
Definition at line 332 of file SDL_opengl.h.
GL_DIFFUSE
#define GL_DIFFUSE 0x1201
Definition at line 351 of file SDL_opengl.h.
GL_DITHER
#define GL_DITHER 0x0BD0
Definition at line 527 of file SDL_opengl.h.
GL_DOMAIN
#define GL_DOMAIN 0x0A02
Definition at line 601 of file SDL_opengl.h.
GL_DONT_CARE
#define GL_DONT_CARE 0x1100
Definition at line 609 of file SDL_opengl.h.
GL_DOT3_RGB
#define GL_DOT3_RGB 0x86AE
Definition at line 1873 of file SDL_opengl.h.
GL_DOT3_RGBA
#define GL_DOT3_RGBA 0x86AF
Definition at line 1874 of file SDL_opengl.h.
GL_DOUBLE
#define GL_DOUBLE 0x140A
Definition at line 213 of file SDL_opengl.h.
GL_DOUBLEBUFFER
#define GL_DOUBLEBUFFER 0x0C32
Definition at line 521 of file SDL_opengl.h.
GL_DRAW_BUFFER
#define GL_DRAW_BUFFER 0x0C01
Definition at line 520 of file SDL_opengl.h.
GL_DRAW_PIXEL_TOKEN
#define GL_DRAW_PIXEL_TOKEN 0x0705
Definition at line 428 of file SDL_opengl.h.
GL_DST_ALPHA
#define GL_DST_ALPHA 0x0304
Definition at line 406 of file SDL_opengl.h.
GL_DST_COLOR
#define GL_DST_COLOR 0x0306
Definition at line 408 of file SDL_opengl.h.
GL_EDGE_FLAG
#define GL_EDGE_FLAG 0x0B43
Definition at line 301 of file SDL_opengl.h.
GL_EDGE_FLAG_ARRAY
#define GL_EDGE_FLAG_ARRAY 0x8079
Definition at line 233 of file SDL_opengl.h.
GL_EDGE_FLAG_ARRAY_POINTER
#define GL_EDGE_FLAG_ARRAY_POINTER 0x8093
Definition at line 253 of file SDL_opengl.h.
GL_EDGE_FLAG_ARRAY_STRIDE
#define GL_EDGE_FLAG_ARRAY_STRIDE 0x808C
Definition at line 247 of file SDL_opengl.h.
GL_EMISSION
#define GL_EMISSION 0x1600
Definition at line 354 of file SDL_opengl.h.
GL_ENABLE_BIT
#define GL_ENABLE_BIT 0x00002000
Definition at line 741 of file SDL_opengl.h.
GL_EQUAL
#define GL_EQUAL 0x0202
Definition at line 321 of file SDL_opengl.h.
GL_EQUIV
#define GL_EQUIV 0x1509
Definition at line 467 of file SDL_opengl.h.
GL_EVAL_BIT
#define GL_EVAL_BIT 0x00010000
Definition at line 744 of file SDL_opengl.h.
GL_EXP
#define GL_EXP 0x0800
Definition at line 448 of file SDL_opengl.h.
GL_EXP2
#define GL_EXP2 0x0801
Definition at line 449 of file SDL_opengl.h.
GL_EXTENSIONS
#define GL_EXTENSIONS 0x1F03
Definition at line 716 of file SDL_opengl.h.
GL_EYE_LINEAR
#define GL_EYE_LINEAR 0x2400
Definition at line 699 of file SDL_opengl.h.
GL_EYE_PLANE
#define GL_EYE_PLANE 0x2502
Definition at line 700 of file SDL_opengl.h.
GL_FALSE
#define GL_FALSE 0
Definition at line 199 of file SDL_opengl.h.
GL_FASTEST
#define GL_FASTEST 0x1101
Definition at line 610 of file SDL_opengl.h.
GL_FEEDBACK
#define GL_FEEDBACK 0x1C01
Definition at line 413 of file SDL_opengl.h.
GL_FEEDBACK_BUFFER_POINTER
#define GL_FEEDBACK_BUFFER_POINTER 0x0DF0
Definition at line 431 of file SDL_opengl.h.
GL_FEEDBACK_BUFFER_SIZE
#define GL_FEEDBACK_BUFFER_SIZE 0x0DF1
Definition at line 432 of file SDL_opengl.h.
GL_FEEDBACK_BUFFER_TYPE
#define GL_FEEDBACK_BUFFER_TYPE 0x0DF2
Definition at line 433 of file SDL_opengl.h.
GL_FILL
#define GL_FILL 0x1B02
Definition at line 293 of file SDL_opengl.h.
GL_FLAT
#define GL_FLAT 0x1D00
Definition at line 364 of file SDL_opengl.h.
GL_FLOAT
#define GL_FLOAT 0x1406
Definition at line 209 of file SDL_opengl.h.
GL_FOG
#define GL_FOG 0x0B60
Definition at line 440 of file SDL_opengl.h.
GL_FOG_BIT
#define GL_FOG_BIT 0x00000080
Definition at line 735 of file SDL_opengl.h.
GL_FOG_COLOR
#define GL_FOG_COLOR 0x0B66
Definition at line 443 of file SDL_opengl.h.
GL_FOG_DENSITY
#define GL_FOG_DENSITY 0x0B62
Definition at line 442 of file SDL_opengl.h.
GL_FOG_END
#define GL_FOG_END 0x0B64
Definition at line 446 of file SDL_opengl.h.
GL_FOG_HINT
#define GL_FOG_HINT 0x0C54
Definition at line 608 of file SDL_opengl.h.
GL_FOG_INDEX
#define GL_FOG_INDEX 0x0B61
Definition at line 444 of file SDL_opengl.h.
GL_FOG_MODE
#define GL_FOG_MODE 0x0B65
Definition at line 441 of file SDL_opengl.h.
GL_FOG_START
#define GL_FOG_START 0x0B63
Definition at line 445 of file SDL_opengl.h.
GL_FRONT
#define GL_FRONT 0x0404
Definition at line 296 of file SDL_opengl.h.
GL_FRONT_AND_BACK
#define GL_FRONT_AND_BACK 0x0408
Definition at line 362 of file SDL_opengl.h.
GL_FRONT_FACE
#define GL_FRONT_FACE 0x0B46
Definition at line 304 of file SDL_opengl.h.
GL_FRONT_LEFT
#define GL_FRONT_LEFT 0x0400
Definition at line 497 of file SDL_opengl.h.
GL_FRONT_RIGHT
#define GL_FRONT_RIGHT 0x0401
Definition at line 498 of file SDL_opengl.h.
GL_FUNC_ADD
#define GL_FUNC_ADD 0x8006
Definition at line 1652 of file SDL_opengl.h.
GL_FUNC_REVERSE_SUBTRACT
#define GL_FUNC_REVERSE_SUBTRACT 0x800B
Definition at line 1654 of file SDL_opengl.h.
GL_FUNC_SUBTRACT
#define GL_FUNC_SUBTRACT 0x800A
Definition at line 1653 of file SDL_opengl.h.
GL_GEQUAL
#define GL_GEQUAL 0x0206
Definition at line 325 of file SDL_opengl.h.
GL_GREATER
#define GL_GREATER 0x0204
Definition at line 323 of file SDL_opengl.h.
GL_GREEN
#define GL_GREEN 0x1904
Definition at line 507 of file SDL_opengl.h.
GL_GREEN_BIAS
#define GL_GREEN_BIAS 0x0D19
Definition at line 625 of file SDL_opengl.h.
GL_GREEN_BITS
#define GL_GREEN_BITS 0x0D53
Definition at line 514 of file SDL_opengl.h.
GL_GREEN_SCALE
#define GL_GREEN_SCALE 0x0D18
Definition at line 624 of file SDL_opengl.h.
GL_HINT_BIT
#define GL_HINT_BIT 0x00008000
Definition at line 743 of file SDL_opengl.h.
GL_HISTOGRAM
#define GL_HISTOGRAM 0x8024
Definition at line 1635 of file SDL_opengl.h.
GL_HISTOGRAM_ALPHA_SIZE
#define GL_HISTOGRAM_ALPHA_SIZE 0x802B
Definition at line 1642 of file SDL_opengl.h.
GL_HISTOGRAM_BLUE_SIZE
#define GL_HISTOGRAM_BLUE_SIZE 0x802A
Definition at line 1641 of file SDL_opengl.h.
GL_HISTOGRAM_FORMAT
#define GL_HISTOGRAM_FORMAT 0x8027
Definition at line 1638 of file SDL_opengl.h.
GL_HISTOGRAM_GREEN_SIZE
#define GL_HISTOGRAM_GREEN_SIZE 0x8029
Definition at line 1640 of file SDL_opengl.h.
GL_HISTOGRAM_LUMINANCE_SIZE
#define GL_HISTOGRAM_LUMINANCE_SIZE 0x802C
Definition at line 1643 of file SDL_opengl.h.
GL_HISTOGRAM_RED_SIZE
#define GL_HISTOGRAM_RED_SIZE 0x8028
Definition at line 1639 of file SDL_opengl.h.
GL_HISTOGRAM_SINK
#define GL_HISTOGRAM_SINK 0x802D
Definition at line 1644 of file SDL_opengl.h.
GL_HISTOGRAM_WIDTH
#define GL_HISTOGRAM_WIDTH 0x8026
Definition at line 1637 of file SDL_opengl.h.
GL_INCR
#define GL_INCR 0x1E02
Definition at line 487 of file SDL_opengl.h.
GL_INDEX_ARRAY
#define GL_INDEX_ARRAY 0x8077
Definition at line 231 of file SDL_opengl.h.
GL_INDEX_ARRAY_POINTER
#define GL_INDEX_ARRAY_POINTER 0x8091
Definition at line 251 of file SDL_opengl.h.
GL_INDEX_ARRAY_STRIDE
#define GL_INDEX_ARRAY_STRIDE 0x8086
Definition at line 243 of file SDL_opengl.h.
GL_INDEX_ARRAY_TYPE
#define GL_INDEX_ARRAY_TYPE 0x8085
Definition at line 242 of file SDL_opengl.h.
GL_INDEX_BITS
#define GL_INDEX_BITS 0x0D51
Definition at line 516 of file SDL_opengl.h.
GL_INDEX_CLEAR_VALUE
#define GL_INDEX_CLEAR_VALUE 0x0C20
Definition at line 561 of file SDL_opengl.h.
GL_INDEX_LOGIC_OP
#define GL_INDEX_LOGIC_OP 0x0BF1
Definition at line 453 of file SDL_opengl.h.
GL_INDEX_MODE
#define GL_INDEX_MODE 0x0C30
Definition at line 562 of file SDL_opengl.h.
GL_INDEX_OFFSET
#define GL_INDEX_OFFSET 0x0D13
Definition at line 621 of file SDL_opengl.h.
GL_INDEX_SHIFT
#define GL_INDEX_SHIFT 0x0D12
Definition at line 620 of file SDL_opengl.h.
GL_INDEX_WRITEMASK
#define GL_INDEX_WRITEMASK 0x0C21
Definition at line 563 of file SDL_opengl.h.
GL_INT
#define GL_INT 0x1404
Definition at line 207 of file SDL_opengl.h.
GL_INTENSITY
#define GL_INTENSITY 0x8049
Definition at line 773 of file SDL_opengl.h.
GL_INTENSITY12
#define GL_INTENSITY12 0x804C
Definition at line 776 of file SDL_opengl.h.
GL_INTENSITY16
#define GL_INTENSITY16 0x804D
Definition at line 777 of file SDL_opengl.h.
GL_INTENSITY4
#define GL_INTENSITY4 0x804A
Definition at line 774 of file SDL_opengl.h.
GL_INTENSITY8
#define GL_INTENSITY8 0x804B
Definition at line 775 of file SDL_opengl.h.
GL_INTERPOLATE
#define GL_INTERPOLATE 0x8575
Definition at line 1867 of file SDL_opengl.h.
GL_INVALID_ENUM
#define GL_INVALID_ENUM 0x0500
Definition at line 720 of file SDL_opengl.h.
GL_INVALID_OPERATION
#define GL_INVALID_OPERATION 0x0502
Definition at line 722 of file SDL_opengl.h.
GL_INVALID_VALUE
#define GL_INVALID_VALUE 0x0501
Definition at line 721 of file SDL_opengl.h.
GL_INVERT
#define GL_INVERT 0x150A
Definition at line 461 of file SDL_opengl.h.
GL_KEEP
#define GL_KEEP 0x1E00
Definition at line 485 of file SDL_opengl.h.
GL_LEFT
#define GL_LEFT 0x0406
Definition at line 492 of file SDL_opengl.h.
GL_LEQUAL
#define GL_LEQUAL 0x0203
Definition at line 322 of file SDL_opengl.h.
GL_LESS
#define GL_LESS 0x0201
Definition at line 320 of file SDL_opengl.h.
GL_LIGHT0
#define GL_LIGHT0 0x4000
Definition at line 337 of file SDL_opengl.h.
GL_LIGHT1
#define GL_LIGHT1 0x4001
Definition at line 338 of file SDL_opengl.h.
GL_LIGHT2
#define GL_LIGHT2 0x4002
Definition at line 339 of file SDL_opengl.h.
GL_LIGHT3
#define GL_LIGHT3 0x4003
Definition at line 340 of file SDL_opengl.h.
GL_LIGHT4
#define GL_LIGHT4 0x4004
Definition at line 341 of file SDL_opengl.h.
GL_LIGHT5
#define GL_LIGHT5 0x4005
Definition at line 342 of file SDL_opengl.h.
GL_LIGHT6
#define GL_LIGHT6 0x4006
Definition at line 343 of file SDL_opengl.h.
GL_LIGHT7
#define GL_LIGHT7 0x4007
Definition at line 344 of file SDL_opengl.h.
GL_LIGHT_MODEL_AMBIENT
#define GL_LIGHT_MODEL_AMBIENT 0x0B53
Definition at line 361 of file SDL_opengl.h.
GL_LIGHT_MODEL_COLOR_CONTROL
#define GL_LIGHT_MODEL_COLOR_CONTROL 0x81F8
Definition at line 1524 of file SDL_opengl.h.
GL_LIGHT_MODEL_LOCAL_VIEWER
#define GL_LIGHT_MODEL_LOCAL_VIEWER 0x0B51
Definition at line 360 of file SDL_opengl.h.
GL_LIGHT_MODEL_TWO_SIDE
#define GL_LIGHT_MODEL_TWO_SIDE 0x0B52
Definition at line 359 of file SDL_opengl.h.
GL_LIGHTING
#define GL_LIGHTING 0x0B50
Definition at line 336 of file SDL_opengl.h.
GL_LIGHTING_BIT
#define GL_LIGHTING_BIT 0x00000040
Definition at line 734 of file SDL_opengl.h.
GL_LINE
#define GL_LINE 0x1B01
Definition at line 292 of file SDL_opengl.h.
GL_LINE_BIT
#define GL_LINE_BIT 0x00000004
Definition at line 730 of file SDL_opengl.h.
GL_LINE_LOOP
#define GL_LINE_LOOP 0x0002
Definition at line 218 of file SDL_opengl.h.
GL_LINE_RESET_TOKEN
#define GL_LINE_RESET_TOKEN 0x0707
Definition at line 425 of file SDL_opengl.h.
GL_LINE_SMOOTH
#define GL_LINE_SMOOTH 0x0B20
Definition at line 282 of file SDL_opengl.h.
GL_LINE_SMOOTH_HINT
#define GL_LINE_SMOOTH_HINT 0x0C52
Definition at line 606 of file SDL_opengl.h.
GL_LINE_STIPPLE
#define GL_LINE_STIPPLE 0x0B24
Definition at line 283 of file SDL_opengl.h.
GL_LINE_STIPPLE_PATTERN
#define GL_LINE_STIPPLE_PATTERN 0x0B25
Definition at line 284 of file SDL_opengl.h.
GL_LINE_STIPPLE_REPEAT
#define GL_LINE_STIPPLE_REPEAT 0x0B26
Definition at line 285 of file SDL_opengl.h.
GL_LINE_STRIP
#define GL_LINE_STRIP 0x0003
Definition at line 219 of file SDL_opengl.h.
GL_LINE_TOKEN
#define GL_LINE_TOKEN 0x0702
Definition at line 424 of file SDL_opengl.h.
GL_LINE_WIDTH
#define GL_LINE_WIDTH 0x0B21
Definition at line 286 of file SDL_opengl.h.
GL_LINE_WIDTH_GRANULARITY
#define GL_LINE_WIDTH_GRANULARITY 0x0B23
Definition at line 287 of file SDL_opengl.h.
GL_LINE_WIDTH_RANGE
#define GL_LINE_WIDTH_RANGE 0x0B22
Definition at line 288 of file SDL_opengl.h.
GL_LINEAR
#define GL_LINEAR 0x2601
Definition at line 447 of file SDL_opengl.h.
GL_LINEAR_ATTENUATION
#define GL_LINEAR_ATTENUATION 0x1208
Definition at line 348 of file SDL_opengl.h.
GL_LINEAR_MIPMAP_LINEAR
#define GL_LINEAR_MIPMAP_LINEAR 0x2703
Definition at line 696 of file SDL_opengl.h.
GL_LINEAR_MIPMAP_NEAREST
#define GL_LINEAR_MIPMAP_NEAREST 0x2701
Definition at line 695 of file SDL_opengl.h.
GL_LINES
#define GL_LINES 0x0001
Definition at line 217 of file SDL_opengl.h.
GL_LIST_BASE
#define GL_LIST_BASE 0x0B32
Definition at line 314 of file SDL_opengl.h.
GL_LIST_BIT
#define GL_LIST_BIT 0x00020000
Definition at line 745 of file SDL_opengl.h.
GL_LIST_INDEX
#define GL_LIST_INDEX 0x0B33
Definition at line 315 of file SDL_opengl.h.
GL_LIST_MODE
#define GL_LIST_MODE 0x0B30
Definition at line 316 of file SDL_opengl.h.
GL_LOAD
#define GL_LOAD 0x0101
Definition at line 387 of file SDL_opengl.h.
GL_LOGIC_OP
#define GL_LOGIC_OP 0x0BF1
Definition at line 452 of file SDL_opengl.h.
GL_LOGIC_OP_MODE
#define GL_LOGIC_OP_MODE 0x0BF0
Definition at line 455 of file SDL_opengl.h.
GL_LUMINANCE
#define GL_LUMINANCE 0x1909
Definition at line 510 of file SDL_opengl.h.
GL_LUMINANCE12
#define GL_LUMINANCE12 0x8041
Definition at line 765 of file SDL_opengl.h.
GL_LUMINANCE12_ALPHA12
#define GL_LUMINANCE12_ALPHA12 0x8047
Definition at line 771 of file SDL_opengl.h.
GL_LUMINANCE12_ALPHA4
#define GL_LUMINANCE12_ALPHA4 0x8046
Definition at line 770 of file SDL_opengl.h.
GL_LUMINANCE16
#define GL_LUMINANCE16 0x8042
Definition at line 766 of file SDL_opengl.h.
GL_LUMINANCE16_ALPHA16
#define GL_LUMINANCE16_ALPHA16 0x8048
Definition at line 772 of file SDL_opengl.h.
GL_LUMINANCE4
#define GL_LUMINANCE4 0x803F
Definition at line 763 of file SDL_opengl.h.
GL_LUMINANCE4_ALPHA4
#define GL_LUMINANCE4_ALPHA4 0x8043
Definition at line 767 of file SDL_opengl.h.
GL_LUMINANCE6_ALPHA2
#define GL_LUMINANCE6_ALPHA2 0x8044
Definition at line 768 of file SDL_opengl.h.
GL_LUMINANCE8
#define GL_LUMINANCE8 0x8040
Definition at line 764 of file SDL_opengl.h.
GL_LUMINANCE8_ALPHA8
#define GL_LUMINANCE8_ALPHA8 0x8045
Definition at line 769 of file SDL_opengl.h.
GL_LUMINANCE_ALPHA
#define GL_LUMINANCE_ALPHA 0x190A
Definition at line 511 of file SDL_opengl.h.
GL_MAP1_COLOR_4
#define GL_MAP1_COLOR_4 0x0D90
Definition at line 577 of file SDL_opengl.h.
GL_MAP1_GRID_DOMAIN
#define GL_MAP1_GRID_DOMAIN 0x0DD0
Definition at line 595 of file SDL_opengl.h.
GL_MAP1_GRID_SEGMENTS
#define GL_MAP1_GRID_SEGMENTS 0x0DD1
Definition at line 596 of file SDL_opengl.h.
GL_MAP1_INDEX
#define GL_MAP1_INDEX 0x0D91
Definition at line 578 of file SDL_opengl.h.
GL_MAP1_NORMAL
#define GL_MAP1_NORMAL 0x0D92
Definition at line 579 of file SDL_opengl.h.
GL_MAP1_TEXTURE_COORD_1
#define GL_MAP1_TEXTURE_COORD_1 0x0D93
Definition at line 580 of file SDL_opengl.h.
GL_MAP1_TEXTURE_COORD_2
#define GL_MAP1_TEXTURE_COORD_2 0x0D94
Definition at line 581 of file SDL_opengl.h.
GL_MAP1_TEXTURE_COORD_3
#define GL_MAP1_TEXTURE_COORD_3 0x0D95
Definition at line 582 of file SDL_opengl.h.
GL_MAP1_TEXTURE_COORD_4
#define GL_MAP1_TEXTURE_COORD_4 0x0D96
Definition at line 583 of file SDL_opengl.h.
GL_MAP1_VERTEX_3
#define GL_MAP1_VERTEX_3 0x0D97
Definition at line 584 of file SDL_opengl.h.
GL_MAP1_VERTEX_4
#define GL_MAP1_VERTEX_4 0x0D98
Definition at line 585 of file SDL_opengl.h.
GL_MAP2_COLOR_4
#define GL_MAP2_COLOR_4 0x0DB0
Definition at line 586 of file SDL_opengl.h.
GL_MAP2_GRID_DOMAIN
#define GL_MAP2_GRID_DOMAIN 0x0DD2
Definition at line 597 of file SDL_opengl.h.
GL_MAP2_GRID_SEGMENTS
#define GL_MAP2_GRID_SEGMENTS 0x0DD3
Definition at line 598 of file SDL_opengl.h.
GL_MAP2_INDEX
#define GL_MAP2_INDEX 0x0DB1
Definition at line 587 of file SDL_opengl.h.
GL_MAP2_NORMAL
#define GL_MAP2_NORMAL 0x0DB2
Definition at line 588 of file SDL_opengl.h.
GL_MAP2_TEXTURE_COORD_1
#define GL_MAP2_TEXTURE_COORD_1 0x0DB3
Definition at line 589 of file SDL_opengl.h.
GL_MAP2_TEXTURE_COORD_2
#define GL_MAP2_TEXTURE_COORD_2 0x0DB4
Definition at line 590 of file SDL_opengl.h.
GL_MAP2_TEXTURE_COORD_3
#define GL_MAP2_TEXTURE_COORD_3 0x0DB5
Definition at line 591 of file SDL_opengl.h.
GL_MAP2_TEXTURE_COORD_4
#define GL_MAP2_TEXTURE_COORD_4 0x0DB6
Definition at line 592 of file SDL_opengl.h.
GL_MAP2_VERTEX_3
#define GL_MAP2_VERTEX_3 0x0DB7
Definition at line 593 of file SDL_opengl.h.
GL_MAP2_VERTEX_4
#define GL_MAP2_VERTEX_4 0x0DB8
Definition at line 594 of file SDL_opengl.h.
GL_MAP_COLOR
#define GL_MAP_COLOR 0x0D10
Definition at line 618 of file SDL_opengl.h.
GL_MAP_STENCIL
#define GL_MAP_STENCIL 0x0D11
Definition at line 619 of file SDL_opengl.h.
GL_MATRIX_MODE
#define GL_MATRIX_MODE 0x0BA0
Definition at line 270 of file SDL_opengl.h.
GL_MAX
#define GL_MAX 0x8008
Definition at line 1651 of file SDL_opengl.h.
GL_MAX_3D_TEXTURE_SIZE
#define GL_MAX_3D_TEXTURE_SIZE 0x8073
Definition at line 1545 of file SDL_opengl.h.
GL_MAX_ATTRIB_STACK_DEPTH
#define GL_MAX_ATTRIB_STACK_DEPTH 0x0D35
Definition at line 538 of file SDL_opengl.h.
GL_MAX_CLIENT_ATTRIB_STACK_DEPTH
#define GL_MAX_CLIENT_ATTRIB_STACK_DEPTH 0x0D3B
Definition at line 544 of file SDL_opengl.h.
GL_MAX_CLIP_PLANES
#define GL_MAX_CLIP_PLANES 0x0D32
Definition at line 535 of file SDL_opengl.h.
GL_MAX_COLOR_MATRIX_STACK_DEPTH
#define GL_MAX_COLOR_MATRIX_STACK_DEPTH 0x80B3
Definition at line 1626 of file SDL_opengl.h.
GL_MAX_CONVOLUTION_HEIGHT
#define GL_MAX_CONVOLUTION_HEIGHT 0x801B
Definition at line 1612 of file SDL_opengl.h.
GL_MAX_CONVOLUTION_WIDTH
#define GL_MAX_CONVOLUTION_WIDTH 0x801A
Definition at line 1611 of file SDL_opengl.h.
GL_MAX_CUBE_MAP_TEXTURE_SIZE
#define GL_MAX_CUBE_MAP_TEXTURE_SIZE 0x851C
Definition at line 1821 of file SDL_opengl.h.
GL_MAX_ELEMENTS_INDICES
#define GL_MAX_ELEMENTS_INDICES 0x80E9
Definition at line 1509 of file SDL_opengl.h.
GL_MAX_ELEMENTS_VERTICES
#define GL_MAX_ELEMENTS_VERTICES 0x80E8
Definition at line 1508 of file SDL_opengl.h.
GL_MAX_EVAL_ORDER
#define GL_MAX_EVAL_ORDER 0x0D30
Definition at line 533 of file SDL_opengl.h.
GL_MAX_LIGHTS
#define GL_MAX_LIGHTS 0x0D31
Definition at line 534 of file SDL_opengl.h.
GL_MAX_LIST_NESTING
#define GL_MAX_LIST_NESTING 0x0B31
Definition at line 532 of file SDL_opengl.h.
GL_MAX_MODELVIEW_STACK_DEPTH
#define GL_MAX_MODELVIEW_STACK_DEPTH 0x0D36
Definition at line 539 of file SDL_opengl.h.
GL_MAX_NAME_STACK_DEPTH
#define GL_MAX_NAME_STACK_DEPTH 0x0D37
Definition at line 540 of file SDL_opengl.h.
GL_MAX_PIXEL_MAP_TABLE
#define GL_MAX_PIXEL_MAP_TABLE 0x0D34
Definition at line 537 of file SDL_opengl.h.
GL_MAX_PROJECTION_STACK_DEPTH
#define GL_MAX_PROJECTION_STACK_DEPTH 0x0D38
Definition at line 541 of file SDL_opengl.h.
GL_MAX_TEXTURE_SIZE
#define GL_MAX_TEXTURE_SIZE 0x0D33
Definition at line 536 of file SDL_opengl.h.
GL_MAX_TEXTURE_STACK_DEPTH
#define GL_MAX_TEXTURE_STACK_DEPTH 0x0D39
Definition at line 542 of file SDL_opengl.h.
GL_MAX_TEXTURE_UNITS
#define GL_MAX_TEXTURE_UNITS 0x84E2
Definition at line 1808 of file SDL_opengl.h.
GL_MAX_TEXTURE_UNITS_ARB
#define GL_MAX_TEXTURE_UNITS_ARB 0x84E2
Definition at line 2024 of file SDL_opengl.h.
GL_MAX_VIEWPORT_DIMS
#define GL_MAX_VIEWPORT_DIMS 0x0D3A
Definition at line 543 of file SDL_opengl.h.
GL_MESA_packed_depth_stencil
#define GL_MESA_packed_depth_stencil 1
Definition at line 2115 of file SDL_opengl.h.
GL_MIN
#define GL_MIN 0x8007
Definition at line 1650 of file SDL_opengl.h.
GL_MINMAX
#define GL_MINMAX 0x802E
Definition at line 1645 of file SDL_opengl.h.
GL_MINMAX_FORMAT
#define GL_MINMAX_FORMAT 0x802F
Definition at line 1646 of file SDL_opengl.h.
GL_MINMAX_SINK
#define GL_MINMAX_SINK 0x8030
Definition at line 1647 of file SDL_opengl.h.
GL_MODELVIEW
#define GL_MODELVIEW 0x1700
Definition at line 271 of file SDL_opengl.h.
GL_MODELVIEW_MATRIX
#define GL_MODELVIEW_MATRIX 0x0BA6
Definition at line 564 of file SDL_opengl.h.
GL_MODELVIEW_STACK_DEPTH
#define GL_MODELVIEW_STACK_DEPTH 0x0BA3
Definition at line 565 of file SDL_opengl.h.
GL_MODULATE
#define GL_MODULATE 0x2100
Definition at line 703 of file SDL_opengl.h.
GL_MULT
#define GL_MULT 0x0103
Definition at line 388 of file SDL_opengl.h.
GL_MULTISAMPLE
#define GL_MULTISAMPLE 0x809D
Definition at line 1835 of file SDL_opengl.h.
GL_MULTISAMPLE_BIT
#define GL_MULTISAMPLE_BIT 0x20000000
Definition at line 1843 of file SDL_opengl.h.
GL_N3F_V3F
#define GL_N3F_V3F 0x2A25
Definition at line 259 of file SDL_opengl.h.
GL_NAME_STACK_DEPTH
#define GL_NAME_STACK_DEPTH 0x0D70
Definition at line 566 of file SDL_opengl.h.
GL_NAND
#define GL_NAND 0x150E
Definition at line 463 of file SDL_opengl.h.
GL_NEAREST
#define GL_NEAREST 0x2600
Definition at line 704 of file SDL_opengl.h.
GL_NEAREST_MIPMAP_LINEAR
#define GL_NEAREST_MIPMAP_LINEAR 0x2702
Definition at line 694 of file SDL_opengl.h.
GL_NEAREST_MIPMAP_NEAREST
#define GL_NEAREST_MIPMAP_NEAREST 0x2700
Definition at line 693 of file SDL_opengl.h.
GL_NEVER
#define GL_NEVER 0x0200
Definition at line 319 of file SDL_opengl.h.
GL_NICEST
#define GL_NICEST 0x1102
Definition at line 611 of file SDL_opengl.h.
GL_NO_ERROR
#define GL_NO_ERROR 0
Definition at line 719 of file SDL_opengl.h.
GL_NONE
#define GL_NONE 0
Definition at line 491 of file SDL_opengl.h.
GL_NOOP
#define GL_NOOP 0x1505
Definition at line 460 of file SDL_opengl.h.
GL_NOR
#define GL_NOR 0x1508
Definition at line 465 of file SDL_opengl.h.
GL_NORMAL_ARRAY
#define GL_NORMAL_ARRAY 0x8075
Definition at line 229 of file SDL_opengl.h.
GL_NORMAL_ARRAY_POINTER
#define GL_NORMAL_ARRAY_POINTER 0x808F
Definition at line 249 of file SDL_opengl.h.
GL_NORMAL_ARRAY_STRIDE
#define GL_NORMAL_ARRAY_STRIDE 0x807F
Definition at line 238 of file SDL_opengl.h.
GL_NORMAL_ARRAY_TYPE
#define GL_NORMAL_ARRAY_TYPE 0x807E
Definition at line 237 of file SDL_opengl.h.
GL_NORMAL_MAP
#define GL_NORMAL_MAP 0x8511
Definition at line 1810 of file SDL_opengl.h.
GL_NORMALIZE
#define GL_NORMALIZE 0x0BA1
Definition at line 369 of file SDL_opengl.h.
GL_NOTEQUAL
#define GL_NOTEQUAL 0x0205
Definition at line 324 of file SDL_opengl.h.
GL_NUM_COMPRESSED_TEXTURE_FORMATS
#define GL_NUM_COMPRESSED_TEXTURE_FORMATS 0x86A2
Definition at line 1832 of file SDL_opengl.h.
GL_OBJECT_LINEAR
#define GL_OBJECT_LINEAR 0x2401
Definition at line 697 of file SDL_opengl.h.
GL_OBJECT_PLANE
#define GL_OBJECT_PLANE 0x2501
Definition at line 698 of file SDL_opengl.h.
GL_OES_EGL_image
#define GL_OES_EGL_image 1
Definition at line 2143 of file SDL_opengl.h.
GL_ONE
#define GL_ONE 1
Definition at line 401 of file SDL_opengl.h.
GL_ONE_MINUS_CONSTANT_ALPHA
#define GL_ONE_MINUS_CONSTANT_ALPHA 0x8004
Definition at line 1584 of file SDL_opengl.h.
GL_ONE_MINUS_CONSTANT_COLOR
#define GL_ONE_MINUS_CONSTANT_COLOR 0x8002
Definition at line 1582 of file SDL_opengl.h.
GL_ONE_MINUS_DST_ALPHA
#define GL_ONE_MINUS_DST_ALPHA 0x0305
Definition at line 407 of file SDL_opengl.h.
GL_ONE_MINUS_DST_COLOR
#define GL_ONE_MINUS_DST_COLOR 0x0307
Definition at line 409 of file SDL_opengl.h.
GL_ONE_MINUS_SRC_ALPHA
#define GL_ONE_MINUS_SRC_ALPHA 0x0303
Definition at line 405 of file SDL_opengl.h.
GL_ONE_MINUS_SRC_COLOR
#define GL_ONE_MINUS_SRC_COLOR 0x0301
Definition at line 403 of file SDL_opengl.h.
GL_OPERAND0_ALPHA
#define GL_OPERAND0_ALPHA 0x8598
Definition at line 1862 of file SDL_opengl.h.
GL_OPERAND0_RGB
#define GL_OPERAND0_RGB 0x8590
Definition at line 1859 of file SDL_opengl.h.
GL_OPERAND1_ALPHA
#define GL_OPERAND1_ALPHA 0x8599
Definition at line 1863 of file SDL_opengl.h.
GL_OPERAND1_RGB
#define GL_OPERAND1_RGB 0x8591
Definition at line 1860 of file SDL_opengl.h.
GL_OPERAND2_ALPHA
#define GL_OPERAND2_ALPHA 0x859A
Definition at line 1864 of file SDL_opengl.h.
GL_OPERAND2_RGB
#define GL_OPERAND2_RGB 0x8592
Definition at line 1861 of file SDL_opengl.h.
GL_OR
#define GL_OR 0x1507
Definition at line 464 of file SDL_opengl.h.
GL_OR_INVERTED
#define GL_OR_INVERTED 0x150D
Definition at line 471 of file SDL_opengl.h.
GL_OR_REVERSE
#define GL_OR_REVERSE 0x150B
Definition at line 470 of file SDL_opengl.h.
GL_ORDER
#define GL_ORDER 0x0A01
Definition at line 600 of file SDL_opengl.h.
GL_OUT_OF_MEMORY
#define GL_OUT_OF_MEMORY 0x0505
Definition at line 725 of file SDL_opengl.h.
GL_PACK_ALIGNMENT
#define GL_PACK_ALIGNMENT 0x0D05
Definition at line 652 of file SDL_opengl.h.
GL_PACK_IMAGE_HEIGHT
#define GL_PACK_IMAGE_HEIGHT 0x806C
Definition at line 1538 of file SDL_opengl.h.
GL_PACK_LSB_FIRST
#define GL_PACK_LSB_FIRST 0x0D01
Definition at line 653 of file SDL_opengl.h.
GL_PACK_ROW_LENGTH
#define GL_PACK_ROW_LENGTH 0x0D02
Definition at line 654 of file SDL_opengl.h.
GL_PACK_SKIP_IMAGES
#define GL_PACK_SKIP_IMAGES 0x806B
Definition at line 1537 of file SDL_opengl.h.
GL_PACK_SKIP_PIXELS
#define GL_PACK_SKIP_PIXELS 0x0D04
Definition at line 655 of file SDL_opengl.h.
GL_PACK_SKIP_ROWS
#define GL_PACK_SKIP_ROWS 0x0D03
Definition at line 656 of file SDL_opengl.h.
GL_PACK_SWAP_BYTES
#define GL_PACK_SWAP_BYTES 0x0D00
Definition at line 657 of file SDL_opengl.h.
GL_PASS_THROUGH_TOKEN
#define GL_PASS_THROUGH_TOKEN 0x0700
Definition at line 430 of file SDL_opengl.h.
GL_PERSPECTIVE_CORRECTION_HINT
#define GL_PERSPECTIVE_CORRECTION_HINT 0x0C50
Definition at line 604 of file SDL_opengl.h.
GL_PIXEL_MAP_A_TO_A
#define GL_PIXEL_MAP_A_TO_A 0x0C79
Definition at line 651 of file SDL_opengl.h.
GL_PIXEL_MAP_A_TO_A_SIZE
#define GL_PIXEL_MAP_A_TO_A_SIZE 0x0CB9
Definition at line 641 of file SDL_opengl.h.
GL_PIXEL_MAP_B_TO_B
#define GL_PIXEL_MAP_B_TO_B 0x0C78
Definition at line 650 of file SDL_opengl.h.
GL_PIXEL_MAP_B_TO_B_SIZE
#define GL_PIXEL_MAP_B_TO_B_SIZE 0x0CB8
Definition at line 640 of file SDL_opengl.h.
GL_PIXEL_MAP_G_TO_G
#define GL_PIXEL_MAP_G_TO_G 0x0C77
Definition at line 649 of file SDL_opengl.h.
GL_PIXEL_MAP_G_TO_G_SIZE
#define GL_PIXEL_MAP_G_TO_G_SIZE 0x0CB7
Definition at line 639 of file SDL_opengl.h.
GL_PIXEL_MAP_I_TO_A
#define GL_PIXEL_MAP_I_TO_A 0x0C75
Definition at line 647 of file SDL_opengl.h.
GL_PIXEL_MAP_I_TO_A_SIZE
#define GL_PIXEL_MAP_I_TO_A_SIZE 0x0CB5
Definition at line 637 of file SDL_opengl.h.
GL_PIXEL_MAP_I_TO_B
#define GL_PIXEL_MAP_I_TO_B 0x0C74
Definition at line 646 of file SDL_opengl.h.
GL_PIXEL_MAP_I_TO_B_SIZE
#define GL_PIXEL_MAP_I_TO_B_SIZE 0x0CB4
Definition at line 636 of file SDL_opengl.h.
GL_PIXEL_MAP_I_TO_G
#define GL_PIXEL_MAP_I_TO_G 0x0C73
Definition at line 645 of file SDL_opengl.h.
GL_PIXEL_MAP_I_TO_G_SIZE
#define GL_PIXEL_MAP_I_TO_G_SIZE 0x0CB3
Definition at line 635 of file SDL_opengl.h.
GL_PIXEL_MAP_I_TO_I
#define GL_PIXEL_MAP_I_TO_I 0x0C70
Definition at line 643 of file SDL_opengl.h.
GL_PIXEL_MAP_I_TO_I_SIZE
#define GL_PIXEL_MAP_I_TO_I_SIZE 0x0CB0
Definition at line 633 of file SDL_opengl.h.
GL_PIXEL_MAP_I_TO_R
#define GL_PIXEL_MAP_I_TO_R 0x0C72
Definition at line 644 of file SDL_opengl.h.
GL_PIXEL_MAP_I_TO_R_SIZE
#define GL_PIXEL_MAP_I_TO_R_SIZE 0x0CB2
Definition at line 634 of file SDL_opengl.h.
GL_PIXEL_MAP_R_TO_R
#define GL_PIXEL_MAP_R_TO_R 0x0C76
Definition at line 648 of file SDL_opengl.h.
GL_PIXEL_MAP_R_TO_R_SIZE
#define GL_PIXEL_MAP_R_TO_R_SIZE 0x0CB6
Definition at line 638 of file SDL_opengl.h.
GL_PIXEL_MAP_S_TO_S
#define GL_PIXEL_MAP_S_TO_S 0x0C71
Definition at line 642 of file SDL_opengl.h.
GL_PIXEL_MAP_S_TO_S_SIZE
#define GL_PIXEL_MAP_S_TO_S_SIZE 0x0CB1
Definition at line 632 of file SDL_opengl.h.
GL_PIXEL_MODE_BIT
#define GL_PIXEL_MODE_BIT 0x00000020
Definition at line 733 of file SDL_opengl.h.
GL_POINT
#define GL_POINT 0x1B00
Definition at line 291 of file SDL_opengl.h.
GL_POINT_BIT
#define GL_POINT_BIT 0x00000002
Definition at line 729 of file SDL_opengl.h.
GL_POINT_SIZE
#define GL_POINT_SIZE 0x0B11
Definition at line 277 of file SDL_opengl.h.
GL_POINT_SIZE_GRANULARITY
#define GL_POINT_SIZE_GRANULARITY 0x0B13
Definition at line 278 of file SDL_opengl.h.
GL_POINT_SIZE_RANGE
#define GL_POINT_SIZE_RANGE 0x0B12
Definition at line 279 of file SDL_opengl.h.
GL_POINT_SMOOTH
#define GL_POINT_SMOOTH 0x0B10
Definition at line 276 of file SDL_opengl.h.
GL_POINT_SMOOTH_HINT
#define GL_POINT_SMOOTH_HINT 0x0C51
Definition at line 605 of file SDL_opengl.h.
GL_POINT_TOKEN
#define GL_POINT_TOKEN 0x0701
Definition at line 423 of file SDL_opengl.h.
GL_POINTS
#define GL_POINTS 0x0000
Definition at line 216 of file SDL_opengl.h.
GL_POLYGON
#define GL_POLYGON 0x0009
Definition at line 225 of file SDL_opengl.h.
GL_POLYGON_BIT
#define GL_POLYGON_BIT 0x00000008
Definition at line 731 of file SDL_opengl.h.
GL_POLYGON_MODE
#define GL_POLYGON_MODE 0x0B40
Definition at line 298 of file SDL_opengl.h.
GL_POLYGON_OFFSET_FACTOR
#define GL_POLYGON_OFFSET_FACTOR 0x8038
Definition at line 305 of file SDL_opengl.h.
GL_POLYGON_OFFSET_FILL
#define GL_POLYGON_OFFSET_FILL 0x8037
Definition at line 309 of file SDL_opengl.h.
GL_POLYGON_OFFSET_LINE
#define GL_POLYGON_OFFSET_LINE 0x2A02
Definition at line 308 of file SDL_opengl.h.
GL_POLYGON_OFFSET_POINT
#define GL_POLYGON_OFFSET_POINT 0x2A01
Definition at line 307 of file SDL_opengl.h.
GL_POLYGON_OFFSET_UNITS
#define GL_POLYGON_OFFSET_UNITS 0x2A00
Definition at line 306 of file SDL_opengl.h.
GL_POLYGON_SMOOTH
#define GL_POLYGON_SMOOTH 0x0B41
Definition at line 299 of file SDL_opengl.h.
GL_POLYGON_SMOOTH_HINT
#define GL_POLYGON_SMOOTH_HINT 0x0C53
Definition at line 607 of file SDL_opengl.h.
GL_POLYGON_STIPPLE
#define GL_POLYGON_STIPPLE 0x0B42
Definition at line 300 of file SDL_opengl.h.
GL_POLYGON_STIPPLE_BIT
#define GL_POLYGON_STIPPLE_BIT 0x00000010
Definition at line 732 of file SDL_opengl.h.
GL_POLYGON_TOKEN
#define GL_POLYGON_TOKEN 0x0703
Definition at line 426 of file SDL_opengl.h.
GL_POSITION
#define GL_POSITION 0x1203
Definition at line 355 of file SDL_opengl.h.
GL_POST_COLOR_MATRIX_ALPHA_BIAS
#define GL_POST_COLOR_MATRIX_ALPHA_BIAS 0x80BB
Definition at line 1634 of file SDL_opengl.h.
GL_POST_COLOR_MATRIX_ALPHA_SCALE
#define GL_POST_COLOR_MATRIX_ALPHA_SCALE 0x80B7
Definition at line 1630 of file SDL_opengl.h.
GL_POST_COLOR_MATRIX_BLUE_BIAS
#define GL_POST_COLOR_MATRIX_BLUE_BIAS 0x80BA
Definition at line 1633 of file SDL_opengl.h.
GL_POST_COLOR_MATRIX_BLUE_SCALE
#define GL_POST_COLOR_MATRIX_BLUE_SCALE 0x80B6
Definition at line 1629 of file SDL_opengl.h.
GL_POST_COLOR_MATRIX_COLOR_TABLE
#define GL_POST_COLOR_MATRIX_COLOR_TABLE 0x80D2
Definition at line 1587 of file SDL_opengl.h.
GL_POST_COLOR_MATRIX_GREEN_BIAS
#define GL_POST_COLOR_MATRIX_GREEN_BIAS 0x80B9
Definition at line 1632 of file SDL_opengl.h.
GL_POST_COLOR_MATRIX_GREEN_SCALE
#define GL_POST_COLOR_MATRIX_GREEN_SCALE 0x80B5
Definition at line 1628 of file SDL_opengl.h.
GL_POST_COLOR_MATRIX_RED_BIAS
#define GL_POST_COLOR_MATRIX_RED_BIAS 0x80B8
Definition at line 1631 of file SDL_opengl.h.
GL_POST_COLOR_MATRIX_RED_SCALE
#define GL_POST_COLOR_MATRIX_RED_SCALE 0x80B4
Definition at line 1627 of file SDL_opengl.h.
GL_POST_CONVOLUTION_ALPHA_BIAS
#define GL_POST_CONVOLUTION_ALPHA_BIAS 0x8023
Definition at line 1620 of file SDL_opengl.h.
GL_POST_CONVOLUTION_ALPHA_SCALE
#define GL_POST_CONVOLUTION_ALPHA_SCALE 0x801F
Definition at line 1616 of file SDL_opengl.h.
GL_POST_CONVOLUTION_BLUE_BIAS
#define GL_POST_CONVOLUTION_BLUE_BIAS 0x8022
Definition at line 1619 of file SDL_opengl.h.
GL_POST_CONVOLUTION_BLUE_SCALE
#define GL_POST_CONVOLUTION_BLUE_SCALE 0x801E
Definition at line 1615 of file SDL_opengl.h.
GL_POST_CONVOLUTION_COLOR_TABLE
#define GL_POST_CONVOLUTION_COLOR_TABLE 0x80D1
Definition at line 1586 of file SDL_opengl.h.
GL_POST_CONVOLUTION_GREEN_BIAS
#define GL_POST_CONVOLUTION_GREEN_BIAS 0x8021
Definition at line 1618 of file SDL_opengl.h.
GL_POST_CONVOLUTION_GREEN_SCALE
#define GL_POST_CONVOLUTION_GREEN_SCALE 0x801D
Definition at line 1614 of file SDL_opengl.h.
GL_POST_CONVOLUTION_RED_BIAS
#define GL_POST_CONVOLUTION_RED_BIAS 0x8020
Definition at line 1617 of file SDL_opengl.h.
GL_POST_CONVOLUTION_RED_SCALE
#define GL_POST_CONVOLUTION_RED_SCALE 0x801C
Definition at line 1613 of file SDL_opengl.h.
GL_PREVIOUS
#define GL_PREVIOUS 0x8578
Definition at line 1871 of file SDL_opengl.h.
GL_PRIMARY_COLOR
#define GL_PRIMARY_COLOR 0x8577
Definition at line 1870 of file SDL_opengl.h.
GL_PROJECTION
#define GL_PROJECTION 0x1701
Definition at line 272 of file SDL_opengl.h.
GL_PROJECTION_MATRIX
#define GL_PROJECTION_MATRIX 0x0BA7
Definition at line 567 of file SDL_opengl.h.
GL_PROJECTION_STACK_DEPTH
#define GL_PROJECTION_STACK_DEPTH 0x0BA4
Definition at line 568 of file SDL_opengl.h.
GL_PROXY_COLOR_TABLE
#define GL_PROXY_COLOR_TABLE 0x80D3
Definition at line 1588 of file SDL_opengl.h.
GL_PROXY_HISTOGRAM
#define GL_PROXY_HISTOGRAM 0x8025
Definition at line 1636 of file SDL_opengl.h.
GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE
#define GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE 0x80D5
Definition at line 1590 of file SDL_opengl.h.
GL_PROXY_POST_CONVOLUTION_COLOR_TABLE
#define GL_PROXY_POST_CONVOLUTION_COLOR_TABLE 0x80D4
Definition at line 1589 of file SDL_opengl.h.
GL_PROXY_TEXTURE_1D
#define GL_PROXY_TEXTURE_1D 0x8063
Definition at line 752 of file SDL_opengl.h.
GL_PROXY_TEXTURE_2D
#define GL_PROXY_TEXTURE_2D 0x8064
Definition at line 753 of file SDL_opengl.h.
GL_PROXY_TEXTURE_3D
#define GL_PROXY_TEXTURE_3D 0x8070
Definition at line 1542 of file SDL_opengl.h.
GL_PROXY_TEXTURE_CUBE_MAP
#define GL_PROXY_TEXTURE_CUBE_MAP 0x851B
Definition at line 1820 of file SDL_opengl.h.
GL_Q
#define GL_Q 0x2003
Definition at line 710 of file SDL_opengl.h.
GL_QUAD_STRIP
#define GL_QUAD_STRIP 0x0008
Definition at line 224 of file SDL_opengl.h.
GL_QUADRATIC_ATTENUATION
#define GL_QUADRATIC_ATTENUATION 0x1209
Definition at line 349 of file SDL_opengl.h.
GL_QUADS
#define GL_QUADS 0x0007
Definition at line 223 of file SDL_opengl.h.
GL_R
#define GL_R 0x2002
Definition at line 709 of file SDL_opengl.h.
GL_R3_G3_B2
#define GL_R3_G3_B2 0x2A10
Definition at line 778 of file SDL_opengl.h.
GL_READ_BUFFER
#define GL_READ_BUFFER 0x0C02
Definition at line 519 of file SDL_opengl.h.
GL_RED
#define GL_RED 0x1903
Definition at line 506 of file SDL_opengl.h.
GL_RED_BIAS
#define GL_RED_BIAS 0x0D15
Definition at line 623 of file SDL_opengl.h.
GL_RED_BITS
#define GL_RED_BITS 0x0D52
Definition at line 513 of file SDL_opengl.h.
GL_RED_SCALE
#define GL_RED_SCALE 0x0D14
Definition at line 622 of file SDL_opengl.h.
GL_REDUCE
#define GL_REDUCE 0x8016
Definition at line 1607 of file SDL_opengl.h.
GL_REFLECTION_MAP
#define GL_REFLECTION_MAP 0x8512
Definition at line 1811 of file SDL_opengl.h.
GL_RENDER
#define GL_RENDER 0x1C00
Definition at line 414 of file SDL_opengl.h.
GL_RENDER_MODE
#define GL_RENDER_MODE 0x0C40
Definition at line 569 of file SDL_opengl.h.
GL_RENDERER
#define GL_RENDERER 0x1F01
Definition at line 714 of file SDL_opengl.h.
GL_REPEAT
#define GL_REPEAT 0x2901
Definition at line 705 of file SDL_opengl.h.
GL_REPLACE
#define GL_REPLACE 0x1E01
Definition at line 486 of file SDL_opengl.h.
GL_REPLICATE_BORDER
#define GL_REPLICATE_BORDER 0x8153
Definition at line 1622 of file SDL_opengl.h.
GL_RESCALE_NORMAL
#define GL_RESCALE_NORMAL 0x803A
Definition at line 1506 of file SDL_opengl.h.
GL_RETURN
#define GL_RETURN 0x0102
Definition at line 389 of file SDL_opengl.h.
GL_RGB
#define GL_RGB 0x1907
Definition at line 528 of file SDL_opengl.h.
GL_RGB10
#define GL_RGB10 0x8052
Definition at line 782 of file SDL_opengl.h.
GL_RGB10_A2
#define GL_RGB10_A2 0x8059
Definition at line 789 of file SDL_opengl.h.
GL_RGB12
#define GL_RGB12 0x8053
Definition at line 783 of file SDL_opengl.h.
GL_RGB16
#define GL_RGB16 0x8054
Definition at line 784 of file SDL_opengl.h.
GL_RGB4
#define GL_RGB4 0x804F
Definition at line 779 of file SDL_opengl.h.
GL_RGB5
#define GL_RGB5 0x8050
Definition at line 780 of file SDL_opengl.h.
GL_RGB5_A1
#define GL_RGB5_A1 0x8057
Definition at line 787 of file SDL_opengl.h.
GL_RGB8
#define GL_RGB8 0x8051
Definition at line 781 of file SDL_opengl.h.
GL_RGB_SCALE
#define GL_RGB_SCALE 0x8573
Definition at line 1865 of file SDL_opengl.h.
GL_RGBA
#define GL_RGBA 0x1908
Definition at line 529 of file SDL_opengl.h.
GL_RGBA12
#define GL_RGBA12 0x805A
Definition at line 790 of file SDL_opengl.h.
GL_RGBA16
#define GL_RGBA16 0x805B
Definition at line 791 of file SDL_opengl.h.
GL_RGBA2
#define GL_RGBA2 0x8055
Definition at line 785 of file SDL_opengl.h.
GL_RGBA4
#define GL_RGBA4 0x8056
Definition at line 786 of file SDL_opengl.h.
GL_RGBA8
#define GL_RGBA8 0x8058
Definition at line 788 of file SDL_opengl.h.
GL_RGBA_MODE
#define GL_RGBA_MODE 0x0C31
Definition at line 570 of file SDL_opengl.h.
GL_RIGHT
#define GL_RIGHT 0x0407
Definition at line 493 of file SDL_opengl.h.
GL_S
#define GL_S 0x2000
Definition at line 707 of file SDL_opengl.h.
GL_SAMPLE_ALPHA_TO_COVERAGE
#define GL_SAMPLE_ALPHA_TO_COVERAGE 0x809E
Definition at line 1836 of file SDL_opengl.h.
GL_SAMPLE_ALPHA_TO_ONE
#define GL_SAMPLE_ALPHA_TO_ONE 0x809F
Definition at line 1837 of file SDL_opengl.h.
GL_SAMPLE_BUFFERS
#define GL_SAMPLE_BUFFERS 0x80A8
Definition at line 1839 of file SDL_opengl.h.
GL_SAMPLE_COVERAGE
#define GL_SAMPLE_COVERAGE 0x80A0
Definition at line 1838 of file SDL_opengl.h.
GL_SAMPLE_COVERAGE_INVERT
#define GL_SAMPLE_COVERAGE_INVERT 0x80AB
Definition at line 1842 of file SDL_opengl.h.
GL_SAMPLE_COVERAGE_VALUE
#define GL_SAMPLE_COVERAGE_VALUE 0x80AA
Definition at line 1841 of file SDL_opengl.h.
GL_SAMPLES
#define GL_SAMPLES 0x80A9
Definition at line 1840 of file SDL_opengl.h.
GL_SCISSOR_BIT
#define GL_SCISSOR_BIT 0x00080000
Definition at line 747 of file SDL_opengl.h.
GL_SCISSOR_BOX
#define GL_SCISSOR_BOX 0x0C10
Definition at line 614 of file SDL_opengl.h.
GL_SCISSOR_TEST
#define GL_SCISSOR_TEST 0x0C11
Definition at line 615 of file SDL_opengl.h.
GL_SELECT
#define GL_SELECT 0x1C02
Definition at line 415 of file SDL_opengl.h.
GL_SELECTION_BUFFER_POINTER
#define GL_SELECTION_BUFFER_POINTER 0x0DF3
Definition at line 436 of file SDL_opengl.h.
GL_SELECTION_BUFFER_SIZE
#define GL_SELECTION_BUFFER_SIZE 0x0DF4
Definition at line 437 of file SDL_opengl.h.
GL_SEPARABLE_2D
#define GL_SEPARABLE_2D 0x8012
Definition at line 1603 of file SDL_opengl.h.
GL_SEPARATE_SPECULAR_COLOR
#define GL_SEPARATE_SPECULAR_COLOR 0x81FA
Definition at line 1526 of file SDL_opengl.h.
GL_SET
#define GL_SET 0x150F
Definition at line 457 of file SDL_opengl.h.
GL_SHADE_MODEL
#define GL_SHADE_MODEL 0x0B54
Definition at line 363 of file SDL_opengl.h.
GL_SHININESS
#define GL_SHININESS 0x1601
Definition at line 353 of file SDL_opengl.h.
GL_SHORT
#define GL_SHORT 0x1402
Definition at line 205 of file SDL_opengl.h.
GL_SINGLE_COLOR
#define GL_SINGLE_COLOR 0x81F9
Definition at line 1525 of file SDL_opengl.h.
GL_SMOOTH
#define GL_SMOOTH 0x1D01
Definition at line 365 of file SDL_opengl.h.
GL_SMOOTH_LINE_WIDTH_GRANULARITY
#define GL_SMOOTH_LINE_WIDTH_GRANULARITY 0x0B23
Definition at line 1534 of file SDL_opengl.h.
GL_SMOOTH_LINE_WIDTH_RANGE
#define GL_SMOOTH_LINE_WIDTH_RANGE 0x0B22
Definition at line 1533 of file SDL_opengl.h.
GL_SMOOTH_POINT_SIZE_GRANULARITY
#define GL_SMOOTH_POINT_SIZE_GRANULARITY 0x0B13
Definition at line 1532 of file SDL_opengl.h.
GL_SMOOTH_POINT_SIZE_RANGE
#define GL_SMOOTH_POINT_SIZE_RANGE 0x0B12
Definition at line 1531 of file SDL_opengl.h.
GL_SOURCE0_ALPHA
#define GL_SOURCE0_ALPHA 0x8588
Definition at line 1856 of file SDL_opengl.h.
GL_SOURCE0_RGB
#define GL_SOURCE0_RGB 0x8580
Definition at line 1853 of file SDL_opengl.h.
GL_SOURCE1_ALPHA
#define GL_SOURCE1_ALPHA 0x8589
Definition at line 1857 of file SDL_opengl.h.
GL_SOURCE1_RGB
#define GL_SOURCE1_RGB 0x8581
Definition at line 1854 of file SDL_opengl.h.
GL_SOURCE2_ALPHA
#define GL_SOURCE2_ALPHA 0x858A
Definition at line 1858 of file SDL_opengl.h.
GL_SOURCE2_RGB
#define GL_SOURCE2_RGB 0x8582
Definition at line 1855 of file SDL_opengl.h.
GL_SPECULAR
#define GL_SPECULAR 0x1202
Definition at line 352 of file SDL_opengl.h.
GL_SPHERE_MAP
#define GL_SPHERE_MAP 0x2402
Definition at line 701 of file SDL_opengl.h.
GL_SPOT_CUTOFF
#define GL_SPOT_CUTOFF 0x1206
Definition at line 346 of file SDL_opengl.h.
GL_SPOT_DIRECTION
#define GL_SPOT_DIRECTION 0x1204
Definition at line 356 of file SDL_opengl.h.
GL_SPOT_EXPONENT
#define GL_SPOT_EXPONENT 0x1205
Definition at line 345 of file SDL_opengl.h.
GL_SRC_ALPHA
#define GL_SRC_ALPHA 0x0302
Definition at line 404 of file SDL_opengl.h.
GL_SRC_ALPHA_SATURATE
#define GL_SRC_ALPHA_SATURATE 0x0308
Definition at line 410 of file SDL_opengl.h.
GL_SRC_COLOR
#define GL_SRC_COLOR 0x0300
Definition at line 402 of file SDL_opengl.h.
GL_STACK_OVERFLOW
#define GL_STACK_OVERFLOW 0x0503
Definition at line 723 of file SDL_opengl.h.
GL_STACK_UNDERFLOW
#define GL_STACK_UNDERFLOW 0x0504
Definition at line 724 of file SDL_opengl.h.
GL_STENCIL
#define GL_STENCIL 0x1802
Definition at line 526 of file SDL_opengl.h.
GL_STENCIL_BITS
#define GL_STENCIL_BITS 0x0D57
Definition at line 474 of file SDL_opengl.h.
GL_STENCIL_BUFFER_BIT
#define GL_STENCIL_BUFFER_BIT 0x00000400
Definition at line 738 of file SDL_opengl.h.
GL_STENCIL_CLEAR_VALUE
#define GL_STENCIL_CLEAR_VALUE 0x0B91
Definition at line 476 of file SDL_opengl.h.
GL_STENCIL_FAIL
#define GL_STENCIL_FAIL 0x0B94
Definition at line 479 of file SDL_opengl.h.
GL_STENCIL_FUNC
#define GL_STENCIL_FUNC 0x0B92
Definition at line 477 of file SDL_opengl.h.
GL_STENCIL_INDEX
#define GL_STENCIL_INDEX 0x1901
Definition at line 484 of file SDL_opengl.h.
GL_STENCIL_PASS_DEPTH_FAIL
#define GL_STENCIL_PASS_DEPTH_FAIL 0x0B95
Definition at line 480 of file SDL_opengl.h.
GL_STENCIL_PASS_DEPTH_PASS
#define GL_STENCIL_PASS_DEPTH_PASS 0x0B96
Definition at line 481 of file SDL_opengl.h.
GL_STENCIL_REF
#define GL_STENCIL_REF 0x0B97
Definition at line 482 of file SDL_opengl.h.
GL_STENCIL_TEST
#define GL_STENCIL_TEST 0x0B90
Definition at line 475 of file SDL_opengl.h.
GL_STENCIL_VALUE_MASK
#define GL_STENCIL_VALUE_MASK 0x0B93
Definition at line 478 of file SDL_opengl.h.
GL_STENCIL_WRITEMASK
#define GL_STENCIL_WRITEMASK 0x0B98
Definition at line 483 of file SDL_opengl.h.
GL_STEREO
#define GL_STEREO 0x0C33
Definition at line 522 of file SDL_opengl.h.
GL_SUBPIXEL_BITS
#define GL_SUBPIXEL_BITS 0x0D50
Definition at line 517 of file SDL_opengl.h.
GL_SUBTRACT
#define GL_SUBTRACT 0x84E7
Definition at line 1868 of file SDL_opengl.h.
GL_T
#define GL_T 0x2001
Definition at line 708 of file SDL_opengl.h.
GL_T2F_C3F_V3F
#define GL_T2F_C3F_V3F 0x2A2A
Definition at line 264 of file SDL_opengl.h.
GL_T2F_C4F_N3F_V3F
#define GL_T2F_C4F_N3F_V3F 0x2A2C
Definition at line 266 of file SDL_opengl.h.
GL_T2F_C4UB_V3F
#define GL_T2F_C4UB_V3F 0x2A29
Definition at line 263 of file SDL_opengl.h.
GL_T2F_N3F_V3F
#define GL_T2F_N3F_V3F 0x2A2B
Definition at line 265 of file SDL_opengl.h.
GL_T2F_V3F
#define GL_T2F_V3F 0x2A27
Definition at line 261 of file SDL_opengl.h.
GL_T4F_C4F_N3F_V4F
#define GL_T4F_C4F_N3F_V4F 0x2A2D
Definition at line 267 of file SDL_opengl.h.
GL_T4F_V4F
#define GL_T4F_V4F 0x2A28
Definition at line 262 of file SDL_opengl.h.
GL_TABLE_TOO_LARGE
#define GL_TABLE_TOO_LARGE 0x8031
Definition at line 1648 of file SDL_opengl.h.
GL_TEXTURE
#define GL_TEXTURE 0x1702
Definition at line 273 of file SDL_opengl.h.
GL_TEXTURE0
#define GL_TEXTURE0 0x84C0
Definition at line 1774 of file SDL_opengl.h.
GL_TEXTURE0_ARB
#define GL_TEXTURE0_ARB 0x84C0
Definition at line 1990 of file SDL_opengl.h.
GL_TEXTURE1
#define GL_TEXTURE1 0x84C1
Definition at line 1775 of file SDL_opengl.h.
GL_TEXTURE10
#define GL_TEXTURE10 0x84CA
Definition at line 1784 of file SDL_opengl.h.
GL_TEXTURE10_ARB
#define GL_TEXTURE10_ARB 0x84CA
Definition at line 2000 of file SDL_opengl.h.
GL_TEXTURE11
#define GL_TEXTURE11 0x84CB
Definition at line 1785 of file SDL_opengl.h.
GL_TEXTURE11_ARB
#define GL_TEXTURE11_ARB 0x84CB
Definition at line 2001 of file SDL_opengl.h.
GL_TEXTURE12
#define GL_TEXTURE12 0x84CC
Definition at line 1786 of file SDL_opengl.h.
GL_TEXTURE12_ARB
#define GL_TEXTURE12_ARB 0x84CC
Definition at line 2002 of file SDL_opengl.h.
GL_TEXTURE13
#define GL_TEXTURE13 0x84CD
Definition at line 1787 of file SDL_opengl.h.
GL_TEXTURE13_ARB
#define GL_TEXTURE13_ARB 0x84CD
Definition at line 2003 of file SDL_opengl.h.
GL_TEXTURE14
#define GL_TEXTURE14 0x84CE
Definition at line 1788 of file SDL_opengl.h.
GL_TEXTURE14_ARB
#define GL_TEXTURE14_ARB 0x84CE
Definition at line 2004 of file SDL_opengl.h.
GL_TEXTURE15
#define GL_TEXTURE15 0x84CF
Definition at line 1789 of file SDL_opengl.h.
GL_TEXTURE15_ARB
#define GL_TEXTURE15_ARB 0x84CF
Definition at line 2005 of file SDL_opengl.h.
GL_TEXTURE16
#define GL_TEXTURE16 0x84D0
Definition at line 1790 of file SDL_opengl.h.
GL_TEXTURE16_ARB
#define GL_TEXTURE16_ARB 0x84D0
Definition at line 2006 of file SDL_opengl.h.
GL_TEXTURE17
#define GL_TEXTURE17 0x84D1
Definition at line 1791 of file SDL_opengl.h.
GL_TEXTURE17_ARB
#define GL_TEXTURE17_ARB 0x84D1
Definition at line 2007 of file SDL_opengl.h.
GL_TEXTURE18
#define GL_TEXTURE18 0x84D2
Definition at line 1792 of file SDL_opengl.h.
GL_TEXTURE18_ARB
#define GL_TEXTURE18_ARB 0x84D2
Definition at line 2008 of file SDL_opengl.h.
GL_TEXTURE19
#define GL_TEXTURE19 0x84D3
Definition at line 1793 of file SDL_opengl.h.
GL_TEXTURE19_ARB
#define GL_TEXTURE19_ARB 0x84D3
Definition at line 2009 of file SDL_opengl.h.
GL_TEXTURE1_ARB
#define GL_TEXTURE1_ARB 0x84C1
Definition at line 1991 of file SDL_opengl.h.
GL_TEXTURE2
#define GL_TEXTURE2 0x84C2
Definition at line 1776 of file SDL_opengl.h.
GL_TEXTURE20
#define GL_TEXTURE20 0x84D4
Definition at line 1794 of file SDL_opengl.h.
GL_TEXTURE20_ARB
#define GL_TEXTURE20_ARB 0x84D4
Definition at line 2010 of file SDL_opengl.h.
GL_TEXTURE21
#define GL_TEXTURE21 0x84D5
Definition at line 1795 of file SDL_opengl.h.
GL_TEXTURE21_ARB
#define GL_TEXTURE21_ARB 0x84D5
Definition at line 2011 of file SDL_opengl.h.
GL_TEXTURE22
#define GL_TEXTURE22 0x84D6
Definition at line 1796 of file SDL_opengl.h.
GL_TEXTURE22_ARB
#define GL_TEXTURE22_ARB 0x84D6
Definition at line 2012 of file SDL_opengl.h.
GL_TEXTURE23
#define GL_TEXTURE23 0x84D7
Definition at line 1797 of file SDL_opengl.h.
GL_TEXTURE23_ARB
#define GL_TEXTURE23_ARB 0x84D7
Definition at line 2013 of file SDL_opengl.h.
GL_TEXTURE24
#define GL_TEXTURE24 0x84D8
Definition at line 1798 of file SDL_opengl.h.
GL_TEXTURE24_ARB
#define GL_TEXTURE24_ARB 0x84D8
Definition at line 2014 of file SDL_opengl.h.
GL_TEXTURE25
#define GL_TEXTURE25 0x84D9
Definition at line 1799 of file SDL_opengl.h.
GL_TEXTURE25_ARB
#define GL_TEXTURE25_ARB 0x84D9
Definition at line 2015 of file SDL_opengl.h.
GL_TEXTURE26
#define GL_TEXTURE26 0x84DA
Definition at line 1800 of file SDL_opengl.h.
GL_TEXTURE26_ARB
#define GL_TEXTURE26_ARB 0x84DA
Definition at line 2016 of file SDL_opengl.h.
GL_TEXTURE27
#define GL_TEXTURE27 0x84DB
Definition at line 1801 of file SDL_opengl.h.
GL_TEXTURE27_ARB
#define GL_TEXTURE27_ARB 0x84DB
Definition at line 2017 of file SDL_opengl.h.
GL_TEXTURE28
#define GL_TEXTURE28 0x84DC
Definition at line 1802 of file SDL_opengl.h.
GL_TEXTURE28_ARB
#define GL_TEXTURE28_ARB 0x84DC
Definition at line 2018 of file SDL_opengl.h.
GL_TEXTURE29
#define GL_TEXTURE29 0x84DD
Definition at line 1803 of file SDL_opengl.h.
GL_TEXTURE29_ARB
#define GL_TEXTURE29_ARB 0x84DD
Definition at line 2019 of file SDL_opengl.h.
GL_TEXTURE2_ARB
#define GL_TEXTURE2_ARB 0x84C2
Definition at line 1992 of file SDL_opengl.h.
GL_TEXTURE3
#define GL_TEXTURE3 0x84C3
Definition at line 1777 of file SDL_opengl.h.
GL_TEXTURE30
#define GL_TEXTURE30 0x84DE
Definition at line 1804 of file SDL_opengl.h.
GL_TEXTURE30_ARB
#define GL_TEXTURE30_ARB 0x84DE
Definition at line 2020 of file SDL_opengl.h.
GL_TEXTURE31
#define GL_TEXTURE31 0x84DF
Definition at line 1805 of file SDL_opengl.h.
GL_TEXTURE31_ARB
#define GL_TEXTURE31_ARB 0x84DF
Definition at line 2021 of file SDL_opengl.h.
GL_TEXTURE3_ARB
#define GL_TEXTURE3_ARB 0x84C3
Definition at line 1993 of file SDL_opengl.h.
GL_TEXTURE4
#define GL_TEXTURE4 0x84C4
Definition at line 1778 of file SDL_opengl.h.
GL_TEXTURE4_ARB
#define GL_TEXTURE4_ARB 0x84C4
Definition at line 1994 of file SDL_opengl.h.
GL_TEXTURE5
#define GL_TEXTURE5 0x84C5
Definition at line 1779 of file SDL_opengl.h.
GL_TEXTURE5_ARB
#define GL_TEXTURE5_ARB 0x84C5
Definition at line 1995 of file SDL_opengl.h.
GL_TEXTURE6
#define GL_TEXTURE6 0x84C6
Definition at line 1780 of file SDL_opengl.h.
GL_TEXTURE6_ARB
#define GL_TEXTURE6_ARB 0x84C6
Definition at line 1996 of file SDL_opengl.h.
GL_TEXTURE7
#define GL_TEXTURE7 0x84C7
Definition at line 1781 of file SDL_opengl.h.
GL_TEXTURE7_ARB
#define GL_TEXTURE7_ARB 0x84C7
Definition at line 1997 of file SDL_opengl.h.
GL_TEXTURE8
#define GL_TEXTURE8 0x84C8
Definition at line 1782 of file SDL_opengl.h.
GL_TEXTURE8_ARB
#define GL_TEXTURE8_ARB 0x84C8
Definition at line 1998 of file SDL_opengl.h.
GL_TEXTURE9
#define GL_TEXTURE9 0x84C9
Definition at line 1783 of file SDL_opengl.h.
GL_TEXTURE9_ARB
#define GL_TEXTURE9_ARB 0x84C9
Definition at line 1999 of file SDL_opengl.h.
GL_TEXTURE_1D
#define GL_TEXTURE_1D 0x0DE0
Definition at line 670 of file SDL_opengl.h.
GL_TEXTURE_2D
#define GL_TEXTURE_2D 0x0DE1
Definition at line 671 of file SDL_opengl.h.
GL_TEXTURE_3D
#define GL_TEXTURE_3D 0x806F
Definition at line 1541 of file SDL_opengl.h.
GL_TEXTURE_ALPHA_SIZE
#define GL_TEXTURE_ALPHA_SIZE 0x805F
Definition at line 690 of file SDL_opengl.h.
GL_TEXTURE_BASE_LEVEL
#define GL_TEXTURE_BASE_LEVEL 0x813C
Definition at line 1529 of file SDL_opengl.h.
GL_TEXTURE_BINDING_1D
#define GL_TEXTURE_BINDING_1D 0x8068
Definition at line 756 of file SDL_opengl.h.
GL_TEXTURE_BINDING_2D
#define GL_TEXTURE_BINDING_2D 0x8069
Definition at line 757 of file SDL_opengl.h.
GL_TEXTURE_BINDING_3D
#define GL_TEXTURE_BINDING_3D 0x806A
Definition at line 1546 of file SDL_opengl.h.
GL_TEXTURE_BINDING_CUBE_MAP
#define GL_TEXTURE_BINDING_CUBE_MAP 0x8514
Definition at line 1813 of file SDL_opengl.h.
GL_TEXTURE_BIT
#define GL_TEXTURE_BIT 0x00040000
Definition at line 746 of file SDL_opengl.h.
GL_TEXTURE_BLUE_SIZE
#define GL_TEXTURE_BLUE_SIZE 0x805E
Definition at line 689 of file SDL_opengl.h.
GL_TEXTURE_BORDER
#define GL_TEXTURE_BORDER 0x1005
Definition at line 685 of file SDL_opengl.h.
GL_TEXTURE_BORDER_COLOR
#define GL_TEXTURE_BORDER_COLOR 0x1004
Definition at line 682 of file SDL_opengl.h.
GL_TEXTURE_COMPONENTS
#define GL_TEXTURE_COMPONENTS 0x1003
Definition at line 686 of file SDL_opengl.h.
GL_TEXTURE_COMPRESSED
#define GL_TEXTURE_COMPRESSED 0x86A1
Definition at line 1831 of file SDL_opengl.h.
GL_TEXTURE_COMPRESSED_IMAGE_SIZE
#define GL_TEXTURE_COMPRESSED_IMAGE_SIZE 0x86A0
Definition at line 1830 of file SDL_opengl.h.
GL_TEXTURE_COMPRESSION_HINT
#define GL_TEXTURE_COMPRESSION_HINT 0x84EF
Definition at line 1829 of file SDL_opengl.h.
GL_TEXTURE_COORD_ARRAY
#define GL_TEXTURE_COORD_ARRAY 0x8078
Definition at line 232 of file SDL_opengl.h.
GL_TEXTURE_COORD_ARRAY_POINTER
#define GL_TEXTURE_COORD_ARRAY_POINTER 0x8092
Definition at line 252 of file SDL_opengl.h.
GL_TEXTURE_COORD_ARRAY_SIZE
#define GL_TEXTURE_COORD_ARRAY_SIZE 0x8088
Definition at line 244 of file SDL_opengl.h.
GL_TEXTURE_COORD_ARRAY_STRIDE
#define GL_TEXTURE_COORD_ARRAY_STRIDE 0x808A
Definition at line 246 of file SDL_opengl.h.
GL_TEXTURE_COORD_ARRAY_TYPE
#define GL_TEXTURE_COORD_ARRAY_TYPE 0x8089
Definition at line 245 of file SDL_opengl.h.
GL_TEXTURE_CUBE_MAP
#define GL_TEXTURE_CUBE_MAP 0x8513
Definition at line 1812 of file SDL_opengl.h.
GL_TEXTURE_CUBE_MAP_NEGATIVE_X
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_X 0x8516
Definition at line 1815 of file SDL_opengl.h.
GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Y 0x8518
Definition at line 1817 of file SDL_opengl.h.
GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
#define GL_TEXTURE_CUBE_MAP_NEGATIVE_Z 0x851A
Definition at line 1819 of file SDL_opengl.h.
GL_TEXTURE_CUBE_MAP_POSITIVE_X
#define GL_TEXTURE_CUBE_MAP_POSITIVE_X 0x8515
Definition at line 1814 of file SDL_opengl.h.
GL_TEXTURE_CUBE_MAP_POSITIVE_Y
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Y 0x8517
Definition at line 1816 of file SDL_opengl.h.
GL_TEXTURE_CUBE_MAP_POSITIVE_Z
#define GL_TEXTURE_CUBE_MAP_POSITIVE_Z 0x8519
Definition at line 1818 of file SDL_opengl.h.
GL_TEXTURE_DEPTH
#define GL_TEXTURE_DEPTH 0x8071
Definition at line 1543 of file SDL_opengl.h.
GL_TEXTURE_ENV
#define GL_TEXTURE_ENV 0x2300
Definition at line 668 of file SDL_opengl.h.
GL_TEXTURE_ENV_COLOR
#define GL_TEXTURE_ENV_COLOR 0x2201
Definition at line 676 of file SDL_opengl.h.
GL_TEXTURE_ENV_MODE
#define GL_TEXTURE_ENV_MODE 0x2200
Definition at line 669 of file SDL_opengl.h.
GL_TEXTURE_GEN_MODE
#define GL_TEXTURE_GEN_MODE 0x2500
Definition at line 681 of file SDL_opengl.h.
GL_TEXTURE_GEN_Q
#define GL_TEXTURE_GEN_Q 0x0C63
Definition at line 680 of file SDL_opengl.h.
GL_TEXTURE_GEN_R
#define GL_TEXTURE_GEN_R 0x0C62
Definition at line 679 of file SDL_opengl.h.
GL_TEXTURE_GEN_S
#define GL_TEXTURE_GEN_S 0x0C60
Definition at line 677 of file SDL_opengl.h.
GL_TEXTURE_GEN_T
#define GL_TEXTURE_GEN_T 0x0C61
Definition at line 678 of file SDL_opengl.h.
GL_TEXTURE_GREEN_SIZE
#define GL_TEXTURE_GREEN_SIZE 0x805D
Definition at line 688 of file SDL_opengl.h.
GL_TEXTURE_HEIGHT
#define GL_TEXTURE_HEIGHT 0x1001
Definition at line 684 of file SDL_opengl.h.
GL_TEXTURE_INTENSITY_SIZE
#define GL_TEXTURE_INTENSITY_SIZE 0x8061
Definition at line 692 of file SDL_opengl.h.
GL_TEXTURE_INTERNAL_FORMAT
#define GL_TEXTURE_INTERNAL_FORMAT 0x1003
Definition at line 758 of file SDL_opengl.h.
GL_TEXTURE_LUMINANCE_SIZE
#define GL_TEXTURE_LUMINANCE_SIZE 0x8060
Definition at line 691 of file SDL_opengl.h.
GL_TEXTURE_MAG_FILTER
#define GL_TEXTURE_MAG_FILTER 0x2800
Definition at line 674 of file SDL_opengl.h.
GL_TEXTURE_MATRIX
#define GL_TEXTURE_MATRIX 0x0BA8
Definition at line 571 of file SDL_opengl.h.
GL_TEXTURE_MAX_LEVEL
#define GL_TEXTURE_MAX_LEVEL 0x813D
Definition at line 1530 of file SDL_opengl.h.
GL_TEXTURE_MAX_LOD
#define GL_TEXTURE_MAX_LOD 0x813B
Definition at line 1528 of file SDL_opengl.h.
GL_TEXTURE_MIN_FILTER
#define GL_TEXTURE_MIN_FILTER 0x2801
Definition at line 675 of file SDL_opengl.h.
GL_TEXTURE_MIN_LOD
#define GL_TEXTURE_MIN_LOD 0x813A
Definition at line 1527 of file SDL_opengl.h.
GL_TEXTURE_PRIORITY
#define GL_TEXTURE_PRIORITY 0x8066
Definition at line 754 of file SDL_opengl.h.
GL_TEXTURE_RED_SIZE
#define GL_TEXTURE_RED_SIZE 0x805C
Definition at line 687 of file SDL_opengl.h.
GL_TEXTURE_RESIDENT
#define GL_TEXTURE_RESIDENT 0x8067
Definition at line 755 of file SDL_opengl.h.
GL_TEXTURE_STACK_DEPTH
#define GL_TEXTURE_STACK_DEPTH 0x0BA5
Definition at line 572 of file SDL_opengl.h.
GL_TEXTURE_WIDTH
#define GL_TEXTURE_WIDTH 0x1000
Definition at line 683 of file SDL_opengl.h.
GL_TEXTURE_WRAP_R
#define GL_TEXTURE_WRAP_R 0x8072
Definition at line 1544 of file SDL_opengl.h.
GL_TEXTURE_WRAP_S
#define GL_TEXTURE_WRAP_S 0x2802
Definition at line 672 of file SDL_opengl.h.
GL_TEXTURE_WRAP_T
#define GL_TEXTURE_WRAP_T 0x2803
Definition at line 673 of file SDL_opengl.h.
GL_TRANSFORM_BIT
#define GL_TRANSFORM_BIT 0x00001000
Definition at line 740 of file SDL_opengl.h.
GL_TRANSPOSE_COLOR_MATRIX
#define GL_TRANSPOSE_COLOR_MATRIX 0x84E6
Definition at line 1848 of file SDL_opengl.h.
GL_TRANSPOSE_MODELVIEW_MATRIX
#define GL_TRANSPOSE_MODELVIEW_MATRIX 0x84E3
Definition at line 1845 of file SDL_opengl.h.
GL_TRANSPOSE_PROJECTION_MATRIX
#define GL_TRANSPOSE_PROJECTION_MATRIX 0x84E4
Definition at line 1846 of file SDL_opengl.h.
GL_TRANSPOSE_TEXTURE_MATRIX
#define GL_TRANSPOSE_TEXTURE_MATRIX 0x84E5
Definition at line 1847 of file SDL_opengl.h.
GL_TRIANGLE_FAN
#define GL_TRIANGLE_FAN 0x0006
Definition at line 222 of file SDL_opengl.h.
GL_TRIANGLE_STRIP
#define GL_TRIANGLE_STRIP 0x0005
Definition at line 221 of file SDL_opengl.h.
GL_TRIANGLES
#define GL_TRIANGLES 0x0004
Definition at line 220 of file SDL_opengl.h.
GL_TRUE
#define GL_TRUE 1
Definition at line 200 of file SDL_opengl.h.
GL_UNPACK_ALIGNMENT
#define GL_UNPACK_ALIGNMENT 0x0CF5
Definition at line 658 of file SDL_opengl.h.
GL_UNPACK_IMAGE_HEIGHT
#define GL_UNPACK_IMAGE_HEIGHT 0x806E
Definition at line 1540 of file SDL_opengl.h.
GL_UNPACK_LSB_FIRST
#define GL_UNPACK_LSB_FIRST 0x0CF1
Definition at line 659 of file SDL_opengl.h.
GL_UNPACK_ROW_LENGTH
#define GL_UNPACK_ROW_LENGTH 0x0CF2
Definition at line 660 of file SDL_opengl.h.
GL_UNPACK_SKIP_IMAGES
#define GL_UNPACK_SKIP_IMAGES 0x806D
Definition at line 1539 of file SDL_opengl.h.
GL_UNPACK_SKIP_PIXELS
#define GL_UNPACK_SKIP_PIXELS 0x0CF4
Definition at line 661 of file SDL_opengl.h.
GL_UNPACK_SKIP_ROWS
#define GL_UNPACK_SKIP_ROWS 0x0CF3
Definition at line 662 of file SDL_opengl.h.
GL_UNPACK_SWAP_BYTES
#define GL_UNPACK_SWAP_BYTES 0x0CF0
Definition at line 663 of file SDL_opengl.h.
GL_UNSIGNED_BYTE
#define GL_UNSIGNED_BYTE 0x1401
Definition at line 204 of file SDL_opengl.h.
GL_UNSIGNED_BYTE_2_3_3_REV
#define GL_UNSIGNED_BYTE_2_3_3_REV 0x8362
Definition at line 1513 of file SDL_opengl.h.
GL_UNSIGNED_BYTE_3_3_2
#define GL_UNSIGNED_BYTE_3_3_2 0x8032
Definition at line 1512 of file SDL_opengl.h.
GL_UNSIGNED_INT
#define GL_UNSIGNED_INT 0x1405
Definition at line 208 of file SDL_opengl.h.
GL_UNSIGNED_INT_10_10_10_2
#define GL_UNSIGNED_INT_10_10_10_2 0x8036
Definition at line 1522 of file SDL_opengl.h.
GL_UNSIGNED_INT_24_8_MESA
#define GL_UNSIGNED_INT_24_8_MESA 0x8751
Definition at line 2118 of file SDL_opengl.h.
GL_UNSIGNED_INT_2_10_10_10_REV
#define GL_UNSIGNED_INT_2_10_10_10_REV 0x8368
Definition at line 1523 of file SDL_opengl.h.
GL_UNSIGNED_INT_8_24_REV_MESA
#define GL_UNSIGNED_INT_8_24_REV_MESA 0x8752
Definition at line 2119 of file SDL_opengl.h.
GL_UNSIGNED_INT_8_8_8_8
#define GL_UNSIGNED_INT_8_8_8_8 0x8035
Definition at line 1520 of file SDL_opengl.h.
GL_UNSIGNED_INT_8_8_8_8_REV
#define GL_UNSIGNED_INT_8_8_8_8_REV 0x8367
Definition at line 1521 of file SDL_opengl.h.
GL_UNSIGNED_SHORT
#define GL_UNSIGNED_SHORT 0x1403
Definition at line 206 of file SDL_opengl.h.
GL_UNSIGNED_SHORT_15_1_MESA
#define GL_UNSIGNED_SHORT_15_1_MESA 0x8753
Definition at line 2120 of file SDL_opengl.h.
GL_UNSIGNED_SHORT_1_15_REV_MESA
#define GL_UNSIGNED_SHORT_1_15_REV_MESA 0x8754
Definition at line 2121 of file SDL_opengl.h.
GL_UNSIGNED_SHORT_1_5_5_5_REV
#define GL_UNSIGNED_SHORT_1_5_5_5_REV 0x8366
Definition at line 1519 of file SDL_opengl.h.
GL_UNSIGNED_SHORT_4_4_4_4
#define GL_UNSIGNED_SHORT_4_4_4_4 0x8033
Definition at line 1516 of file SDL_opengl.h.
GL_UNSIGNED_SHORT_4_4_4_4_REV
#define GL_UNSIGNED_SHORT_4_4_4_4_REV 0x8365
Definition at line 1517 of file SDL_opengl.h.
GL_UNSIGNED_SHORT_5_5_5_1
#define GL_UNSIGNED_SHORT_5_5_5_1 0x8034
Definition at line 1518 of file SDL_opengl.h.
GL_UNSIGNED_SHORT_5_6_5
#define GL_UNSIGNED_SHORT_5_6_5 0x8363
Definition at line 1514 of file SDL_opengl.h.
GL_UNSIGNED_SHORT_5_6_5_REV
#define GL_UNSIGNED_SHORT_5_6_5_REV 0x8364
Definition at line 1515 of file SDL_opengl.h.
GL_V2F
#define GL_V2F 0x2A20
Definition at line 254 of file SDL_opengl.h.
GL_V3F
#define GL_V3F 0x2A21
Definition at line 255 of file SDL_opengl.h.
GL_VENDOR
#define GL_VENDOR 0x1F00
Definition at line 713 of file SDL_opengl.h.
GL_VERSION
#define GL_VERSION 0x1F02
Definition at line 715 of file SDL_opengl.h.
GL_VERSION_1_1
#define GL_VERSION_1_1 1
Definition at line 167 of file SDL_opengl.h.
GL_VERSION_1_2
#define GL_VERSION_1_2 1
Definition at line 168 of file SDL_opengl.h.
GL_VERSION_1_3
#define GL_VERSION_1_3 1
Definition at line 169 of file SDL_opengl.h.
GL_VERTEX_ARRAY
#define GL_VERTEX_ARRAY 0x8074
Definition at line 228 of file SDL_opengl.h.
GL_VERTEX_ARRAY_POINTER
#define GL_VERTEX_ARRAY_POINTER 0x808E
Definition at line 248 of file SDL_opengl.h.
GL_VERTEX_ARRAY_SIZE
#define GL_VERTEX_ARRAY_SIZE 0x807A
Definition at line 234 of file SDL_opengl.h.
GL_VERTEX_ARRAY_STRIDE
#define GL_VERTEX_ARRAY_STRIDE 0x807C
Definition at line 236 of file SDL_opengl.h.
GL_VERTEX_ARRAY_TYPE
#define GL_VERTEX_ARRAY_TYPE 0x807B
Definition at line 235 of file SDL_opengl.h.
GL_VIEWPORT
#define GL_VIEWPORT 0x0BA2
Definition at line 573 of file SDL_opengl.h.
GL_VIEWPORT_BIT
#define GL_VIEWPORT_BIT 0x00000800
Definition at line 739 of file SDL_opengl.h.
GL_XOR
#define GL_XOR 0x1506
Definition at line 466 of file SDL_opengl.h.
GL_ZERO
#define GL_ZERO 0
Definition at line 400 of file SDL_opengl.h.
GL_ZOOM_X
#define GL_ZOOM_X 0x0D16
Definition at line 664 of file SDL_opengl.h.
GL_ZOOM_Y
#define GL_ZOOM_Y 0x0D17
Definition at line 665 of file SDL_opengl.h.
GLAPI
#define GLAPI extern
Definition at line 131 of file SDL_opengl.h.
GLAPIENTRY
#define GLAPIENTRY
Definition at line 135 of file SDL_opengl.h.
GLAPIENTRYP
#define GLAPIENTRYP GLAPIENTRY *
Definition at line 148 of file SDL_opengl.h.
Typedef Documentation
border
typedef GLint GLenum GLsizei GLsizei GLsizei GLint border
Definition at line 1572 of file SDL_opengl.h.
count
typedef GLsizei count
Definition at line 1571 of file SDL_opengl.h.
data
typedef GLint GLsizei GLsizei GLenum GLenum GLsizei GLvoid * data
Definition at line 1974 of file SDL_opengl.h.
depth
typedef GLint GLint GLint GLint GLsizei GLsizei GLsizei depth
Definition at line 1572 of file SDL_opengl.h.
end
typedef GLuint GLuint end
Definition at line 1571 of file SDL_opengl.h.
format
typedef GLint GLint GLsizei GLenum format
Definition at line 1572 of file SDL_opengl.h.
GLbitfield
typedef unsigned int GLbitfield
Definition at line 178 of file SDL_opengl.h.
GLboolean
typedef GLboolean
Definition at line 177 of file SDL_opengl.h.
GLbyte
typedef signed char GLbyte
Definition at line 180 of file SDL_opengl.h.
GLclampd
typedef double GLclampd
Definition at line 190 of file SDL_opengl.h.
GLclampf
typedef float GLclampf
Definition at line 188 of file SDL_opengl.h.
GLdouble
typedef double GLdouble
Definition at line 189 of file SDL_opengl.h.
GLeglImageOES
typedef void* GLeglImageOES
Definition at line 2139 of file SDL_opengl.h.
GLenum
typedef GLenum
Definition at line 176 of file SDL_opengl.h.
GLfloat
typedef float GLfloat
Definition at line 187 of file SDL_opengl.h.
GLint
typedef GLint
Definition at line 182 of file SDL_opengl.h.
GLshort
typedef short GLshort
Definition at line 181 of file SDL_opengl.h.
GLsizei
typedef int GLsizei
Definition at line 186 of file SDL_opengl.h.
GLubyte
typedef unsigned char GLubyte
Definition at line 183 of file SDL_opengl.h.
GLuint
typedef GLuint
Definition at line 185 of file SDL_opengl.h.
GLushort
typedef unsigned short GLushort
Definition at line 184 of file SDL_opengl.h.
GLvoid
typedef void GLvoid
Definition at line 179 of file SDL_opengl.h.
height
typedef GLuint GLuint GLuint height
Definition at line 1572 of file SDL_opengl.h.
image
typedef GLeglImageOES image
Definition at line 2148 of file SDL_opengl.h.
imageSize
typedef GLint GLint GLint GLint GLsizei GLsizei GLsizei GLenum GLsizei imageSize
Definition at line 1974 of file SDL_opengl.h.
img
typedef GLenum GLint void * img
Definition at line 1980 of file SDL_opengl.h.
indices
typedef GLsizei GLenum const GLvoid * indices
Definition at line 1571 of file SDL_opengl.h.
internalformat
typedef GLsizei GLenum internalformat
Definition at line 1572 of file SDL_opengl.h.
invert
typedef GLboolean invert
Definition at line 1973 of file SDL_opengl.h.
level
typedef GLint level
Definition at line 1572 of file SDL_opengl.h.
modeA
typedef GLenum modeA
Definition at line 2132 of file SDL_opengl.h.
pixels
typedef GLint GLint GLint GLint GLsizei GLsizei GLsizei GLenum GLenum const GLvoid * pixels
Definition at line 1572 of file SDL_opengl.h.
q
typedef GLfloat GLfloat GLfloat q
Definition at line 2087 of file SDL_opengl.h.
r
typedef GLfloat GLfloat GLfloat r
Definition at line 2079 of file SDL_opengl.h.
s
typedef GLfloat s
Definition at line 2063 of file SDL_opengl.h.
start
typedef GLuint start
Definition at line 1571 of file SDL_opengl.h.
t
typedef GLfloat GLfloat t
Definition at line 2071 of file SDL_opengl.h.
type
typedef GLint GLint GLint GLint GLsizei GLsizei GLsizei GLenum GLenum type
Definition at line 1571 of file SDL_opengl.h.
v
typedef const GLfloat const GLfloat const GLfloat const GLfloat * v
Definition at line 2064 of file SDL_opengl.h.
width
typedef GLuint GLuint width
Definition at line 1572 of file SDL_opengl.h.
x
typedef GLint GLfloat x
Definition at line 1574 of file SDL_opengl.h.
xoffset
typedef GLint GLint xoffset
Definition at line 1573 of file SDL_opengl.h.
y
typedef GLuint y
Definition at line 1574 of file SDL_opengl.h.
yoffset
typedef GLint GLint GLint yoffset
Definition at line 1573 of file SDL_opengl.h.
zoffset
typedef GLint GLint GLint GLint zoffset
Definition at line 1573 of file SDL_opengl.h.
Function Documentation
glAccum()
GLAPI void GLAPIENTRY glAccum (GLenum op, GLfloat value)
glActiveTexture()
GLAPI void GLAPIENTRY glActiveTexture (GLenum texture)
glActiveTextureARB()
GLAPI void GLAPIENTRY glActiveTextureARB (GLenum texture)
glAlphaFunc()
GLAPI void GLAPIENTRY glAlphaFunc (GLenum func, GLclampf ref)
glAreTexturesResident()
GLAPI GLboolean GLAPIENTRY glAreTexturesResident (GLsizei n, const GLuint * textures, GLboolean * residences)
glArrayElement()
GLAPI void GLAPIENTRY glArrayElement (GLint i)
glBegin()
GLAPI void GLAPIENTRY glBegin (GLenum mode)
Referenced by TexturedPolygons::CreateAngledPolygon(), TexturedPolygons::CreateDisplayList(), TexturedPolygons::CreateXtoYWindowList(), TexturedPolygons::CreateYtoZWindowList(), CameraMap::DisplayMap(), DisplayShaysWorld::DrawAboveWindowBlock(), DisplayShaysWorld::DrawAngledRoofBeam(), DisplayShaysWorld::DrawAngledRoofBeam2(), DisplayShaysWorld::DrawBookSteps(), DisplayShaysWorld::DrawBookStepsTwo(), DisplayShaysWorld::DrawChancPosts(), DisplayShaysWorld::DrawCylinders(), DisplayShaysWorld::DrawExtras(), DisplayShaysWorld::DrawLibraryPosts(), DisplayShaysWorld::DrawLights(), DisplayShaysWorld::DrawPavement(), DisplayShaysWorld::DrawPhysSciPosts(), DisplayShaysWorld::DrawRoof(), and DisplayShaysWorld::drawStairRailing().
glBindTexture()
GLAPI void GLAPIENTRY glBindTexture (GLenum target, GLuint texture)
Referenced by TexturedPolygons::CreatePNGTexture(), TexturedPolygons::CreateTexture(), DisplayShaysWorld::DisplayAboveWindowBlock(), DisplayShaysWorld::DisplayBench(), DisplayShaysWorld::DisplayBookSteps(), DisplayShaysWorld::DisplayBookStepsTwo(), DisplayShaysWorld::DisplayBricks(), DisplayShaysWorld::DisplayChancPosts(), DisplayShaysWorld::DisplayCylinders(), DisplayShaysWorld::DisplayDoorPaving(), DisplayShaysWorld::DisplayDoorPosts(), DisplayShaysWorld::DisplayEntranceSteps(), DisplayShaysWorld::DisplayExtras(), DisplayShaysWorld::DisplayGrass(), DisplayWrathWorld::displayGroundPlane(), DisplayShaysWorld::DisplayLargerTextures(), DisplayShaysWorld::DisplayLibraryPosts(), DisplayShaysWorld::DisplayLights(), DisplayShaysWorld::DisplayMainPosts(), CameraMap::DisplayMap(), CameraMap::DisplayNoExit(), DisplayShaysWorld::DisplayPavement(), DisplayShaysWorld::DisplayPhysSciPosts(), DisplayWrathWorld::displayPortal(), DisplayShaysWorld::displayPortal(), DisplayShaysWorld::DisplayPurplePosts(), DisplayShaysWorld::DisplayRedPosts(), DisplayShaysWorld::DisplayRoof(), DisplayWrathWorld::displaySkyBox(), DisplayShaysWorld::displaySpecialPortal(), DisplayShaysWorld::displayStairRailing(), DisplayShaysWorld::DisplayStepBricks(), and CameraMap::DisplayWelcomeScreen().
glBitmap()
GLAPI void GLAPIENTRY glBitmap (GLsizei width, GLsizei height, GLfloat xorig, GLfloat yorig, GLfloat xmove, GLfloat ymove, const GLubyte * bitmap)
glBlendColor()
GLAPI void GLAPIENTRY glBlendColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
glBlendEquation()
GLAPI void GLAPIENTRY glBlendEquation (GLenum mode)
glBlendEquationSeparateATI()
GLAPI void GLAPIENTRY glBlendEquationSeparateATI (GLenum modeRGB, GLenum modeA)
glBlendFunc()
GLAPI void GLAPIENTRY glBlendFunc (GLenum sfactor, GLenum dfactor)
glCallList()
GLAPI void GLAPIENTRY glCallList (GLuint list)
Referenced by DisplayShaysWorld::DisplayAboveWindowBlock(), DisplayShaysWorld::DisplayBench(), DisplayShaysWorld::DisplayBookSteps(), DisplayShaysWorld::DisplayBookStepsTwo(), DisplayShaysWorld::DisplayBricks(), DisplayShaysWorld::DisplayChancPosts(), DisplayShaysWorld::DisplayCylinders(), DisplayShaysWorld::DisplayDoorPaving(), DisplayShaysWorld::DisplayDoorPosts(), DisplayShaysWorld::DisplayEntranceSteps(), DisplayShaysWorld::DisplayExtras(), DisplayShaysWorld::DisplayGrass(), DisplayWrathWorld::displayGroundPlane(), DisplayShaysWorld::DisplayLargerTextures(), DisplayShaysWorld::DisplayLibraryPosts(), DisplayShaysWorld::DisplayLights(), DisplayShaysWorld::DisplayMainPosts(), CameraMap::DisplayMap(), CameraMap::DisplayNoExit(), DisplayShaysWorld::DisplayPavement(), DisplayShaysWorld::DisplayPhysSciPosts(), DisplayWrathWorld::displayPortal(), DisplayShaysWorld::displayPortal(), DisplayShaysWorld::DisplayPurplePosts(), DisplayShaysWorld::DisplayRedPosts(), DisplayShaysWorld::DisplayRoof(), DisplayWrathWorld::displaySkyBox(), DisplayShaysWorld::displaySpecialPortal(), DisplayShaysWorld::displayStairRailing(), DisplayShaysWorld::DisplayStepBricks(), and CameraMap::DisplayWelcomeScreen().
glCallLists()
GLAPI void GLAPIENTRY glCallLists (GLsizei n, GLenum type, const GLvoid * lists)
glClear()
GLAPI void GLAPIENTRY glClear (GLbitfield mask)
Referenced by Display().
glClearAccum()
GLAPI void GLAPIENTRY glClearAccum (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
glClearColor()
GLAPI void GLAPIENTRY glClearColor (GLclampf red, GLclampf green, GLclampf blue, GLclampf alpha)
Referenced by DisplayWrathWorld::myinit(), and DisplayShaysWorld::myinit().
glClearDepth()
GLAPI void GLAPIENTRY glClearDepth (GLclampd depth)
glClearIndex()
GLAPI void GLAPIENTRY glClearIndex (GLfloat c)
glClearStencil()
GLAPI void GLAPIENTRY glClearStencil (GLint s)
glClientActiveTexture()
GLAPI void GLAPIENTRY glClientActiveTexture (GLenum texture)
glClientActiveTextureARB()
GLAPI void GLAPIENTRY glClientActiveTextureARB (GLenum texture)
glClipPlane()
GLAPI void GLAPIENTRY glClipPlane (GLenum plane, const GLdouble * equation)
glColor3b()
GLAPI void GLAPIENTRY glColor3b (GLbyte red, GLbyte green, GLbyte blue)
glColor3bv()
GLAPI void GLAPIENTRY glColor3bv (const GLbyte * v)
glColor3d()
GLAPI void GLAPIENTRY glColor3d (GLdouble red, GLdouble green, GLdouble blue)
glColor3dv()
GLAPI void GLAPIENTRY glColor3dv (const GLdouble * v)
glColor3f()
GLAPI void GLAPIENTRY glColor3f (GLfloat red, GLfloat green, GLfloat blue)
glColor3fv()
GLAPI void GLAPIENTRY glColor3fv (const GLfloat * v)
glColor3i()
GLAPI void GLAPIENTRY glColor3i (GLint red, GLint green, GLint blue)
glColor3iv()
GLAPI void GLAPIENTRY glColor3iv (const GLint * v)
glColor3s()
GLAPI void GLAPIENTRY glColor3s (GLshort red, GLshort green, GLshort blue)
glColor3sv()
GLAPI void GLAPIENTRY glColor3sv (const GLshort * v)
glColor3ub()
GLAPI void GLAPIENTRY glColor3ub (GLubyte red, GLubyte green, GLubyte blue)
glColor3ubv()
GLAPI void GLAPIENTRY glColor3ubv (const GLubyte * v)
glColor3ui()
GLAPI void GLAPIENTRY glColor3ui (GLuint red, GLuint green, GLuint blue)
glColor3uiv()
GLAPI void GLAPIENTRY glColor3uiv (const GLuint * v)
glColor3us()
GLAPI void GLAPIENTRY glColor3us (GLushort red, GLushort green, GLushort blue)
glColor3usv()
GLAPI void GLAPIENTRY glColor3usv (const GLushort * v)
glColor4b()
GLAPI void GLAPIENTRY glColor4b (GLbyte red, GLbyte green, GLbyte blue, GLbyte alpha)
glColor4bv()
GLAPI void GLAPIENTRY glColor4bv (const GLbyte * v)
glColor4d()
GLAPI void GLAPIENTRY glColor4d (GLdouble red, GLdouble green, GLdouble blue, GLdouble alpha)
glColor4dv()
GLAPI void GLAPIENTRY glColor4dv (const GLdouble * v)
glColor4f()
GLAPI void GLAPIENTRY glColor4f (GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha)
glColor4fv()
GLAPI void GLAPIENTRY glColor4fv (const GLfloat * v)
glColor4i()
GLAPI void GLAPIENTRY glColor4i (GLint red, GLint green, GLint blue, GLint alpha)
glColor4iv()
GLAPI void GLAPIENTRY glColor4iv (const GLint * v)
glColor4s()
GLAPI void GLAPIENTRY glColor4s (GLshort red, GLshort green, GLshort blue, GLshort alpha)
glColor4sv()
GLAPI void GLAPIENTRY glColor4sv (const GLshort * v)
glColor4ub()
GLAPI void GLAPIENTRY glColor4ub (GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha)
glColor4ubv()
GLAPI void GLAPIENTRY glColor4ubv (const GLubyte * v)
glColor4ui()
GLAPI void GLAPIENTRY glColor4ui (GLuint red, GLuint green, GLuint blue, GLuint alpha)
glColor4uiv()
GLAPI void GLAPIENTRY glColor4uiv (const GLuint * v)
glColor4us()
GLAPI void GLAPIENTRY glColor4us (GLushort red, GLushort green, GLushort blue, GLushort alpha)
glColor4usv()
GLAPI void GLAPIENTRY glColor4usv (const GLushort * v)
glColorMask()
GLAPI void GLAPIENTRY glColorMask (GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha)
glColorMaterial()
GLAPI void GLAPIENTRY glColorMaterial (GLenum face, GLenum mode)
glColorPointer()
GLAPI void GLAPIENTRY glColorPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
glColorSubTable()
GLAPI void GLAPIENTRY glColorSubTable (GLenum target, GLsizei start, GLsizei count, GLenum format, GLenum type, const GLvoid * data)
glColorTable()
GLAPI void GLAPIENTRY glColorTable (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid * table)
glColorTableParameterfv()
GLAPI void GLAPIENTRY glColorTableParameterfv (GLenum target, GLenum pname, const GLfloat * params)
glColorTableParameteriv()
GLAPI void GLAPIENTRY glColorTableParameteriv (GLenum target, GLenum pname, const GLint * params)
glCompressedTexImage1D()
GLAPI void GLAPIENTRY glCompressedTexImage1D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLint border, GLsizei imageSize, const GLvoid * data)
glCompressedTexImage2D()
GLAPI void GLAPIENTRY glCompressedTexImage2D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const GLvoid * data)
glCompressedTexImage3D()
GLAPI void GLAPIENTRY glCompressedTexImage3D (GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLsizei imageSize, const GLvoid * data)
glCompressedTexSubImage1D()
GLAPI void GLAPIENTRY glCompressedTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLsizei imageSize, const GLvoid * data)
glCompressedTexSubImage2D()
GLAPI void GLAPIENTRY glCompressedTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const GLvoid * data)
glCompressedTexSubImage3D()
GLAPI void GLAPIENTRY glCompressedTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLsizei imageSize, const GLvoid * data)
glConvolutionFilter1D()
GLAPI void GLAPIENTRY glConvolutionFilter1D (GLenum target, GLenum internalformat, GLsizei width, GLenum format, GLenum type, const GLvoid * image)
glConvolutionFilter2D()
GLAPI void GLAPIENTRY glConvolutionFilter2D (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * image)
glConvolutionParameterf()
GLAPI void GLAPIENTRY glConvolutionParameterf (GLenum target, GLenum pname, GLfloat params)
glConvolutionParameterfv()
GLAPI void GLAPIENTRY glConvolutionParameterfv (GLenum target, GLenum pname, const GLfloat * params)
glConvolutionParameteri()
GLAPI void GLAPIENTRY glConvolutionParameteri (GLenum target, GLenum pname, GLint params)
glConvolutionParameteriv()
GLAPI void GLAPIENTRY glConvolutionParameteriv (GLenum target, GLenum pname, const GLint * params)
glCopyColorSubTable()
GLAPI void GLAPIENTRY glCopyColorSubTable (GLenum target, GLsizei start, GLint x, GLint y, GLsizei width)
glCopyColorTable()
GLAPI void GLAPIENTRY glCopyColorTable (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
glCopyConvolutionFilter1D()
GLAPI void GLAPIENTRY glCopyConvolutionFilter1D (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width)
glCopyConvolutionFilter2D()
GLAPI void GLAPIENTRY glCopyConvolutionFilter2D (GLenum target, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height)
glCopyPixels()
GLAPI void GLAPIENTRY glCopyPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum type)
glCopyTexImage1D()
GLAPI void GLAPIENTRY glCopyTexImage1D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLint border)
glCopyTexImage2D()
GLAPI void GLAPIENTRY glCopyTexImage2D (GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border)
glCopyTexSubImage1D()
GLAPI void GLAPIENTRY glCopyTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLint x, GLint y, GLsizei width)
glCopyTexSubImage2D()
GLAPI void GLAPIENTRY glCopyTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height)
glCopyTexSubImage3D()
GLAPI void GLAPIENTRY glCopyTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLint x, GLint y, GLsizei width, GLsizei height)
glCullFace()
GLAPI void GLAPIENTRY glCullFace (GLenum mode)
glDeleteLists()
GLAPI void GLAPIENTRY glDeleteLists (GLuint list, GLsizei range)
glDeleteTextures()
GLAPI void GLAPIENTRY glDeleteTextures (GLsizei n, const GLuint * textures)
glDepthFunc()
GLAPI void GLAPIENTRY glDepthFunc (GLenum func)
glDepthMask()
GLAPI void GLAPIENTRY glDepthMask (GLboolean flag)
glDepthRange()
GLAPI void GLAPIENTRY glDepthRange (GLclampd near_val, GLclampd far_val)
glDisable()
GLAPI void GLAPIENTRY glDisable (GLenum cap)
Referenced by Display().
glDisableClientState()
GLAPI void GLAPIENTRY glDisableClientState (GLenum cap)
glDrawArrays()
GLAPI void GLAPIENTRY glDrawArrays (GLenum mode, GLint first, GLsizei count)
glDrawBuffer()
GLAPI void GLAPIENTRY glDrawBuffer (GLenum mode)
glDrawElements()
GLAPI void GLAPIENTRY glDrawElements (GLenum mode, GLsizei count, GLenum type, const GLvoid * indices)
glDrawPixels()
GLAPI void GLAPIENTRY glDrawPixels (GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
glDrawRangeElements()
GLAPI void GLAPIENTRY glDrawRangeElements (GLenum mode, GLuint start, GLuint end, GLsizei count, GLenum type, const GLvoid * indices)
glEdgeFlag()
GLAPI void GLAPIENTRY glEdgeFlag (GLboolean flag)
glEdgeFlagPointer()
GLAPI void GLAPIENTRY glEdgeFlagPointer (GLsizei stride, const GLvoid * ptr)
glEdgeFlagv()
GLAPI void GLAPIENTRY glEdgeFlagv (const GLboolean * flag)
glEnable()
GLAPI void GLAPIENTRY glEnable (GLenum cap)
Referenced by DisplayWrathWorld::CreateTextures(), DisplayShaysWorld::CreateTextures(), and Display().
glEnableClientState()
GLAPI void GLAPIENTRY glEnableClientState (GLenum cap)
glEnd()
GLAPI void GLAPIENTRY glEnd (void)
Referenced by TexturedPolygons::CreateAngledPolygon(), TexturedPolygons::CreateDisplayList(), TexturedPolygons::CreateXtoYWindowList(), TexturedPolygons::CreateYtoZWindowList(), CameraMap::DisplayMap(), DisplayShaysWorld::DrawAboveWindowBlock(), DisplayShaysWorld::DrawAngledRoofBeam(), DisplayShaysWorld::DrawAngledRoofBeam2(), DisplayShaysWorld::DrawBookSteps(), DisplayShaysWorld::DrawBookStepsTwo(), DisplayShaysWorld::DrawChancPosts(), DisplayShaysWorld::DrawCylinders(), DisplayShaysWorld::DrawExtras(), DisplayShaysWorld::DrawLibraryPosts(), DisplayShaysWorld::DrawLights(), DisplayShaysWorld::DrawPavement(), DisplayShaysWorld::DrawPhysSciPosts(), DisplayShaysWorld::DrawRoof(), and DisplayShaysWorld::drawStairRailing().
glEndList()
GLAPI void GLAPIENTRY glEndList (void)
Referenced by TexturedPolygons::CreateAngledPolygon(), TexturedPolygons::CreateDisplayList(), TexturedPolygons::CreateXtoYWindowList(), TexturedPolygons::CreateYtoZWindowList(), DisplayShaysWorld::DrawAboveWindowBlock(), DisplayShaysWorld::DrawAngledRoofBeam(), DisplayShaysWorld::DrawAngledRoofBeam2(), DisplayShaysWorld::DrawBookSteps(), DisplayShaysWorld::DrawBookStepsTwo(), DisplayShaysWorld::DrawChancPosts(), DisplayShaysWorld::DrawCylinders(), DisplayShaysWorld::DrawExtras(), DisplayShaysWorld::DrawLibraryPosts(), DisplayShaysWorld::DrawLights(), DisplayShaysWorld::DrawPavement(), DisplayShaysWorld::DrawPhysSciPosts(), DisplayShaysWorld::DrawRoof(), and DisplayShaysWorld::drawStairRailing().
glEvalCoord1d()
GLAPI void GLAPIENTRY glEvalCoord1d (GLdouble u)
glEvalCoord1dv()
GLAPI void GLAPIENTRY glEvalCoord1dv (const GLdouble * u)
glEvalCoord1f()
GLAPI void GLAPIENTRY glEvalCoord1f (GLfloat u)
glEvalCoord1fv()
GLAPI void GLAPIENTRY glEvalCoord1fv (const GLfloat * u)
glEvalCoord2d()
GLAPI void GLAPIENTRY glEvalCoord2d (GLdouble u, GLdouble v)
glEvalCoord2dv()
GLAPI void GLAPIENTRY glEvalCoord2dv (const GLdouble * u)
glEvalCoord2f()
GLAPI void GLAPIENTRY glEvalCoord2f (GLfloat u, GLfloat v)
glEvalCoord2fv()
GLAPI void GLAPIENTRY glEvalCoord2fv (const GLfloat * u)
glEvalMesh1()
GLAPI void GLAPIENTRY glEvalMesh1 (GLenum mode, GLint i1, GLint i2)
glEvalMesh2()
GLAPI void GLAPIENTRY glEvalMesh2 (GLenum mode, GLint i1, GLint i2, GLint j1, GLint j2)
glEvalPoint1()
GLAPI void GLAPIENTRY glEvalPoint1 (GLint i)
glEvalPoint2()
GLAPI void GLAPIENTRY glEvalPoint2 (GLint i, GLint j)
glFeedbackBuffer()
GLAPI void GLAPIENTRY glFeedbackBuffer (GLsizei size, GLenum type, GLfloat * buffer)
glFinish()
GLAPI void GLAPIENTRY glFinish (void)
glFlush()
GLAPI void GLAPIENTRY glFlush (void)
Referenced by Display().
glFogf()
GLAPI void GLAPIENTRY glFogf (GLenum pname, GLfloat param)
glFogfv()
GLAPI void GLAPIENTRY glFogfv (GLenum pname, const GLfloat * params)
glFogi()
GLAPI void GLAPIENTRY glFogi (GLenum pname, GLint param)
glFogiv()
GLAPI void GLAPIENTRY glFogiv (GLenum pname, const GLint * params)
glFrontFace()
GLAPI void GLAPIENTRY glFrontFace (GLenum mode)
glFrustum()
GLAPI void GLAPIENTRY glFrustum (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val)
glGenLists()
GLAPI GLuint GLAPIENTRY glGenLists (GLsizei range)
glGenTextures()
GLAPI void GLAPIENTRY glGenTextures (GLsizei n, GLuint * textures)
Referenced by TexturedPolygons::SetTextureCount().
glGetBooleanv()
GLAPI void GLAPIENTRY glGetBooleanv (GLenum pname, GLboolean * params)
glGetClipPlane()
GLAPI void GLAPIENTRY glGetClipPlane (GLenum plane, GLdouble * equation)
glGetColorTable()
GLAPI void GLAPIENTRY glGetColorTable (GLenum target, GLenum format, GLenum type, GLvoid * table)
glGetColorTableParameterfv()
GLAPI void GLAPIENTRY glGetColorTableParameterfv (GLenum target, GLenum pname, GLfloat * params)
glGetColorTableParameteriv()
GLAPI void GLAPIENTRY glGetColorTableParameteriv (GLenum target, GLenum pname, GLint * params)
glGetCompressedTexImage()
GLAPI void GLAPIENTRY glGetCompressedTexImage (GLenum target, GLint lod, GLvoid * img)
glGetConvolutionFilter()
GLAPI void GLAPIENTRY glGetConvolutionFilter (GLenum target, GLenum format, GLenum type, GLvoid * image)
glGetConvolutionParameterfv()
GLAPI void GLAPIENTRY glGetConvolutionParameterfv (GLenum target, GLenum pname, GLfloat * params)
glGetConvolutionParameteriv()
GLAPI void GLAPIENTRY glGetConvolutionParameteriv (GLenum target, GLenum pname, GLint * params)
glGetDoublev()
GLAPI void GLAPIENTRY glGetDoublev (GLenum pname, GLdouble * params)
glGetError()
GLAPI GLenum GLAPIENTRY glGetError (void)
glGetFloatv()
GLAPI void GLAPIENTRY glGetFloatv (GLenum pname, GLfloat * params)
glGetHistogram()
GLAPI void GLAPIENTRY glGetHistogram (GLenum target, GLboolean reset, GLenum format, GLenum type, GLvoid * values)
glGetHistogramParameterfv()
GLAPI void GLAPIENTRY glGetHistogramParameterfv (GLenum target, GLenum pname, GLfloat * params)
glGetHistogramParameteriv()
GLAPI void GLAPIENTRY glGetHistogramParameteriv (GLenum target, GLenum pname, GLint * params)
glGetIntegerv()
GLAPI void GLAPIENTRY glGetIntegerv (GLenum pname, GLint * params)
glGetLightfv()
GLAPI void GLAPIENTRY glGetLightfv (GLenum light, GLenum pname, GLfloat * params)
glGetLightiv()
GLAPI void GLAPIENTRY glGetLightiv (GLenum light, GLenum pname, GLint * params)
glGetMapdv()
GLAPI void GLAPIENTRY glGetMapdv (GLenum target, GLenum query, GLdouble * v)
glGetMapfv()
GLAPI void GLAPIENTRY glGetMapfv (GLenum target, GLenum query, GLfloat * v)
glGetMapiv()
GLAPI void GLAPIENTRY glGetMapiv (GLenum target, GLenum query, GLint * v)
glGetMaterialfv()
GLAPI void GLAPIENTRY glGetMaterialfv (GLenum face, GLenum pname, GLfloat * params)
glGetMaterialiv()
GLAPI void GLAPIENTRY glGetMaterialiv (GLenum face, GLenum pname, GLint * params)
glGetMinmax()
GLAPI void GLAPIENTRY glGetMinmax (GLenum target, GLboolean reset, GLenum format, GLenum types, GLvoid * values)
glGetMinmaxParameterfv()
GLAPI void GLAPIENTRY glGetMinmaxParameterfv (GLenum target, GLenum pname, GLfloat * params)
glGetMinmaxParameteriv()
GLAPI void GLAPIENTRY glGetMinmaxParameteriv (GLenum target, GLenum pname, GLint * params)
glGetPixelMapfv()
GLAPI void GLAPIENTRY glGetPixelMapfv (GLenum map, GLfloat * values)
glGetPixelMapuiv()
GLAPI void GLAPIENTRY glGetPixelMapuiv (GLenum map, GLuint * values)
glGetPixelMapusv()
GLAPI void GLAPIENTRY glGetPixelMapusv (GLenum map, GLushort * values)
glGetPointerv()
GLAPI void GLAPIENTRY glGetPointerv (GLenum pname, GLvoid ** params)
glGetPolygonStipple()
GLAPI void GLAPIENTRY glGetPolygonStipple (GLubyte * mask)
glGetSeparableFilter()
GLAPI void GLAPIENTRY glGetSeparableFilter (GLenum target, GLenum format, GLenum type, GLvoid * row, GLvoid * column, GLvoid * span)
glGetString()
const GLAPI GLubyte* GLAPIENTRY glGetString (GLenum name)
glGetTexEnvfv()
GLAPI void GLAPIENTRY glGetTexEnvfv (GLenum target, GLenum pname, GLfloat * params)
glGetTexEnviv()
GLAPI void GLAPIENTRY glGetTexEnviv (GLenum target, GLenum pname, GLint * params)
glGetTexGendv()
GLAPI void GLAPIENTRY glGetTexGendv (GLenum coord, GLenum pname, GLdouble * params)
glGetTexGenfv()
GLAPI void GLAPIENTRY glGetTexGenfv (GLenum coord, GLenum pname, GLfloat * params)
glGetTexGeniv()
GLAPI void GLAPIENTRY glGetTexGeniv (GLenum coord, GLenum pname, GLint * params)
glGetTexImage()
GLAPI void GLAPIENTRY glGetTexImage (GLenum target, GLint level, GLenum format, GLenum type, GLvoid * pixels)
glGetTexLevelParameterfv()
GLAPI void GLAPIENTRY glGetTexLevelParameterfv (GLenum target, GLint level, GLenum pname, GLfloat * params)
glGetTexLevelParameteriv()
GLAPI void GLAPIENTRY glGetTexLevelParameteriv (GLenum target, GLint level, GLenum pname, GLint * params)
glGetTexParameterfv()
GLAPI void GLAPIENTRY glGetTexParameterfv (GLenum target, GLenum pname, GLfloat * params)
glGetTexParameteriv()
GLAPI void GLAPIENTRY glGetTexParameteriv (GLenum target, GLenum pname, GLint * params)
glHint()
GLAPI void GLAPIENTRY glHint (GLenum target, GLenum mode)
Referenced by DisplayWrathWorld::CreateTextures(), and DisplayShaysWorld::CreateTextures().
glHistogram()
GLAPI void GLAPIENTRY glHistogram (GLenum target, GLsizei width, GLenum internalformat, GLboolean sink)
glIndexd()
GLAPI void GLAPIENTRY glIndexd (GLdouble c)
glIndexdv()
GLAPI void GLAPIENTRY glIndexdv (const GLdouble * c)
glIndexf()
GLAPI void GLAPIENTRY glIndexf (GLfloat c)
glIndexfv()
GLAPI void GLAPIENTRY glIndexfv (const GLfloat * c)
glIndexi()
GLAPI void GLAPIENTRY glIndexi (GLint c)
glIndexiv()
GLAPI void GLAPIENTRY glIndexiv (const GLint * c)
glIndexMask()
GLAPI void GLAPIENTRY glIndexMask (GLuint mask)
glIndexPointer()
GLAPI void GLAPIENTRY glIndexPointer (GLenum type, GLsizei stride, const GLvoid * ptr)
glIndexs()
GLAPI void GLAPIENTRY glIndexs (GLshort c)
glIndexsv()
GLAPI void GLAPIENTRY glIndexsv (const GLshort * c)
glIndexub()
GLAPI void GLAPIENTRY glIndexub (GLubyte c)
glIndexubv()
GLAPI void GLAPIENTRY glIndexubv (const GLubyte * c)
glInitNames()
GLAPI void GLAPIENTRY glInitNames (void)
glInterleavedArrays()
GLAPI void GLAPIENTRY glInterleavedArrays (GLenum format, GLsizei stride, const GLvoid * pointer)
glIsEnabled()
GLAPI GLboolean GLAPIENTRY glIsEnabled (GLenum cap)
glIsList()
GLAPI GLboolean GLAPIENTRY glIsList (GLuint list)
glIsTexture()
GLAPI GLboolean GLAPIENTRY glIsTexture (GLuint texture)
glLightf()
GLAPI void GLAPIENTRY glLightf (GLenum light, GLenum pname, GLfloat param)
glLightfv()
GLAPI void GLAPIENTRY glLightfv (GLenum light, GLenum pname, const GLfloat * params)
glLighti()
GLAPI void GLAPIENTRY glLighti (GLenum light, GLenum pname, GLint param)
glLightiv()
GLAPI void GLAPIENTRY glLightiv (GLenum light, GLenum pname, const GLint * params)
glLightModelf()
GLAPI void GLAPIENTRY glLightModelf (GLenum pname, GLfloat param)
glLightModelfv()
GLAPI void GLAPIENTRY glLightModelfv (GLenum pname, const GLfloat * params)
glLightModeli()
GLAPI void GLAPIENTRY glLightModeli (GLenum pname, GLint param)
glLightModeliv()
GLAPI void GLAPIENTRY glLightModeliv (GLenum pname, const GLint * params)
glLineStipple()
GLAPI void GLAPIENTRY glLineStipple (GLint factor, GLushort pattern)
glLineWidth()
GLAPI void GLAPIENTRY glLineWidth (GLfloat width)
glListBase()
GLAPI void GLAPIENTRY glListBase (GLuint base)
glLoadIdentity()
GLAPI void GLAPIENTRY glLoadIdentity (void)
Referenced by Camera::callGLLookAt(), CameraMap::DisplayMap(), CameraMap::DisplayNoExit(), CameraMap::DisplayWelcomeScreen(), and reshape().
glLoadMatrixd()
GLAPI void GLAPIENTRY glLoadMatrixd (const GLdouble * m)
glLoadMatrixf()
GLAPI void GLAPIENTRY glLoadMatrixf (const GLfloat * m)
glLoadName()
GLAPI void GLAPIENTRY glLoadName (GLuint name)
glLoadTransposeMatrixd()
GLAPI void GLAPIENTRY glLoadTransposeMatrixd (const GLdouble m[16])
glLoadTransposeMatrixf()
GLAPI void GLAPIENTRY glLoadTransposeMatrixf (const GLfloat m[16])
glLogicOp()
GLAPI void GLAPIENTRY glLogicOp (GLenum opcode)
glMap1d()
GLAPI void GLAPIENTRY glMap1d (GLenum target, GLdouble u1, GLdouble u2, GLint stride, GLint order, const GLdouble * points)
glMap1f()
GLAPI void GLAPIENTRY glMap1f (GLenum target, GLfloat u1, GLfloat u2, GLint stride, GLint order, const GLfloat * points)
glMap2d()
GLAPI void GLAPIENTRY glMap2d (GLenum target, GLdouble u1, GLdouble u2, GLint ustride, GLint uorder, GLdouble v1, GLdouble v2, GLint vstride, GLint vorder, const GLdouble * points)
glMap2f()
GLAPI void GLAPIENTRY glMap2f (GLenum target, GLfloat u1, GLfloat u2, GLint ustride, GLint uorder, GLfloat v1, GLfloat v2, GLint vstride, GLint vorder, const GLfloat * points)
glMapGrid1d()
GLAPI void GLAPIENTRY glMapGrid1d (GLint un, GLdouble u1, GLdouble u2)
glMapGrid1f()
GLAPI void GLAPIENTRY glMapGrid1f (GLint un, GLfloat u1, GLfloat u2)
glMapGrid2d()
GLAPI void GLAPIENTRY glMapGrid2d (GLint un, GLdouble u1, GLdouble u2, GLint vn, GLdouble v1, GLdouble v2)
glMapGrid2f()
GLAPI void GLAPIENTRY glMapGrid2f (GLint un, GLfloat u1, GLfloat u2, GLint vn, GLfloat v1, GLfloat v2)
glMaterialf()
GLAPI void GLAPIENTRY glMaterialf (GLenum face, GLenum pname, GLfloat param)
glMaterialfv()
GLAPI void GLAPIENTRY glMaterialfv (GLenum face, GLenum pname, const GLfloat * params)
glMateriali()
GLAPI void GLAPIENTRY glMateriali (GLenum face, GLenum pname, GLint param)
glMaterialiv()
GLAPI void GLAPIENTRY glMaterialiv (GLenum face, GLenum pname, const GLint * params)
glMatrixMode()
GLAPI void GLAPIENTRY glMatrixMode (GLenum mode)
Referenced by CameraMap::DisplayMap(), CameraMap::DisplayNoExit(), CameraMap::DisplayWelcomeScreen(), and reshape().
glMinmax()
GLAPI void GLAPIENTRY glMinmax (GLenum target, GLenum internalformat, GLboolean sink)
glMultiTexCoord1d()
GLAPI void GLAPIENTRY glMultiTexCoord1d (GLenum target, GLdouble s)
glMultiTexCoord1dARB()
GLAPI void GLAPIENTRY glMultiTexCoord1dARB (GLenum target, GLdouble s)
glMultiTexCoord1dv()
GLAPI void GLAPIENTRY glMultiTexCoord1dv (GLenum target, const GLdouble * v)
glMultiTexCoord1dvARB()
GLAPI void GLAPIENTRY glMultiTexCoord1dvARB (GLenum target, const GLdouble * v)
glMultiTexCoord1f()
GLAPI void GLAPIENTRY glMultiTexCoord1f (GLenum target, GLfloat s)
glMultiTexCoord1fARB()
GLAPI void GLAPIENTRY glMultiTexCoord1fARB (GLenum target, GLfloat s)
glMultiTexCoord1fv()
GLAPI void GLAPIENTRY glMultiTexCoord1fv (GLenum target, const GLfloat * v)
glMultiTexCoord1fvARB()
GLAPI void GLAPIENTRY glMultiTexCoord1fvARB (GLenum target, const GLfloat * v)
glMultiTexCoord1i()
GLAPI void GLAPIENTRY glMultiTexCoord1i (GLenum target, GLint s)
glMultiTexCoord1iARB()
GLAPI void GLAPIENTRY glMultiTexCoord1iARB (GLenum target, GLint s)
glMultiTexCoord1iv()
GLAPI void GLAPIENTRY glMultiTexCoord1iv (GLenum target, const GLint * v)
glMultiTexCoord1ivARB()
GLAPI void GLAPIENTRY glMultiTexCoord1ivARB (GLenum target, const GLint * v)
glMultiTexCoord1s()
GLAPI void GLAPIENTRY glMultiTexCoord1s (GLenum target, GLshort s)
glMultiTexCoord1sARB()
GLAPI void GLAPIENTRY glMultiTexCoord1sARB (GLenum target, GLshort s)
glMultiTexCoord1sv()
GLAPI void GLAPIENTRY glMultiTexCoord1sv (GLenum target, const GLshort * v)
glMultiTexCoord1svARB()
GLAPI void GLAPIENTRY glMultiTexCoord1svARB (GLenum target, const GLshort * v)
glMultiTexCoord2d()
GLAPI void GLAPIENTRY glMultiTexCoord2d (GLenum target, GLdouble s, GLdouble t)
glMultiTexCoord2dARB()
GLAPI void GLAPIENTRY glMultiTexCoord2dARB (GLenum target, GLdouble s, GLdouble t)
glMultiTexCoord2dv()
GLAPI void GLAPIENTRY glMultiTexCoord2dv (GLenum target, const GLdouble * v)
glMultiTexCoord2dvARB()
GLAPI void GLAPIENTRY glMultiTexCoord2dvARB (GLenum target, const GLdouble * v)
glMultiTexCoord2f()
GLAPI void GLAPIENTRY glMultiTexCoord2f (GLenum target, GLfloat s, GLfloat t)
glMultiTexCoord2fARB()
GLAPI void GLAPIENTRY glMultiTexCoord2fARB (GLenum target, GLfloat s, GLfloat t)
glMultiTexCoord2fv()
GLAPI void GLAPIENTRY glMultiTexCoord2fv (GLenum target, const GLfloat * v)
glMultiTexCoord2fvARB()
GLAPI void GLAPIENTRY glMultiTexCoord2fvARB (GLenum target, const GLfloat * v)
glMultiTexCoord2i()
GLAPI void GLAPIENTRY glMultiTexCoord2i (GLenum target, GLint s, GLint t)
glMultiTexCoord2iARB()
GLAPI void GLAPIENTRY glMultiTexCoord2iARB (GLenum target, GLint s, GLint t)
glMultiTexCoord2iv()
GLAPI void GLAPIENTRY glMultiTexCoord2iv (GLenum target, const GLint * v)
glMultiTexCoord2ivARB()
GLAPI void GLAPIENTRY glMultiTexCoord2ivARB (GLenum target, const GLint * v)
glMultiTexCoord2s()
GLAPI void GLAPIENTRY glMultiTexCoord2s (GLenum target, GLshort s, GLshort t)
glMultiTexCoord2sARB()
GLAPI void GLAPIENTRY glMultiTexCoord2sARB (GLenum target, GLshort s, GLshort t)
glMultiTexCoord2sv()
GLAPI void GLAPIENTRY glMultiTexCoord2sv (GLenum target, const GLshort * v)
glMultiTexCoord2svARB()
GLAPI void GLAPIENTRY glMultiTexCoord2svARB (GLenum target, const GLshort * v)
glMultiTexCoord3d()
GLAPI void GLAPIENTRY glMultiTexCoord3d (GLenum target, GLdouble s, GLdouble t, GLdouble r)
glMultiTexCoord3dARB()
GLAPI void GLAPIENTRY glMultiTexCoord3dARB (GLenum target, GLdouble s, GLdouble t, GLdouble r)
glMultiTexCoord3dv()
GLAPI void GLAPIENTRY glMultiTexCoord3dv (GLenum target, const GLdouble * v)
glMultiTexCoord3dvARB()
GLAPI void GLAPIENTRY glMultiTexCoord3dvARB (GLenum target, const GLdouble * v)
glMultiTexCoord3f()
GLAPI void GLAPIENTRY glMultiTexCoord3f (GLenum target, GLfloat s, GLfloat t, GLfloat r)
glMultiTexCoord3fARB()
GLAPI void GLAPIENTRY glMultiTexCoord3fARB (GLenum target, GLfloat s, GLfloat t, GLfloat r)
glMultiTexCoord3fv()
GLAPI void GLAPIENTRY glMultiTexCoord3fv (GLenum target, const GLfloat * v)
glMultiTexCoord3fvARB()
GLAPI void GLAPIENTRY glMultiTexCoord3fvARB (GLenum target, const GLfloat * v)
glMultiTexCoord3i()
GLAPI void GLAPIENTRY glMultiTexCoord3i (GLenum target, GLint s, GLint t, GLint r)
glMultiTexCoord3iARB()
GLAPI void GLAPIENTRY glMultiTexCoord3iARB (GLenum target, GLint s, GLint t, GLint r)
glMultiTexCoord3iv()
GLAPI void GLAPIENTRY glMultiTexCoord3iv (GLenum target, const GLint * v)
glMultiTexCoord3ivARB()
GLAPI void GLAPIENTRY glMultiTexCoord3ivARB (GLenum target, const GLint * v)
glMultiTexCoord3s()
GLAPI void GLAPIENTRY glMultiTexCoord3s (GLenum target, GLshort s, GLshort t, GLshort r)
glMultiTexCoord3sARB()
GLAPI void GLAPIENTRY glMultiTexCoord3sARB (GLenum target, GLshort s, GLshort t, GLshort r)
glMultiTexCoord3sv()
GLAPI void GLAPIENTRY glMultiTexCoord3sv (GLenum target, const GLshort * v)
glMultiTexCoord3svARB()
GLAPI void GLAPIENTRY glMultiTexCoord3svARB (GLenum target, const GLshort * v)
glMultiTexCoord4d()
GLAPI void GLAPIENTRY glMultiTexCoord4d (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
glMultiTexCoord4dARB()
GLAPI void GLAPIENTRY glMultiTexCoord4dARB (GLenum target, GLdouble s, GLdouble t, GLdouble r, GLdouble q)
glMultiTexCoord4dv()
GLAPI void GLAPIENTRY glMultiTexCoord4dv (GLenum target, const GLdouble * v)
glMultiTexCoord4dvARB()
GLAPI void GLAPIENTRY glMultiTexCoord4dvARB (GLenum target, const GLdouble * v)
glMultiTexCoord4f()
GLAPI void GLAPIENTRY glMultiTexCoord4f (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
glMultiTexCoord4fARB()
GLAPI void GLAPIENTRY glMultiTexCoord4fARB (GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q)
glMultiTexCoord4fv()
GLAPI void GLAPIENTRY glMultiTexCoord4fv (GLenum target, const GLfloat * v)
glMultiTexCoord4fvARB()
GLAPI void GLAPIENTRY glMultiTexCoord4fvARB (GLenum target, const GLfloat * v)
glMultiTexCoord4i()
GLAPI void GLAPIENTRY glMultiTexCoord4i (GLenum target, GLint s, GLint t, GLint r, GLint q)
glMultiTexCoord4iARB()
GLAPI void GLAPIENTRY glMultiTexCoord4iARB (GLenum target, GLint s, GLint t, GLint r, GLint q)
glMultiTexCoord4iv()
GLAPI void GLAPIENTRY glMultiTexCoord4iv (GLenum target, const GLint * v)
glMultiTexCoord4ivARB()
GLAPI void GLAPIENTRY glMultiTexCoord4ivARB (GLenum target, const GLint * v)
glMultiTexCoord4s()
GLAPI void GLAPIENTRY glMultiTexCoord4s (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
glMultiTexCoord4sARB()
GLAPI void GLAPIENTRY glMultiTexCoord4sARB (GLenum target, GLshort s, GLshort t, GLshort r, GLshort q)
glMultiTexCoord4sv()
GLAPI void GLAPIENTRY glMultiTexCoord4sv (GLenum target, const GLshort * v)
glMultiTexCoord4svARB()
GLAPI void GLAPIENTRY glMultiTexCoord4svARB (GLenum target, const GLshort * v)
glMultMatrixd()
GLAPI void GLAPIENTRY glMultMatrixd (const GLdouble * m)
glMultMatrixf()
GLAPI void GLAPIENTRY glMultMatrixf (const GLfloat * m)
glMultTransposeMatrixd()
GLAPI void GLAPIENTRY glMultTransposeMatrixd (const GLdouble m[16])
glMultTransposeMatrixf()
GLAPI void GLAPIENTRY glMultTransposeMatrixf (const GLfloat m[16])
glNewList()
GLAPI void GLAPIENTRY glNewList (GLuint list, GLenum mode)
Referenced by TexturedPolygons::CreateAngledPolygon(), TexturedPolygons::CreateDisplayList(), TexturedPolygons::CreateXtoYWindowList(), TexturedPolygons::CreateYtoZWindowList(), DisplayShaysWorld::DrawAboveWindowBlock(), DisplayShaysWorld::DrawAngledRoofBeam(), DisplayShaysWorld::DrawAngledRoofBeam2(), DisplayShaysWorld::DrawBookSteps(), DisplayShaysWorld::DrawBookStepsTwo(), DisplayShaysWorld::DrawChancPosts(), DisplayShaysWorld::DrawCylinders(), DisplayShaysWorld::DrawExtras(), DisplayShaysWorld::DrawLibraryPosts(), DisplayShaysWorld::DrawLights(), DisplayShaysWorld::DrawPavement(), DisplayShaysWorld::DrawPhysSciPosts(), DisplayShaysWorld::DrawRoof(), and DisplayShaysWorld::drawStairRailing().
glNormal3b()
GLAPI void GLAPIENTRY glNormal3b (GLbyte nx, GLbyte ny, GLbyte nz)
glNormal3bv()
GLAPI void GLAPIENTRY glNormal3bv (const GLbyte * v)
glNormal3d()
GLAPI void GLAPIENTRY glNormal3d (GLdouble nx, GLdouble ny, GLdouble nz)
glNormal3dv()
GLAPI void GLAPIENTRY glNormal3dv (const GLdouble * v)
glNormal3f()
GLAPI void GLAPIENTRY glNormal3f (GLfloat nx, GLfloat ny, GLfloat nz)
glNormal3fv()
GLAPI void GLAPIENTRY glNormal3fv (const GLfloat * v)
glNormal3i()
GLAPI void GLAPIENTRY glNormal3i (GLint nx, GLint ny, GLint nz)
glNormal3iv()
GLAPI void GLAPIENTRY glNormal3iv (const GLint * v)
glNormal3s()
GLAPI void GLAPIENTRY glNormal3s (GLshort nx, GLshort ny, GLshort nz)
glNormal3sv()
GLAPI void GLAPIENTRY glNormal3sv (const GLshort * v)
glNormalPointer()
GLAPI void GLAPIENTRY glNormalPointer (GLenum type, GLsizei stride, const GLvoid * ptr)
glOrtho()
GLAPI void GLAPIENTRY glOrtho (GLdouble left, GLdouble right, GLdouble bottom, GLdouble top, GLdouble near_val, GLdouble far_val)
glPassThrough()
GLAPI void GLAPIENTRY glPassThrough (GLfloat token)
glPixelMapfv()
GLAPI void GLAPIENTRY glPixelMapfv (GLenum map, GLsizei mapsize, const GLfloat * values)
glPixelMapuiv()
GLAPI void GLAPIENTRY glPixelMapuiv (GLenum map, GLsizei mapsize, const GLuint * values)
glPixelMapusv()
GLAPI void GLAPIENTRY glPixelMapusv (GLenum map, GLsizei mapsize, const GLushort * values)
glPixelStoref()
GLAPI void GLAPIENTRY glPixelStoref (GLenum pname, GLfloat param)
glPixelStorei()
GLAPI void GLAPIENTRY glPixelStorei (GLenum pname, GLint param)
Referenced by DisplayWrathWorld::CreateTextures(), and DisplayShaysWorld::CreateTextures().
glPixelTransferf()
GLAPI void GLAPIENTRY glPixelTransferf (GLenum pname, GLfloat param)
glPixelTransferi()
GLAPI void GLAPIENTRY glPixelTransferi (GLenum pname, GLint param)
glPixelZoom()
GLAPI void GLAPIENTRY glPixelZoom (GLfloat xfactor, GLfloat yfactor)
glPointSize()
GLAPI void GLAPIENTRY glPointSize (GLfloat size)
glPolygonMode()
GLAPI void GLAPIENTRY glPolygonMode (GLenum face, GLenum mode)
glPolygonOffset()
GLAPI void GLAPIENTRY glPolygonOffset (GLfloat factor, GLfloat units)
glPolygonStipple()
GLAPI void GLAPIENTRY glPolygonStipple (const GLubyte * mask)
glPopAttrib()
GLAPI void GLAPIENTRY glPopAttrib (void)
glPopClientAttrib()
GLAPI void GLAPIENTRY glPopClientAttrib (void)
glPopMatrix()
GLAPI void GLAPIENTRY glPopMatrix (void)
Referenced by Display(), DisplayShaysWorld::DisplayAboveWindowBlock(), DisplayShaysWorld::DisplayBench(), DisplayShaysWorld::DisplayBricks(), DisplayShaysWorld::DisplayChancPosts(), DisplayShaysWorld::DisplayCylinders(), DisplayShaysWorld::DisplayDoorPosts(), DisplayShaysWorld::DisplayEntranceSteps(), DisplayShaysWorld::DisplayExtras(), DisplayShaysWorld::DisplayLargerTextures(), DisplayShaysWorld::DisplayLibraryPosts(), DisplayShaysWorld::DisplayLights(), DisplayShaysWorld::DisplayMainPosts(), CameraMap::DisplayMap(), CameraMap::DisplayNoExit(), DisplayShaysWorld::DisplayPavement(), DisplayShaysWorld::DisplayPhysSciPosts(), DisplayShaysWorld::DisplayPurplePosts(), DisplayShaysWorld::DisplayRedPosts(), DisplayShaysWorld::DisplayRoof(), DisplayShaysWorld::DisplayStepBricks(), and CameraMap::DisplayWelcomeScreen().
glPopName()
GLAPI void GLAPIENTRY glPopName (void)
glPrioritizeTextures()
GLAPI void GLAPIENTRY glPrioritizeTextures (GLsizei n, const GLuint * textures, const GLclampf * priorities)
glPushAttrib()
GLAPI void GLAPIENTRY glPushAttrib (GLbitfield mask)
glPushClientAttrib()
GLAPI void GLAPIENTRY glPushClientAttrib (GLbitfield mask)
glPushMatrix()
GLAPI void GLAPIENTRY glPushMatrix (void)
Referenced by Display(), DisplayShaysWorld::DisplayAboveWindowBlock(), DisplayShaysWorld::DisplayBench(), DisplayShaysWorld::DisplayBricks(), DisplayShaysWorld::DisplayChancPosts(), DisplayShaysWorld::DisplayCylinders(), DisplayShaysWorld::DisplayDoorPosts(), DisplayShaysWorld::DisplayEntranceSteps(), DisplayShaysWorld::DisplayExtras(), DisplayShaysWorld::DisplayLargerTextures(), DisplayShaysWorld::DisplayLibraryPosts(), DisplayShaysWorld::DisplayLights(), DisplayShaysWorld::DisplayMainPosts(), CameraMap::DisplayMap(), CameraMap::DisplayNoExit(), DisplayShaysWorld::DisplayPavement(), DisplayShaysWorld::DisplayPhysSciPosts(), DisplayShaysWorld::DisplayPurplePosts(), DisplayShaysWorld::DisplayRedPosts(), DisplayShaysWorld::DisplayRoof(), DisplayShaysWorld::DisplayStepBricks(), and CameraMap::DisplayWelcomeScreen().
glPushName()
GLAPI void GLAPIENTRY glPushName (GLuint name)
glRasterPos2d()
GLAPI void GLAPIENTRY glRasterPos2d (GLdouble x, GLdouble y)
glRasterPos2dv()
GLAPI void GLAPIENTRY glRasterPos2dv (const GLdouble * v)
glRasterPos2f()
GLAPI void GLAPIENTRY glRasterPos2f (GLfloat x, GLfloat y)
glRasterPos2fv()
GLAPI void GLAPIENTRY glRasterPos2fv (const GLfloat * v)
glRasterPos2i()
GLAPI void GLAPIENTRY glRasterPos2i (GLint x, GLint y)
glRasterPos2iv()
GLAPI void GLAPIENTRY glRasterPos2iv (const GLint * v)
glRasterPos2s()
GLAPI void GLAPIENTRY glRasterPos2s (GLshort x, GLshort y)
glRasterPos2sv()
GLAPI void GLAPIENTRY glRasterPos2sv (const GLshort * v)
glRasterPos3d()
GLAPI void GLAPIENTRY glRasterPos3d (GLdouble x, GLdouble y, GLdouble z)
glRasterPos3dv()
GLAPI void GLAPIENTRY glRasterPos3dv (const GLdouble * v)
glRasterPos3f()
GLAPI void GLAPIENTRY glRasterPos3f (GLfloat x, GLfloat y, GLfloat z)
glRasterPos3fv()
GLAPI void GLAPIENTRY glRasterPos3fv (const GLfloat * v)
glRasterPos3i()
GLAPI void GLAPIENTRY glRasterPos3i (GLint x, GLint y, GLint z)
glRasterPos3iv()
GLAPI void GLAPIENTRY glRasterPos3iv (const GLint * v)
glRasterPos3s()
GLAPI void GLAPIENTRY glRasterPos3s (GLshort x, GLshort y, GLshort z)
glRasterPos3sv()
GLAPI void GLAPIENTRY glRasterPos3sv (const GLshort * v)
glRasterPos4d()
GLAPI void GLAPIENTRY glRasterPos4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
glRasterPos4dv()
GLAPI void GLAPIENTRY glRasterPos4dv (const GLdouble * v)
glRasterPos4f()
GLAPI void GLAPIENTRY glRasterPos4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
glRasterPos4fv()
GLAPI void GLAPIENTRY glRasterPos4fv (const GLfloat * v)
glRasterPos4i()
GLAPI void GLAPIENTRY glRasterPos4i (GLint x, GLint y, GLint z, GLint w)
glRasterPos4iv()
GLAPI void GLAPIENTRY glRasterPos4iv (const GLint * v)
glRasterPos4s()
GLAPI void GLAPIENTRY glRasterPos4s (GLshort x, GLshort y, GLshort z, GLshort w)
glRasterPos4sv()
GLAPI void GLAPIENTRY glRasterPos4sv (const GLshort * v)
glReadBuffer()
GLAPI void GLAPIENTRY glReadBuffer (GLenum mode)
glReadPixels()
GLAPI void GLAPIENTRY glReadPixels (GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, GLvoid * pixels)
glRectd()
GLAPI void GLAPIENTRY glRectd (GLdouble x1, GLdouble y1, GLdouble x2, GLdouble y2)
glRectdv()
GLAPI void GLAPIENTRY glRectdv (const GLdouble * v1, const GLdouble * v2)
glRectf()
GLAPI void GLAPIENTRY glRectf (GLfloat x1, GLfloat y1, GLfloat x2, GLfloat y2)
glRectfv()
GLAPI void GLAPIENTRY glRectfv (const GLfloat * v1, const GLfloat * v2)
glRecti()
GLAPI void GLAPIENTRY glRecti (GLint x1, GLint y1, GLint x2, GLint y2)
glRectiv()
GLAPI void GLAPIENTRY glRectiv (const GLint * v1, const GLint * v2)
glRects()
GLAPI void GLAPIENTRY glRects (GLshort x1, GLshort y1, GLshort x2, GLshort y2)
glRectsv()
GLAPI void GLAPIENTRY glRectsv (const GLshort * v1, const GLshort * v2)
glRenderMode()
GLAPI GLint GLAPIENTRY glRenderMode (GLenum mode)
glResetHistogram()
GLAPI void GLAPIENTRY glResetHistogram (GLenum target)
glResetMinmax()
GLAPI void GLAPIENTRY glResetMinmax (GLenum target)
glRotated()
GLAPI void GLAPIENTRY glRotated (GLdouble angle, GLdouble x, GLdouble y, GLdouble z)
glRotatef()
GLAPI void GLAPIENTRY glRotatef (GLfloat angle, GLfloat x, GLfloat y, GLfloat z)
Referenced by DisplayShaysWorld::DisplayCylinders(), DisplayShaysWorld::DisplayLights(), and DisplayShaysWorld::DisplayStepBricks().
glSampleCoverage()
GLAPI void GLAPIENTRY glSampleCoverage (GLclampf value, GLboolean invert)
glScaled()
GLAPI void GLAPIENTRY glScaled (GLdouble x, GLdouble y, GLdouble z)
glScalef()
GLAPI void GLAPIENTRY glScalef (GLfloat x, GLfloat y, GLfloat z)
Referenced by DisplayShaysWorld::DisplayCylinders(), CameraMap::DisplayMap(), CameraMap::DisplayNoExit(), and CameraMap::DisplayWelcomeScreen().
glScissor()
GLAPI void GLAPIENTRY glScissor (GLint x, GLint y, GLsizei width, GLsizei height)
glSelectBuffer()
GLAPI void GLAPIENTRY glSelectBuffer (GLsizei size, GLuint * buffer)
glSeparableFilter2D()
GLAPI void GLAPIENTRY glSeparableFilter2D (GLenum target, GLenum internalformat, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * row, const GLvoid * column)
glShadeModel()
GLAPI void GLAPIENTRY glShadeModel (GLenum mode)
glStencilFunc()
GLAPI void GLAPIENTRY glStencilFunc (GLenum func, GLint ref, GLuint mask)
glStencilMask()
GLAPI void GLAPIENTRY glStencilMask (GLuint mask)
glStencilOp()
GLAPI void GLAPIENTRY glStencilOp (GLenum fail, GLenum zfail, GLenum zpass)
glTexCoord1d()
GLAPI void GLAPIENTRY glTexCoord1d (GLdouble s)
glTexCoord1dv()
GLAPI void GLAPIENTRY glTexCoord1dv (const GLdouble * v)
glTexCoord1f()
GLAPI void GLAPIENTRY glTexCoord1f (GLfloat s)
glTexCoord1fv()
GLAPI void GLAPIENTRY glTexCoord1fv (const GLfloat * v)
glTexCoord1i()
GLAPI void GLAPIENTRY glTexCoord1i (GLint s)
glTexCoord1iv()
GLAPI void GLAPIENTRY glTexCoord1iv (const GLint * v)
glTexCoord1s()
GLAPI void GLAPIENTRY glTexCoord1s (GLshort s)
glTexCoord1sv()
GLAPI void GLAPIENTRY glTexCoord1sv (const GLshort * v)
glTexCoord2d()
GLAPI void GLAPIENTRY glTexCoord2d (GLdouble s, GLdouble t)
glTexCoord2dv()
GLAPI void GLAPIENTRY glTexCoord2dv (const GLdouble * v)
glTexCoord2f()
GLAPI void GLAPIENTRY glTexCoord2f (GLfloat s, GLfloat t)
Referenced by TexturedPolygons::CreateAngledPolygon(), TexturedPolygons::CreateXtoYTextureList(), TexturedPolygons::CreateXtoYWindowList(), TexturedPolygons::CreateXtoZTextureList(), TexturedPolygons::CreateYtoZTextureList(), TexturedPolygons::CreateYtoZWindowList(), DisplayShaysWorld::DrawAboveWindowBlock(), DisplayShaysWorld::DrawAngledRoofBeam(), DisplayShaysWorld::DrawAngledRoofBeam2(), DisplayShaysWorld::DrawBookSteps(), DisplayShaysWorld::DrawBookStepsTwo(), DisplayShaysWorld::DrawChancPosts(), DisplayShaysWorld::DrawExtras(), DisplayShaysWorld::DrawLibraryPosts(), DisplayShaysWorld::DrawPavement(), DisplayShaysWorld::DrawPhysSciPosts(), DisplayShaysWorld::DrawRoof(), and DisplayShaysWorld::drawStairRailing().
glTexCoord2fv()
GLAPI void GLAPIENTRY glTexCoord2fv (const GLfloat * v)
glTexCoord2i()
GLAPI void GLAPIENTRY glTexCoord2i (GLint s, GLint t)
glTexCoord2iv()
GLAPI void GLAPIENTRY glTexCoord2iv (const GLint * v)
glTexCoord2s()
GLAPI void GLAPIENTRY glTexCoord2s (GLshort s, GLshort t)
glTexCoord2sv()
GLAPI void GLAPIENTRY glTexCoord2sv (const GLshort * v)
glTexCoord3d()
GLAPI void GLAPIENTRY glTexCoord3d (GLdouble s, GLdouble t, GLdouble r)
glTexCoord3dv()
GLAPI void GLAPIENTRY glTexCoord3dv (const GLdouble * v)
glTexCoord3f()
GLAPI void GLAPIENTRY glTexCoord3f (GLfloat s, GLfloat t, GLfloat r)
glTexCoord3fv()
GLAPI void GLAPIENTRY glTexCoord3fv (const GLfloat * v)
glTexCoord3i()
GLAPI void GLAPIENTRY glTexCoord3i (GLint s, GLint t, GLint r)
glTexCoord3iv()
GLAPI void GLAPIENTRY glTexCoord3iv (const GLint * v)
glTexCoord3s()
GLAPI void GLAPIENTRY glTexCoord3s (GLshort s, GLshort t, GLshort r)
glTexCoord3sv()
GLAPI void GLAPIENTRY glTexCoord3sv (const GLshort * v)
glTexCoord4d()
GLAPI void GLAPIENTRY glTexCoord4d (GLdouble s, GLdouble t, GLdouble r, GLdouble q)
glTexCoord4dv()
GLAPI void GLAPIENTRY glTexCoord4dv (const GLdouble * v)
glTexCoord4f()
GLAPI void GLAPIENTRY glTexCoord4f (GLfloat s, GLfloat t, GLfloat r, GLfloat q)
glTexCoord4fv()
GLAPI void GLAPIENTRY glTexCoord4fv (const GLfloat * v)
glTexCoord4i()
GLAPI void GLAPIENTRY glTexCoord4i (GLint s, GLint t, GLint r, GLint q)
glTexCoord4iv()
GLAPI void GLAPIENTRY glTexCoord4iv (const GLint * v)
glTexCoord4s()
GLAPI void GLAPIENTRY glTexCoord4s (GLshort s, GLshort t, GLshort r, GLshort q)
glTexCoord4sv()
GLAPI void GLAPIENTRY glTexCoord4sv (const GLshort * v)
glTexCoordPointer()
GLAPI void GLAPIENTRY glTexCoordPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
glTexEnvf()
GLAPI void GLAPIENTRY glTexEnvf (GLenum target, GLenum pname, GLfloat param)
Referenced by DisplayWrathWorld::CreateTextures(), and DisplayShaysWorld::CreateTextures().
glTexEnvfv()
GLAPI void GLAPIENTRY glTexEnvfv (GLenum target, GLenum pname, const GLfloat * params)
glTexEnvi()
GLAPI void GLAPIENTRY glTexEnvi (GLenum target, GLenum pname, GLint param)
glTexEnviv()
GLAPI void GLAPIENTRY glTexEnviv (GLenum target, GLenum pname, const GLint * params)
glTexGend()
GLAPI void GLAPIENTRY glTexGend (GLenum coord, GLenum pname, GLdouble param)
glTexGendv()
GLAPI void GLAPIENTRY glTexGendv (GLenum coord, GLenum pname, const GLdouble * params)
glTexGenf()
GLAPI void GLAPIENTRY glTexGenf (GLenum coord, GLenum pname, GLfloat param)
glTexGenfv()
GLAPI void GLAPIENTRY glTexGenfv (GLenum coord, GLenum pname, const GLfloat * params)
glTexGeni()
GLAPI void GLAPIENTRY glTexGeni (GLenum coord, GLenum pname, GLint param)
glTexGeniv()
GLAPI void GLAPIENTRY glTexGeniv (GLenum coord, GLenum pname, const GLint * params)
glTexImage1D()
GLAPI void GLAPIENTRY glTexImage1D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
glTexImage2D()
GLAPI void GLAPIENTRY glTexImage2D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
glTexImage3D()
GLAPI void GLAPIENTRY glTexImage3D (GLenum target, GLint level, GLint internalFormat, GLsizei width, GLsizei height, GLsizei depth, GLint border, GLenum format, GLenum type, const GLvoid * pixels)
glTexParameterf()
GLAPI void GLAPIENTRY glTexParameterf (GLenum target, GLenum pname, GLfloat param)
Referenced by TexturedPolygons::CreatePNGTexture(), and TexturedPolygons::CreateTexture().
glTexParameterfv()
GLAPI void GLAPIENTRY glTexParameterfv (GLenum target, GLenum pname, const GLfloat * params)
glTexParameteri()
GLAPI void GLAPIENTRY glTexParameteri (GLenum target, GLenum pname, GLint param)
glTexParameteriv()
GLAPI void GLAPIENTRY glTexParameteriv (GLenum target, GLenum pname, const GLint * params)
glTexSubImage1D()
GLAPI void GLAPIENTRY glTexSubImage1D (GLenum target, GLint level, GLint xoffset, GLsizei width, GLenum format, GLenum type, const GLvoid * pixels)
glTexSubImage2D()
GLAPI void GLAPIENTRY glTexSubImage2D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const GLvoid * pixels)
glTexSubImage3D()
GLAPI void GLAPIENTRY glTexSubImage3D (GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint zoffset, GLsizei width, GLsizei height, GLsizei depth, GLenum format, GLenum type, const GLvoid * pixels)
glTranslated()
GLAPI void GLAPIENTRY glTranslated (GLdouble x, GLdouble y, GLdouble z)
glTranslatef()
GLAPI void GLAPIENTRY glTranslatef (GLfloat x, GLfloat y, GLfloat z)
Referenced by DisplayShaysWorld::DisplayAboveWindowBlock(), DisplayShaysWorld::DisplayBench(), DisplayShaysWorld::DisplayBricks(), DisplayShaysWorld::DisplayChancPosts(), DisplayShaysWorld::DisplayCylinders(), DisplayShaysWorld::DisplayDoorPosts(), DisplayShaysWorld::DisplayEntranceSteps(), DisplayShaysWorld::DisplayExtras(), DisplayShaysWorld::DisplayLargerTextures(), DisplayShaysWorld::DisplayLibraryPosts(), DisplayShaysWorld::DisplayLights(), DisplayShaysWorld::DisplayMainPosts(), CameraMap::DisplayMap(), CameraMap::DisplayNoExit(), DisplayShaysWorld::DisplayPavement(), DisplayShaysWorld::DisplayPhysSciPosts(), DisplayShaysWorld::DisplayPurplePosts(), DisplayShaysWorld::DisplayRedPosts(), DisplayShaysWorld::DisplayRoof(), DisplayShaysWorld::DisplayStepBricks(), and CameraMap::DisplayWelcomeScreen().
glVertex2d()
GLAPI void GLAPIENTRY glVertex2d (GLdouble x, GLdouble y)
glVertex2dv()
GLAPI void GLAPIENTRY glVertex2dv (const GLdouble * v)
glVertex2f()
GLAPI void GLAPIENTRY glVertex2f (GLfloat x, GLfloat y)
glVertex2fv()
GLAPI void GLAPIENTRY glVertex2fv (const GLfloat * v)
glVertex2i()
GLAPI void GLAPIENTRY glVertex2i (GLint x, GLint y)
glVertex2iv()
GLAPI void GLAPIENTRY glVertex2iv (const GLint * v)
glVertex2s()
GLAPI void GLAPIENTRY glVertex2s (GLshort x, GLshort y)
glVertex2sv()
GLAPI void GLAPIENTRY glVertex2sv (const GLshort * v)
glVertex3d()
GLAPI void GLAPIENTRY glVertex3d (GLdouble x, GLdouble y, GLdouble z)
glVertex3dv()
GLAPI void GLAPIENTRY glVertex3dv (const GLdouble * v)
glVertex3f()
GLAPI void GLAPIENTRY glVertex3f (GLfloat x, GLfloat y, GLfloat z)
Referenced by TexturedPolygons::CreateAngledPolygon(), TexturedPolygons::CreateXtoYTextureList(), TexturedPolygons::CreateXtoYWindowList(), TexturedPolygons::CreateXtoZTextureList(), TexturedPolygons::CreateYtoZTextureList(), TexturedPolygons::CreateYtoZWindowList(), CameraMap::DisplayMap(), DisplayShaysWorld::DrawAboveWindowBlock(), DisplayShaysWorld::DrawAngledRoofBeam(), DisplayShaysWorld::DrawAngledRoofBeam2(), DisplayShaysWorld::DrawBookSteps(), DisplayShaysWorld::DrawBookStepsTwo(), DisplayShaysWorld::DrawChancPosts(), DisplayShaysWorld::DrawExtras(), DisplayShaysWorld::DrawLibraryPosts(), DisplayShaysWorld::DrawPavement(), DisplayShaysWorld::DrawPhysSciPosts(), DisplayShaysWorld::DrawRoof(), and DisplayShaysWorld::drawStairRailing().
glVertex3fv()
GLAPI void GLAPIENTRY glVertex3fv (const GLfloat * v)
glVertex3i()
GLAPI void GLAPIENTRY glVertex3i (GLint x, GLint y, GLint z)
glVertex3iv()
GLAPI void GLAPIENTRY glVertex3iv (const GLint * v)
glVertex3s()
GLAPI void GLAPIENTRY glVertex3s (GLshort x, GLshort y, GLshort z)
glVertex3sv()
GLAPI void GLAPIENTRY glVertex3sv (const GLshort * v)
glVertex4d()
GLAPI void GLAPIENTRY glVertex4d (GLdouble x, GLdouble y, GLdouble z, GLdouble w)
glVertex4dv()
GLAPI void GLAPIENTRY glVertex4dv (const GLdouble * v)
glVertex4f()
GLAPI void GLAPIENTRY glVertex4f (GLfloat x, GLfloat y, GLfloat z, GLfloat w)
glVertex4fv()
GLAPI void GLAPIENTRY glVertex4fv (const GLfloat * v)
glVertex4i()
GLAPI void GLAPIENTRY glVertex4i (GLint x, GLint y, GLint z, GLint w)
glVertex4iv()
GLAPI void GLAPIENTRY glVertex4iv (const GLint * v)
glVertex4s()
GLAPI void GLAPIENTRY glVertex4s (GLshort x, GLshort y, GLshort z, GLshort w)
glVertex4sv()
GLAPI void GLAPIENTRY glVertex4sv (const GLshort * v)
glVertexPointer()
GLAPI void GLAPIENTRY glVertexPointer (GLint size, GLenum type, GLsizei stride, const GLvoid * ptr)
glViewport()
GLAPI void GLAPIENTRY glViewport (GLint x, GLint y, GLsizei width, GLsizei height)
Referenced by reshape().
void()
typedef void (APIENTRYP PFNGLDRAWRANGEELEMENTSPROC)