ICT290 Assignment 1: TexturedPolygons Class Reference
TexturedPolygons Class Reference
#include <texturedPolygons.h>
Public Member Functions
TexturedPolygons ()
virtual ~TexturedPolygons ()
GLuint GetTexture (const int &tempIndex)
Returns the texture.
GLubyte * LoadTexture (char *filename, int imgWidth, int imgHeight)
Loads the texture.
GLubyte * LoadTexture (const char *filename)
Loads the texture.
void SetTextureCount (const int &textureNo)
Set the number of textures to be used.
void CreateTexture (int textureNo, unsigned char *image, int imgWidth, int imgHeight)
Creates RAW texture and set required values for texture mapping.
void CreatePNGTexture (int textureNo, unsigned char *image, int imgWidth, int imgHeight)
Creates PNG texture and set required values for texture mapping.
void CreateDisplayList (const int &XYZ, const int &listNo, const GLdouble &xImgSize, const GLdouble &zImgSize, const GLdouble &xStart, const GLdouble &yStart, const GLdouble &zStart, const GLdouble &xTimes, const GLdouble &zTimes)
Calls function to creates display list to contain image.
void CreateYtoZWindowList (const int &listNo, const GLdouble &xStart, const GLdouble &yStart, const GLdouble &ySize, const GLdouble &zStart, const GLdouble &zSize, const GLdouble &yImgSize, const GLdouble &zImgSize)
used to create display lists where image is larger than world scale on YZ axis
void CreateXtoYWindowList (const int &listNo, const GLdouble &zStart, const GLdouble &xStart, const GLdouble &xSize, const GLdouble &yStart, const GLdouble &ySize, const GLdouble &xImgSize, const GLdouble &yImgSize)
Used to create display lists where image is larger than world scale on XY axis.
void CreateAngledPolygon (const int &listNo, const GLdouble &imageWidth, const GLdouble &imageHeight, const GLdouble &x1, const GLdouble &x2, const GLdouble &x3, const GLdouble &x4, const GLdouble &y1, const GLdouble &y2, const GLdouble &y3, const GLdouble &y4, const GLdouble &z1, const GLdouble &z2, const GLdouble &z3, const GLdouble &z4, const int &smallestX, const int &smallestZ)
used to create display lists where image is on an angle
Private Member Functions
GLubyte * LoadRawImageFile (char *filename, int width, int height)
Loads RAW image file.
void Clear ()
void CreateXtoZTextureList (const GLdouble &xImgSize, const GLdouble &zImgSize, const GLdouble &xStart, const GLdouble &yStart, const GLdouble &zStart, const GLdouble &xTimes, const GLdouble &zTimes)
void CreateXtoYTextureList (const GLdouble &xImgSize, const GLdouble &yImgSize, const GLdouble &xStart, const GLdouble &yStart, const GLdouble &zStart, const GLdouble &xTimes, const GLdouble &yTimes, const bool &flip)
void CreateYtoZTextureList (const GLdouble &yImgSize, const GLdouble &zImgSize, const GLdouble &xStart, const GLdouble &yStart, const GLdouble &zStart, const GLdouble &yTimes, const GLdouble &zTimes, const bool &flip)
void CreateTextureScale (GLdouble &xzImage1, GLdouble &xzImage2, GLdouble &xzImage3, GLdouble &xzImage4, const GLdouble &imageSize)
TexturedPolygons (const TexturedPolygons &tp)
TexturedPolygons & operator= (const TexturedPolygons &tp)
Private Attributes
GLuint * m_texture
pointer to display list
Detailed Description
Definition at line 20 of file texturedPolygons.h.
Constructor & Destructor Documentation
TexturedPolygons() [1/2]
TexturedPolygons::TexturedPolygons () inline
Definition at line 24 of file texturedPolygons.h.
 {}
~TexturedPolygons()
virtual TexturedPolygons::~TexturedPolygons () inline virtual
Definition at line 25 of file texturedPolygons.h.
 {Clear();}
References Clear().
TexturedPolygons() [2/2]
TexturedPolygons::TexturedPolygons (const TexturedPolygons & tp) inline private
Definition at line 192 of file texturedPolygons.h.
 {};
Member Function Documentation
Clear()
void TexturedPolygons::Clear () private
Definition at line 73 of file texturedPolygons.cpp.
 {
     m_texture = NULL;
     if (m_texture == NULL)
     {
         delete [] m_texture;
     }
 }
References m_texture.
Referenced by ~TexturedPolygons().
CreateAngledPolygon()
void TexturedPolygons::CreateAngledPolygon (const int & listNo, const GLdouble & imageWidth, const GLdouble & imageHeight, const GLdouble & x1, const GLdouble & x2, const GLdouble & x3, const GLdouble & x4, const GLdouble & y1, const GLdouble & y2, const GLdouble & y3, const GLdouble & y4, const GLdouble & z1, const GLdouble & z2, const GLdouble & z3, const GLdouble & z4, const int & smallestX, const int & smallestZ)
used to create display lists where image is on an angle
Parameters
listNo - number the item is in the list
imageWidth - width of image
imageHeight - height of image
x1 - first corner x
x2 - second corner x
x3 - third corner x
x4 - fourth corner x
y1 - first corner y
y2 - second corner y
y3 - third corner y
y4 - fourth corner y
z1 - first corner z
z2 - second corner z
z3 - third corner z
z4 - fourth corner z
smallestX - the smallest x
smallestZ - the smallest z
Returns
void
Definition at line 270 of file texturedPolygons.cpp.
 {
     GLdouble xImage1 = x1;
     GLdouble xImage2 = x2;
     GLdouble xImage3 = x3;
     GLdouble xImage4 = x4;
     GLdouble zImage1 = z1;
     GLdouble zImage2 = z2;
     GLdouble zImage3 = z3;
     GLdouble zImage4 = z4;
     if (smallestX == 1)
     {
         CreateTextureScale(xImage1, xImage2, xImage3, xImage4, imageWidth);
     }
     else if (smallestX == 2)
     {
         CreateTextureScale(xImage2, xImage1, xImage3, xImage4, imageWidth);
     }
     else if (smallestX == 3)
     {
         CreateTextureScale(xImage3, xImage1, xImage2, xImage4, imageWidth);
     }
     else if (smallestX == 4)
     {
         CreateTextureScale(xImage4, xImage1, xImage2, xImage3, imageWidth);
     }
     else
     {
         xImage1 = y1;
         xImage2 = y2;
         xImage3 = y3;
         xImage4 = y4;
         if (smallestX == 5)
         {
             CreateTextureScale(xImage1, xImage2, xImage3, xImage4, imageWidth);
         }
         else if (smallestX == 6)
         {
             CreateTextureScale(xImage2, xImage1, xImage3, xImage4, imageWidth);
         }
         else if (smallestX == 7)
         {
             CreateTextureScale(xImage3, xImage1, xImage2, xImage4, imageWidth);
         }
         else if (smallestX == 8)
         {
             CreateTextureScale(xImage4, xImage1, xImage2, xImage3, imageWidth);
         }
     }
     if (smallestZ == 1)
     {
         CreateTextureScale(zImage1, zImage2, zImage3, zImage4, imageHeight);
     }
     else if (smallestZ == 2)
     {
         CreateTextureScale(zImage2, zImage1, zImage3, zImage4, imageHeight);
     }
     else if (smallestZ == 3)
     {
         CreateTextureScale(zImage3, zImage1, zImage2, zImage4, imageHeight);
     }
     else if (smallestZ == 4)
     {
         CreateTextureScale(zImage4, zImage1, zImage2, zImage3, imageHeight);
     }
     else
     {
         zImage1 = y1;
         zImage2 = y2;
         zImage3 = y3;
         zImage4 = y4;
         if (smallestZ == 5)
         {
             CreateTextureScale(zImage1, zImage2, zImage3, zImage4, imageHeight);
         }
         else if (smallestZ == 6)
         {
             CreateTextureScale(zImage2, zImage1, zImage3, zImage4, imageHeight);
         }
         else if (smallestZ == 7)
         {
             CreateTextureScale(zImage3, zImage1, zImage2, zImage4, imageHeight);
         }
         else if (smallestZ == 8)
         {
             CreateTextureScale(zImage4, zImage1, zImage2, zImage3, imageHeight);
         }
     }
     // create display list
     glNewList(listNo, GL_COMPILE);
         glBegin(GL_QUADS);
             glTexCoord2f(xImage1, zImage1);
             glVertex3f(x1, y1, z1);
             glTexCoord2f(xImage2, zImage2);
             glVertex3f(x2, y2, z2);
             glTexCoord2f(xImage3, zImage3);
             glVertex3f(x3, y3, z3);
             glTexCoord2f(xImage4, zImage4);
             glVertex3f(x4, y4, z4);
         glEnd();
     glEndList();
 }
References CreateTextureScale(), glBegin(), glEnd(), glEndList(), glNewList(), glTexCoord2f(), and glVertex3f().
Referenced by DisplayShaysWorld::DrawExtras(), DisplayShaysWorld::DrawGrass(), DisplayShaysWorld::DrawLibraryPosts(), and DisplayShaysWorld::DrawStepBricks().
CreateDisplayList()
void TexturedPolygons::CreateDisplayList (const int & XYZ, const int & listNo, const GLdouble & xImgSize, const GLdouble & zImgSize, const GLdouble & xStart, const GLdouble & yStart, const GLdouble & zStart, const GLdouble & xTimes, const GLdouble & zTimes)
Calls function to creates display list to contain image.
Parameters
XYZ
listNo - number the item is in the list
xImgSize - x size of image
zImgSize - z size of image
xStart - starting x
yStart - starting y
zStart - starting z
xTimes
zTimes
Returns
void
Definition at line 109 of file texturedPolygons.cpp.
 {
     glNewList(listNo, GL_COMPILE);
         glBegin(GL_QUADS);
         switch (XYZ)
         {
             case 0:
                 // create list where image is on X and Y axis
                 CreateXtoYTextureList(xImgSize, zImgSize, xStart, yStart, zStart, xTimes, zTimes, false);
                 break;
             case 1:
                 // create list where image is on X and Z axis
                 CreateXtoZTextureList(xImgSize, zImgSize, xStart, yStart, zStart, xTimes, zTimes);
                 break;
             case 2:
                 // create list where image is on Y and Z axis
                 CreateYtoZTextureList(xImgSize, zImgSize, xStart, yStart, zStart, xTimes, zTimes, false);
                 break;
             case 3:
                 // create list where (flipped) image is on X and Z axis
                 CreateYtoZTextureList(xImgSize, zImgSize, xStart, yStart, zStart, xTimes, zTimes, true);
                 break;
             case 4:
                 // create list where (flipped) image is on X and Y axis
                 CreateXtoYTextureList(xImgSize, zImgSize, xStart, yStart, zStart, xTimes, zTimes, true);
                 break;
         }
         glEnd();
     glEndList();
 }
References CreateXtoYTextureList(), CreateXtoZTextureList(), CreateYtoZTextureList(), glBegin(), glEnd(), glEndList(), and glNewList().
Referenced by DisplayShaysWorld::DrawAboveWindowBlock(), DisplayShaysWorld::DrawBench(), DisplayShaysWorld::DrawBricks(), DisplayShaysWorld::DrawChancPosts(), DisplayShaysWorld::DrawCylinders(), DisplayShaysWorld::DrawDoorPaving(), DisplayShaysWorld::DrawDoorPosts(), DisplayShaysWorld::DrawEntranceSteps(), DisplayShaysWorld::DrawExtras(), DisplayShaysWorld::DrawGrass(), DisplayWrathWorld::drawGroundPlane(), DisplayShaysWorld::DrawLargerTextures(), DisplayShaysWorld::DrawLibraryPosts(), DisplayShaysWorld::DrawLights(), DisplayShaysWorld::DrawMainPosts(), DisplayShaysWorld::DrawMapExit(), DisplayShaysWorld::DrawPavement(), DisplayShaysWorld::DrawPhysSciPosts(), DisplayWrathWorld::drawPortal(), DisplayShaysWorld::drawPortal(), DisplayShaysWorld::DrawPurplePosts(), DisplayShaysWorld::DrawRedPosts(), DisplayShaysWorld::DrawRoof(), DisplayWrathWorld::drawSkyBox(), DisplayShaysWorld::drawSpecialPortal(), and DisplayShaysWorld::DrawStepBricks().
CreatePNGTexture()
void TexturedPolygons::CreatePNGTexture (int textureNo, unsigned char * image, int imgWidth, int imgHeight)
Creates PNG texture and set required values for texture mapping.
Parameters
textureNo - number of the texture
image - character array of the image
imgWidth - width of the image
imgHeight - height of the image
Returns
void
Definition at line 93 of file texturedPolygons.cpp.
 {
     glBindTexture(GL_TEXTURE_2D, m_texture[textureNo]);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST_MIPMAP_LINEAR);
     gluBuild2DMipmaps(GL_TEXTURE_2D, 3, imgWidth, imgHeight, GL_RGBA, GL_UNSIGNED_BYTE, image);
 }
References glBindTexture(), glTexParameterf(), and m_texture.
Referenced by DisplayWrathWorld::CreateTextures(), and DisplayShaysWorld::CreateTextures().
CreateTexture()
void TexturedPolygons::CreateTexture (int textureNo, unsigned char * image, int imgWidth, int imgHeight)
Creates RAW texture and set required values for texture mapping.
Parameters
textureNo - number of the texture
image - character array of the image
imgWidth - width of the image
imgHeight - height of the image
Returns
void
Definition at line 86 of file texturedPolygons.cpp.
 {
     glBindTexture(GL_TEXTURE_2D, m_texture[textureNo]);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
     glTexParameterf(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST_MIPMAP_LINEAR);
     gluBuild2DMipmaps(GL_TEXTURE_2D, 3, imgWidth, imgHeight, GL_RGB, GL_UNSIGNED_BYTE, image);
 }
References glBindTexture(), glTexParameterf(), and m_texture.
Referenced by DisplayWrathWorld::CreateTextures(), and DisplayShaysWorld::CreateTextures().
CreateTextureScale()
void TexturedPolygons::CreateTextureScale (GLdouble & xzImage1, GLdouble & xzImage2, GLdouble & xzImage3, GLdouble & xzImage4, const GLdouble & imageSize) private
Definition at line 387 of file texturedPolygons.cpp.
 {
     xzImage2 = ((xzImage2 - xzImage1) / imageSize);
     xzImage3 = ((xzImage3 - xzImage1) / imageSize);
     xzImage4 = ((xzImage4 - xzImage1) / imageSize);
     xzImage1 = 0.0;
 }
Referenced by CreateAngledPolygon().
CreateXtoYTextureList()
void TexturedPolygons::CreateXtoYTextureList (const GLdouble & xImgSize, const GLdouble & yImgSize, const GLdouble & xStart, const GLdouble & yStart, const GLdouble & zStart, const GLdouble & xTimes, const GLdouble & yTimes, const bool & flip) private
Definition at line 165 of file texturedPolygons.cpp.
 {
     GLdouble flipX = 0.0;
     GLdouble tempX = xTimes;
     // if image is required to be flipped (this will be improved)
     if (flip)
     {
         flipX = xTimes;
         tempX = 0.0;
     }
     glTexCoord2f(flipX, 0.0);
     glVertex3f(xStart, yStart, zStart);
     glTexCoord2f(flipX, yTimes);
     glVertex3f(xStart, yStart + (yImgSize * yTimes), zStart);
     glTexCoord2f(tempX, yTimes);
     glVertex3f(xStart + (xImgSize * xTimes), yStart + (yImgSize * yTimes), zStart);
     glTexCoord2f(tempX, 0.0);
     glVertex3f(xStart + (xImgSize * xTimes), yStart, zStart);
 }
References glTexCoord2f(), and glVertex3f().
Referenced by CreateDisplayList().
CreateXtoYWindowList()
void TexturedPolygons::CreateXtoYWindowList (const int & listNo, const GLdouble & zStart, const GLdouble & xStart, const GLdouble & xSize, const GLdouble & yStart, const GLdouble & ySize, const GLdouble & xImgSize, const GLdouble & yImgSize)
Used to create display lists where image is larger than world scale on XY axis.
Parameters
listNo - number the item is in the list
zStart - starting z
xStart - starting x
xSize - size of x
yStart - starting y
ySize - size of y
xImgSize - y size of image
yImgSize - z size of image
Returns
void
Definition at line 241 of file texturedPolygons.cpp.
 {
     glNewList(listNo, GL_COMPILE);
         glBegin(GL_QUADS);
             glTexCoord2f(0.0, 0.0);
             glVertex3f(xStart, yStart, zStart);
             glTexCoord2f(xImgSize, 0.0);
             glVertex3f(xStart + xSize, yStart, zStart);
             glTexCoord2f(xImgSize, yImgSize);
             glVertex3f(xStart + xSize, yStart + ySize, zStart);
             glTexCoord2f(0.0, yImgSize);
             glVertex3f(xStart, yStart + ySize, zStart);
         glEnd();
     glEndList();
 }
References glBegin(), glEnd(), glEndList(), glNewList(), glTexCoord2f(), and glVertex3f().
Referenced by DisplayShaysWorld::DrawBricks(), and DisplayShaysWorld::DrawLargerTextures().
CreateXtoZTextureList()
void TexturedPolygons::CreateXtoZTextureList (const GLdouble & xImgSize, const GLdouble & zImgSize, const GLdouble & xStart, const GLdouble & yStart, const GLdouble & zStart, const GLdouble & xTimes, const GLdouble & zTimes) private
Definition at line 147 of file texturedPolygons.cpp.
 {
     glTexCoord2f(0.0, 0.0);
     glVertex3f(xStart, yStart , zStart);
     glTexCoord2f(0.0, zTimes);
     glVertex3f(xStart, yStart,zStart + (zImgSize * zTimes));
     glTexCoord2f(xTimes, zTimes);
     glVertex3f(xStart + (xImgSize * xTimes), yStart,zStart + (zImgSize * zTimes));
     glTexCoord2f(xTimes, 0.0);
     glVertex3f(xStart + (xImgSize * xTimes), yStart, zStart);
 }
References glTexCoord2f(), and glVertex3f().
Referenced by CreateDisplayList().
CreateYtoZTextureList()
void TexturedPolygons::CreateYtoZTextureList (const GLdouble & yImgSize, const GLdouble & zImgSize, const GLdouble & xStart, const GLdouble & yStart, const GLdouble & zStart, const GLdouble & yTimes, const GLdouble & zTimes, const bool & flip) private
Definition at line 191 of file texturedPolygons.cpp.
 {
     GLdouble flipZ = 0.0;
     GLdouble tempZ = zTimes;
     // if image is required to be flipped
     if (flip)
     {
         flipZ = zTimes;
         tempZ = 0.0;
     }
     glTexCoord2f(0.0, flipZ);
     glVertex3f(xStart, yStart, zStart);
     glTexCoord2f(0.0, tempZ);
     glVertex3f(xStart, yStart, zStart + (zImgSize * zTimes));
     glTexCoord2f(yTimes, tempZ);
     glVertex3f(xStart,yStart + (yImgSize * yTimes), zStart + (zImgSize * zTimes));
     glTexCoord2f(yTimes, flipZ);
     glVertex3f(xStart, yStart + (yImgSize * yTimes), zStart);
 }
References glTexCoord2f(), and glVertex3f().
Referenced by CreateDisplayList().
CreateYtoZWindowList()
void TexturedPolygons::CreateYtoZWindowList (const int & listNo, const GLdouble & xStart, const GLdouble & yStart, const GLdouble & ySize, const GLdouble & zStart, const GLdouble & zSize, const GLdouble & yImgSize, const GLdouble & zImgSize)
used to create display lists where image is larger than world scale on YZ axis
Parameters
listNo - number the item is in the list
xStart - starting x
xSize - size of x
yStart - starting y
ySize - size of y
zStart - starting z
zSize - size of z
yImgSize - y size of image
zImgSize - z size of image
Returns
void
Definition at line 220 of file texturedPolygons.cpp.
 {
     glNewList(listNo, GL_COMPILE);
         glBegin(GL_QUADS);
             glTexCoord2f(0.0, zImgSize);
             glVertex3f(xStart, yStart, zStart);
             glTexCoord2f(0.0, 0.0);
             glVertex3f(xStart, yStart, zStart + zSize);
             glTexCoord2f(yImgSize, 0.0);
             glVertex3f(xStart,yStart + ySize, zStart + zSize);
             glTexCoord2f(yImgSize, zImgSize);
             glVertex3f(xStart, yStart + ySize, zStart);
         glEnd();
     glEndList();
 }
References glBegin(), glEnd(), glEndList(), glNewList(), glTexCoord2f(), and glVertex3f().
Referenced by DisplayShaysWorld::DrawLargerTextures(), and DisplayShaysWorld::DrawRoof().
GetTexture()
GLuint TexturedPolygons::GetTexture (const int & tempIndex) inline
Returns the texture.
Parameters
tempIndex - Index of texture
Returns
Gluint
Definition at line 34 of file texturedPolygons.h.
 {return m_texture[tempIndex];}
References m_texture.
Referenced by Display(), DisplayShaysWorld::DisplayAboveWindowBlock(), DisplayShaysWorld::DisplayBench(), DisplayShaysWorld::DisplayBookSteps(), DisplayShaysWorld::DisplayBookStepsTwo(), DisplayShaysWorld::DisplayBricks(), DisplayShaysWorld::DisplayChancPosts(), DisplayShaysWorld::DisplayCylinders(), DisplayShaysWorld::DisplayDoorPaving(), DisplayShaysWorld::DisplayDoorPosts(), DisplayShaysWorld::DisplayEntranceSteps(), DisplayShaysWorld::DisplayExtras(), DisplayShaysWorld::DisplayGrass(), DisplayWrathWorld::displayGroundPlane(), DisplayShaysWorld::DisplayLargerTextures(), DisplayShaysWorld::DisplayLibraryPosts(), DisplayShaysWorld::DisplayLights(), DisplayShaysWorld::DisplayMainPosts(), DisplayShaysWorld::DisplayPavement(), DisplayShaysWorld::DisplayPhysSciPosts(), DisplayWrathWorld::displayPortal(), DisplayShaysWorld::displayPortal(), DisplayShaysWorld::DisplayPurplePosts(), DisplayShaysWorld::DisplayRedPosts(), DisplayShaysWorld::DisplayRoof(), DisplayWrathWorld::displaySkyBox(), DisplayShaysWorld::displaySpecialPortal(), DisplayShaysWorld::displayStairRailing(), and DisplayShaysWorld::DisplayStepBricks().
LoadRawImageFile()
GLubyte * TexturedPolygons::LoadRawImageFile (char * filename, int width, int height) private
Loads RAW image file.
Parameters
filename - name of the file
width - width of the image
height - height of the image
Returns
GLubyte*
Definition at line 41 of file texturedPolygons.cpp.
 {
     FILE* file;
     unsigned char* image;
     // create memory space w x h x 3 (3 stores RGB values)
     image = (unsigned char*)malloc(sizeof(unsigned char) * width * height * 3);
     file = fopen(filename, "rb" );
     // exit program if image not found and inform user
     if (file == NULL)
     {
         std::cout << "ERROR loading image file: " << filename << "...\n";
         exit(0);
     }
     fread(image, width * height * 3, 1, file);
     fclose(file);
     return image;
 }
Referenced by LoadTexture().
LoadTexture() [1/2]
GLubyte * TexturedPolygons::LoadTexture (char * filename, int imgWidth, int imgHeight)
Loads the texture.
Parameters
filename - name of the file
imgWidth - width of the image
imgHeight - height of the image
Returns
GLubyte*
Definition at line 17 of file texturedPolygons.cpp.
 {
     //
     unsigned char* image = NULL;
     image = LoadRawImageFile(filename, imgWidth, imgHeight);
     // inform user if file loaded
      std::cout << "Loading image file " << filename << "...\n";
     return image;
 }
References LoadRawImageFile().
Referenced by DisplayWrathWorld::CreateTextures(), and DisplayShaysWorld::CreateTextures().
LoadTexture() [2/2]
GLubyte * TexturedPolygons::LoadTexture (const char * filename)
Loads the texture.
Parameters
filename - name of the file
Returns
GLubyte*
Definition at line 26 of file texturedPolygons.cpp.
 {
     unsigned char* image;
     unsigned width, height;
     unsigned error = lodepng_decode32_file(&image, &width, &height, filename);
     if(error) std::cout << "decoder error " << error << ": " << lodepng_error_text(error) << std::endl;
     std::cout << "Loading image file " << filename << "...\n";
     return image;
 }
References lodepng_decode32_file(), and lodepng_error_text().
Referenced by DisplayWrathWorld::CreateTextures(), and DisplayShaysWorld::CreateTextures().
operator=()
TexturedPolygons& TexturedPolygons::operator= (const TexturedPolygons & tp) inline private
Definition at line 193 of file texturedPolygons.h.
 {};
SetTextureCount()
void TexturedPolygons::SetTextureCount (const int & textureNo)
Set the number of textures to be used.
Parameters
textureNo - number of the texture
Returns
void
Definition at line 63 of file texturedPolygons.cpp.
 {
     m_texture = new GLuint[textureNo];
     glGenTextures(textureNo, &m_texture[0]);
 }
References glGenTextures(), and m_texture.
Referenced by DisplayWrathWorld::CreateTextures(), and DisplayShaysWorld::CreateTextures().
Member Data Documentation
m_texture
GLuint* TexturedPolygons::m_texture private
pointer to display list
Definition at line 157 of file texturedPolygons.h.
Referenced by Clear(), CreatePNGTexture(), CreateTexture(), GetTexture(), and SetTextureCount().
The documentation for this class was generated from the following files:
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/texturedPolygons.h
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/texturedPolygons.cpp