ICT290 Assignment 1: DisplayWrathWorld Class Reference
DisplayWrathWorld Class Reference
#include <displayWrathWorld.h>
Public Member Functions
void myinit ()
void DrawBackdrop ()
void DeleteImageFromMemory (unsigned char *tempImage)
bool stairsReturnPortal ()
Public Attributes
Camera cam
TexturedPolygons tp
unsigned char * image = NULL
bool DisplayMap = false
bool DisplayWelcome = false
bool DisplayExit = false
Private Member Functions
void displaySkyBox ()
void displayGroundPlane ()
void displayPortal ()
void CreateTextureList ()
void drawSkyBox ()
void drawGroundPlane ()
void drawPortal ()
void CreateTextures ()
void CreateBoundingBoxes ()
Private Attributes
GLdouble step
GLdouble step2
GLdouble stepLength
GLUquadricObj * glu_cylinder
std::vector< unsigned char > * pngImage
Detailed Description
Definition at line 23 of file displayWrathWorld.h.
Member Function Documentation
CreateBoundingBoxes()
void DisplayWrathWorld::CreateBoundingBoxes () private
Definition at line 71 of file displayWrathWorld.cpp.
 {
     // chanc block
     //cam.SetAABBMaxX(0, 35879.0);
     //cam.SetAABBMinX(0, 33808.0);
     //cam.SetAABBMaxZ(0, 22096.0);
     //cam.SetAABBMinZ(0, 4688.0);
     // current AABB array size = 5
     // change array size with cam.SetNoBoundingBoxes() found in myinit()
 }
Referenced by myinit().
CreateTextureList()
void DisplayWrathWorld::CreateTextureList () private
Definition at line 173 of file displayWrathWorld.cpp.
 {
     drawSkyBox();               // 4-9
     drawGroundPlane();          // 3
     drawPortal();               //10
                                 //last number used: 10
 }
References drawGroundPlane(), drawPortal(), and drawSkyBox().
Referenced by myinit().
CreateTextures()
void DisplayWrathWorld::CreateTextures () private
Definition at line 93 of file displayWrathWorld.cpp.
 {
     glEnable(GL_DEPTH_TEST);
     glPixelStorei(GL_UNPACK_ALIGNMENT, 1);
     // set texture count
     tp.SetTextureCount(256);
     image = tp.LoadTexture("data/map.raw", 256, 256);
     tp.CreateTexture(217, image, 256, 256);
     image = tp.LoadTexture("data/welcome.png");
     tp.CreatePNGTexture(WELCOME_SCREEN, image, 512, 512);
     image = tp.LoadTexture("data/thanks.png");
     tp.CreatePNGTexture(EXIT_SCREEN, image, 512, 512);
     image = tp.LoadTexture("data/groundPlane.png");
     tp.CreatePNGTexture(GROUND_PLANE, image, 431, 431);
     image = tp.LoadTexture("data/space1.png");
     tp.CreatePNGTexture(SPACE_1, image, 1024, 1024);
     image = tp.LoadTexture("data/spaceportal.png");
     tp.CreatePNGTexture(PORTAL_1, image, 512, 385);
     glTexEnvf(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_DECAL);
     glHint(GL_PERSPECTIVE_CORRECTION_HINT, GL_NICEST);
 }
References TexturedPolygons::CreatePNGTexture(), TexturedPolygons::CreateTexture(), glEnable(), glHint(), glPixelStorei(), glTexEnvf(), image, TexturedPolygons::LoadTexture(), TexturedPolygons::SetTextureCount(), and tp.
Referenced by myinit().
DeleteImageFromMemory()
void DisplayWrathWorld::DeleteImageFromMemory (unsigned char * tempImage)
Definition at line 59 of file displayWrathWorld.cpp.
 {
     tempImage = NULL;
     if (tempImage == NULL)
     {
         delete[] tempImage;
     }
 }
Referenced by Mouse().
displayGroundPlane()
void DisplayWrathWorld::displayGroundPlane () private
Definition at line 147 of file displayWrathWorld.cpp.
 {
     glBindTexture(GL_TEXTURE_2D, tp.GetTexture(GROUND_PLANE));
     glCallList(3);
 }
References TexturedPolygons::GetTexture(), glBindTexture(), glCallList(), and tp.
Referenced by DrawBackdrop().
displayPortal()
void DisplayWrathWorld::displayPortal () private
Definition at line 158 of file displayWrathWorld.cpp.
 {
     glBindTexture(GL_TEXTURE_2D, tp.GetTexture(PORTAL_1));
     glCallList(10);
 }
References TexturedPolygons::GetTexture(), glBindTexture(), glCallList(), and tp.
Referenced by DrawBackdrop().
displaySkyBox()
void DisplayWrathWorld::displaySkyBox () private
Definition at line 130 of file displayWrathWorld.cpp.
 {
     glBindTexture(GL_TEXTURE_2D, tp.GetTexture(SPACE_1));
     for(int i=4; i<10; i++)
         glCallList(i);
 }
References TexturedPolygons::GetTexture(), glBindTexture(), glCallList(), and tp.
Referenced by DrawBackdrop().
DrawBackdrop()
void DisplayWrathWorld::DrawBackdrop ()
Definition at line 123 of file displayWrathWorld.cpp.
 {
     displaySkyBox();
     displayGroundPlane();
     displayPortal();
 }
References displayGroundPlane(), displayPortal(), and displaySkyBox().
Referenced by Display().
drawGroundPlane()
void DisplayWrathWorld::drawGroundPlane () private
Definition at line 153 of file displayWrathWorld.cpp.
 {
     tp.CreateDisplayList(XZ, 3, 431, 431, 0.0, 10000.0, 0.0, 50, 50);   // groundPlane
 }
References TexturedPolygons::CreateDisplayList(), and tp.
Referenced by CreateTextureList().
drawPortal()
void DisplayWrathWorld::drawPortal () private
Definition at line 164 of file displayWrathWorld.cpp.
 {
     tp.CreateDisplayList(XY, 10, 512, 385, 10000, 10000, 15000, 1.0, 2);
 }
References TexturedPolygons::CreateDisplayList(), and tp.
Referenced by CreateTextureList().
drawSkyBox()
void DisplayWrathWorld::drawSkyBox () private
Definition at line 137 of file displayWrathWorld.cpp.
 {
     tp.CreateDisplayList(XZ, 4, 1024, 1024, -10000.0, -10000.0, -30000.0, 100, 100);    // Bottom
     tp.CreateDisplayList(XZ, 5, 1024, 1024, -10000.0, 92400.0, -30000.0, 100, 100);     // Top
     tp.CreateDisplayList(YZ, 6, 1024, 1024, -10000.0, -10000.0, -30000.0, 100, 100);    // FRONT
     tp.CreateDisplayList(YZ, 7, 1024, 1024, 30000.0, -10000.0, -30000.0, 100, 100);     // Back
     tp.CreateDisplayList(XY, 8, 1024, 1024, -10000.0, -10000.0, -10000.0, 100, 100);    // Left
     tp.CreateDisplayList(XY, 9, 1024, 1024, -10000.0, -10000.0, 72400, 100, 100);       // Right
 }
References TexturedPolygons::CreateDisplayList(), and tp.
Referenced by CreateTextureList().
myinit()
void DisplayWrathWorld::myinit ()
Definition at line 11 of file displayWrathWorld.cpp.
 {
     // set background (sky colour)
     glClearColor(97.0 / 255.0, 140.0 / 255.0, 185.0 / 255.0, 1.0);
     // set perpsective
     gluLookAt(0.0, 1.75, 0.0,
         0.0, 1.75, -1,
         0.0f, 1.0f, 0.0f);
     // settings for glut cylinders
     //glu_cylinder = gluNewQuadric();
     //gluQuadricTexture(glu_cylinder, GL_TRUE);
     // set the world co-ordinates (used to set quadrants for bounding boxes)
     cam.SetWorldCoordinates(36000.0, 43200.0);
     // turn collision detection on
     cam.SetCollisionDetectionOn(true);
     // set number of bounding boxes required
     cam.SetNoBoundingBoxes(5);
     // set starting position of user
     cam.Position(10000, 10450.0, 10000.0, 180.0);
     //ORIGINAL POSITION
     /*
     cam.Position(32720.0, 9536.0,
         4800.0, 180.0);
         */
     //CreatePlains();
     // creates bounding boxes and places in array
     CreateBoundingBoxes();
     // copies bounding boxes from array to linked lists (one fopr each quadrant)
     cam.InitiateBoundingBoxes();
     // load texture images and create display lists
     CreateTextureList();
     CreateTextures();
 }
References cam, CreateBoundingBoxes(), CreateTextureList(), CreateTextures(), glClearColor(), Camera::InitiateBoundingBoxes(), Camera::Position(), Camera::SetCollisionDetectionOn(), Camera::SetNoBoundingBoxes(), and Camera::SetWorldCoordinates().
Referenced by Display(), and processKeys().
stairsReturnPortal()
bool DisplayWrathWorld::stairsReturnPortal ()
Definition at line 82 of file displayWrathWorld.cpp.
 {
     Portal stepsReturn;
     stepsReturn.setLocation(cam.GetLR(), cam.GetUD(), cam.GetFB());
     stepsReturn.portalDimensions(-500, -500, -500);
     return(stepsReturn.createPortal(10500, 10500.0, 15000.0));
 }
References cam, Portal::createPortal(), Camera::GetFB(), Camera::GetLR(), Camera::GetUD(), Portal::portalDimensions(), and Portal::setLocation().
Referenced by Display().
Member Data Documentation
cam
Camera DisplayWrathWorld::cam
Definition at line 27 of file displayWrathWorld.h.
Referenced by Display(), keyPressed(), mouseMove(), myinit(), processKeys(), and stairsReturnPortal().
DisplayExit
bool DisplayWrathWorld::DisplayExit = false
Definition at line 37 of file displayWrathWorld.h.
Referenced by Display(), Mouse(), and processKeys().
DisplayMap
bool DisplayWrathWorld::DisplayMap = false
Definition at line 33 of file displayWrathWorld.h.
DisplayWelcome
bool DisplayWrathWorld::DisplayWelcome = false
Definition at line 35 of file displayWrathWorld.h.
Referenced by Display(), and keyPressed().
glu_cylinder
GLUquadricObj* DisplayWrathWorld::glu_cylinder private
Definition at line 53 of file displayWrathWorld.h.
image
unsigned char* DisplayWrathWorld::image = NULL
Definition at line 29 of file displayWrathWorld.h.
Referenced by CreateTextures(), and Mouse().
pngImage
std::vector<unsigned char>* DisplayWrathWorld::pngImage private
Definition at line 56 of file displayWrathWorld.h.
step
GLdouble DisplayWrathWorld::step private
Definition at line 51 of file displayWrathWorld.h.
step2
GLdouble DisplayWrathWorld::step2 private
Definition at line 51 of file displayWrathWorld.h.
stepLength
GLdouble DisplayWrathWorld::stepLength private
Definition at line 51 of file displayWrathWorld.h.
tp
TexturedPolygons DisplayWrathWorld::tp
Definition at line 28 of file displayWrathWorld.h.
Referenced by CreateTextures(), Display(), displayGroundPlane(), displayPortal(), displaySkyBox(), drawGroundPlane(), drawPortal(), and drawSkyBox().
The documentation for this class was generated from the following files:
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/displayWrathWorld.h
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/displayWrathWorld.cpp