ICT290 Assignment 1: AABB Class Reference
AABB Class Reference
#include <AABB.H>
Classes
struct BoundingBox
stores max and min values of co-ordinates
struct XYZ
stores x,y,z co-ordinates
Public Member Functions
AABB ()
virtual ~AABB ()
void SetMaxX (const int &tempIndex, const GLdouble &tempX)
Sets max x of bounding box.
void SetMinX (const int &tempIndex, const GLdouble &tempX)
Sets min x of bounding box.
void SetMaxY (const int &tempIndex, const GLdouble &tempY)
Sets max y of bounding box.
void SetMinY (const int &tempIndex, const GLdouble &tempY)
Sets min y of bounding box.
void SetMaxZ (const int &tempIndex, const GLdouble &tempZ)
Sets max z of bounding box.
void SetMinZ (const int &tempIndex, const GLdouble &tempZ)
Sets min z of bounding box.
void SetNoBoundingBoxes (const int &tempSize)
Sets size of bounding box.
GLdouble GetMaxX (const int &tempIndex)
Gets max x of bounding box.
GLdouble GetMinX (const int &tempIndex)
Gets min x of bounding box.
GLdouble GetMaxY (const int &tempIndex)
Gets max y of bounding box.
GLdouble GetMinY (const int &tempIndex)
Gets min y of bounding box.
GLdouble GetMaxZ (const int &tempIndex)
Gets max z of bounding box.
GLdouble GetMinZ (const int &tempIndex)
Gets min z of bounding box.
int GetNoBoundingBoxes ()
Gets number of bounding boxes.
Private Member Functions
void ClearBB (BoundingBox *&tempArray)
Deletes arrays and clears memory.
AABB (const AABB &aabb)
AABB & operator= (const AABB &aabb)
Private Attributes
BoundingBox * m_BBox
dynamic array to store info
int m_NoOfBoxes
Detailed Description
Definition at line 26 of file AABB.H.
Constructor & Destructor Documentation
AABB() [1/2]
AABB::AABB (const AABB & aabb) inline private
Definition at line 54 of file AABB.H.
 {};
AABB() [2/2]
AABB::AABB () inline
Definition at line 58 of file AABB.H.
 {}
~AABB()
virtual AABB::~AABB () inline virtual
Definition at line 59 of file AABB.H.
 {ClearBB(m_BBox);}
References ClearBB(), and m_BBox.
Referenced by Collision::CreateLinkedList().
Member Function Documentation
ClearBB()
void AABB::ClearBB (BoundingBox *& tempArray) private
Deletes arrays and clears memory.
Parameters
tempArray - bounding box to clear
Returns
void
Definition at line 22 of file AABB.CPP.
 {
     tempArray = NULL;
     if (tempArray == NULL)
     {
         delete [] tempArray;
     }
 }
Referenced by ~AABB().
GetMaxX()
GLdouble AABB::GetMaxX (const int & tempIndex) inline
Gets max x of bounding box.
Parameters
tempIndex - index of Bounding Box
Returns
GLdouble
Definition at line 121 of file AABB.H.
 {return m_BBox[tempIndex].max.x;}
References m_BBox, AABB::BoundingBox::max, and AABB::XYZ::x.
Referenced by Collision::GetAABBMaxX().
GetMaxY()
GLdouble AABB::GetMaxY (const int & tempIndex) inline
Gets max y of bounding box.
Parameters
tempIndex - index of Bounding Box
Returns
GLdouble
Definition at line 133 of file AABB.H.
 {return m_BBox[tempIndex].max.y;}
References m_BBox, AABB::BoundingBox::max, and AABB::XYZ::y.
Referenced by Collision::GetAABBMaxY().
GetMaxZ()
GLdouble AABB::GetMaxZ (const int & tempIndex) inline
Gets max z of bounding box.
Parameters
tempIndex - index of Bounding Box
Returns
GLdouble
Definition at line 145 of file AABB.H.
 {return m_BBox[tempIndex].max.z;}
References m_BBox, AABB::BoundingBox::max, and AABB::XYZ::z.
Referenced by Collision::GetAABBMaxZ().
GetMinX()
GLdouble AABB::GetMinX (const int & tempIndex) inline
Gets min x of bounding box.
Parameters
tempIndex - index of Bounding Box
Returns
GLdouble
Definition at line 127 of file AABB.H.
 {return m_BBox[tempIndex].min.x;}
References m_BBox, AABB::BoundingBox::min, and AABB::XYZ::x.
Referenced by Collision::GetAABBMinX().
GetMinY()
GLdouble AABB::GetMinY (const int & tempIndex) inline
Gets min y of bounding box.
Parameters
tempIndex - index of Bounding Box
Returns
GLdouble
Definition at line 139 of file AABB.H.
 {return m_BBox[tempIndex].min.y;}
References m_BBox, AABB::BoundingBox::min, and AABB::XYZ::y.
Referenced by Collision::GetAABBMinY().
GetMinZ()
GLdouble AABB::GetMinZ (const int & tempIndex) inline
Gets min z of bounding box.
Parameters
tempIndex - index of Bounding Box
Returns
GLdouble
Definition at line 151 of file AABB.H.
 {return m_BBox[tempIndex].min.z;}
References m_BBox, AABB::BoundingBox::min, and AABB::XYZ::z.
Referenced by Collision::GetAABBMinZ().
GetNoBoundingBoxes()
int AABB::GetNoBoundingBoxes () inline
Gets number of bounding boxes.
Returns
int
Definition at line 156 of file AABB.H.
 {return m_NoOfBoxes;}
References m_NoOfBoxes.
Referenced by Collision::GetNoBoundingBoxes().
operator=()
AABB& AABB::operator= (const AABB & aabb) inline private
Definition at line 55 of file AABB.H.
 {};
SetMaxX()
void AABB::SetMaxX (const int & tempIndex, const GLdouble & tempX) inline
Sets max x of bounding box.
Parameters
tempIndex - index of bounding box
tempX - Max x of bounding box
Returns
void
Definition at line 70 of file AABB.H.
 {m_BBox[tempIndex].max.x = tempX;}
References m_BBox, AABB::BoundingBox::max, and AABB::XYZ::x.
Referenced by Collision::SetAABBMaxX().
SetMaxY()
void AABB::SetMaxY (const int & tempIndex, const GLdouble & tempY) inline
Sets max y of bounding box.
Parameters
tempIndex - index of bounding box
tempY - Max y of bounding box
Returns
void
Definition at line 84 of file AABB.H.
 {m_BBox[tempIndex].max.y = tempY;}
References m_BBox, AABB::BoundingBox::max, and AABB::XYZ::y.
Referenced by Collision::SetAABBMaxY().
SetMaxZ()
void AABB::SetMaxZ (const int & tempIndex, const GLdouble & tempZ) inline
Sets max z of bounding box.
Parameters
tempIndex - index of bounding box
tempY - Max z of bounding box
Returns
void
Definition at line 98 of file AABB.H.
 {m_BBox[tempIndex].max.z = tempZ;}
References m_BBox, AABB::BoundingBox::max, and AABB::XYZ::z.
Referenced by Collision::SetAABBMaxZ().
SetMinX()
void AABB::SetMinX (const int & tempIndex, const GLdouble & tempX) inline
Sets min x of bounding box.
Parameters
tempIndex - index of bounding box
tempX - Min x of bounding box
Returns
void
Definition at line 77 of file AABB.H.
 {m_BBox[tempIndex].min.x = tempX;}
References m_BBox, AABB::BoundingBox::min, and AABB::XYZ::x.
Referenced by Collision::SetAABBMinX().
SetMinY()
void AABB::SetMinY (const int & tempIndex, const GLdouble & tempY) inline
Sets min y of bounding box.
Parameters
tempIndex - index of bounding box
tempY - Min y of bounding box
Returns
void
Definition at line 91 of file AABB.H.
 {m_BBox[tempIndex].min.y = tempY;}
References m_BBox, AABB::BoundingBox::min, and AABB::XYZ::y.
Referenced by Collision::SetAABBMinY().
SetMinZ()
void AABB::SetMinZ (const int & tempIndex, const GLdouble & tempZ) inline
Sets min z of bounding box.
Parameters
tempIndex - index of bounding box
tempY - Min z of bounding box
Returns
void
Definition at line 105 of file AABB.H.
 {m_BBox[tempIndex].min.z = tempZ;}
References m_BBox, AABB::BoundingBox::min, and AABB::XYZ::z.
Referenced by Collision::SetAABBMinZ().
SetNoBoundingBoxes()
void AABB::SetNoBoundingBoxes (const int & tempSize)
Sets size of bounding box.
Parameters
tempSize - size of bounding box
Returns
void
Definition at line 14 of file AABB.CPP.
 {
     m_BBox = new BoundingBox[tempSize];
     m_NoOfBoxes = tempSize;
 }
References m_BBox, and m_NoOfBoxes.
Referenced by Collision::SetNoBoundingBoxes().
Member Data Documentation
m_BBox
BoundingBox* AABB::m_BBox private
dynamic array to store info
Definition at line 41 of file AABB.H.
Referenced by GetMaxX(), GetMaxY(), GetMaxZ(), GetMinX(), GetMinY(), GetMinZ(), SetMaxX(), SetMaxY(), SetMaxZ(), SetMinX(), SetMinY(), SetMinZ(), SetNoBoundingBoxes(), and ~AABB().
m_NoOfBoxes
int AABB::m_NoOfBoxes private
Definition at line 43 of file AABB.H.
Referenced by GetNoBoundingBoxes(), and SetNoBoundingBoxes().
The documentation for this class was generated from the following files:
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/AABB.H
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/AABB.CPP