ICT290 Assignment 1: CSound Class Reference
CSound Class Reference
#include <Sound.h>
Public Member Functions
CSound (char *filename, int iSoundID)
virtual ~CSound ()
bool Play (CSoundTime start, CSoundTime length)
bool Play ()
CSoundTime Stop ()
CSoundTime GetLength ()
int GetSoundID ()
Public Attributes
Uint8 * m_data
CSoundTime m_pos
CSoundTime m_len
CSoundTime m_stop
SDL_AudioSpec m_spec
int m_iSoundID
Detailed Description
class CSound: This class is the sound object, and it allow to play, stop, etc
Author
Shannon, Grahan and Shay
Definition at line 16 of file Sound.h.
Constructor & Destructor Documentation
CSound()
CSound::CSound (char * filename, int iSoundID)
CSound:
Parameters
filename
iSoundID
Returns
Definition at line 14 of file Sound.cpp.
 {
     m_iSoundID = iSoundID;
     Uint32 len;
     if (SDL_LoadWAV(filename, &m_spec, &m_data, &len) == NULL ) {
         fprintf(stderr, "Couldn't load %s: %s\n",filename, SDL_GetError());
         m_len = CSoundTime(0);
         return;
     }
     m_len = CSoundTime(len);
     m_pos = CSoundTime(0);
     CEasySound *es = CEasySound::Instance();
     SDL_AudioSpec obtained = es->GetObtained();
     SDL_AudioCVT cvt;
     SDL_BuildAudioCVT(&cvt, m_spec.format, m_spec.channels, m_spec.freq, obtained.format, obtained.channels, obtained.freq);
     cvt.buf = (Uint8*)malloc(m_len.GetSDLTime() * cvt.len_mult);
     memcpy(cvt.buf, m_data, m_len.GetSDLTime());
     cvt.len = m_len.GetSDLTime();
     SDL_ConvertAudio(&cvt);
     SDL_FreeWAV(m_data);
     SDL_LockAudio();
     m_data = cvt.buf;
     // the new length of sound after convert from 8bit to 16bit
     m_len = CSoundTime( cvt.len_cvt );
     m_pos = CSoundTime( 0 );
     SDL_UnlockAudio();
 }
References SDL_AudioCVT::buf, SDL_AudioSpec::channels, CSoundTime::CSoundTime(), SDL_AudioSpec::format, SDL_AudioSpec::freq, CEasySound::GetObtained(), CSoundTime::GetSDLTime(), CEasySound::Instance(), SDL_AudioCVT::len, SDL_AudioCVT::len_cvt, SDL_AudioCVT::len_mult, m_data, m_iSoundID, m_len, m_pos, m_spec, SDL_BuildAudioCVT(), SDL_ConvertAudio(), SDL_FreeWAV(), SDL_GetError(), SDL_LockAudio(), and SDL_UnlockAudio().
Referenced by CEasySound::Load().
~CSound()
CSound::~CSound () virtual
~CSound:
Returns
Definition at line 46 of file Sound.cpp.
 {
     SDL_FreeWAV(m_data);
 }
References m_data, and SDL_FreeWAV().
Member Function Documentation
GetLength()
CSoundTime CSound::GetLength ()
GetLength:
Returns
CSoundTime
Definition at line 75 of file Sound.cpp.
 {
     return CSoundTime(m_len);
 }
References m_len.
Referenced by CEasySound::Load().
GetSoundID()
int CSound::GetSoundID () inline
GetSoundID:
Returns
int
Definition at line 65 of file Sound.h.
 { return m_iSoundID; };
Referenced by CEasySound::GetSound(), CEasySound::Load(), and CEasySound::Unload().
Play() [1/2]
bool CSound::Play ()
Play:
Returns
bool
Definition at line 60 of file Sound.cpp.
 {
     m_pos = CSoundTime(0);
     m_stop = m_len;
     SDL_PauseAudio(0);
     return 0;
 }
References CSoundTime::CSoundTime(), m_len, m_pos, m_stop, and SDL_PauseAudio().
Play() [2/2]
bool CSound::Play (CSoundTime start, CSoundTime length)
Play:
Parameters
start
length
Returns
bool
Definition at line 52 of file Sound.cpp.
 {
     m_pos = start;
     m_stop = length;
     SDL_PauseAudio(0);
     return 0;
 }
References m_pos, m_stop, and SDL_PauseAudio().
Stop()
CSoundTime CSound::Stop ()
Stop:
Returns
CSoundTime
Definition at line 69 of file Sound.cpp.
 {
     SDL_PauseAudio(1);
     return CSoundTime(0,0,0);
 }
References CSoundTime::CSoundTime(), and SDL_PauseAudio().
Member Data Documentation
m_data
Uint8* CSound::m_data
m_data:
Definition at line 65 of file Sound.h.
Referenced by CEasySound::CallMixAudio(), CSound(), and ~CSound().
m_iSoundID
int CSound::m_iSoundID
m_iSoundID:
Definition at line 88 of file Sound.h.
Referenced by CSound().
m_len
CSoundTime CSound::m_len
m_len:
Definition at line 79 of file Sound.h.
Referenced by CSound(), GetLength(), and Play().
m_pos
CSoundTime CSound::m_pos
m_pos:
Definition at line 75 of file Sound.h.
Referenced by CEasySound::CallMixAudio(), CSound(), and Play().
m_spec
SDL_AudioSpec CSound::m_spec
m_spec:
Definition at line 84 of file Sound.h.
Referenced by CSound().
m_stop
CSoundTime CSound::m_stop
Definition at line 80 of file Sound.h.
Referenced by CEasySound::CallMixAudio(), and Play().
The documentation for this class was generated from the following files:
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/Sound.h
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/Sound.cpp