ICT290 Assignment 1: CameraMap Class Reference
CameraMap Class Reference
#include <cameraMap.h>
Public Member Functions
CameraMap ()
virtual ~CameraMap ()
void DisplayMap (const int &screenWidth, const int &screenHeight, const GLdouble &xPos, const GLdouble &zPos, const GLuint &tempImage)
void DisplayWelcomeScreen (const int &screenWidth, const int &screenHeight, const int &tempExit, const GLuint &tempImage)
void DisplayNoExit (const int &screenWidth, const int &screenHeight, const GLuint &tempImage)
Private Member Functions
CameraMap (const CameraMap &cam)
CameraMap & operator= (const CameraMap &cam)
Detailed Description
Definition at line 15 of file cameraMap.h.
Constructor & Destructor Documentation
CameraMap() [1/2]
CameraMap::CameraMap () inline
Definition at line 18 of file cameraMap.h.
 {};
~CameraMap()
virtual CameraMap::~CameraMap () inline virtual
Definition at line 19 of file cameraMap.h.
 {};
CameraMap() [2/2]
CameraMap::CameraMap (const CameraMap & cam) inline private
Definition at line 37 of file cameraMap.h.
 {};
Member Function Documentation
DisplayMap()
void CameraMap::DisplayMap (const int & screenWidth, const int & screenHeight, const GLdouble & xPos, const GLdouble & zPos, const GLuint & tempImage)
Definition at line 15 of file cameraMap.cpp.
 {
     GLdouble tempX = xPos/163.0 - 2096/163;
     GLdouble tempZ = zPos/164.0 - 4688/164;
     glPushMatrix();
     glMatrixMode(GL_PROJECTION);
     glPushMatrix();
     glLoadIdentity();
     gluOrtho2D(0, screenWidth, 0, screenHeight);
     glScalef(1, -1, 1);
     // mover the origin from the bottom left corner
     // to the upper left corner
     glTranslatef(0, -screenHeight, 0);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     // display the cursor of the camera position
     glBegin(GL_QUADS);
         glVertex3f(219.0 - tempX - 2.0, 256.0 - tempZ - 2.0, 0.0);
         glVertex3f(219.0 - tempX + 2.0, 256.0 - tempZ - 2.0,  0.0);
         glVertex3f(219.0 - tempX + 2.0, 256.0 - tempZ + 2.0,  0.0);
         glVertex3f(219.0 - tempX - 2.0, 256.0 - tempZ + 2.0, 0.0);
     glEnd();
     // display map
     glBindTexture(GL_TEXTURE_2D, tempImage);
     glCallList(448);
     // Reset Perspective Projection
     glMatrixMode(GL_PROJECTION);
     glPopMatrix();
     glMatrixMode(GL_MODELVIEW);
     glPopMatrix();
 }
References glBegin(), glBindTexture(), glCallList(), glEnd(), glLoadIdentity(), glMatrixMode(), glPopMatrix(), glPushMatrix(), glScalef(), glTranslatef(), and glVertex3f().
Referenced by Camera::DisplayMap().
DisplayNoExit()
void CameraMap::DisplayNoExit (const int & screenWidth, const int & screenHeight, const GLuint & tempImage)
Definition at line 88 of file cameraMap.cpp.
 {
     glPushMatrix();
     glMatrixMode(GL_PROJECTION);
     glPushMatrix();
     glLoadIdentity();
     gluOrtho2D(0, screenWidth, 0, screenHeight);
     glScalef(1, -1, 1);
     // move to centre of screen
     glTranslatef(screenWidth/2 -128.0, -screenHeight/2 -32.0, 0);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     // display sign
     glBindTexture(GL_TEXTURE_2D, tempImage);
     // display image
     glCallList(454);
     // Reset Perspective Projection
     glMatrixMode(GL_PROJECTION);
     glPopMatrix();
     glMatrixMode(GL_MODELVIEW);
     glPopMatrix();
 }
References glBindTexture(), glCallList(), glLoadIdentity(), glMatrixMode(), glPopMatrix(), glPushMatrix(), glScalef(), and glTranslatef().
Referenced by Camera::DisplayNoExit().
DisplayWelcomeScreen()
void CameraMap::DisplayWelcomeScreen (const int & screenWidth, const int & screenHeight, const int & tempExit, const GLuint & tempImage)
Definition at line 56 of file cameraMap.cpp.
 {
     glPushMatrix();
     glMatrixMode(GL_PROJECTION);
     glPushMatrix();
     glLoadIdentity();
     gluOrtho2D(0, screenWidth, 0, screenHeight);
     glScalef(1, -1, 1);
     // move to centre of screen
     glTranslatef(screenWidth/2 -256.0, -screenHeight/2 -256.0, 0);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     // display exit screen or welcome screen
     if (tempExit == 1)
     {
         glBindTexture(GL_TEXTURE_2D, tempImage);
     }
     else
     {
         glBindTexture(GL_TEXTURE_2D, tempImage);
     }
     // display image
     glCallList(449);
     // Reset Perspective Projection
     glMatrixMode(GL_PROJECTION);
     glPopMatrix();
     glMatrixMode(GL_MODELVIEW);
     glPopMatrix();
 }
References glBindTexture(), glCallList(), glLoadIdentity(), glMatrixMode(), glPopMatrix(), glPushMatrix(), glScalef(), and glTranslatef().
Referenced by Camera::DisplayWelcomeScreen().
operator=()
CameraMap& CameraMap::operator= (const CameraMap & cam) inline private
Definition at line 38 of file cameraMap.h.
 {};
The documentation for this class was generated from the following files:
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/cameraMap.h
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/cameraMap.cpp