ICT290 Assignment 1: C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/lodepng.h File Reference
lodepng.h File Reference
#include <string.h>
Classes
struct LodePNGDecompressSettings
struct LodePNGCompressSettings
struct LodePNGColorMode
struct LodePNGTime
struct LodePNGInfo
struct LodePNGDecoderSettings
struct LodePNGColorStats
struct LodePNGEncoderSettings
struct LodePNGState
Macros
#define LODEPNG_H
#define LODEPNG_COMPILE_ZLIB
#define LODEPNG_COMPILE_PNG
#define LODEPNG_COMPILE_DECODER
#define LODEPNG_COMPILE_ENCODER
#define LODEPNG_COMPILE_DISK
#define LODEPNG_COMPILE_ANCILLARY_CHUNKS
#define LODEPNG_COMPILE_ERROR_TEXT
#define LODEPNG_COMPILE_ALLOCATORS
Typedefs
typedef enum LodePNGColorType LodePNGColorType
typedef struct LodePNGDecompressSettings LodePNGDecompressSettings
typedef struct LodePNGCompressSettings LodePNGCompressSettings
typedef struct LodePNGColorMode LodePNGColorMode
typedef struct LodePNGTime LodePNGTime
typedef struct LodePNGInfo LodePNGInfo
typedef struct LodePNGDecoderSettings LodePNGDecoderSettings
typedef enum LodePNGFilterStrategy LodePNGFilterStrategy
typedef struct LodePNGColorStats LodePNGColorStats
typedef struct LodePNGEncoderSettings LodePNGEncoderSettings
typedef struct LodePNGState LodePNGState
Enumerations
enum LodePNGColorType {
LCT_GREY = 0, LCT_RGB = 2, LCT_PALETTE = 3, LCT_GREY_ALPHA = 4,
LCT_RGBA = 6, LCT_MAX_OCTET_VALUE = 255
}
enum LodePNGFilterStrategy {
LFS_ZERO = 0, LFS_ONE = 1, LFS_TWO = 2, LFS_THREE = 3,
LFS_FOUR = 4, LFS_MINSUM, LFS_ENTROPY, LFS_BRUTE_FORCE,
LFS_PREDEFINED
}
Functions
unsigned lodepng_decode_memory (unsigned char **out, unsigned *w, unsigned *h, const unsigned char *in, size_t insize, LodePNGColorType colortype, unsigned bitdepth)
unsigned lodepng_decode32 (unsigned char **out, unsigned *w, unsigned *h, const unsigned char *in, size_t insize)
unsigned lodepng_decode24 (unsigned char **out, unsigned *w, unsigned *h, const unsigned char *in, size_t insize)
unsigned lodepng_decode_file (unsigned char **out, unsigned *w, unsigned *h, const char *filename, LodePNGColorType colortype, unsigned bitdepth)
unsigned lodepng_decode32_file (unsigned char **out, unsigned *w, unsigned *h, const char *filename)
unsigned lodepng_decode24_file (unsigned char **out, unsigned *w, unsigned *h, const char *filename)
unsigned lodepng_encode_memory (unsigned char **out, size_t *outsize, const unsigned char *image, unsigned w, unsigned h, LodePNGColorType colortype, unsigned bitdepth)
unsigned lodepng_encode32 (unsigned char **out, size_t *outsize, const unsigned char *image, unsigned w, unsigned h)
unsigned lodepng_encode24 (unsigned char **out, size_t *outsize, const unsigned char *image, unsigned w, unsigned h)
unsigned lodepng_encode_file (const char *filename, const unsigned char *image, unsigned w, unsigned h, LodePNGColorType colortype, unsigned bitdepth)
unsigned lodepng_encode32_file (const char *filename, const unsigned char *image, unsigned w, unsigned h)
unsigned lodepng_encode24_file (const char *filename, const unsigned char *image, unsigned w, unsigned h)
const char * lodepng_error_text (unsigned code)
void lodepng_decompress_settings_init (LodePNGDecompressSettings *settings)
void lodepng_compress_settings_init (LodePNGCompressSettings *settings)
void lodepng_color_mode_init (LodePNGColorMode *info)
void lodepng_color_mode_cleanup (LodePNGColorMode *info)
unsigned lodepng_color_mode_copy (LodePNGColorMode *dest, const LodePNGColorMode *source)
LodePNGColorMode lodepng_color_mode_make (LodePNGColorType colortype, unsigned bitdepth)
void lodepng_palette_clear (LodePNGColorMode *info)
unsigned lodepng_palette_add (LodePNGColorMode *info, unsigned char r, unsigned char g, unsigned char b, unsigned char a)
unsigned lodepng_get_bpp (const LodePNGColorMode *info)
unsigned lodepng_get_channels (const LodePNGColorMode *info)
unsigned lodepng_is_greyscale_type (const LodePNGColorMode *info)
unsigned lodepng_is_alpha_type (const LodePNGColorMode *info)
unsigned lodepng_is_palette_type (const LodePNGColorMode *info)
unsigned lodepng_has_palette_alpha (const LodePNGColorMode *info)
unsigned lodepng_can_have_alpha (const LodePNGColorMode *info)
size_t lodepng_get_raw_size (unsigned w, unsigned h, const LodePNGColorMode *color)
void lodepng_info_init (LodePNGInfo *info)
void lodepng_info_cleanup (LodePNGInfo *info)
unsigned lodepng_info_copy (LodePNGInfo *dest, const LodePNGInfo *source)
unsigned lodepng_add_text (LodePNGInfo *info, const char *key, const char *str)
void lodepng_clear_text (LodePNGInfo *info)
unsigned lodepng_add_itext (LodePNGInfo *info, const char *key, const char *langtag, const char *transkey, const char *str)
void lodepng_clear_itext (LodePNGInfo *info)
unsigned lodepng_set_icc (LodePNGInfo *info, const char *name, const unsigned char *profile, unsigned profile_size)
void lodepng_clear_icc (LodePNGInfo *info)
unsigned lodepng_convert (unsigned char *out, const unsigned char *in, const LodePNGColorMode *mode_out, const LodePNGColorMode *mode_in, unsigned w, unsigned h)
void lodepng_decoder_settings_init (LodePNGDecoderSettings *settings)
void lodepng_color_stats_init (LodePNGColorStats *stats)
unsigned lodepng_compute_color_stats (LodePNGColorStats *stats, const unsigned char *image, unsigned w, unsigned h, const LodePNGColorMode *mode_in)
void lodepng_encoder_settings_init (LodePNGEncoderSettings *settings)
void lodepng_state_init (LodePNGState *state)
void lodepng_state_cleanup (LodePNGState *state)
void lodepng_state_copy (LodePNGState *dest, const LodePNGState *source)
unsigned lodepng_decode (unsigned char **out, unsigned *w, unsigned *h, LodePNGState *state, const unsigned char *in, size_t insize)
unsigned lodepng_inspect (unsigned *w, unsigned *h, LodePNGState *state, const unsigned char *in, size_t insize)
unsigned lodepng_inspect_chunk (LodePNGState *state, size_t pos, const unsigned char *in, size_t insize)
unsigned lodepng_encode (unsigned char **out, size_t *outsize, const unsigned char *image, unsigned w, unsigned h, LodePNGState *state)
unsigned lodepng_chunk_length (const unsigned char *chunk)
void lodepng_chunk_type (char type[5], const unsigned char *chunk)
unsigned char lodepng_chunk_type_equals (const unsigned char *chunk, const char *type)
unsigned char lodepng_chunk_ancillary (const unsigned char *chunk)
unsigned char lodepng_chunk_private (const unsigned char *chunk)
unsigned char lodepng_chunk_safetocopy (const unsigned char *chunk)
unsigned char * lodepng_chunk_data (unsigned char *chunk)
const unsigned char * lodepng_chunk_data_const (const unsigned char *chunk)
unsigned lodepng_chunk_check_crc (const unsigned char *chunk)
void lodepng_chunk_generate_crc (unsigned char *chunk)
unsigned char * lodepng_chunk_next (unsigned char *chunk, unsigned char *end)
const unsigned char * lodepng_chunk_next_const (const unsigned char *chunk, const unsigned char *end)
unsigned char * lodepng_chunk_find (unsigned char *chunk, unsigned char *end, const char type[5])
const unsigned char * lodepng_chunk_find_const (const unsigned char *chunk, const unsigned char *end, const char type[5])
unsigned lodepng_chunk_append (unsigned char **out, size_t *outsize, const unsigned char *chunk)
unsigned lodepng_chunk_create (unsigned char **out, size_t *outsize, unsigned length, const char *type, const unsigned char *data)
unsigned lodepng_crc32 (const unsigned char *buf, size_t len)
unsigned lodepng_inflate (unsigned char **out, size_t *outsize, const unsigned char *in, size_t insize, const LodePNGDecompressSettings *settings)
unsigned lodepng_zlib_decompress (unsigned char **out, size_t *outsize, const unsigned char *in, size_t insize, const LodePNGDecompressSettings *settings)
unsigned lodepng_zlib_compress (unsigned char **out, size_t *outsize, const unsigned char *in, size_t insize, const LodePNGCompressSettings *settings)
unsigned lodepng_huffman_code_lengths (unsigned *lengths, const unsigned *frequencies, size_t numcodes, unsigned maxbitlen)
unsigned lodepng_deflate (unsigned char **out, size_t *outsize, const unsigned char *in, size_t insize, const LodePNGCompressSettings *settings)
unsigned lodepng_load_file (unsigned char **out, size_t *outsize, const char *filename)
unsigned lodepng_save_file (const unsigned char *buffer, size_t buffersize, const char *filename)
Variables
const char * LODEPNG_VERSION_STRING
const LodePNGDecompressSettings lodepng_default_decompress_settings
const LodePNGCompressSettings lodepng_default_compress_settings
Macro Definition Documentation
LODEPNG_COMPILE_ALLOCATORS
#define LODEPNG_COMPILE_ALLOCATORS
Definition at line 83 of file lodepng.h.
LODEPNG_COMPILE_ANCILLARY_CHUNKS
#define LODEPNG_COMPILE_ANCILLARY_CHUNKS
Definition at line 71 of file lodepng.h.
LODEPNG_COMPILE_DECODER
#define LODEPNG_COMPILE_DECODER
Definition at line 56 of file lodepng.h.
LODEPNG_COMPILE_DISK
#define LODEPNG_COMPILE_DISK
Definition at line 66 of file lodepng.h.
LODEPNG_COMPILE_ENCODER
#define LODEPNG_COMPILE_ENCODER
Definition at line 61 of file lodepng.h.
LODEPNG_COMPILE_ERROR_TEXT
#define LODEPNG_COMPILE_ERROR_TEXT
Definition at line 76 of file lodepng.h.
LODEPNG_COMPILE_PNG
#define LODEPNG_COMPILE_PNG
Definition at line 51 of file lodepng.h.
LODEPNG_COMPILE_ZLIB
#define LODEPNG_COMPILE_ZLIB
Definition at line 46 of file lodepng.h.
LODEPNG_H
#define LODEPNG_H
Definition at line 28 of file lodepng.h.
Typedef Documentation
LodePNGColorMode
typedef struct LodePNGColorMode LodePNGColorMode
LodePNGColorStats
typedef struct LodePNGColorStats LodePNGColorStats
LodePNGColorType
typedef enum LodePNGColorType LodePNGColorType
LodePNGCompressSettings
typedef struct LodePNGCompressSettings LodePNGCompressSettings
Definition at line 296 of file lodepng.h.
LodePNGDecoderSettings
typedef struct LodePNGDecoderSettings LodePNGDecoderSettings
LodePNGDecompressSettings
typedef struct LodePNGDecompressSettings LodePNGDecompressSettings
Definition at line 268 of file lodepng.h.
LodePNGEncoderSettings
typedef struct LodePNGEncoderSettings LodePNGEncoderSettings
LodePNGFilterStrategy
typedef enum LodePNGFilterStrategy LodePNGFilterStrategy
LodePNGInfo
typedef struct LodePNGInfo LodePNGInfo
LodePNGState
typedef struct LodePNGState LodePNGState
LodePNGTime
typedef struct LodePNGTime LodePNGTime
Enumeration Type Documentation
LodePNGColorType
enum LodePNGColorType
Enumerator
LCT_GREY
LCT_RGB
LCT_PALETTE
LCT_GREY_ALPHA
LCT_RGBA
LCT_MAX_OCTET_VALUE
Definition at line 100 of file lodepng.h.
{
     LCT_GREY = 0, /*grayscale: 1,2,4,8,16 bit*/
     LCT_RGB = 2, /*RGB: 8,16 bit*/
     LCT_PALETTE = 3, /*palette: 1,2,4,8 bit*/
     LCT_GREY_ALPHA = 4, /*grayscale with alpha: 8,16 bit*/
     LCT_RGBA = 6, /*RGB with alpha: 8,16 bit*/
     /*LCT_MAX_OCTET_VALUE lets the compiler allow this enum to represent any invalid
     byte value from 0 to 255 that could be present in an invalid PNG file header. Do
     not use, compare with or set the name LCT_MAX_OCTET_VALUE, instead either use
     the valid color type names above, or numeric values like 1 or 7 when checking for
     particular disallowed color type byte values, or cast to integer to print it.*/
     LCT_MAX_OCTET_VALUE = 255
 } LodePNGColorType;
LodePNGFilterStrategy
enum LodePNGFilterStrategy
Enumerator
LFS_ZERO
LFS_ONE
LFS_TWO
LFS_THREE
LFS_FOUR
LFS_MINSUM
LFS_ENTROPY
LFS_BRUTE_FORCE
LFS_PREDEFINED
Definition at line 653 of file lodepng.h.
{
     /*every filter at zero*/
     LFS_ZERO = 0,
     /*every filter at 1, 2, 3 or 4 (paeth), unlike LFS_ZERO not a good choice, but for testing*/
     LFS_ONE = 1,
     LFS_TWO = 2,
     LFS_THREE = 3,
     LFS_FOUR = 4,
     /*Use filter that gives minimum sum, as described in the official PNG filter heuristic.*/
     LFS_MINSUM,
     /*Use the filter type that gives smallest Shannon entropy for this scanline. Depending
     on the image, this is better or worse than minsum.*/
     LFS_ENTROPY,
     /*
     Brute-force-search PNG filters by compressing each filter for each scanline.
     Experimental, very slow, and only rarely gives better compression than MINSUM.
     */
     LFS_BRUTE_FORCE,
     /*use predefined_filters buffer: you specify the filter type for each scanline*/
     LFS_PREDEFINED
 } LodePNGFilterStrategy;
Function Documentation
lodepng_add_itext()
unsigned lodepng_add_itext (LodePNGInfo * info, const char * key, const char * langtag, const char * transkey, const char * str)
Definition at line 3013 of file lodepng.cpp.
{
     return lodepng_add_itext_sized(info, key, langtag, transkey, str, lodepng_strlen(str));
 }
References lodepng_add_itext_sized(), and lodepng_strlen().
Referenced by LodePNGIText_copy().
lodepng_add_text()
unsigned lodepng_add_text (LodePNGInfo * info, const char * key, const char * str)
Definition at line 2939 of file lodepng.cpp.
{
     return lodepng_add_text_sized(info, key, str, lodepng_strlen(str));
 }
References lodepng_add_text_sized(), and lodepng_strlen().
Referenced by LodePNGText_copy(), and readChunk_tEXt().
lodepng_can_have_alpha()
unsigned lodepng_can_have_alpha (const LodePNGColorMode * info)
Definition at line 2803 of file lodepng.cpp.
{
     return info->key_defined
         || lodepng_is_alpha_type(info)
         || lodepng_has_palette_alpha(info);
 }
References LodePNGColorMode::key_defined, lodepng_has_palette_alpha(), and lodepng_is_alpha_type().
Referenced by lodepng_compute_color_stats().
lodepng_chunk_ancillary()
unsigned char lodepng_chunk_ancillary (const unsigned char * chunk)
Definition at line 2496 of file lodepng.cpp.
{
     return((chunk[4] & 32) != 0);
 }
Referenced by decodeGeneric().
lodepng_chunk_append()
unsigned lodepng_chunk_append (unsigned char ** out, size_t * outsize, const unsigned char * chunk)
Definition at line 2581 of file lodepng.cpp.
{
     unsigned i;
     size_t total_chunk_length, new_length;
     unsigned char* chunk_start, * new_buffer;
     if (lodepng_addofl(lodepng_chunk_length(chunk), 12, &total_chunk_length)) return 77;
     if (lodepng_addofl(*outsize, total_chunk_length, &new_length)) return 77;
     new_buffer = (unsigned char*)lodepng_realloc(*out, new_length);
     if (!new_buffer) return 83; /*alloc fail*/
     (*out) = new_buffer;
     (*outsize) = new_length;
     chunk_start = &(*out)[new_length - total_chunk_length];
     for (i = 0; i != total_chunk_length; ++i) chunk_start[i] = chunk[i];
     return 0;
 }
References lodepng_addofl(), lodepng_chunk_length(), and lodepng_realloc().
Referenced by addUnknownChunks(), and decodeGeneric().
lodepng_chunk_check_crc()
unsigned lodepng_chunk_check_crc (const unsigned char * chunk)
Definition at line 2516 of file lodepng.cpp.
{
     unsigned length = lodepng_chunk_length(chunk);
     unsigned CRC = lodepng_read32bitInt(&chunk[length + 8]);
     /*the CRC is taken of the data and the 4 chunk type letters, not the length*/
     unsigned checksum = lodepng_crc32(&chunk[4], length + 4);
     if (CRC != checksum) return 1;
     else return 0;
 }
References lodepng_chunk_length(), lodepng_crc32(), and lodepng_read32bitInt().
Referenced by decodeGeneric(), and lodepng_inspect_chunk().
lodepng_chunk_create()
unsigned lodepng_chunk_create (unsigned char ** out, size_t * outsize, unsigned length, const char * type, const unsigned char * data)
Definition at line 2637 of file lodepng.cpp.
{
     ucvector v = ucvector_init(*out, *outsize);
     unsigned error = lodepng_chunk_createv(&v, length, type, data);
     *out = v.data;
     *outsize = v.size;
     return error;
 }
References ucvector::data, lodepng_chunk_createv(), ucvector::size, and ucvector_init().
lodepng_chunk_data()
unsigned char* lodepng_chunk_data (unsigned char * chunk)
Definition at line 2508 of file lodepng.cpp.
{
     return &chunk[8];
 }
lodepng_chunk_data_const()
const unsigned char* lodepng_chunk_data_const (const unsigned char * chunk)
Definition at line 2512 of file lodepng.cpp.
{
     return &chunk[8];
 }
Referenced by decodeGeneric(), and lodepng_inspect_chunk().
lodepng_chunk_find()
unsigned char* lodepng_chunk_find (unsigned char * chunk, unsigned char * end, const char type[5])
Definition at line 2565 of file lodepng.cpp.
{
     for (;;) {
         if (chunk >= end || end - chunk < 12) return 0; /* past file end: chunk + 12 > end */
         if (lodepng_chunk_type_equals(chunk, type)) return chunk;
         chunk = lodepng_chunk_next(chunk, end);
     }
 }
References lodepng_chunk_next(), and lodepng_chunk_type_equals().
lodepng_chunk_find_const()
const unsigned char* lodepng_chunk_find_const (const unsigned char * chunk, const unsigned char * end, const char type[5])
Definition at line 2573 of file lodepng.cpp.
{
     for (;;) {
         if (chunk >= end || end - chunk < 12) return 0; /* past file end: chunk + 12 > end */
         if (lodepng_chunk_type_equals(chunk, type)) return chunk;
         chunk = lodepng_chunk_next_const(chunk, end);
     }
 }
References lodepng_chunk_next_const(), and lodepng_chunk_type_equals().
lodepng_chunk_generate_crc()
void lodepng_chunk_generate_crc (unsigned char * chunk)
Definition at line 2525 of file lodepng.cpp.
{
     unsigned length = lodepng_chunk_length(chunk);
     unsigned CRC = lodepng_crc32(&chunk[4], length + 4);
     lodepng_set32bitInt(chunk + 8 + length, CRC);
 }
References lodepng_chunk_length(), lodepng_crc32(), and lodepng_set32bitInt().
Referenced by addChunk_bKGD(), addChunk_cHRM(), addChunk_gAMA(), addChunk_iCCP(), addChunk_IHDR(), addChunk_iTXt(), addChunk_pHYs(), addChunk_PLTE(), addChunk_tEXt(), addChunk_tIME(), addChunk_tRNS(), addChunk_zTXt(), and lodepng_chunk_createv().
lodepng_chunk_length()
unsigned lodepng_chunk_length (const unsigned char * chunk)
Definition at line 2481 of file lodepng.cpp.
{
     return lodepng_read32bitInt(&chunk[0]);
 }
References lodepng_read32bitInt().
Referenced by decodeGeneric(), lodepng_chunk_append(), lodepng_chunk_check_crc(), lodepng_chunk_generate_crc(), lodepng_chunk_next(), lodepng_chunk_next_const(), lodepng_inspect(), and lodepng_inspect_chunk().
lodepng_chunk_next()
unsigned char* lodepng_chunk_next (unsigned char * chunk, unsigned char * end)
Definition at line 2531 of file lodepng.cpp.
{
     if (chunk >= end || end - chunk < 12) return end; /*too small to contain a chunk*/
     if (chunk[0] == 0x89 && chunk[1] == 0x50 && chunk[2] == 0x4e && chunk[3] == 0x47
         && chunk[4] == 0x0d && chunk[5] == 0x0a && chunk[6] == 0x1a && chunk[7] == 0x0a) {
         /* Is PNG magic header at start of PNG file. Jump to first actual chunk. */
         return chunk + 8;
     }
     else {
         size_t total_chunk_length;
         unsigned char* result;
         if (lodepng_addofl(lodepng_chunk_length(chunk), 12, &total_chunk_length)) return end;
         result = chunk + total_chunk_length;
         if (result < chunk) return end; /*pointer overflow*/
         return result;
     }
 }
References lodepng_addofl(), and lodepng_chunk_length().
Referenced by addUnknownChunks(), and lodepng_chunk_find().
lodepng_chunk_next_const()
const unsigned char* lodepng_chunk_next_const (const unsigned char * chunk, const unsigned char * end)
Definition at line 2548 of file lodepng.cpp.
{
     if (chunk >= end || end - chunk < 12) return end; /*too small to contain a chunk*/
     if (chunk[0] == 0x89 && chunk[1] == 0x50 && chunk[2] == 0x4e && chunk[3] == 0x47
         && chunk[4] == 0x0d && chunk[5] == 0x0a && chunk[6] == 0x1a && chunk[7] == 0x0a) {
         /* Is PNG magic header at start of PNG file. Jump to first actual chunk. */
         return chunk + 8;
     }
     else {
         size_t total_chunk_length;
         const unsigned char* result;
         if (lodepng_addofl(lodepng_chunk_length(chunk), 12, &total_chunk_length)) return end;
         result = chunk + total_chunk_length;
         if (result < chunk) return end; /*pointer overflow*/
         return result;
     }
 }
References lodepng_addofl(), and lodepng_chunk_length().
Referenced by decodeGeneric(), and lodepng_chunk_find_const().
lodepng_chunk_private()
unsigned char lodepng_chunk_private (const unsigned char * chunk)
Definition at line 2500 of file lodepng.cpp.
{
     return((chunk[6] & 32) != 0);
 }
lodepng_chunk_safetocopy()
unsigned char lodepng_chunk_safetocopy (const unsigned char * chunk)
Definition at line 2504 of file lodepng.cpp.
{
     return((chunk[7] & 32) != 0);
 }
lodepng_chunk_type()
void lodepng_chunk_type (char type[5], const unsigned char * chunk)
Definition at line 2485 of file lodepng.cpp.
{
     unsigned i;
     for (i = 0; i != 4; ++i) type[i] = (char)chunk[4 + i];
     type[4] = 0; /*null termination char*/
 }
lodepng_chunk_type_equals()
unsigned char lodepng_chunk_type_equals (const unsigned char * chunk, const char * type)
Definition at line 2491 of file lodepng.cpp.
{
     if (lodepng_strlen(type) != 4) return 0;
     return (chunk[4] == type[0] && chunk[5] == type[1] && chunk[6] == type[2] && chunk[7] == type[3]);
 }
References lodepng_strlen().
Referenced by decodeGeneric(), lodepng_chunk_find(), lodepng_chunk_find_const(), lodepng_inspect(), and lodepng_inspect_chunk().
lodepng_clear_icc()
void lodepng_clear_icc (LodePNGInfo * info)
Definition at line 3040 of file lodepng.cpp.
{
     string_cleanup(&info->iccp_name);
     lodepng_free(info->iccp_profile);
     info->iccp_profile = NULL;
     info->iccp_profile_size = 0;
     info->iccp_defined = 0;
 }
References LodePNGInfo::iccp_defined, LodePNGInfo::iccp_name, LodePNGInfo::iccp_profile, LodePNGInfo::iccp_profile_size, lodepng_free(), and string_cleanup().
Referenced by lodepng_info_cleanup(), lodepng_set_icc(), and readChunk_iCCP().
lodepng_clear_itext()
void lodepng_clear_itext (LodePNGInfo * info)
Definition at line 2985 of file lodepng.cpp.
{
     LodePNGIText_cleanup(info);
 }
References LodePNGIText_cleanup().
lodepng_clear_text()
void lodepng_clear_text (LodePNGInfo * info)
Definition at line 2943 of file lodepng.cpp.
{
     LodePNGText_cleanup(info);
 }
References LodePNGText_cleanup().
lodepng_color_mode_cleanup()
void lodepng_color_mode_cleanup (LodePNGColorMode * info)
Definition at line 2711 of file lodepng.cpp.
{
     lodepng_palette_clear(info);
 }
References lodepng_palette_clear().
Referenced by auto_choose_color(), lodepng_color_mode_copy(), lodepng_color_stats_add(), lodepng_info_cleanup(), and lodepng_state_cleanup().
lodepng_color_mode_copy()
unsigned lodepng_color_mode_copy (LodePNGColorMode * dest, const LodePNGColorMode * source)
Definition at line 2715 of file lodepng.cpp.
{
     lodepng_color_mode_cleanup(dest);
     lodepng_memcpy(dest, source, sizeof(LodePNGColorMode));
     if (source->palette) {
         dest->palette = (unsigned char*)lodepng_malloc(1024);
         if (!dest->palette && source->palettesize) return 83; /*alloc fail*/
         lodepng_memcpy(dest->palette, source->palette, source->palettesize * 4);
     }
     return 0;
 }
References lodepng_color_mode_cleanup(), lodepng_malloc(), lodepng_memcpy(), LodePNGColorMode::palette, and LodePNGColorMode::palettesize.
Referenced by auto_choose_color(), lodepng_decode(), lodepng_info_copy(), and lodepng_state_copy().
lodepng_color_mode_init()
void lodepng_color_mode_init (LodePNGColorMode * info)
Definition at line 2684 of file lodepng.cpp.
{
     info->key_defined = 0;
     info->key_r = info->key_g = info->key_b = 0;
     info->colortype = LCT_RGBA;
     info->bitdepth = 8;
     info->palette = 0;
     info->palettesize = 0;
 }
References LodePNGColorMode::bitdepth, LodePNGColorMode::colortype, LodePNGColorMode::key_b, LodePNGColorMode::key_defined, LodePNGColorMode::key_g, LodePNGColorMode::key_r, LCT_RGBA, LodePNGColorMode::palette, and LodePNGColorMode::palettesize.
Referenced by lodepng_color_mode_make(), lodepng_color_stats_add(), lodepng_info_copy(), lodepng_info_init(), lodepng_state_copy(), and lodepng_state_init().
lodepng_color_mode_make()
LodePNGColorMode lodepng_color_mode_make (LodePNGColorType colortype, unsigned bitdepth)
Definition at line 2726 of file lodepng.cpp.
{
     LodePNGColorMode result;
     lodepng_color_mode_init(&result);
     result.colortype = colortype;
     result.bitdepth = bitdepth;
     return result;
 }
References LodePNGColorMode::bitdepth, LodePNGColorMode::colortype, and lodepng_color_mode_init().
Referenced by lodepng_encode().
lodepng_color_stats_init()
void lodepng_color_stats_init (LodePNGColorStats * stats)
Definition at line 3725 of file lodepng.cpp.
{
     /*stats*/
     stats->colored = 0;
     stats->key = 0;
     stats->key_r = stats->key_g = stats->key_b = 0;
     stats->alpha = 0;
     stats->numcolors = 0;
     stats->bits = 1;
     stats->numpixels = 0;
     /*settings*/
     stats->allow_palette = 1;
     stats->allow_greyscale = 1;
 }
References LodePNGColorStats::allow_greyscale, LodePNGColorStats::allow_palette, LodePNGColorStats::alpha, LodePNGColorStats::bits, LodePNGColorStats::colored, LodePNGColorStats::key, LodePNGColorStats::key_b, LodePNGColorStats::key_g, LodePNGColorStats::key_r, LodePNGColorStats::numcolors, and LodePNGColorStats::numpixels.
Referenced by lodepng_encode().
lodepng_compress_settings_init()
void lodepng_compress_settings_init (LodePNGCompressSettings * settings)
Definition at line 2349 of file lodepng.cpp.
{
     /*compress with dynamic huffman tree (not in the mathematical sense, just not the predefined one)*/
     settings->btype = 2;
     settings->use_lz77 = 1;
     settings->windowsize = DEFAULT_WINDOWSIZE;
     settings->minmatch = 3;
     settings->nicematch = 128;
     settings->lazymatching = 1;
     settings->custom_zlib = 0;
     settings->custom_deflate = 0;
     settings->custom_context = 0;
 }
References LodePNGCompressSettings::btype, LodePNGCompressSettings::custom_context, LodePNGCompressSettings::custom_deflate, LodePNGCompressSettings::custom_zlib, LodePNGCompressSettings::lazymatching, LodePNGCompressSettings::minmatch, LodePNGCompressSettings::nicematch, LodePNGCompressSettings::use_lz77, and LodePNGCompressSettings::windowsize.
Referenced by lodepng_encoder_settings_init().
lodepng_compute_color_stats()
unsigned lodepng_compute_color_stats (LodePNGColorStats * stats, const unsigned char * image, unsigned w, unsigned h, const LodePNGColorMode * mode_in)
Definition at line 3760 of file lodepng.cpp.
{
     size_t i;
     ColorTree tree;
     size_t numpixels = (size_t)w * (size_t)h;
     unsigned error = 0;
     /* mark things as done already if it would be impossible to have a more expensive case */
     unsigned colored_done = lodepng_is_greyscale_type(mode_in) ? 1 : 0;
     unsigned alpha_done = lodepng_can_have_alpha(mode_in) ? 0 : 1;
     unsigned numcolors_done = 0;
     unsigned bpp = lodepng_get_bpp(mode_in);
     unsigned bits_done = (stats->bits == 1 && bpp == 1) ? 1 : 0;
     unsigned sixteen = 0; /* whether the input image is 16 bit */
     unsigned maxnumcolors = 257;
     if (bpp <= 8) maxnumcolors = LODEPNG_MIN(257, stats->numcolors + (1u << bpp));
     stats->numpixels += numpixels;
     /*if palette not allowed, no need to compute numcolors*/
     if (!stats->allow_palette) numcolors_done = 1;
     color_tree_init(&tree);
     /*If the stats was already filled in from previous data, fill its palette in tree
     and mark things as done already if we know they are the most expensive case already*/
     if (stats->alpha) alpha_done = 1;
     if (stats->colored) colored_done = 1;
     if (stats->bits == 16) numcolors_done = 1;
     if (stats->bits >= bpp) bits_done = 1;
     if (stats->numcolors >= maxnumcolors) numcolors_done = 1;
     if (!numcolors_done) {
         for (i = 0; i < stats->numcolors; i++) {
             const unsigned char* color = &stats->palette[i * 4];
             error = color_tree_add(&tree, color[0], color[1], color[2], color[3], i);
             if (error) goto cleanup;
         }
     }
     /*Check if the 16-bit input is truly 16-bit*/
     if (mode_in->bitdepth == 16 && !sixteen) {
         unsigned short r = 0, g = 0, b = 0, a = 0;
         for (i = 0; i != numpixels; ++i) {
             getPixelColorRGBA16(&r, &g, &b, &a, in, i, mode_in);
             if ((r & 255) != ((r >> 8) & 255) || (g & 255) != ((g >> 8) & 255) ||
                 (b & 255) != ((b >> 8) & 255) || (a & 255) != ((a >> 8) & 255)) /*first and second byte differ*/ {
                 stats->bits = 16;
                 sixteen = 1;
                 bits_done = 1;
                 numcolors_done = 1; /*counting colors no longer useful, palette doesn't support 16-bit*/
                 break;
             }
         }
     }
     if (sixteen) {
         unsigned short r = 0, g = 0, b = 0, a = 0;
         for (i = 0; i != numpixels; ++i) {
             getPixelColorRGBA16(&r, &g, &b, &a, in, i, mode_in);
             if (!colored_done && (r != g || r != b)) {
                 stats->colored = 1;
                 colored_done = 1;
             }
             if (!alpha_done) {
                 unsigned matchkey = (r == stats->key_r && g == stats->key_g && b == stats->key_b);
                 if (a != 65535 && (a != 0 || (stats->key && !matchkey))) {
                     stats->alpha = 1;
                     stats->key = 0;
                     alpha_done = 1;
                 }
                 else if (a == 0 && !stats->alpha && !stats->key) {
                     stats->key = 1;
                     stats->key_r = r;
                     stats->key_g = g;
                     stats->key_b = b;
                 }
                 else if (a == 65535 && stats->key && matchkey) {
                     /* Color key cannot be used if an opaque pixel also has that RGB color. */
                     stats->alpha = 1;
                     stats->key = 0;
                     alpha_done = 1;
                 }
             }
             if (alpha_done && numcolors_done && colored_done && bits_done) break;
         }
         if (stats->key && !stats->alpha) {
             for (i = 0; i != numpixels; ++i) {
                 getPixelColorRGBA16(&r, &g, &b, &a, in, i, mode_in);
                 if (a != 0 && r == stats->key_r && g == stats->key_g && b == stats->key_b) {
                     /* Color key cannot be used if an opaque pixel also has that RGB color. */
                     stats->alpha = 1;
                     stats->key = 0;
                     alpha_done = 1;
                 }
             }
         }
     }
     else /* < 16-bit */ {
         unsigned char r = 0, g = 0, b = 0, a = 0;
         for (i = 0; i != numpixels; ++i) {
             getPixelColorRGBA8(&r, &g, &b, &a, in, i, mode_in);
             if (!bits_done && stats->bits < 8) {
                 /*only r is checked, < 8 bits is only relevant for grayscale*/
                 unsigned bits = getValueRequiredBits(r);
                 if (bits > stats->bits) stats->bits = bits;
             }
             bits_done = (stats->bits >= bpp);
             if (!colored_done && (r != g || r != b)) {
                 stats->colored = 1;
                 colored_done = 1;
                 if (stats->bits < 8) stats->bits = 8; /*PNG has no colored modes with less than 8-bit per channel*/
             }
             if (!alpha_done) {
                 unsigned matchkey = (r == stats->key_r && g == stats->key_g && b == stats->key_b);
                 if (a != 255 && (a != 0 || (stats->key && !matchkey))) {
                     stats->alpha = 1;
                     stats->key = 0;
                     alpha_done = 1;
                     if (stats->bits < 8) stats->bits = 8; /*PNG has no alphachannel modes with less than 8-bit per channel*/
                 }
                 else if (a == 0 && !stats->alpha && !stats->key) {
                     stats->key = 1;
                     stats->key_r = r;
                     stats->key_g = g;
                     stats->key_b = b;
                 }
                 else if (a == 255 && stats->key && matchkey) {
                     /* Color key cannot be used if an opaque pixel also has that RGB color. */
                     stats->alpha = 1;
                     stats->key = 0;
                     alpha_done = 1;
                     if (stats->bits < 8) stats->bits = 8; /*PNG has no alphachannel modes with less than 8-bit per channel*/
                 }
             }
             if (!numcolors_done) {
                 if (!color_tree_has(&tree, r, g, b, a)) {
                     error = color_tree_add(&tree, r, g, b, a, stats->numcolors);
                     if (error) goto cleanup;
                     if (stats->numcolors < 256) {
                         unsigned char* p = stats->palette;
                         unsigned n = stats->numcolors;
                         p[n * 4 + 0] = r;
                         p[n * 4 + 1] = g;
                         p[n * 4 + 2] = b;
                         p[n * 4 + 3] = a;
                     }
                     ++stats->numcolors;
                     numcolors_done = stats->numcolors >= maxnumcolors;
                 }
             }
             if (alpha_done && numcolors_done && colored_done && bits_done) break;
         }
         if (stats->key && !stats->alpha) {
             for (i = 0; i != numpixels; ++i) {
                 getPixelColorRGBA8(&r, &g, &b, &a, in, i, mode_in);
                 if (a != 0 && r == stats->key_r && g == stats->key_g && b == stats->key_b) {
                     /* Color key cannot be used if an opaque pixel also has that RGB color. */
                     stats->alpha = 1;
                     stats->key = 0;
                     alpha_done = 1;
                     if (stats->bits < 8) stats->bits = 8; /*PNG has no alphachannel modes with less than 8-bit per channel*/
                 }
             }
         }
         /*make the stats's key always 16-bit for consistency - repeat each byte twice*/
         stats->key_r += (stats->key_r << 8);
         stats->key_g += (stats->key_g << 8);
         stats->key_b += (stats->key_b << 8);
     }
 cleanup:
     color_tree_cleanup(&tree);
     return error;
 }
References LodePNGColorStats::allow_palette, LodePNGColorStats::alpha, LodePNGColorMode::bitdepth, LodePNGColorStats::bits, color_tree_add(), color_tree_cleanup(), color_tree_has(), color_tree_init(), LodePNGColorStats::colored, getPixelColorRGBA16(), getPixelColorRGBA8(), getValueRequiredBits(), LodePNGColorStats::key, LodePNGColorStats::key_b, LodePNGColorStats::key_g, LodePNGColorStats::key_r, lodepng_can_have_alpha(), lodepng_get_bpp(), lodepng_is_greyscale_type(), LodePNGColorStats::numcolors, LodePNGColorStats::numpixels, and LodePNGColorStats::palette.
Referenced by lodepng_color_stats_add(), and lodepng_encode().
lodepng_convert()
unsigned lodepng_convert (unsigned char * out, const unsigned char * in, const LodePNGColorMode * mode_out, const LodePNGColorMode * mode_in, unsigned w, unsigned h)
Definition at line 3583 of file lodepng.cpp.
{
     size_t i;
     ColorTree tree;
     size_t numpixels = (size_t)w * (size_t)h;
     unsigned error = 0;
     if (mode_in->colortype == LCT_PALETTE && !mode_in->palette) {
         return 107; /* error: must provide palette if input mode is palette */
     }
     if (lodepng_color_mode_equal(mode_out, mode_in)) {
         size_t numbytes = lodepng_get_raw_size(w, h, mode_in);
         lodepng_memcpy(out, in, numbytes);
         return 0;
     }
     if (mode_out->colortype == LCT_PALETTE) {
         size_t palettesize = mode_out->palettesize;
         const unsigned char* palette = mode_out->palette;
         size_t palsize = (size_t)1u << mode_out->bitdepth;
         /*if the user specified output palette but did not give the values, assume
         they want the values of the input color type (assuming that one is palette).
         Note that we never create a new palette ourselves.*/
         if (palettesize == 0) {
             palettesize = mode_in->palettesize;
             palette = mode_in->palette;
             /*if the input was also palette with same bitdepth, then the color types are also
             equal, so copy literally. This to preserve the exact indices that were in the PNG
             even in case there are duplicate colors in the palette.*/
             if (mode_in->colortype == LCT_PALETTE && mode_in->bitdepth == mode_out->bitdepth) {
                 size_t numbytes = lodepng_get_raw_size(w, h, mode_in);
                 lodepng_memcpy(out, in, numbytes);
                 return 0;
             }
         }
         if (palettesize < palsize) palsize = palettesize;
         color_tree_init(&tree);
         for (i = 0; i != palsize; ++i) {
             const unsigned char* p = &palette[i * 4];
             error = color_tree_add(&tree, p[0], p[1], p[2], p[3], (unsigned)i);
             if (error) break;
         }
     }
     if (!error) {
         if (mode_in->bitdepth == 16 && mode_out->bitdepth == 16) {
             for (i = 0; i != numpixels; ++i) {
                 unsigned short r = 0, g = 0, b = 0, a = 0;
                 getPixelColorRGBA16(&r, &g, &b, &a, in, i, mode_in);
                 rgba16ToPixel(out, i, mode_out, r, g, b, a);
             }
         }
         else if (mode_out->bitdepth == 8 && mode_out->colortype == LCT_RGBA) {
             getPixelColorsRGBA8(out, numpixels, in, mode_in);
         }
         else if (mode_out->bitdepth == 8 && mode_out->colortype == LCT_RGB) {
             getPixelColorsRGB8(out, numpixels, in, mode_in);
         }
         else {
             unsigned char r = 0, g = 0, b = 0, a = 0;
             for (i = 0; i != numpixels; ++i) {
                 getPixelColorRGBA8(&r, &g, &b, &a, in, i, mode_in);
                 error = rgba8ToPixel(out, i, mode_out, &tree, r, g, b, a);
                 if (error) break;
             }
         }
     }
     if (mode_out->colortype == LCT_PALETTE) {
         color_tree_cleanup(&tree);
     }
     return error;
 }
References LodePNGColorMode::bitdepth, color_tree_add(), color_tree_cleanup(), color_tree_init(), LodePNGColorMode::colortype, getPixelColorRGBA16(), getPixelColorRGBA8(), getPixelColorsRGB8(), getPixelColorsRGBA8(), LCT_PALETTE, LCT_RGB, LCT_RGBA, lodepng_color_mode_equal(), lodepng_get_raw_size(), lodepng_memcpy(), LodePNGColorMode::palette, LodePNGColorMode::palettesize, rgba16ToPixel(), and rgba8ToPixel().
Referenced by lodepng_decode(), and lodepng_encode().
lodepng_crc32()
unsigned lodepng_crc32 (const unsigned char * buf, size_t len)
Definition at line 2434 of file lodepng.cpp.
{
     unsigned r = 0xffffffffu;
     size_t i;
     for (i = 0; i < length; ++i) {
         r = lodepng_crc32_table[(r ^ data[i]) & 0xffu] ^ (r >> 8u);
     }
     return r ^ 0xffffffffu;
 }
References lodepng_crc32_table.
Referenced by lodepng_chunk_check_crc(), lodepng_chunk_generate_crc(), and lodepng_inspect().
lodepng_decode()
unsigned lodepng_decode (unsigned char ** out, unsigned * w, unsigned * h, LodePNGState * state, const unsigned char * in, size_t insize)
Definition at line 5048 of file lodepng.cpp.
{
     *out = 0;
     decodeGeneric(out, w, h, state, in, insize);
     if (state->error) return state->error;
     if (!state->decoder.color_convert || lodepng_color_mode_equal(&state->info_raw, &state->info_png.color)) {
         /*same color type, no copying or converting of data needed*/
         /*store the info_png color settings on the info_raw so that the info_raw still reflects what colortype
         the raw image has to the end user*/
         if (!state->decoder.color_convert) {
             state->error = lodepng_color_mode_copy(&state->info_raw, &state->info_png.color);
             if (state->error) return state->error;
         }
     }
     else { /*color conversion needed*/
         unsigned char* data = *out;
         size_t outsize;
         /*TODO: check if this works according to the statement in the documentation: "The converter can convert
         from grayscale input color type, to 8-bit grayscale or grayscale with alpha"*/
         if (!(state->info_raw.colortype == LCT_RGB || state->info_raw.colortype == LCT_RGBA)
             && !(state->info_raw.bitdepth == 8)) {
             return 56; /*unsupported color mode conversion*/
         }
         outsize = lodepng_get_raw_size(*w, *h, &state->info_raw);
         *out = (unsigned char*)lodepng_malloc(outsize);
         if (!(*out)) {
             state->error = 83; /*alloc fail*/
         }
         else state->error = lodepng_convert(*out, data, &state->info_raw,
             &state->info_png.color, *w, *h);
         lodepng_free(data);
     }
     return state->error;
 }
References LodePNGColorMode::bitdepth, LodePNGInfo::color, LodePNGDecoderSettings::color_convert, LodePNGColorMode::colortype, decodeGeneric(), LodePNGState::decoder, LodePNGState::error, LodePNGState::info_png, LodePNGState::info_raw, LCT_RGB, LCT_RGBA, lodepng_color_mode_copy(), lodepng_color_mode_equal(), lodepng_convert(), lodepng_free(), lodepng_get_raw_size(), and lodepng_malloc().
Referenced by lodepng_decode_memory().
lodepng_decode24()
unsigned lodepng_decode24 (unsigned char ** out, unsigned * w, unsigned * h, const unsigned char * in, size_t insize)
Definition at line 5102 of file lodepng.cpp.
{
     return lodepng_decode_memory(out, w, h, in, insize, LCT_RGB, 8);
 }
References LCT_RGB, and lodepng_decode_memory().
lodepng_decode24_file()
unsigned lodepng_decode24_file (unsigned char ** out, unsigned * w, unsigned * h, const char * filename)
Definition at line 5125 of file lodepng.cpp.
{
     return lodepng_decode_file(out, w, h, filename, LCT_RGB, 8);
 }
References LCT_RGB, and lodepng_decode_file().
lodepng_decode32()
unsigned lodepng_decode32 (unsigned char ** out, unsigned * w, unsigned * h, const unsigned char * in, size_t insize)
Definition at line 5098 of file lodepng.cpp.
{
     return lodepng_decode_memory(out, w, h, in, insize, LCT_RGBA, 8);
 }
References LCT_RGBA, and lodepng_decode_memory().
lodepng_decode32_file()
unsigned lodepng_decode32_file (unsigned char ** out, unsigned * w, unsigned * h, const char * filename)
Definition at line 5121 of file lodepng.cpp.
{
     return lodepng_decode_file(out, w, h, filename, LCT_RGBA, 8);
 }
References LCT_RGBA, and lodepng_decode_file().
Referenced by TexturedPolygons::LoadTexture().
lodepng_decode_file()
unsigned lodepng_decode_file (unsigned char ** out, unsigned * w, unsigned * h, const char * filename, LodePNGColorType colortype, unsigned bitdepth)
Definition at line 5107 of file lodepng.cpp.
{
     unsigned char* buffer = 0;
     size_t buffersize;
     unsigned error;
     /* safe output values in case error happens */
     *out = 0;
     *w = *h = 0;
     error = lodepng_load_file(&buffer, &buffersize, filename);
     if (!error) error = lodepng_decode_memory(out, w, h, buffer, buffersize, colortype, bitdepth);
     lodepng_free(buffer);
     return error;
 }
References lodepng_decode_memory(), lodepng_free(), and lodepng_load_file().
Referenced by lodepng_decode24_file(), and lodepng_decode32_file().
lodepng_decode_memory()
unsigned lodepng_decode_memory (unsigned char ** out, unsigned * w, unsigned * h, const unsigned char * in, size_t insize, LodePNGColorType colortype, unsigned bitdepth)
Definition at line 5086 of file lodepng.cpp.
{
     unsigned error;
     LodePNGState state;
     lodepng_state_init(&state);
     state.info_raw.colortype = colortype;
     state.info_raw.bitdepth = bitdepth;
     error = lodepng_decode(out, w, h, &state, in, insize);
     lodepng_state_cleanup(&state);
     return error;
 }
References LodePNGColorMode::bitdepth, LodePNGColorMode::colortype, LodePNGState::info_raw, lodepng_decode(), lodepng_state_cleanup(), and lodepng_state_init().
Referenced by lodepng_decode24(), lodepng_decode32(), and lodepng_decode_file().
lodepng_decoder_settings_init()
void lodepng_decoder_settings_init (LodePNGDecoderSettings * settings)
Definition at line 5130 of file lodepng.cpp.
{
     settings->color_convert = 1;
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
     settings->read_text_chunks = 1;
     settings->remember_unknown_chunks = 0;
 #endif /*LODEPNG_COMPILE_ANCILLARY_CHUNKS*/
     settings->ignore_crc = 0;
     settings->ignore_critical = 0;
     settings->ignore_end = 0;
     lodepng_decompress_settings_init(&settings->zlibsettings);
 }
References LodePNGDecoderSettings::color_convert, LodePNGDecoderSettings::ignore_crc, LodePNGDecoderSettings::ignore_critical, LodePNGDecoderSettings::ignore_end, lodepng_decompress_settings_init(), LodePNGDecoderSettings::read_text_chunks, LodePNGDecoderSettings::remember_unknown_chunks, and LodePNGDecoderSettings::zlibsettings.
Referenced by lodepng_state_init().
lodepng_decompress_settings_init()
void lodepng_decompress_settings_init (LodePNGDecompressSettings * settings)
Definition at line 2370 of file lodepng.cpp.
{
     settings->ignore_adler32 = 0;
     settings->ignore_nlen = 0;
     settings->custom_zlib = 0;
     settings->custom_inflate = 0;
     settings->custom_context = 0;
 }
References LodePNGDecompressSettings::custom_context, LodePNGDecompressSettings::custom_inflate, LodePNGDecompressSettings::custom_zlib, LodePNGDecompressSettings::ignore_adler32, and LodePNGDecompressSettings::ignore_nlen.
Referenced by lodepng_decoder_settings_init().
lodepng_deflate()
unsigned lodepng_deflate (unsigned char ** out, size_t * outsize, const unsigned char * in, size_t insize, const LodePNGCompressSettings * settings)
Definition at line 2138 of file lodepng.cpp.
{
     ucvector v = ucvector_init(*out, *outsize);
     unsigned error = lodepng_deflatev(&v, in, insize, settings);
     *out = v.data;
     *outsize = v.size;
     return error;
 }
References ucvector::data, lodepng_deflatev(), ucvector::size, and ucvector_init().
Referenced by deflate().
lodepng_encode()
unsigned lodepng_encode (unsigned char ** out, size_t * outsize, const unsigned char * image, unsigned w, unsigned h, LodePNGState * state)
Definition at line 5922 of file lodepng.cpp.
{
     unsigned char* data = 0; /*uncompressed version of the IDAT chunk data*/
     size_t datasize = 0;
     ucvector outv = ucvector_init(NULL, 0);
     LodePNGInfo info;
     const LodePNGInfo* info_png = &state->info_png;
     lodepng_info_init(&info);
     /*provide some proper output values if error will happen*/
     *out = 0;
     *outsize = 0;
     state->error = 0;
     /*check input values validity*/
     if ((info_png->color.colortype == LCT_PALETTE || state->encoder.force_palette)
         && (info_png->color.palettesize == 0 || info_png->color.palettesize > 256)) {
         state->error = 68; /*invalid palette size, it is only allowed to be 1-256*/
         goto cleanup;
     }
     if (state->encoder.zlibsettings.btype > 2) {
         state->error = 61; /*error: invalid btype*/
         goto cleanup;
     }
     if (info_png->interlace_method > 1) {
         state->error = 71; /*error: invalid interlace mode*/
         goto cleanup;
     }
     state->error = checkColorValidity(info_png->color.colortype, info_png->color.bitdepth);
     if (state->error) goto cleanup; /*error: invalid color type given*/
     state->error = checkColorValidity(state->info_raw.colortype, state->info_raw.bitdepth);
     if (state->error) goto cleanup; /*error: invalid color type given*/
     /* color convert and compute scanline filter types */
     lodepng_info_copy(&info, &state->info_png);
     if (state->encoder.auto_convert) {
         LodePNGColorStats stats;
         lodepng_color_stats_init(&stats);
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
         if (info_png->iccp_defined &&
             isGrayICCProfile(info_png->iccp_profile, info_png->iccp_profile_size)) {
             /*the PNG specification does not allow to use palette with a GRAY ICC profile, even
             if the palette has only gray colors, so disallow it.*/
             stats.allow_palette = 0;
         }
         if (info_png->iccp_defined &&
             isRGBICCProfile(info_png->iccp_profile, info_png->iccp_profile_size)) {
             /*the PNG specification does not allow to use grayscale color with RGB ICC profile, so disallow gray.*/
             stats.allow_greyscale = 0;
         }
 #endif /* LODEPNG_COMPILE_ANCILLARY_CHUNKS */
         state->error = lodepng_compute_color_stats(&stats, image, w, h, &state->info_raw);
         if (state->error) goto cleanup;
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
         if (info_png->background_defined) {
             /*the background chunk's color must be taken into account as well*/
             unsigned r = 0, g = 0, b = 0;
             LodePNGColorMode mode16 = lodepng_color_mode_make(LCT_RGB, 16);
             lodepng_convert_rgb(&r, &g, &b, info_png->background_r, info_png->background_g, info_png->background_b, &mode16, &info_png->color);
             state->error = lodepng_color_stats_add(&stats, r, g, b, 65535);
             if (state->error) goto cleanup;
         }
 #endif /* LODEPNG_COMPILE_ANCILLARY_CHUNKS */
         state->error = auto_choose_color(&info.color, &state->info_raw, &stats);
         if (state->error) goto cleanup;
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
         /*also convert the background chunk*/
         if (info_png->background_defined) {
             if (lodepng_convert_rgb(&info.background_r, &info.background_g, &info.background_b,
                 info_png->background_r, info_png->background_g, info_png->background_b, &info.color, &info_png->color)) {
                 state->error = 104;
                 goto cleanup;
             }
         }
 #endif /* LODEPNG_COMPILE_ANCILLARY_CHUNKS */
     }
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
     if (info_png->iccp_defined) {
         unsigned gray_icc = isGrayICCProfile(info_png->iccp_profile, info_png->iccp_profile_size);
         unsigned rgb_icc = isRGBICCProfile(info_png->iccp_profile, info_png->iccp_profile_size);
         unsigned gray_png = info.color.colortype == LCT_GREY || info.color.colortype == LCT_GREY_ALPHA;
         if (!gray_icc && !rgb_icc) {
             state->error = 100; /* Disallowed profile color type for PNG */
             goto cleanup;
         }
         if (gray_icc != gray_png) {
             /*Not allowed to use RGB/RGBA/palette with GRAY ICC profile or vice versa,
             or in case of auto_convert, it wasn't possible to find appropriate model*/
             state->error = state->encoder.auto_convert ? 102 : 101;
             goto cleanup;
         }
     }
 #endif /*LODEPNG_COMPILE_ANCILLARY_CHUNKS*/
     if (!lodepng_color_mode_equal(&state->info_raw, &info.color)) {
         unsigned char* converted;
         size_t size = ((size_t)w * (size_t)h * (size_t)lodepng_get_bpp(&info.color) + 7u) / 8u;
         converted = (unsigned char*)lodepng_malloc(size);
         if (!converted && size) state->error = 83; /*alloc fail*/
         if (!state->error) {
             state->error = lodepng_convert(converted, image, &info.color, &state->info_raw, w, h);
         }
         if (!state->error) {
             state->error = preProcessScanlines(&data, &datasize, converted, w, h, &info, &state->encoder);
         }
         lodepng_free(converted);
         if (state->error) goto cleanup;
     }
     else {
         state->error = preProcessScanlines(&data, &datasize, image, w, h, &info, &state->encoder);
         if (state->error) goto cleanup;
     }
     /* output all PNG chunks */ {
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
         size_t i;
 #endif /*LODEPNG_COMPILE_ANCILLARY_CHUNKS*/
         /*write signature and chunks*/
         state->error = writeSignature(&outv);
         if (state->error) goto cleanup;
         /*IHDR*/
         state->error = addChunk_IHDR(&outv, w, h, info.color.colortype, info.color.bitdepth, info.interlace_method);
         if (state->error) goto cleanup;
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
         /*unknown chunks between IHDR and PLTE*/
         if (info.unknown_chunks_data[0]) {
             state->error = addUnknownChunks(&outv, info.unknown_chunks_data[0], info.unknown_chunks_size[0]);
             if (state->error) goto cleanup;
         }
         /*color profile chunks must come before PLTE */
         if (info.iccp_defined) {
             state->error = addChunk_iCCP(&outv, &info, &state->encoder.zlibsettings);
             if (state->error) goto cleanup;
         }
         if (info.srgb_defined) {
             state->error = addChunk_sRGB(&outv, &info);
             if (state->error) goto cleanup;
         }
         if (info.gama_defined) {
             state->error = addChunk_gAMA(&outv, &info);
             if (state->error) goto cleanup;
         }
         if (info.chrm_defined) {
             state->error = addChunk_cHRM(&outv, &info);
             if (state->error) goto cleanup;
         }
 #endif /*LODEPNG_COMPILE_ANCILLARY_CHUNKS*/
         /*PLTE*/
         if (info.color.colortype == LCT_PALETTE) {
             state->error = addChunk_PLTE(&outv, &info.color);
             if (state->error) goto cleanup;
         }
         if (state->encoder.force_palette && (info.color.colortype == LCT_RGB || info.color.colortype == LCT_RGBA)) {
             /*force_palette means: write suggested palette for truecolor in PLTE chunk*/
             state->error = addChunk_PLTE(&outv, &info.color);
             if (state->error) goto cleanup;
         }
         /*tRNS (this will only add if when necessary) */
         state->error = addChunk_tRNS(&outv, &info.color);
         if (state->error) goto cleanup;
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
         /*bKGD (must come between PLTE and the IDAt chunks*/
         if (info.background_defined) {
             state->error = addChunk_bKGD(&outv, &info);
             if (state->error) goto cleanup;
         }
         /*pHYs (must come before the IDAT chunks)*/
         if (info.phys_defined) {
             state->error = addChunk_pHYs(&outv, &info);
             if (state->error) goto cleanup;
         }
         /*unknown chunks between PLTE and IDAT*/
         if (info.unknown_chunks_data[1]) {
             state->error = addUnknownChunks(&outv, info.unknown_chunks_data[1], info.unknown_chunks_size[1]);
             if (state->error) goto cleanup;
         }
 #endif /*LODEPNG_COMPILE_ANCILLARY_CHUNKS*/
         /*IDAT (multiple IDAT chunks must be consecutive)*/
         state->error = addChunk_IDAT(&outv, data, datasize, &state->encoder.zlibsettings);
         if (state->error) goto cleanup;
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
         /*tIME*/
         if (info.time_defined) {
             state->error = addChunk_tIME(&outv, &info.time);
             if (state->error) goto cleanup;
         }
         /*tEXt and/or zTXt*/
         for (i = 0; i != info.text_num; ++i) {
             if (lodepng_strlen(info.text_keys[i]) > 79) {
                 state->error = 66; /*text chunk too large*/
                 goto cleanup;
             }
             if (lodepng_strlen(info.text_keys[i]) < 1) {
                 state->error = 67; /*text chunk too small*/
                 goto cleanup;
             }
             if (state->encoder.text_compression) {
                 state->error = addChunk_zTXt(&outv, info.text_keys[i], info.text_strings[i], &state->encoder.zlibsettings);
                 if (state->error) goto cleanup;
             }
             else {
                 state->error = addChunk_tEXt(&outv, info.text_keys[i], info.text_strings[i]);
                 if (state->error) goto cleanup;
             }
         }
         /*LodePNG version id in text chunk*/
         if (state->encoder.add_id) {
             unsigned already_added_id_text = 0;
             for (i = 0; i != info.text_num; ++i) {
                 const char* k = info.text_keys[i];
                 /* Could use strcmp, but we're not calling or reimplementing this C library function for this use only */
                 if (k[0] == 'L' && k[1] == 'o' && k[2] == 'd' && k[3] == 'e' &&
                     k[4] == 'P' && k[5] == 'N' && k[6] == 'G' && k[7] == '\0') {
                     already_added_id_text = 1;
                     break;
                 }
             }
             if (already_added_id_text == 0) {
                 state->error = addChunk_tEXt(&outv, "LodePNG", LODEPNG_VERSION_STRING); /*it's shorter as tEXt than as zTXt chunk*/
                 if (state->error) goto cleanup;
             }
         }
         /*iTXt*/
         for (i = 0; i != info.itext_num; ++i) {
             if (lodepng_strlen(info.itext_keys[i]) > 79) {
                 state->error = 66; /*text chunk too large*/
                 goto cleanup;
             }
             if (lodepng_strlen(info.itext_keys[i]) < 1) {
                 state->error = 67; /*text chunk too small*/
                 goto cleanup;
             }
             state->error = addChunk_iTXt(
                 &outv, state->encoder.text_compression,
                 info.itext_keys[i], info.itext_langtags[i], info.itext_transkeys[i], info.itext_strings[i],
                 &state->encoder.zlibsettings);
             if (state->error) goto cleanup;
         }
         /*unknown chunks between IDAT and IEND*/
         if (info.unknown_chunks_data[2]) {
             state->error = addUnknownChunks(&outv, info.unknown_chunks_data[2], info.unknown_chunks_size[2]);
             if (state->error) goto cleanup;
         }
 #endif /*LODEPNG_COMPILE_ANCILLARY_CHUNKS*/
         state->error = addChunk_IEND(&outv);
         if (state->error) goto cleanup;
     }
 cleanup:
     lodepng_info_cleanup(&info);
     lodepng_free(data);
     /*instead of cleaning the vector up, give it to the output*/
     *out = outv.data;
     *outsize = outv.size;
     return state->error;
 }
References LodePNGEncoderSettings::add_id, addChunk_bKGD(), addChunk_cHRM(), addChunk_gAMA(), addChunk_iCCP(), addChunk_IDAT(), addChunk_IEND(), addChunk_IHDR(), addChunk_iTXt(), addChunk_pHYs(), addChunk_PLTE(), addChunk_sRGB(), addChunk_tEXt(), addChunk_tIME(), addChunk_tRNS(), addChunk_zTXt(), addUnknownChunks(), LodePNGColorStats::allow_greyscale, LodePNGColorStats::allow_palette, auto_choose_color(), LodePNGEncoderSettings::auto_convert, LodePNGInfo::background_b, LodePNGInfo::background_defined, LodePNGInfo::background_g, LodePNGInfo::background_r, LodePNGColorMode::bitdepth, LodePNGCompressSettings::btype, checkColorValidity(), LodePNGInfo::chrm_defined, LodePNGInfo::color, LodePNGColorMode::colortype, ucvector::data, LodePNGState::encoder, LodePNGState::error, LodePNGEncoderSettings::force_palette, LodePNGInfo::gama_defined, LodePNGInfo::iccp_defined, LodePNGInfo::iccp_profile, LodePNGInfo::iccp_profile_size, LodePNGState::info_png, LodePNGState::info_raw, LodePNGInfo::interlace_method, isGrayICCProfile(), isRGBICCProfile(), LodePNGInfo::itext_keys, LodePNGInfo::itext_langtags, LodePNGInfo::itext_num, LodePNGInfo::itext_strings, LodePNGInfo::itext_transkeys, LCT_GREY, LCT_GREY_ALPHA, LCT_PALETTE, LCT_RGB, LCT_RGBA, lodepng_color_mode_equal(), lodepng_color_mode_make(), lodepng_color_stats_add(), lodepng_color_stats_init(), lodepng_compute_color_stats(), lodepng_convert(), lodepng_convert_rgb(), lodepng_free(), lodepng_get_bpp(), lodepng_info_cleanup(), lodepng_info_copy(), lodepng_info_init(), lodepng_malloc(), lodepng_strlen(), LODEPNG_VERSION_STRING, LodePNGColorMode::palettesize, LodePNGInfo::phys_defined, preProcessScanlines(), ucvector::size, LodePNGInfo::srgb_defined, LodePNGEncoderSettings::text_compression, LodePNGInfo::text_keys, LodePNGInfo::text_num, LodePNGInfo::text_strings, LodePNGInfo::time, LodePNGInfo::time_defined, ucvector_init(), LodePNGInfo::unknown_chunks_data, LodePNGInfo::unknown_chunks_size, writeSignature(), and LodePNGEncoderSettings::zlibsettings.
Referenced by lodepng_encode_memory().
lodepng_encode24()
unsigned lodepng_encode24 (unsigned char ** out, size_t * outsize, const unsigned char * image, unsigned w, unsigned h)
Definition at line 6204 of file lodepng.cpp.
{
     return lodepng_encode_memory(out, outsize, image, w, h, LCT_RGB, 8);
 }
References LCT_RGB, and lodepng_encode_memory().
lodepng_encode24_file()
unsigned lodepng_encode24_file (const char * filename, const unsigned char * image, unsigned w, unsigned h)
Definition at line 6223 of file lodepng.cpp.
{
     return lodepng_encode_file(filename, image, w, h, LCT_RGB, 8);
 }
References LCT_RGB, and lodepng_encode_file().
lodepng_encode32()
unsigned lodepng_encode32 (unsigned char ** out, size_t * outsize, const unsigned char * image, unsigned w, unsigned h)
Definition at line 6200 of file lodepng.cpp.
{
     return lodepng_encode_memory(out, outsize, image, w, h, LCT_RGBA, 8);
 }
References LCT_RGBA, and lodepng_encode_memory().
lodepng_encode32_file()
unsigned lodepng_encode32_file (const char * filename, const unsigned char * image, unsigned w, unsigned h)
Definition at line 6219 of file lodepng.cpp.
{
     return lodepng_encode_file(filename, image, w, h, LCT_RGBA, 8);
 }
References LCT_RGBA, and lodepng_encode_file().
lodepng_encode_file()
unsigned lodepng_encode_file (const char * filename, const unsigned char * image, unsigned w, unsigned h, LodePNGColorType colortype, unsigned bitdepth)
Definition at line 6209 of file lodepng.cpp.
{
     unsigned char* buffer;
     size_t buffersize;
     unsigned error = lodepng_encode_memory(&buffer, &buffersize, image, w, h, colortype, bitdepth);
     if (!error) error = lodepng_save_file(buffer, buffersize, filename);
     lodepng_free(buffer);
     return error;
 }
References lodepng_encode_memory(), lodepng_free(), and lodepng_save_file().
Referenced by lodepng_encode24_file(), and lodepng_encode32_file().
lodepng_encode_memory()
unsigned lodepng_encode_memory (unsigned char ** out, size_t * outsize, const unsigned char * image, unsigned w, unsigned h, LodePNGColorType colortype, unsigned bitdepth)
Definition at line 6185 of file lodepng.cpp.
{
     unsigned error;
     LodePNGState state;
     lodepng_state_init(&state);
     state.info_raw.colortype = colortype;
     state.info_raw.bitdepth = bitdepth;
     state.info_png.color.colortype = colortype;
     state.info_png.color.bitdepth = bitdepth;
     lodepng_encode(out, outsize, image, w, h, &state);
     error = state.error;
     lodepng_state_cleanup(&state);
     return error;
 }
References LodePNGColorMode::bitdepth, LodePNGInfo::color, LodePNGColorMode::colortype, LodePNGState::error, LodePNGState::info_png, LodePNGState::info_raw, lodepng_encode(), lodepng_state_cleanup(), and lodepng_state_init().
Referenced by lodepng_encode24(), lodepng_encode32(), and lodepng_encode_file().
lodepng_encoder_settings_init()
void lodepng_encoder_settings_init (LodePNGEncoderSettings * settings)
Definition at line 6228 of file lodepng.cpp.
{
     lodepng_compress_settings_init(&settings->zlibsettings);
     settings->filter_palette_zero = 1;
     settings->filter_strategy = LFS_MINSUM;
     settings->auto_convert = 1;
     settings->force_palette = 0;
     settings->predefined_filters = 0;
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
     settings->add_id = 0;
     settings->text_compression = 1;
 #endif /*LODEPNG_COMPILE_ANCILLARY_CHUNKS*/
 }
References LodePNGEncoderSettings::add_id, LodePNGEncoderSettings::auto_convert, LodePNGEncoderSettings::filter_palette_zero, LodePNGEncoderSettings::filter_strategy, LodePNGEncoderSettings::force_palette, LFS_MINSUM, lodepng_compress_settings_init(), LodePNGEncoderSettings::predefined_filters, LodePNGEncoderSettings::text_compression, and LodePNGEncoderSettings::zlibsettings.
Referenced by lodepng_state_init().
lodepng_error_text()
const char* lodepng_error_text (unsigned code)
Definition at line 6249 of file lodepng.cpp.
{
     switch (code) {
     case 0: return "no error, everything went ok";
     case 1: return "nothing done yet"; /*the Encoder/Decoder has done nothing yet, error checking makes no sense yet*/
     case 10: return "end of input memory reached without huffman end code"; /*while huffman decoding*/
     case 11: return "error in code tree made it jump outside of huffman tree"; /*while huffman decoding*/
     case 13: return "problem while processing dynamic deflate block";
     case 14: return "problem while processing dynamic deflate block";
     case 15: return "problem while processing dynamic deflate block";
         /*this error could happen if there are only 0 or 1 symbols present in the huffman code:*/
     case 16: return "invalid code while processing dynamic deflate block";
     case 17: return "end of out buffer memory reached while inflating";
     case 18: return "invalid distance code while inflating";
     case 19: return "end of out buffer memory reached while inflating";
     case 20: return "invalid deflate block BTYPE encountered while decoding";
     case 21: return "NLEN is not ones complement of LEN in a deflate block";
         /*end of out buffer memory reached while inflating:
         This can happen if the inflated deflate data is longer than the amount of bytes required to fill up
         all the pixels of the image, given the color depth and image dimensions. Something that doesn't
         happen in a normal, well encoded, PNG image.*/
     case 22: return "end of out buffer memory reached while inflating";
     case 23: return "end of in buffer memory reached while inflating";
     case 24: return "invalid FCHECK in zlib header";
     case 25: return "invalid compression method in zlib header";
     case 26: return "FDICT encountered in zlib header while it's not used for PNG";
     case 27: return "PNG file is smaller than a PNG header";
         /*Checks the magic file header, the first 8 bytes of the PNG file*/
     case 28: return "incorrect PNG signature, it's no PNG or corrupted";
     case 29: return "first chunk is not the header chunk";
     case 30: return "chunk length too large, chunk broken off at end of file";
     case 31: return "illegal PNG color type or bpp";
     case 32: return "illegal PNG compression method";
     case 33: return "illegal PNG filter method";
     case 34: return "illegal PNG interlace method";
     case 35: return "chunk length of a chunk is too large or the chunk too small";
     case 36: return "illegal PNG filter type encountered";
     case 37: return "illegal bit depth for this color type given";
     case 38: return "the palette is too small or too big"; /*0, or more than 256 colors*/
     case 39: return "tRNS chunk before PLTE or has more entries than palette size";
     case 40: return "tRNS chunk has wrong size for grayscale image";
     case 41: return "tRNS chunk has wrong size for RGB image";
     case 42: return "tRNS chunk appeared while it was not allowed for this color type";
     case 43: return "bKGD chunk has wrong size for palette image";
     case 44: return "bKGD chunk has wrong size for grayscale image";
     case 45: return "bKGD chunk has wrong size for RGB image";
     case 48: return "empty input buffer given to decoder. Maybe caused by non-existing file?";
     case 49: return "jumped past memory while generating dynamic huffman tree";
     case 50: return "jumped past memory while generating dynamic huffman tree";
     case 51: return "jumped past memory while inflating huffman block";
     case 52: return "jumped past memory while inflating";
     case 53: return "size of zlib data too small";
     case 54: return "repeat symbol in tree while there was no value symbol yet";
         /*jumped past tree while generating huffman tree, this could be when the
         tree will have more leaves than symbols after generating it out of the
         given lengths. They call this an oversubscribed dynamic bit lengths tree in zlib.*/
     case 55: return "jumped past tree while generating huffman tree";
     case 56: return "given output image colortype or bitdepth not supported for color conversion";
     case 57: return "invalid CRC encountered (checking CRC can be disabled)";
     case 58: return "invalid ADLER32 encountered (checking ADLER32 can be disabled)";
     case 59: return "requested color conversion not supported";
     case 60: return "invalid window size given in the settings of the encoder (must be 0-32768)";
     case 61: return "invalid BTYPE given in the settings of the encoder (only 0, 1 and 2 are allowed)";
         /*LodePNG leaves the choice of RGB to grayscale conversion formula to the user.*/
     case 62: return "conversion from color to grayscale not supported";
         /*(2^31-1)*/
     case 63: return "length of a chunk too long, max allowed for PNG is 2147483647 bytes per chunk";
         /*this would result in the inability of a deflated block to ever contain an end code. It must be at least 1.*/
     case 64: return "the length of the END symbol 256 in the Huffman tree is 0";
     case 66: return "the length of a text chunk keyword given to the encoder is longer than the maximum of 79 bytes";
     case 67: return "the length of a text chunk keyword given to the encoder is smaller than the minimum of 1 byte";
     case 68: return "tried to encode a PLTE chunk with a palette that has less than 1 or more than 256 colors";
     case 69: return "unknown chunk type with 'critical' flag encountered by the decoder";
     case 71: return "invalid interlace mode given to encoder (must be 0 or 1)";
     case 72: return "while decoding, invalid compression method encountering in zTXt or iTXt chunk (it must be 0)";
     case 73: return "invalid tIME chunk size";
     case 74: return "invalid pHYs chunk size";
         /*length could be wrong, or data chopped off*/
     case 75: return "no null termination char found while decoding text chunk";
     case 76: return "iTXt chunk too short to contain required bytes";
     case 77: return "integer overflow in buffer size";
     case 78: return "failed to open file for reading"; /*file doesn't exist or couldn't be opened for reading*/
     case 79: return "failed to open file for writing";
     case 80: return "tried creating a tree of 0 symbols";
     case 81: return "lazy matching at pos 0 is impossible";
     case 82: return "color conversion to palette requested while a color isn't in palette, or index out of bounds";
     case 83: return "memory allocation failed";
     case 84: return "given image too small to contain all pixels to be encoded";
     case 86: return "impossible offset in lz77 encoding (internal bug)";
     case 87: return "must provide custom zlib function pointer if LODEPNG_COMPILE_ZLIB is not defined";
     case 88: return "invalid filter strategy given for LodePNGEncoderSettings.filter_strategy";
     case 89: return "text chunk keyword too short or long: must have size 1-79";
         /*the windowsize in the LodePNGCompressSettings. Requiring POT(==> & instead of %) makes encoding 12% faster.*/
     case 90: return "windowsize must be a power of two";
     case 91: return "invalid decompressed idat size";
     case 92: return "integer overflow due to too many pixels";
     case 93: return "zero width or height is invalid";
     case 94: return "header chunk must have a size of 13 bytes";
     case 95: return "integer overflow with combined idat chunk size";
     case 96: return "invalid gAMA chunk size";
     case 97: return "invalid cHRM chunk size";
     case 98: return "invalid sRGB chunk size";
     case 99: return "invalid sRGB rendering intent";
     case 100: return "invalid ICC profile color type, the PNG specification only allows RGB or GRAY";
     case 101: return "PNG specification does not allow RGB ICC profile on gray color types and vice versa";
     case 102: return "not allowed to set grayscale ICC profile with colored pixels by PNG specification";
     case 103: return "invalid palette index in bKGD chunk. Maybe it came before PLTE chunk?";
     case 104: return "invalid bKGD color while encoding (e.g. palette index out of range)";
     case 105: return "integer overflow of bitsize";
     case 106: return "PNG file must have PLTE chunk if color type is palette";
     case 107: return "color convert from palette mode requested without setting the palette data in it";
     case 108: return "tried to add more than 256 values to a palette";
     }
     return "unknown error code";
 }
Referenced by TexturedPolygons::LoadTexture().
lodepng_get_bpp()
unsigned lodepng_get_bpp (const LodePNGColorMode * info)
Definition at line 2775 of file lodepng.cpp.
{
     return lodepng_get_bpp_lct(info->colortype, info->bitdepth);
 }
References LodePNGColorMode::bitdepth, LodePNGColorMode::colortype, and lodepng_get_bpp_lct().
Referenced by decodeGeneric(), filter(), lodepng_compute_color_stats(), lodepng_encode(), lodepng_pixel_overflow(), postProcessScanlines(), and preProcessScanlines().
lodepng_get_channels()
unsigned lodepng_get_channels (const LodePNGColorMode * info)
Definition at line 2779 of file lodepng.cpp.
{
     return getNumColorChannels(info->colortype);
 }
References LodePNGColorMode::colortype, and getNumColorChannels().
lodepng_get_raw_size()
size_t lodepng_get_raw_size (unsigned w, unsigned h, const LodePNGColorMode * color)
Definition at line 2815 of file lodepng.cpp.
{
     return lodepng_get_raw_size_lct(w, h, color->colortype, color->bitdepth);
 }
References LodePNGColorMode::bitdepth, LodePNGColorMode::colortype, and lodepng_get_raw_size_lct().
Referenced by decodeGeneric(), lodepng_convert(), and lodepng_decode().
lodepng_has_palette_alpha()
unsigned lodepng_has_palette_alpha (const LodePNGColorMode * info)
Definition at line 2795 of file lodepng.cpp.
{
     size_t i;
     for (i = 0; i != info->palettesize; ++i) {
         if (info->palette[i * 4 + 3] < 255) return 1;
     }
     return 0;
 }
References LodePNGColorMode::palette, and LodePNGColorMode::palettesize.
Referenced by lodepng_can_have_alpha().
lodepng_huffman_code_lengths()
unsigned lodepng_huffman_code_lengths (unsigned * lengths, const unsigned * frequencies, size_t numcodes, unsigned maxbitlen)
Definition at line 974 of file lodepng.cpp.
{
     unsigned error = 0;
     unsigned i;
     size_t numpresent = 0; /*number of symbols with non-zero frequency*/
     BPMNode* leaves; /*the symbols, only those with > 0 frequency*/
     if (numcodes == 0) return 80; /*error: a tree of 0 symbols is not supposed to be made*/
     if ((1u << maxbitlen) < (unsigned)numcodes) return 80; /*error: represent all symbols*/
     leaves = (BPMNode*)lodepng_malloc(numcodes * sizeof(*leaves));
     if (!leaves) return 83; /*alloc fail*/
     for (i = 0; i != numcodes; ++i) {
         if (frequencies[i] > 0) {
             leaves[numpresent].weight = (int)frequencies[i];
             leaves[numpresent].index = i;
             ++numpresent;
         }
     }
     lodepng_memset(lengths, 0, numcodes * sizeof(*lengths));
     /*ensure at least two present symbols. There should be at least one symbol
     according to RFC 1951 section 3.2.7. Some decoders incorrectly require two. To
     make these work as well ensure there are at least two symbols. The
     Package-Merge code below also doesn't work correctly if there's only one
     symbol, it'd give it the theoretical 0 bits but in practice zlib wants 1 bit*/
     if (numpresent == 0) {
         lengths[0] = lengths[1] = 1; /*note that for RFC 1951 section 3.2.7, only lengths[0] = 1 is needed*/
     }
     else if (numpresent == 1) {
         lengths[leaves[0].index] = 1;
         lengths[leaves[0].index == 0 ? 1 : 0] = 1;
     }
     else {
         BPMLists lists;
         BPMNode* node;
         bpmnode_sort(leaves, numpresent);
         lists.listsize = maxbitlen;
         lists.memsize = 2 * maxbitlen * (maxbitlen + 1);
         lists.nextfree = 0;
         lists.numfree = lists.memsize;
         lists.memory = (BPMNode*)lodepng_malloc(lists.memsize * sizeof(*lists.memory));
         lists.freelist = (BPMNode**)lodepng_malloc(lists.memsize * sizeof(BPMNode*));
         lists.chains0 = (BPMNode**)lodepng_malloc(lists.listsize * sizeof(BPMNode*));
         lists.chains1 = (BPMNode**)lodepng_malloc(lists.listsize * sizeof(BPMNode*));
         if (!lists.memory || !lists.freelist || !lists.chains0 || !lists.chains1) error = 83; /*alloc fail*/
         if (!error) {
             for (i = 0; i != lists.memsize; ++i) lists.freelist[i] = &lists.memory[i];
             bpmnode_create(&lists, leaves[0].weight, 1, 0);
             bpmnode_create(&lists, leaves[1].weight, 2, 0);
             for (i = 0; i != lists.listsize; ++i) {
                 lists.chains0[i] = &lists.memory[0];
                 lists.chains1[i] = &lists.memory[1];
             }
             /*each boundaryPM call adds one chain to the last list, and we need 2 * numpresent - 2 chains.*/
             for (i = 2; i != 2 * numpresent - 2; ++i) boundaryPM(&lists, leaves, numpresent, (int)maxbitlen - 1, (int)i);
             for (node = lists.chains1[maxbitlen - 1]; node; node = node->tail) {
                 for (i = 0; i != node->index; ++i) ++lengths[leaves[i].index];
             }
         }
         lodepng_free(lists.memory);
         lodepng_free(lists.freelist);
         lodepng_free(lists.chains0);
         lodepng_free(lists.chains1);
     }
     lodepng_free(leaves);
     return error;
 }
References boundaryPM(), bpmnode_create(), bpmnode_sort(), BPMLists::chains0, BPMLists::chains1, BPMLists::freelist, BPMNode::index, BPMLists::listsize, lodepng_free(), lodepng_malloc(), lodepng_memset(), BPMLists::memory, BPMLists::memsize, BPMLists::nextfree, BPMLists::numfree, BPMNode::tail, and BPMNode::weight.
Referenced by HuffmanTree_makeFromFrequencies().
lodepng_inflate()
unsigned lodepng_inflate (unsigned char ** out, size_t * outsize, const unsigned char * in, size_t insize, const LodePNGDecompressSettings * settings)
Definition at line 1429 of file lodepng.cpp.
{
     ucvector v = ucvector_init(*out, *outsize);
     unsigned error = lodepng_inflatev(&v, in, insize, settings);
     *out = v.data;
     *outsize = v.size;
     return error;
 }
References ucvector::data, lodepng_inflatev(), ucvector::size, and ucvector_init().
lodepng_info_cleanup()
void lodepng_info_cleanup (LodePNGInfo * info)
Definition at line 3075 of file lodepng.cpp.
{
     lodepng_color_mode_cleanup(&info->color);
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
     LodePNGText_cleanup(info);
     LodePNGIText_cleanup(info);
     lodepng_clear_icc(info);
     LodePNGUnknownChunks_cleanup(info);
 #endif /*LODEPNG_COMPILE_ANCILLARY_CHUNKS*/
 }
References LodePNGInfo::color, lodepng_clear_icc(), lodepng_color_mode_cleanup(), LodePNGIText_cleanup(), LodePNGText_cleanup(), and LodePNGUnknownChunks_cleanup().
Referenced by lodepng_encode(), lodepng_info_copy(), lodepng_inspect(), and lodepng_state_cleanup().
lodepng_info_copy()
unsigned lodepng_info_copy (LodePNGInfo * dest, const LodePNGInfo * source)
Definition at line 3087 of file lodepng.cpp.
{
     lodepng_info_cleanup(dest);
     lodepng_memcpy(dest, source, sizeof(LodePNGInfo));
     lodepng_color_mode_init(&dest->color);
     CERROR_TRY_RETURN(lodepng_color_mode_copy(&dest->color, &source->color));
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
     CERROR_TRY_RETURN(LodePNGText_copy(dest, source));
     CERROR_TRY_RETURN(LodePNGIText_copy(dest, source));
     if (source->iccp_defined) {
         CERROR_TRY_RETURN(lodepng_assign_icc(dest, source->iccp_name, source->iccp_profile, source->iccp_profile_size));
     }
     LodePNGUnknownChunks_init(dest);
     CERROR_TRY_RETURN(LodePNGUnknownChunks_copy(dest, source));
 #endif /*LODEPNG_COMPILE_ANCILLARY_CHUNKS*/
     return 0;
 }
References LodePNGInfo::color, LodePNGInfo::iccp_defined, LodePNGInfo::iccp_name, LodePNGInfo::iccp_profile, LodePNGInfo::iccp_profile_size, lodepng_assign_icc(), lodepng_color_mode_copy(), lodepng_color_mode_init(), lodepng_info_cleanup(), lodepng_memcpy(), LodePNGIText_copy(), LodePNGText_copy(), LodePNGUnknownChunks_copy(), and LodePNGUnknownChunks_init().
Referenced by lodepng_encode(), and lodepng_state_copy().
lodepng_info_init()
void lodepng_info_init (LodePNGInfo * info)
Definition at line 3049 of file lodepng.cpp.
{
     lodepng_color_mode_init(&info->color);
     info->interlace_method = 0;
     info->compression_method = 0;
     info->filter_method = 0;
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
     info->background_defined = 0;
     info->background_r = info->background_g = info->background_b = 0;
     LodePNGText_init(info);
     LodePNGIText_init(info);
     info->time_defined = 0;
     info->phys_defined = 0;
     info->gama_defined = 0;
     info->chrm_defined = 0;
     info->srgb_defined = 0;
     info->iccp_defined = 0;
     info->iccp_name = NULL;
     info->iccp_profile = NULL;
     LodePNGUnknownChunks_init(info);
 #endif /*LODEPNG_COMPILE_ANCILLARY_CHUNKS*/
 }
References LodePNGInfo::background_b, LodePNGInfo::background_defined, LodePNGInfo::background_g, LodePNGInfo::background_r, LodePNGInfo::chrm_defined, LodePNGInfo::color, LodePNGInfo::compression_method, LodePNGInfo::filter_method, LodePNGInfo::gama_defined, LodePNGInfo::iccp_defined, LodePNGInfo::iccp_name, LodePNGInfo::iccp_profile, LodePNGInfo::interlace_method, lodepng_color_mode_init(), LodePNGIText_init(), LodePNGText_init(), LodePNGUnknownChunks_init(), LodePNGInfo::phys_defined, LodePNGInfo::srgb_defined, and LodePNGInfo::time_defined.
Referenced by lodepng_encode(), lodepng_inspect(), lodepng_state_copy(), and lodepng_state_init().
lodepng_inspect()
unsigned lodepng_inspect (unsigned * w, unsigned * h, LodePNGState * state, const unsigned char * in, size_t insize)
Definition at line 4111 of file lodepng.cpp.
{
     unsigned width, height;
     LodePNGInfo* info = &state->info_png;
     if (insize == 0 || in == 0) {
         CERROR_RETURN_ERROR(state->error, 48); /*error: the given data is empty*/
     }
     if (insize < 33) {
         CERROR_RETURN_ERROR(state->error, 27); /*error: the data length is smaller than the length of a PNG header*/
     }
     /*when decoding a new PNG image, make sure all parameters created after previous decoding are reset*/
     /* TODO: remove this. One should use a new LodePNGState for new sessions */
     lodepng_info_cleanup(info);
     lodepng_info_init(info);
     if (in[0] != 137 || in[1] != 80 || in[2] != 78 || in[3] != 71
         || in[4] != 13 || in[5] != 10 || in[6] != 26 || in[7] != 10) {
         CERROR_RETURN_ERROR(state->error, 28); /*error: the first 8 bytes are not the correct PNG signature*/
     }
     if (lodepng_chunk_length(in + 8) != 13) {
         CERROR_RETURN_ERROR(state->error, 94); /*error: header size must be 13 bytes*/
     }
     if (!lodepng_chunk_type_equals(in + 8, "IHDR")) {
         CERROR_RETURN_ERROR(state->error, 29); /*error: it doesn't start with a IHDR chunk!*/
     }
     /*read the values given in the header*/
     width = lodepng_read32bitInt(&in[16]);
     height = lodepng_read32bitInt(&in[20]);
     /*TODO: remove the undocumented feature that allows to give null pointers to width or height*/
     if (w) *w = width;
     if (h) *h = height;
     info->color.bitdepth = in[24];
     info->color.colortype = (LodePNGColorType)in[25];
     info->compression_method = in[26];
     info->filter_method = in[27];
     info->interlace_method = in[28];
     /*errors returned only after the parsing so other values are still output*/
     /*error: invalid image size*/
     if (width == 0 || height == 0) CERROR_RETURN_ERROR(state->error, 93);
     /*error: invalid colortype or bitdepth combination*/
     state->error = checkColorValidity(info->color.colortype, info->color.bitdepth);
     if (state->error) return state->error;
     /*error: only compression method 0 is allowed in the specification*/
     if (info->compression_method != 0) CERROR_RETURN_ERROR(state->error, 32);
     /*error: only filter method 0 is allowed in the specification*/
     if (info->filter_method != 0) CERROR_RETURN_ERROR(state->error, 33);
     /*error: only interlace methods 0 and 1 exist in the specification*/
     if (info->interlace_method > 1) CERROR_RETURN_ERROR(state->error, 34);
     if (!state->decoder.ignore_crc) {
         unsigned CRC = lodepng_read32bitInt(&in[29]);
         unsigned checksum = lodepng_crc32(&in[12], 17);
         if (CRC != checksum) {
             CERROR_RETURN_ERROR(state->error, 57); /*invalid CRC*/
         }
     }
     return state->error;
 }
References LodePNGColorMode::bitdepth, checkColorValidity(), LodePNGInfo::color, LodePNGColorMode::colortype, LodePNGInfo::compression_method, LodePNGState::decoder, LodePNGState::error, LodePNGInfo::filter_method, LodePNGDecoderSettings::ignore_crc, LodePNGState::info_png, LodePNGInfo::interlace_method, lodepng_chunk_length(), lodepng_chunk_type_equals(), lodepng_crc32(), lodepng_info_cleanup(), lodepng_info_init(), and lodepng_read32bitInt().
Referenced by decodeGeneric().
lodepng_inspect_chunk()
unsigned lodepng_inspect_chunk (LodePNGState * state, size_t pos, const unsigned char * in, size_t insize)
Definition at line 4774 of file lodepng.cpp.
{
     const unsigned char* chunk = in + pos;
     unsigned chunkLength;
     const unsigned char* data;
     unsigned unhandled = 0;
     unsigned error = 0;
     if (pos + 4 > insize) return 30;
     chunkLength = lodepng_chunk_length(chunk);
     if (chunkLength > 2147483647) return 63;
     data = lodepng_chunk_data_const(chunk);
     if (data + chunkLength + 4 > in + insize) return 30;
     if (lodepng_chunk_type_equals(chunk, "PLTE")) {
         error = readChunk_PLTE(&state->info_png.color, data, chunkLength);
     }
     else if (lodepng_chunk_type_equals(chunk, "tRNS")) {
         error = readChunk_tRNS(&state->info_png.color, data, chunkLength);
 #ifdef LODEPNG_COMPILE_ANCILLARY_CHUNKS
     }
     else if (lodepng_chunk_type_equals(chunk, "bKGD")) {
         error = readChunk_bKGD(&state->info_png, data, chunkLength);
     }
     else if (lodepng_chunk_type_equals(chunk, "tEXt")) {
         error = readChunk_tEXt(&state->info_png, data, chunkLength);
     }
     else if (lodepng_chunk_type_equals(chunk, "zTXt")) {
         error = readChunk_zTXt(&state->info_png, &state->decoder.zlibsettings, data, chunkLength);
     }
     else if (lodepng_chunk_type_equals(chunk, "iTXt")) {
         error = readChunk_iTXt(&state->info_png, &state->decoder.zlibsettings, data, chunkLength);
     }
     else if (lodepng_chunk_type_equals(chunk, "tIME")) {
         error = readChunk_tIME(&state->info_png, data, chunkLength);
     }
     else if (lodepng_chunk_type_equals(chunk, "pHYs")) {
         error = readChunk_pHYs(&state->info_png, data, chunkLength);
     }
     else if (lodepng_chunk_type_equals(chunk, "gAMA")) {
         error = readChunk_gAMA(&state->info_png, data, chunkLength);
     }
     else if (lodepng_chunk_type_equals(chunk, "cHRM")) {
         error = readChunk_cHRM(&state->info_png, data, chunkLength);
     }
     else if (lodepng_chunk_type_equals(chunk, "sRGB")) {
         error = readChunk_sRGB(&state->info_png, data, chunkLength);
     }
     else if (lodepng_chunk_type_equals(chunk, "iCCP")) {
         error = readChunk_iCCP(&state->info_png, &state->decoder.zlibsettings, data, chunkLength);
 #endif /*LODEPNG_COMPILE_ANCILLARY_CHUNKS*/
     }
     else {
         /* unhandled chunk is ok (is not an error) */
         unhandled = 1;
     }
     if (!error && !unhandled && !state->decoder.ignore_crc) {
         if (lodepng_chunk_check_crc(chunk)) return 57; /*invalid CRC*/
     }
     return error;
 }
References LodePNGInfo::color, LodePNGState::decoder, LodePNGDecoderSettings::ignore_crc, LodePNGState::info_png, lodepng_chunk_check_crc(), lodepng_chunk_data_const(), lodepng_chunk_length(), lodepng_chunk_type_equals(), readChunk_bKGD(), readChunk_cHRM(), readChunk_gAMA(), readChunk_iCCP(), readChunk_iTXt(), readChunk_pHYs(), readChunk_PLTE(), readChunk_sRGB(), readChunk_tEXt(), readChunk_tIME(), readChunk_tRNS(), readChunk_zTXt(), and LodePNGDecoderSettings::zlibsettings.
lodepng_is_alpha_type()
unsigned lodepng_is_alpha_type (const LodePNGColorMode * info)
Definition at line 2787 of file lodepng.cpp.
{
     return (info->colortype & 4) != 0; /*4 or 6*/
 }
References LodePNGColorMode::colortype.
Referenced by lodepng_can_have_alpha().
lodepng_is_greyscale_type()
unsigned lodepng_is_greyscale_type (const LodePNGColorMode * info)
Definition at line 2783 of file lodepng.cpp.
{
     return info->colortype == LCT_GREY || info->colortype == LCT_GREY_ALPHA;
 }
References LodePNGColorMode::colortype, LCT_GREY, and LCT_GREY_ALPHA.
Referenced by lodepng_compute_color_stats().
lodepng_is_palette_type()
unsigned lodepng_is_palette_type (const LodePNGColorMode * info)
Definition at line 2791 of file lodepng.cpp.
{
     return info->colortype == LCT_PALETTE;
 }
References LodePNGColorMode::colortype, and LCT_PALETTE.
lodepng_load_file()
unsigned lodepng_load_file (unsigned char ** out, size_t * outsize, const char * filename)
Definition at line 377 of file lodepng.cpp.
{
     long size = lodepng_filesize(filename);
     if (size < 0) return 78;
     *outsize = (size_t)size;
     *out = (unsigned char*)lodepng_malloc((size_t)size);
     if (!(*out) && size > 0) return 83; /*the above malloc failed*/
     return lodepng_buffer_file(*out, (size_t)size, filename);
 }
References lodepng_buffer_file(), lodepng_filesize(), and lodepng_malloc().
Referenced by lodepng_decode_file().
lodepng_palette_add()
unsigned lodepng_palette_add (LodePNGColorMode * info, unsigned char r, unsigned char g, unsigned char b, unsigned char a)
Definition at line 2757 of file lodepng.cpp.
{
     if (!info->palette) /*allocate palette if empty*/ {
         lodepng_color_mode_alloc_palette(info);
         if (!info->palette) return 83; /*alloc fail*/
     }
     if (info->palettesize >= 256) {
         return 108; /*too many palette values*/
     }
     info->palette[4 * info->palettesize + 0] = r;
     info->palette[4 * info->palettesize + 1] = g;
     info->palette[4 * info->palettesize + 2] = b;
     info->palette[4 * info->palettesize + 3] = a;
     ++info->palettesize;
     return 0;
 }
References lodepng_color_mode_alloc_palette(), LodePNGColorMode::palette, and LodePNGColorMode::palettesize.
Referenced by auto_choose_color().
lodepng_palette_clear()
void lodepng_palette_clear (LodePNGColorMode * info)
Definition at line 2751 of file lodepng.cpp.
{
     if (info->palette) lodepng_free(info->palette);
     info->palette = 0;
     info->palettesize = 0;
 }
References lodepng_free(), LodePNGColorMode::palette, and LodePNGColorMode::palettesize.
Referenced by auto_choose_color(), and lodepng_color_mode_cleanup().
lodepng_save_file()
unsigned lodepng_save_file (const unsigned char * buffer, size_t buffersize, const char * filename)
Definition at line 389 of file lodepng.cpp.
{
     FILE* file;
     file = fopen(filename, "wb");
     if (!file) return 79;
     fwrite(buffer, 1, buffersize, file);
     fclose(file);
     return 0;
 }
Referenced by lodepng_encode_file().
lodepng_set_icc()
unsigned lodepng_set_icc (LodePNGInfo * info, const char * name, const unsigned char * profile, unsigned profile_size)
Definition at line 3033 of file lodepng.cpp.
{
     if (info->iccp_name) lodepng_clear_icc(info);
     info->iccp_defined = 1;
     return lodepng_assign_icc(info, name, profile, profile_size);
 }
References LodePNGInfo::iccp_defined, LodePNGInfo::iccp_name, lodepng_assign_icc(), and lodepng_clear_icc().
lodepng_state_cleanup()
void lodepng_state_cleanup (LodePNGState * state)
Definition at line 5158 of file lodepng.cpp.
{
     lodepng_color_mode_cleanup(&state->info_raw);
     lodepng_info_cleanup(&state->info_png);
 }
References LodePNGState::info_png, LodePNGState::info_raw, lodepng_color_mode_cleanup(), and lodepng_info_cleanup().
Referenced by lodepng_decode_memory(), lodepng_encode_memory(), and lodepng_state_copy().
lodepng_state_copy()
void lodepng_state_copy (LodePNGState * dest, const LodePNGState * source)
Definition at line 5163 of file lodepng.cpp.
{
     lodepng_state_cleanup(dest);
     *dest = *source;
     lodepng_color_mode_init(&dest->info_raw);
     lodepng_info_init(&dest->info_png);
     dest->error = lodepng_color_mode_copy(&dest->info_raw, &source->info_raw); if (dest->error) return;
     dest->error = lodepng_info_copy(&dest->info_png, &source->info_png); if (dest->error) return;
 }
References LodePNGState::error, LodePNGState::info_png, LodePNGState::info_raw, lodepng_color_mode_copy(), lodepng_color_mode_init(), lodepng_info_copy(), lodepng_info_init(), and lodepng_state_cleanup().
lodepng_state_init()
void lodepng_state_init (LodePNGState * state)
Definition at line 5146 of file lodepng.cpp.
{
 #ifdef LODEPNG_COMPILE_DECODER
     lodepng_decoder_settings_init(&state->decoder);
 #endif /*LODEPNG_COMPILE_DECODER*/
 #ifdef LODEPNG_COMPILE_ENCODER
     lodepng_encoder_settings_init(&state->encoder);
 #endif /*LODEPNG_COMPILE_ENCODER*/
     lodepng_color_mode_init(&state->info_raw);
     lodepng_info_init(&state->info_png);
     state->error = 1;
 }
References LodePNGState::decoder, LodePNGState::encoder, LodePNGState::error, LodePNGState::info_png, LodePNGState::info_raw, lodepng_color_mode_init(), lodepng_decoder_settings_init(), lodepng_encoder_settings_init(), and lodepng_info_init().
Referenced by lodepng_decode_memory(), and lodepng_encode_memory().
lodepng_zlib_compress()
unsigned lodepng_zlib_compress (unsigned char ** out, size_t * outsize, const unsigned char * in, size_t insize, const LodePNGCompressSettings * settings)
Definition at line 2272 of file lodepng.cpp.
{
     size_t i;
     unsigned error;
     unsigned char* deflatedata = 0;
     size_t deflatesize = 0;
     error = deflate(&deflatedata, &deflatesize, in, insize, settings);
     *out = NULL;
     *outsize = 0;
     if (!error) {
         *outsize = deflatesize + 6;
         *out = (unsigned char*)lodepng_malloc(*outsize);
         if (!*out) error = 83; /*alloc fail*/
     }
     if (!error) {
         unsigned ADLER32 = adler32(in, (unsigned)insize);
         /*zlib data: 1 byte CMF (CM+CINFO), 1 byte FLG, deflate data, 4 byte ADLER32 checksum of the Decompressed data*/
         unsigned CMF = 120; /*0b01111000: CM 8, CINFO 7. With CINFO 7, any window size up to 32768 can be used.*/
         unsigned FLEVEL = 0;
         unsigned FDICT = 0;
         unsigned CMFFLG = 256 * CMF + FDICT * 32 + FLEVEL * 64;
         unsigned FCHECK = 31 - CMFFLG % 31;
         CMFFLG += FCHECK;
         (*out)[0] = (unsigned char)(CMFFLG >> 8);
         (*out)[1] = (unsigned char)(CMFFLG & 255);
         for (i = 0; i != deflatesize; ++i) (*out)[i + 2] = deflatedata[i];
         lodepng_set32bitInt(&(*out)[*outsize - 4], ADLER32);
     }
     lodepng_free(deflatedata);
     return error;
 }
References adler32(), deflate(), lodepng_free(), lodepng_malloc(), and lodepng_set32bitInt().
Referenced by zlib_compress().
lodepng_zlib_decompress()
unsigned lodepng_zlib_decompress (unsigned char ** out, size_t * outsize, const unsigned char * in, size_t insize, const LodePNGDecompressSettings * settings)
Definition at line 2238 of file lodepng.cpp.
{
     ucvector v = ucvector_init(*out, *outsize);
     unsigned error = lodepng_zlib_decompressv(&v, in, insize, settings);
     *out = v.data;
     *outsize = v.size;
     return error;
 }
References ucvector::data, lodepng_zlib_decompressv(), ucvector::size, and ucvector_init().
Variable Documentation
lodepng_default_compress_settings
const LodePNGCompressSettings lodepng_default_compress_settings
Definition at line 2363 of file lodepng.cpp.
lodepng_default_decompress_settings
const LodePNGDecompressSettings lodepng_default_decompress_settings
Definition at line 2379 of file lodepng.cpp.
LODEPNG_VERSION_STRING
const char* LODEPNG_VERSION_STRING
Definition at line 47 of file lodepng.cpp.
Referenced by lodepng_encode().