ICT290 Assignment 1: C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/main.cpp File Reference
main.cpp File Reference
#include <math.h>
#include <GL/glut.h>
#include <time.h>
#include "camera.h"
#include "texturedPolygons.h"
#include "Portal.h"
#include "DisplayShaysWorld.h"
#include "displayWrathWorld.h"
Macros
#define PI 3.1415962654
Functions
void initKeyStates ()
void keyPressed (unsigned char, int x, int y)
void releaseKey (unsigned char key, int x, int y)
void processKeys ()
void Mouse (int button, int state, int x, int y)
void mouseMove (int x, int y)
void Display ()
void reshape (int w, int h)
void IncrementFrameCount ()
int main (int argc, char **argv)
Variables
DisplayShaysWorld shaysWorld
DisplayWrathWorld wrathWorld
GLdouble movementSpeed = 15.0
GLdouble xrotationSpeed = 0.0015
GLdouble yrotationSpeed = 0.0012
GLdouble stepIncrement
GLdouble angleIncrement
int frameCount = 0
clock_t lastClock = 0
float ratio
int width
int height
bool * keyStates = new bool[256]
bool isShaysWorld = true
Macro Definition Documentation
PI
#define PI 3.1415962654
Definition at line 19 of file main.cpp.
Function Documentation
Display()
void Display ()
Definition at line 90 of file main.cpp.
 {
     processKeys();
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     // DISPLAY TEXTURES
     //enable texture mapping
     glEnable(GL_TEXTURE_2D);
     glPushMatrix();
     // displays the welcome screen
     if (shaysWorld.DisplayWelcome && isShaysWorld) shaysWorld.cam.DisplayWelcomeScreen(width, height, 1, shaysWorld.tp.GetTexture(WELCOME));
     if (wrathWorld.DisplayWelcome && !isShaysWorld) wrathWorld.cam.DisplayWelcomeScreen(width, height, 1, wrathWorld.tp.GetTexture(WELCOME_SCREEN));
     // displays the exit screen
     // displays the exit screen
     if (shaysWorld.DisplayExit) shaysWorld.cam.DisplayWelcomeScreen(width, height, 0, shaysWorld.tp.GetTexture(EXIT));
     if (wrathWorld.DisplayExit) wrathWorld.cam.DisplayWelcomeScreen(width, height, 0, wrathWorld.tp.GetTexture(EXIT_SCREEN));
     if (isShaysWorld)
     {
         shaysWorld.cam.CheckCamera();
         // set the movement and rotation speed accordiwng to frame count
         IncrementFrameCount();
         shaysWorld.cam.SetMoveSpeed(stepIncrement);
         if (shaysWorld.stairsPortal())
         {
             isShaysWorld = false;
             wrathWorld.myinit();
         }
         shaysWorld.stairsReturnPortal();
         shaysWorld.specialPortal();
         // displays the map
         if (shaysWorld.DisplayMap) shaysWorld.cam.DisplayMap(width, height, shaysWorld.tp.GetTexture(MAP));
         // display no exit sign (position check should really be in an object, but didn't have time)
         if ((shaysWorld.cam.GetLR() > 35500.0) && (shaysWorld.cam.GetFB() < 25344.0) ||
             (shaysWorld.cam.GetLR() > 34100.0) && (shaysWorld.cam.GetFB() > 41127.0))
         {
             shaysWorld.cam.DisplayNoExit(width, height, shaysWorld.tp.GetTexture(NO_EXIT));
         }
         // print postion to assist development
         shaysWorld.cam.printPosition();
         // display images
         shaysWorld.DrawBackdrop();
         glPopMatrix();
         glDisable(GL_TEXTURE_2D);
     }
     if(!isShaysWorld)
     {
         wrathWorld.cam.CheckCamera();
         // set the movement and rotation speed according to frame count
         IncrementFrameCount();
         wrathWorld.cam.SetMoveSpeed(stepIncrement);
         if (wrathWorld.stairsReturnPortal())
         {
             isShaysWorld = true;
             shaysWorld.myinit();
             shaysWorld.cam.Position(1400, 11234, 39740, 0);
         }
         // print postion to assist development
         wrathWorld.cam.printPosition();
         // display images
         wrathWorld.DrawBackdrop();
         glPopMatrix();
         glDisable(GL_TEXTURE_2D);
     }
     // clear buffers
     glFlush();
     glutSwapBuffers();
 }
References DisplayWrathWorld::cam, DisplayShaysWorld::cam, Camera::CheckCamera(), DisplayWrathWorld::DisplayExit, DisplayShaysWorld::DisplayExit, Camera::DisplayMap(), DisplayShaysWorld::DisplayMap, Camera::DisplayNoExit(), DisplayWrathWorld::DisplayWelcome, DisplayShaysWorld::DisplayWelcome, Camera::DisplayWelcomeScreen(), DisplayWrathWorld::DrawBackdrop(), DisplayShaysWorld::DrawBackdrop(), Camera::GetFB(), Camera::GetLR(), TexturedPolygons::GetTexture(), glClear(), glDisable(), glEnable(), glFlush(), glPopMatrix(), glPushMatrix(), glutSwapBuffers(), height, IncrementFrameCount(), isShaysWorld, DisplayWrathWorld::myinit(), DisplayShaysWorld::myinit(), Camera::Position(), Camera::printPosition(), processKeys(), Camera::SetMoveSpeed(), shaysWorld, DisplayShaysWorld::specialPortal(), DisplayShaysWorld::stairsPortal(), DisplayWrathWorld::stairsReturnPortal(), DisplayShaysWorld::stairsReturnPortal(), stepIncrement, DisplayWrathWorld::tp, DisplayShaysWorld::tp, width, and wrathWorld.
Referenced by main().
IncrementFrameCount()
void IncrementFrameCount ()
Definition at line 373 of file main.cpp.
 {
     double t = ((GLdouble)(clock()-lastClock))/(GLdouble)CLOCKS_PER_SEC;
     frameCount ++;
     // reset after t
     if (t > 0.1)
     {
         stepIncrement = t/frameCount * 1400;
         angleIncrement = t/frameCount;
         frameCount = 0;
         lastClock = clock();
     }
 }
References angleIncrement, frameCount, lastClock, and stepIncrement.
Referenced by Display().
initKeyStates()
void initKeyStates ()
Definition at line 188 of file main.cpp.
 {
     for (int i = 0; i < 256; i++)
         keyStates[i] = false;
 }
References keyStates.
Referenced by main().
keyPressed()
void keyPressed (unsigned char key, int x, int y)
Definition at line 194 of file main.cpp.
 {
     keyStates[key] = true;  //set keystate to pressed
     // display welcome page (space key)
     if (key == ' ' && isShaysWorld)
     {
         if (shaysWorld.DisplayWelcome)      //if info screen is up don't allow player to look around
         {
             shaysWorld.cam.SetXRotateSpeed(xrotationSpeed);
             shaysWorld.cam.SetYRotateSpeed(yrotationSpeed);
             shaysWorld.cam.SetMoveSpeed(movementSpeed);
             shaysWorld.DisplayWelcome = false;
         }
         else
         {
             shaysWorld.cam.SetXRotateSpeed(0.0f);
             shaysWorld.cam.SetYRotateSpeed(0.0f);
             shaysWorld.cam.SetMoveSpeed(0.0f);
             shaysWorld.DisplayWelcome = true;
         }
     }
     else if (key == ' ' && !isShaysWorld)
     {
         if (wrathWorld.DisplayWelcome)      //if info screen is up don't allow player to look around
         {
             wrathWorld.cam.SetXRotateSpeed(xrotationSpeed);
             wrathWorld.cam.SetYRotateSpeed(yrotationSpeed);
             wrathWorld.cam.SetMoveSpeed(movementSpeed);
             wrathWorld.DisplayWelcome = false;
         }
         else
         {
             wrathWorld.cam.SetXRotateSpeed(0.0f);
             wrathWorld.cam.SetYRotateSpeed(0.0f);
             wrathWorld.cam.SetMoveSpeed(0.0f);
             wrathWorld.DisplayWelcome = true;
         }
     }
 }
References DisplayWrathWorld::cam, DisplayShaysWorld::cam, DisplayWrathWorld::DisplayWelcome, DisplayShaysWorld::DisplayWelcome, isShaysWorld, keyStates, movementSpeed, Camera::SetMoveSpeed(), Camera::SetXRotateSpeed(), Camera::SetYRotateSpeed(), shaysWorld, wrathWorld, xrotationSpeed, and yrotationSpeed.
Referenced by main().
main()
int main (int argc, char ** argv)
Definition at line 57 of file main.cpp.
 {
     glutInit(&argc, argv);
     glutInitDisplayMode(GLUT_DEPTH | GLUT_DOUBLE | GLUT_RGBA);
     //glutInitWindowPosition(100,100);
     //glutInitWindowSize(800,500);
     //glutCreateWindow("Murdoch University Campus Tour");
     glutGameModeString("1920x1080:32@60");
     glutEnterGameMode();
     initKeyStates();    //clear keystate array
     shaysWorld.myinit();
     glutIgnoreKeyRepeat(1);
     glutKeyboardUpFunc(releaseKey);
     glutKeyboardFunc(keyPressed);
     glutDisplayFunc(Display);
     glutIdleFunc(Display);
     glutMouseFunc(Mouse);
     // ONLY USE IF REQUIRE MOUSE MOVEMENT
     glutPassiveMotionFunc(mouseMove);
     glutSetCursor(GLUT_CURSOR_CROSSHAIR);
     glutReshapeFunc(reshape);
     glutMainLoop();
     return(0);
 }
References Display(), glutDisplayFunc(), glutEnterGameMode(), glutGameModeString(), glutIdleFunc(), glutIgnoreKeyRepeat(), glutInitDisplayMode(), glutKeyboardFunc(), glutKeyboardUpFunc(), glutMainLoop(), glutMouseFunc(), glutPassiveMotionFunc(), glutReshapeFunc(), glutSetCursor(), initKeyStates(), keyPressed(), Mouse(), mouseMove(), DisplayShaysWorld::myinit(), releaseKey(), reshape(), and shaysWorld.
Mouse()
void Mouse (int button, int state, int x, int y)
Definition at line 330 of file main.cpp.
 {
     // exit tour if clicked on exit splash screen
     if (((button == GLUT_LEFT_BUTTON) && (state == GLUT_DOWN)) && isShaysWorld)
     {
         if ((shaysWorld.DisplayExit) && (x <= width/2.0 + 256.0) && (x >= width/2.0 - 256.0)
             && (y <= height/2.0 + 256.0) && (y >= height/2.0 - 256.0))
         {
             shaysWorld.DeleteImageFromMemory(shaysWorld.image);
             exit(1);
         }
      }
     if (((button == GLUT_LEFT_BUTTON) && (state == GLUT_DOWN)) && !isShaysWorld)
     {
         if ((wrathWorld.DisplayExit) && (x <= width / 2.0 + 256.0) && (x >= width / 2.0 - 256.0)
             && (y <= height / 2.0 + 256.0) && (y >= height / 2.0 - 256.0))
         {
             wrathWorld.DeleteImageFromMemory(wrathWorld.image);
             exit(1);
         }
     }
 }
References DisplayWrathWorld::DeleteImageFromMemory(), DisplayShaysWorld::DeleteImageFromMemory(), DisplayWrathWorld::DisplayExit, DisplayShaysWorld::DisplayExit, height, DisplayWrathWorld::image, DisplayShaysWorld::image, isShaysWorld, shaysWorld, width, and wrathWorld.
Referenced by main().
mouseMove()
void mouseMove (int x, int y)
Definition at line 356 of file main.cpp.
 {
     if (isShaysWorld)
     {
         shaysWorld.cam.RotateCamera(x, y, width, height);
         glutWarpPointer(width / 2, height / 2);
     }
     if(!isShaysWorld)
     {
         wrathWorld.cam.RotateCamera(x, y, width, height);
         glutWarpPointer(width / 2, height / 2);
     }
 }
References DisplayWrathWorld::cam, DisplayShaysWorld::cam, glutWarpPointer(), height, isShaysWorld, Camera::RotateCamera(), shaysWorld, width, and wrathWorld.
Referenced by main().
processKeys()
void processKeys ()
Definition at line 241 of file main.cpp.
 {
     int speed = 3;
     if ((keyStates['a'] || keyStates['A']) && isShaysWorld)     //step left
         shaysWorld.cam.DirectionLR(-speed);
     if ((keyStates['a'] || keyStates['A']) && !isShaysWorld)        //step left
         wrathWorld.cam.DirectionLR(-speed);
     if ((keyStates['d'] || keyStates['D']) && isShaysWorld)     //step right
         shaysWorld.cam.DirectionLR(speed);
     if ((keyStates['d'] || keyStates['D']) && !isShaysWorld)        //step right
         wrathWorld.cam.DirectionLR(speed);
     if ((keyStates['w'] || keyStates['W']) && isShaysWorld)     //step forward
         shaysWorld.cam.DirectionFB(speed);
     if ((keyStates['w'] || keyStates['W']) && !isShaysWorld)    //step forward
         wrathWorld.cam.DirectionFB(speed);
     if ((keyStates['s'] || keyStates['S']) && isShaysWorld) // step backward
         shaysWorld.cam.DirectionFB(-speed);
     if ((keyStates['s'] || keyStates['S']) && !isShaysWorld)    // step backward
         wrathWorld.cam.DirectionFB(-speed);
     if ((!keyStates['a'] && !keyStates['A'] && !keyStates['d'] && !keyStates['D']) && isShaysWorld) //stops player LR
         shaysWorld.cam.DirectionLR(0);
     if ((!keyStates['a'] && !keyStates['A'] && !keyStates['d'] && !keyStates['D']) && !isShaysWorld)    //stops player LR
         wrathWorld.cam.DirectionLR(0);
     if ((!keyStates['w'] && !keyStates['W'] && !keyStates['s'] && !keyStates['S']) && isShaysWorld) //stops player FB
         shaysWorld.cam.DirectionFB(0);
     if ((!keyStates['w'] && !keyStates['W'] && !keyStates['s'] && !keyStates['S']) && !isShaysWorld)    //stops player FB
         wrathWorld.cam.DirectionFB(0);
     if ((keyStates['m'] || keyStates['M']) && isShaysWorld) // display campus map
     {
         if (shaysWorld.DisplayMap)
         {
             shaysWorld.DisplayMap = false;
         }
         else
         {
             shaysWorld.DisplayMap = true;
         }
     }
     if ((keyStates['p'] || keyStates['P']) && isShaysWorld) // change world - temp
     {
         wrathWorld.myinit();
         isShaysWorld = false;
     }
     /*if ((keyStates['p'] || keyStates['P']) && !isShaysWorld)  // change world - temp
     {
         isShaysWorld = true;
     }*/
     if ((keyStates[27]) && isShaysWorld)    // exit tour (escape key)
     {
         shaysWorld.cam.SetXRotateSpeed(0.0f);
         shaysWorld.cam.SetYRotateSpeed(0.0f);
         shaysWorld.cam.SetMoveSpeed(0.0f);
         shaysWorld.DisplayExit = true;
     }
     if ((keyStates[27]) && !isShaysWorld)   // exit tour (escape key)
     {
         wrathWorld.cam.SetXRotateSpeed(0.0f);
         wrathWorld.cam.SetYRotateSpeed(0.0f);
         wrathWorld.cam.SetMoveSpeed(0.0f);
         wrathWorld.DisplayExit = true;
     }
     // display light fittings
     if ((keyStates['l'] || keyStates['L']) && isShaysWorld)
     {
         if (shaysWorld.lightsOn)
         {
             shaysWorld.lightsOn = false;
         }
         else
         {
             shaysWorld.lightsOn = true;
         }
     }
 }
References DisplayWrathWorld::cam, DisplayShaysWorld::cam, Camera::DirectionFB(), Camera::DirectionLR(), DisplayWrathWorld::DisplayExit, DisplayShaysWorld::DisplayExit, DisplayShaysWorld::DisplayMap, isShaysWorld, keyStates, DisplayShaysWorld::lightsOn, DisplayWrathWorld::myinit(), Camera::SetMoveSpeed(), Camera::SetXRotateSpeed(), Camera::SetYRotateSpeed(), shaysWorld, and wrathWorld.
Referenced by Display().
releaseKey()
void releaseKey (unsigned char key, int x, int y)
Definition at line 235 of file main.cpp.
 {
     keyStates[key] = false;     //set keystate to released
 }
References keyStates.
Referenced by main().
reshape()
void reshape (int w, int h)
Definition at line 170 of file main.cpp.
 {
     width = w;
     height = h;
     // Prevent a divide by zero, when window is too short
     // (you cant make a window of zero width).
     if (h == 0) h = 1;
     ratio = 1.0f * w / h;
     // Reset the coordinate system before modifying
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     glViewport(0, 0, w, h);
     gluPerspective(45,ratio,1,250000);
     glMatrixMode(GL_MODELVIEW);
 }
References glLoadIdentity(), glMatrixMode(), glViewport(), height, ratio, and width.
Referenced by main().
Variable Documentation
angleIncrement
GLdouble angleIncrement
Definition at line 31 of file main.cpp.
Referenced by IncrementFrameCount().
frameCount
int frameCount = 0
Definition at line 32 of file main.cpp.
Referenced by IncrementFrameCount().
height
int height
Definition at line 38 of file main.cpp.
Referenced by Display(), Mouse(), mouseMove(), and reshape().
isShaysWorld
bool isShaysWorld = true
Definition at line 49 of file main.cpp.
Referenced by Display(), keyPressed(), Mouse(), mouseMove(), and processKeys().
keyStates
bool* keyStates = new bool[256]
Definition at line 41 of file main.cpp.
Referenced by initKeyStates(), keyPressed(), processKeys(), and releaseKey().
lastClock
clock_t lastClock = 0
Definition at line 33 of file main.cpp.
Referenced by IncrementFrameCount().
movementSpeed
GLdouble movementSpeed = 15.0
Definition at line 26 of file main.cpp.
Referenced by keyPressed().
ratio
float ratio
Definition at line 36 of file main.cpp.
Referenced by reshape().
shaysWorld
DisplayShaysWorld shaysWorld
Definition at line 24 of file main.cpp.
Referenced by Display(), keyPressed(), main(), Mouse(), mouseMove(), and processKeys().
stepIncrement
GLdouble stepIncrement
Definition at line 30 of file main.cpp.
Referenced by Display(), and IncrementFrameCount().
width
int width
Definition at line 38 of file main.cpp.
Referenced by Display(), Mouse(), mouseMove(), and reshape().
wrathWorld
DisplayWrathWorld wrathWorld
Definition at line 25 of file main.cpp.
Referenced by Display(), keyPressed(), Mouse(), mouseMove(), and processKeys().
xrotationSpeed
GLdouble xrotationSpeed = 0.0015
Definition at line 27 of file main.cpp.
Referenced by keyPressed().
yrotationSpeed
GLdouble yrotationSpeed = 0.0012
Definition at line 28 of file main.cpp.
Referenced by keyPressed().