ICT290 Assignment 1: LodePNGDecompressSettings Struct Reference
LodePNGDecompressSettings Struct Reference
#include <lodepng.h>
Public Attributes
unsigned ignore_adler32
unsigned ignore_nlen
unsigned(* custom_zlib)(unsigned char **, size_t *, const unsigned char *, size_t, const LodePNGDecompressSettings *)
unsigned(* custom_inflate)(unsigned char **, size_t *, const unsigned char *, size_t, const LodePNGDecompressSettings *)
const void * custom_context
Detailed Description
Definition at line 269 of file lodepng.h.
Member Data Documentation
custom_context
const void* LodePNGDecompressSettings::custom_context
Definition at line 284 of file lodepng.h.
Referenced by lodepng_decompress_settings_init().
custom_inflate
unsigned(* LodePNGDecompressSettings::custom_inflate) (unsigned char **, size_t *, const unsigned char *, size_t, const LodePNGDecompressSettings *)
Definition at line 280 of file lodepng.h.
Referenced by inflatev(), and lodepng_decompress_settings_init().
custom_zlib
unsigned(* LodePNGDecompressSettings::custom_zlib) (unsigned char **, size_t *, const unsigned char *, size_t, const LodePNGDecompressSettings *)
Definition at line 275 of file lodepng.h.
Referenced by lodepng_decompress_settings_init(), and zlib_decompress().
ignore_adler32
unsigned LodePNGDecompressSettings::ignore_adler32
Definition at line 271 of file lodepng.h.
Referenced by lodepng_decompress_settings_init(), and lodepng_zlib_decompressv().
ignore_nlen
unsigned LodePNGDecompressSettings::ignore_nlen
Definition at line 272 of file lodepng.h.
Referenced by inflateNoCompression(), and lodepng_decompress_settings_init().
The documentation for this struct was generated from the following file:
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/lodepng.h