ICT290 Assignment 1: AABBNode Class Reference
AABBNode Class Reference
#include <AABBNode.h>
Classes
struct BoundingBox
stores max and min values of co-ordinates
struct XYZ
stores x,y,z co-ordinates
Public Member Functions
AABBNode ()
virtual ~AABBNode ()
void Clear ()
Clears node.
GLdouble GetMaxX ()
Gets Max X of node.
GLdouble GetMinX ()
Gets Min X of node.
GLdouble GetMaxY ()
Gets Max Y of node.
GLdouble GetMinY ()
Gets Min Y of node.
GLdouble GetMaxZ ()
Gets Max Z of node.
GLdouble GetMinZ ()
Gets Min Z of node.
AABBNode * GetNext () const
Return the address of the link to the next node in the list.
void SetData (const GLdouble maxX, const GLdouble minX, const GLdouble maxY, const GLdouble minY, const GLdouble maxZ, const GLdouble minZ)
Sets Data.
void SetNext (AABBNode *next)
Set the address of the link to the next node in the list.
Private Member Functions
AABBNode (const AABBNode &newNode)
AABBNode & operator= (const AABBNode &newNode)
Private Attributes
AABBNode * m_next
The address of the next node in the list.
BoundingBox m_BBox
stores info on Bounding Box
Detailed Description
Definition at line 17 of file AABBNode.h.
Constructor & Destructor Documentation
AABBNode() [1/2]
AABBNode::AABBNode () inline
Definition at line 20 of file AABBNode.h.
 {Clear();}
References Clear().
~AABBNode()
virtual AABBNode::~AABBNode () inline virtual
Definition at line 21 of file AABBNode.h.
 {Clear();}
References Clear().
AABBNode() [2/2]
AABBNode::AABBNode (const AABBNode & newNode) inline private
Definition at line 114 of file AABBNode.h.
 {};
Member Function Documentation
Clear()
void AABBNode::Clear ()
Clears node.
Returns
void
Definition at line 13 of file AABBNode.cpp.
 {
     m_next = NULL;
 }
References m_next.
Referenced by AABBNode(), and ~AABBNode().
GetMaxX()
GLdouble AABBNode::GetMaxX () inline
Gets Max X of node.
Returns
GLdouble
Definition at line 37 of file AABBNode.h.
 {return m_BBox.max.x;}
GetMaxY()
GLdouble AABBNode::GetMaxY () inline
Gets Max Y of node.
Returns
GLdouble
Definition at line 47 of file AABBNode.h.
 {return m_BBox.max.y;}
GetMaxZ()
GLdouble AABBNode::GetMaxZ () inline
Gets Max Z of node.
Returns
GLdouble
Definition at line 57 of file AABBNode.h.
 {return m_BBox.max.z;}
GetMinX()
GLdouble AABBNode::GetMinX () inline
Gets Min X of node.
Returns
GLdouble
Definition at line 42 of file AABBNode.h.
 {return m_BBox.min.x;}
GetMinY()
GLdouble AABBNode::GetMinY () inline
Gets Min Y of node.
Returns
GLdouble
Definition at line 52 of file AABBNode.h.
 {return m_BBox.min.y;}
GetMinZ()
GLdouble AABBNode::GetMinZ () inline
Gets Min Z of node.
Returns
GLdouble
Definition at line 62 of file AABBNode.h.
 {return m_BBox.min.z;}
GetNext()
AABBNode* AABBNode::GetNext () const inline
Return the address of the link to the next node in the list.
Returns
AABBNode
Definition at line 67 of file AABBNode.h.
 {return m_next;}
References m_next.
Referenced by AABBLinkedList::AddToStart(), AABBLinkedList::Clear(), AABBLinkedList::Delete(), AABBLinkedList::GetListSize(), AABBLinkedList::GetMaxX(), AABBLinkedList::GetMaxY(), AABBLinkedList::GetMaxZ(), AABBLinkedList::GetMinX(), AABBLinkedList::GetMinY(), AABBLinkedList::GetMinZ(), AABBLinkedList::GetNext(), and AABBLinkedList::SetData().
operator=()
AABBNode& AABBNode::operator= (const AABBNode & newNode) inline private
Definition at line 115 of file AABBNode.h.
 {};
SetData()
void AABBNode::SetData (const GLdouble maxX, const GLdouble minX, const GLdouble maxY, const GLdouble minY, const GLdouble maxZ, const GLdouble minZ)
Sets Data.
Parameters
maxX - maximum x
minX - minimum x
maxY - maximum y
minY - minimum y
maxZ - maximum z
minZ - minimum z
Returns
void
Definition at line 21 of file AABBNode.cpp.
 {
     m_BBox.max.x = maxX;
     m_BBox.min.x = minX;
     m_BBox.max.y = maxY;
     m_BBox.min.y = minY;
     m_BBox.max.z = maxZ;
     m_BBox.min.z = minZ;
 }
SetNext()
void AABBNode::SetNext (AABBNode * next) inline
Set the address of the link to the next node in the list.
Parameters
next - next node
Returns
void
Definition at line 91 of file AABBNode.h.
 {m_next = next;}
References m_next.
Referenced by AABBLinkedList::AddToStart(), and AABBLinkedList::Delete().
Member Data Documentation
m_BBox
BoundingBox AABBNode::m_BBox private
stores info on Bounding Box
Definition at line 109 of file AABBNode.h.
m_next
AABBNode* AABBNode::m_next private
The address of the next node in the list.
Definition at line 95 of file AABBNode.h.
Referenced by Clear(), GetNext(), and SetNext().
The documentation for this class was generated from the following files:
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/AABBNode.h
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/AABBNode.cpp