ICT290 Assignment 1: PlainNode Class Reference
PlainNode Class Reference
Set of functions and parameters to hold the plain data.
#include <PlainNode.h>
Public Member Functions
PlainNode ()
virtual ~PlainNode ()
void Clear ()
Used to Clear a node.
GLdouble GetType ()
Returns the Type.
GLdouble GetXstart ()
Returns the X Start.
GLdouble GetXend ()
Returns the X End.
GLdouble GetYstart ()
Returns the Y Start.
GLdouble GetYend ()
Returns the Y End.
GLdouble GetZstart ()
Returns the Z Start.
GLdouble GetZend ()
Returns the Z End.
PlainNode * GetNext () const
Return the address of the link to the next node in the list.
void SetData (const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
Set the values of the node data.
void SetNext (PlainNode *next)
Set the address of the link to the next node in the list.
Private Member Functions
PlainNode (const PlainNode &newNode)
PlainNode & operator= (const PlainNode &newNode)
Private Attributes
PlainNode * m_next
GLdouble m_type
GLdouble m_xPlainStart
GLdouble m_xPlainEnd
GLdouble m_yPlainStart
GLdouble m_yPlainEnd
GLdouble m_zPlainStart
GLdouble m_zPlainEnd
Detailed Description
Set of functions and parameters to hold the plain data.
Author
Group Team No Name 2
Version
Date
14 Sep 20
Definition at line 23 of file PlainNode.h.
Constructor & Destructor Documentation
PlainNode() [1/2]
PlainNode::PlainNode () inline
Definition at line 27 of file PlainNode.h.
 {Clear();}
References Clear().
~PlainNode()
virtual PlainNode::~PlainNode () inline virtual
Definition at line 28 of file PlainNode.h.
 {Clear();}
References Clear().
PlainNode() [2/2]
PlainNode::PlainNode (const PlainNode & newNode) inline private
Definition at line 125 of file PlainNode.h.
 {};
Member Function Documentation
Clear()
void PlainNode::Clear ()
Used to Clear a node.
Returns
void
Definition at line 13 of file PlainNode.cpp.
 {
     m_next = NULL;
 }
References m_next.
Referenced by PlainNode(), and ~PlainNode().
GetNext()
PlainNode* PlainNode::GetNext () const inline
Return the address of the link to the next node in the list.
Returns
PlainNode
Definition at line 79 of file PlainNode.h.
 {return m_next;}
References m_next.
Referenced by PlainLinkedList::AddToStart(), PlainLinkedList::Clear(), PlainLinkedList::Delete(), PlainLinkedList::GetListSize(), PlainLinkedList::GetNext(), PlainLinkedList::GetType(), PlainLinkedList::GetXend(), PlainLinkedList::GetXstart(), PlainLinkedList::GetYend(), PlainLinkedList::GetYstart(), PlainLinkedList::GetZend(), PlainLinkedList::GetZstart(), and PlainLinkedList::SetData().
GetType()
GLdouble PlainNode::GetType () inline
Returns the Type.
Returns
GLdouble
Definition at line 44 of file PlainNode.h.
 {return m_type;}
GetXend()
GLdouble PlainNode::GetXend () inline
Returns the X End.
Returns
GLdouble
Definition at line 54 of file PlainNode.h.
 {return m_xPlainEnd;}
GetXstart()
GLdouble PlainNode::GetXstart () inline
Returns the X Start.
Returns
GLdouble
Definition at line 49 of file PlainNode.h.
 {return m_xPlainStart;}
GetYend()
GLdouble PlainNode::GetYend () inline
Returns the Y End.
Returns
GLdouble
Definition at line 64 of file PlainNode.h.
 {return m_yPlainEnd;}
GetYstart()
GLdouble PlainNode::GetYstart () inline
Returns the Y Start.
Returns
GLdouble
Definition at line 59 of file PlainNode.h.
 {return m_yPlainStart;}
GetZend()
GLdouble PlainNode::GetZend () inline
Returns the Z End.
Returns
GLdouble
Definition at line 74 of file PlainNode.h.
 {return m_zPlainEnd;}
GetZstart()
GLdouble PlainNode::GetZstart () inline
Returns the Z Start.
Returns
GLdouble
Definition at line 69 of file PlainNode.h.
 {return m_zPlainStart;}
operator=()
PlainNode& PlainNode::operator= (const PlainNode & newNode) inline private
Definition at line 126 of file PlainNode.h.
 {};
SetData()
void PlainNode::SetData (const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
Set the values of the node data.
Parameters
tempType - type of data
tempXs - x start
tempXe - x end
tempYs - y start
tempYe - y end
tempZs - z start
tempZe - z end
Returns
void
Definition at line 20 of file PlainNode.cpp.
 {
     m_type = tempType;
     m_xPlainStart = tempXs;
     m_xPlainEnd = tempXe;
     m_yPlainStart = tempYs;
     m_yPlainEnd = tempYe;
     m_zPlainStart = tempZs;
     m_zPlainEnd = tempZe;
 }
SetNext()
void PlainNode::SetNext (PlainNode * next) inline
Set the address of the link to the next node in the list.
Parameters
next - pointer of the next node
Returns
void
Definition at line 104 of file PlainNode.h.
 {m_next = next;}
References m_next.
Referenced by PlainLinkedList::AddToStart(), and PlainLinkedList::Delete().
Member Data Documentation
m_next
PlainNode* PlainNode::m_next private
Definition at line 108 of file PlainNode.h.
Referenced by Clear(), GetNext(), and SetNext().
m_type
GLdouble PlainNode::m_type private
Definition at line 114 of file PlainNode.h.
m_xPlainEnd
GLdouble PlainNode::m_xPlainEnd private
Definition at line 118 of file PlainNode.h.
m_xPlainStart
GLdouble PlainNode::m_xPlainStart private
Definition at line 118 of file PlainNode.h.
m_yPlainEnd
GLdouble PlainNode::m_yPlainEnd private
Definition at line 119 of file PlainNode.h.
m_yPlainStart
GLdouble PlainNode::m_yPlainStart private
Definition at line 119 of file PlainNode.h.
m_zPlainEnd
GLdouble PlainNode::m_zPlainEnd private
Definition at line 120 of file PlainNode.h.
m_zPlainStart
GLdouble PlainNode::m_zPlainStart private
Definition at line 120 of file PlainNode.h.
The documentation for this class was generated from the following files:
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/PlainNode.h
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/PlainNode.cpp