ICT290 Assignment 1: PlainLinkedList Class Reference
PlainLinkedList Class Reference
Class that defines the links between the Plain Nodes.
#include <PlainLinkedList.h>
Public Member Functions
PlainLinkedList ()
virtual ~PlainLinkedList ()
void Clear ()
Clears linked list and frees memory.
bool AddToStart (const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
add a node to the start of the linked list
void SetData (const int &ptrCount, const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
set the values of the node data
GLdouble GetType (int ptrCount)
Gets Type.
GLdouble GetXstart (int ptrCount)
Gets starting x.
GLdouble GetXend (int ptrCount)
Gets ending x.
GLdouble GetYstart (int ptrCount)
Gets starting y.
GLdouble GetYend (int ptrCount)
Gets ending x.
GLdouble GetZstart (int ptrCount)
Gets starting z.
GLdouble GetZend (int ptrCount)
Gets ending z.
int GetListSize ()
Gets size of the plains list.
PlainNode * GetNext () const
Return the address of the link to the next node in the list.
PlainNode * GetFirst () const
Return the address of the link to the first node in the list.
Private Member Functions
void Delete (PlainNode *before)
Used to Clear Memory.
PlainLinkedList (const PlainLinkedList &array)
PlainLinkedList & operator= (const PlainLinkedList &array)
Private Attributes
PlainNode * m_first
Detailed Description
Class that defines the links between the Plain Nodes.
Author
Group Team No Name 2
Version
Date
14 Sep 20
Definition at line 28 of file PlainLinkedList.h.
Constructor & Destructor Documentation
PlainLinkedList() [1/2]
PlainLinkedList::PlainLinkedList () inline
Definition at line 32 of file PlainLinkedList.h.
 {m_first = new PlainNode;}
References m_first.
~PlainLinkedList()
virtual PlainLinkedList::~PlainLinkedList () inline virtual
Definition at line 34 of file PlainLinkedList.h.
 {Clear();}
References Clear().
PlainLinkedList() [2/2]
PlainLinkedList::PlainLinkedList (const PlainLinkedList & array) inline private
Definition at line 149 of file PlainLinkedList.h.
 {};
Member Function Documentation
AddToStart()
bool PlainLinkedList::AddToStart (const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
add a node to the start of the linked list
Parameters
tempType - type of plain
tempXs - x start
tempXe - x end
tempYs - y start
tempYe - y end
tempZs - z start
tempZe - z end
Returns
bool
Definition at line 37 of file PlainLinkedList.cpp.
 {
     PlainNode *newNode;
     try
     {
         newNode = new PlainNode;
     }
     catch(...)
     {
         return false;
     }
     // add the value to the node
     newNode->SetData(tempType, tempXs, tempXe, tempYs, tempYe, tempZs, tempZe);
     // set the address of the net node
     newNode->SetNext(m_first->GetNext());
     // reset the address of the first node
     m_first->SetNext(newNode);
     return true;
 }
References PlainNode::GetNext(), m_first, and PlainNode::SetNext().
Clear()
void PlainLinkedList::Clear ()
Clears linked list and frees memory.
Returns
void
Definition at line 13 of file PlainLinkedList.cpp.
 {
     PlainNode *ptr = m_first;
     while (ptr->GetNext() != NULL)
     // clear memory
     Delete(ptr);
 }
References Delete(), PlainNode::GetNext(), and m_first.
Referenced by ~PlainLinkedList().
Delete()
void PlainLinkedList::Delete (PlainNode * before) private
Used to Clear Memory.
Parameters
before - node before one to be deleted
Returns
void
Definition at line 25 of file PlainLinkedList.cpp.
 {
     PlainNode *temp = before->GetNext();
     before->SetNext(temp->GetNext());
     delete temp;
 }
References PlainNode::GetNext(), and PlainNode::SetNext().
Referenced by Clear().
GetFirst()
PlainNode* PlainLinkedList::GetFirst () const inline
Return the address of the link to the first node in the list.
Returns
PlainNode
Definition at line 133 of file PlainLinkedList.h.
 {return m_first;}
References m_first.
GetListSize()
int PlainLinkedList::GetListSize ()
Gets size of the plains list.
Returns
int
Definition at line 194 of file PlainLinkedList.cpp.
 {
     int tmpSize = 0;
     // count size of list
     for (PlainNode *ptr = (m_first); ptr->GetNext() != NULL; ptr = ptr->GetNext())
     {
         tmpSize++;
     }
     return tmpSize;
 }
References PlainNode::GetNext(), and m_first.
Referenced by Camera::SetPlains().
GetNext()
PlainNode* PlainLinkedList::GetNext () const inline
Return the address of the link to the next node in the list.
Returns
PlainNode
Definition at line 128 of file PlainLinkedList.h.
 {return m_first->GetNext();}
References PlainNode::GetNext(), and m_first.
GetType()
GLdouble PlainLinkedList::GetType (int ptrCount)
Gets Type.
Parameters
ptrCount - the pointer of the node
Returns
GLdouble
Definition at line 65 of file PlainLinkedList.cpp.
 {
     PlainNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetType();
     else
         return NULL;
 }
References PlainNode::GetNext(), and m_first.
GetXend()
GLdouble PlainLinkedList::GetXend (int ptrCount)
Gets ending x.
Parameters
ptrCount - the pointer of the node
Returns
GLdouble
Definition at line 97 of file PlainLinkedList.cpp.
 {
     PlainNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetXend();
     else
         return NULL;
 }
References PlainNode::GetNext(), and m_first.
GetXstart()
GLdouble PlainLinkedList::GetXstart (int ptrCount)
Gets starting x.
Parameters
ptrCount - the pointer of the node
Returns
GLdouble
Definition at line 81 of file PlainLinkedList.cpp.
 {
     PlainNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetXstart();
     else
         return NULL;
 }
References PlainNode::GetNext(), and m_first.
GetYend()
GLdouble PlainLinkedList::GetYend (int ptrCount)
Gets ending x.
Parameters
ptrCount - the pointer of the node
Returns
GLdouble
Definition at line 129 of file PlainLinkedList.cpp.
 {
     PlainNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetYend();
     else
         return NULL;
 }
References PlainNode::GetNext(), and m_first.
GetYstart()
GLdouble PlainLinkedList::GetYstart (int ptrCount)
Gets starting y.
Parameters
ptrCount - the pointer of the node
Returns
GLdouble
Definition at line 113 of file PlainLinkedList.cpp.
 {
     PlainNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetYstart();
     else
         return NULL;
 }
References PlainNode::GetNext(), and m_first.
GetZend()
GLdouble PlainLinkedList::GetZend (int ptrCount)
Gets ending z.
Parameters
ptrCount - the pointer of the node
Returns
GLdouble
Definition at line 161 of file PlainLinkedList.cpp.
 {
     PlainNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetZend();
     else
         return NULL;
 }
References PlainNode::GetNext(), and m_first.
GetZstart()
GLdouble PlainLinkedList::GetZstart (int ptrCount)
Gets starting z.
Parameters
ptrCount - the pointer of the node
Returns
GLdouble
Definition at line 145 of file PlainLinkedList.cpp.
 {
     PlainNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetZstart();
     else
         return NULL;
 }
References PlainNode::GetNext(), and m_first.
operator=()
PlainLinkedList& PlainLinkedList::operator= (const PlainLinkedList & array) inline private
Definition at line 150 of file PlainLinkedList.h.
 {};
SetData()
void PlainLinkedList::SetData (const int & ptrCount, const int tempType, const GLdouble tempXs, const GLdouble tempXe, const GLdouble tempYs, const GLdouble tempYe, const GLdouble tempZs, const GLdouble tempZe)
set the values of the node data
Parameters
ptrCount - the pointer of the node
tempType - type of data
tempXs - x start
tempXe - x end
tempYs - y start
tempYe - y end
tempZs - z start
tempZe - z end
Returns
void
Definition at line 178 of file PlainLinkedList.cpp.
 {
     PlainNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     ptr->GetNext()->SetData(tempType, tempXs, tempXe, tempYs, tempYe, tempZs, tempZe);
 }
References PlainNode::GetNext(), and m_first.
Member Data Documentation
m_first
PlainNode* PlainLinkedList::m_first private
Definition at line 140 of file PlainLinkedList.h.
Referenced by AddToStart(), Clear(), GetFirst(), GetListSize(), GetNext(), GetType(), GetXend(), GetXstart(), GetYend(), GetYstart(), GetZend(), GetZstart(), PlainLinkedList(), and SetData().
The documentation for this class was generated from the following files:
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/PlainLinkedList.h
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/PlainLinkedList.cpp