ICT290 Assignment 1: Collision Class Reference
Collision Class Reference
Class defines functions to handle collision detection.
#include <collision.h>
Public Member Functions
Collision ()
virtual ~Collision ()
void SetAABBMaxX (const int &tempIndex, const double &tempX)
Sets AABB MaxX.
void SetAABBMinX (const int &tempIndex, const double &tempX)
Sets AABB MinX.
void SetAABBMaxY (const int &tempIndex, const double &tempY)
Sets AABB MaxY.
void SetAABBMinY (const int &tempIndex, const double &tempY)
Sets AABB MinY.
void SetAABBMaxZ (const int &tempIndex, const double &tempZ)
Sets AABB MaxZ.
void SetAABBMinZ (const int &tempIndex, const double &tempZ)
Sets AABB MinZ.
void SetWorldX (const double &tempX)
Sets world X of object.
void SetWorldZ (const double &tempZ)
Sets world Z of object.
void SetNoBoundingBoxes (const int &tempSize)
Sets number of bounding boxes.
double GetAABBMaxX (const int &tempIndex)
Returns Max x of bounding box.
double GetAABBMinX (const int &tempIndex)
Returns Min x of bounding box.
double GetAABBMaxY (const int &tempIndex)
Returns Max y of bounding box.
double GetAABBMinY (const int &tempIndex)
Returns Min y of bounding box.
double GetAABBMaxZ (const int &tempIndex)
Returns Max z of bounding box.
double GetAABBMinZ (const int &tempIndex)
Returns Min z of bounding box.
int GetNoBoundingBoxes ()
Returns number of bounding boxes.
bool Collide (double endX, double endY, double endZ)
Checks for collision returns true if occoured.
void CreateLinkedList ()
reads the BB info from AABB (dynamic array) and creates a Linked List with AABB data
Private Member Functions
bool CheckCollision (int index, double endX, double endY, double endZ)
checks if collsion occurred (called from Collide)
Collision (const Collision &coll)
Collision & operator= (const Collision &coll)
Private Attributes
AABB m_AABB
AABBLinkedList m_list [4]
int m_listSize [4]
double m_worldSizeX
double m_worldSizeZ
Detailed Description
Class defines functions to handle collision detection.
Author
Group Team No Name 2
Version
Date
14 Sep 20
Definition at line 23 of file collision.h.
Constructor & Destructor Documentation
Collision() [1/2]
Collision::Collision () inline
Definition at line 27 of file collision.h.
 {}
~Collision()
virtual Collision::~Collision () inline virtual
Definition at line 28 of file collision.h.
 {}
Collision() [2/2]
Collision::Collision (const Collision & coll) inline private
Definition at line 181 of file collision.h.
 {};
Member Function Documentation
CheckCollision()
bool Collision::CheckCollision (int index, double endX, double endY, double endZ) private
checks if collsion occurred (called from Collide)
Parameters
index - index of AABB to check
endX - x to check collision
endY - y to check collision
endZ - z to check collision
Returns
bool
Definition at line 119 of file collision.cpp.
 {
     bool CollisionFound = false;
     for (int count = 0; count < m_listSize[index]; count++)
     {
         if (((endX < m_list[index].GetMaxX(count)) && (endX > m_list[index].GetMinX(count))) &&
             ((endZ < m_list[index].GetMaxZ(count)) && (endZ > m_list[index].GetMinZ(count))))
         {
             CollisionFound = true;
         }
     }
     return CollisionFound;
 }
References m_listSize.
Collide()
bool Collision::Collide (double endX, double endY, double endZ)
Checks for collision returns true if occoured.
Parameters
endX - x to check collision
endY - y to check collision
endZ - z to check collision
Returns
bool
Definition at line 86 of file collision.cpp.
 {
     bool Collision = false;
     // check 1st quadrant (1st linked list)
     if (((endX <= m_worldSizeX / 2.0) || (endX <= m_worldSizeX / 2.0)) &&
         ((endZ <= m_worldSizeZ / 2.0) || (endZ <= m_worldSizeZ / 2.0)))
     {
         Collision = CheckCollision(0, endX, endY, endZ);
     }
     // check 2nd quadrant (2nd linked list)
     if (((endX <= m_worldSizeX / 2.0) || (endX <= m_worldSizeX / 2.0)) &&
         ((endZ >= m_worldSizeZ / 2.0) || (endZ >= m_worldSizeZ / 2.0)))
     {
         Collision = CheckCollision(1, endX, endY, endZ);
     }
     // check 3rd quadrant (3rd linked list)
     if (((endX >= m_worldSizeX / 2.0) || (endX >= m_worldSizeX / 2.0)) &&
     ((endZ <= m_worldSizeZ / 2.0) || (endZ <= m_worldSizeZ / 2.0)))
     {
         Collision = CheckCollision(2, endX, endY, endZ);
     }
     // check 4th quadrant (4th linked list)
     if (((endX >= m_worldSizeX / 2.0) || (endX >= m_worldSizeX / 2.0)) &&
     ((endZ >= m_worldSizeZ / 2.0) || (endZ >= m_worldSizeZ / 2.0)))
     {
         Collision = CheckCollision(3, endX, endY, endZ);
     }
     return Collision;
 }
CreateLinkedList()
void Collision::CreateLinkedList ()
reads the BB info from AABB (dynamic array) and creates a Linked List with AABB data
Returns
void
Definition at line 18 of file collision.cpp.
 {
     int tempNoBoxes = GetNoBoundingBoxes();
     // initilize list size for each quadrant
     m_listSize[0] = 0;
     m_listSize[1] = 0;
     m_listSize[2] = 0;
     m_listSize[3] = 0;
     for (int count = 0; count < tempNoBoxes; count++)
     {
         GLdouble maxX = GetAABBMaxX(count);
         GLdouble minX = GetAABBMinX(count);
         GLdouble maxY = GetAABBMaxY(count);
         GLdouble minY = GetAABBMinY(count);
         GLdouble maxZ = GetAABBMaxZ(count);
         GLdouble minZ = GetAABBMinZ(count);
         // 1st quadrant
         if (((minX <= m_worldSizeX / 2.0) || (maxX <= m_worldSizeX / 2.0)) &&
             ((minZ <= m_worldSizeZ / 2.0) || (maxZ <= m_worldSizeZ / 2.0)))
         {
             // increment list size
             m_listSize[0]++;
             // add bb data to list
             m_list[0].AddToStart(maxX, minX, maxY, minY, maxZ, minZ);
         }
         // 2nd quadrant
         if (((minX <= m_worldSizeX / 2.0) || (maxX <= m_worldSizeX / 2.0)) &&
             ((minZ >= m_worldSizeZ / 2.0) || (maxZ >= m_worldSizeZ / 2.0)))
         {
             // increment list size
             m_listSize[1]++;
             // add bb data to list
             m_list[1].AddToStart(maxX, minX, maxY, minY, maxZ, minZ);
         }
         // 3rd quadrant
         if (((minX >= m_worldSizeX / 2.0) || (maxX >= m_worldSizeX / 2.0)) &&
             ((minZ <= m_worldSizeZ / 2.0) || (maxZ <= m_worldSizeZ / 2.0)))
         {
             // increment list size
             m_listSize[2]++;
             // add bb data to list
             m_list[2].AddToStart(maxX, minX, maxY, minY, maxZ, minZ);
         }
         // 4th quadrant
         if (((minX >= m_worldSizeX / 2.0) || (maxX >= m_worldSizeX / 2.0)) &&
             ((minZ >= m_worldSizeZ / 2.0) || (maxZ >= m_worldSizeZ / 2.0)))
         {
             // increment list size
             m_listSize[3]++;
             // add bb data to list
             m_list[3].AddToStart(maxX, minX, maxY, minY, maxZ, minZ);
         }
     }
     // Call AABB constructor the delete array and clear memory
     // (the array AABB is not required once the lists have been created)
     m_AABB.~AABB();
 }
References GetNoBoundingBoxes(), m_AABB, m_listSize, and AABB::~AABB().
Referenced by Camera::InitiateBoundingBoxes().
GetAABBMaxX()
double Collision::GetAABBMaxX (const int & tempIndex) inline
Returns Max x of bounding box.
Parameters
tempIndex - index of AABB
Returns
double
Definition at line 102 of file collision.h.
 {return m_AABB.GetMaxX (tempIndex);}
Referenced by Camera::GetAABBMaxX().
GetAABBMaxY()
double Collision::GetAABBMaxY (const int & tempIndex) inline
Returns Max y of bounding box.
Parameters
tempIndex - index of AABB
Returns
double
Definition at line 114 of file collision.h.
 {return m_AABB.GetMaxY (tempIndex);}
Referenced by Camera::GetAABBMaxY().
GetAABBMaxZ()
double Collision::GetAABBMaxZ (const int & tempIndex) inline
Returns Max z of bounding box.
Parameters
tempIndex - index of AABB
Returns
double
Definition at line 126 of file collision.h.
 {return m_AABB.GetMaxZ (tempIndex);}
Referenced by Camera::GetAABBMaxZ().
GetAABBMinX()
double Collision::GetAABBMinX (const int & tempIndex) inline
Returns Min x of bounding box.
Parameters
tempIndex - index of AABB
Returns
double
Definition at line 108 of file collision.h.
 {return m_AABB.GetMinX (tempIndex);}
Referenced by Camera::GetAABBMinX().
GetAABBMinY()
double Collision::GetAABBMinY (const int & tempIndex) inline
Returns Min y of bounding box.
Parameters
tempIndex - index of AABB
Returns
double
Definition at line 120 of file collision.h.
 {return m_AABB.GetMinY (tempIndex);}
Referenced by Camera::GetAABBMinY().
GetAABBMinZ()
double Collision::GetAABBMinZ (const int & tempIndex) inline
Returns Min z of bounding box.
Parameters
tempIndex - index of AABB
Returns
double
Definition at line 132 of file collision.h.
 {return m_AABB.GetMinZ (tempIndex);}
Referenced by Camera::GetAABBMinZ().
GetNoBoundingBoxes()
int Collision::GetNoBoundingBoxes () inline
Returns number of bounding boxes.
Returns
int
Definition at line 137 of file collision.h.
 {return m_AABB.GetNoBoundingBoxes();}
References AABB::GetNoBoundingBoxes(), and m_AABB.
Referenced by CreateLinkedList().
operator=()
Collision& Collision::operator= (const Collision & coll) inline private
Definition at line 182 of file collision.h.
 {};
SetAABBMaxX()
void Collision::SetAABBMaxX (const int & tempIndex, const double & tempX) inline
Sets AABB MaxX.
Parameters
tempIndex - index of the AABB
tempX - max x of AABB
Returns
void
Definition at line 39 of file collision.h.
 {m_AABB.SetMaxX(tempIndex, tempX);}
SetAABBMaxY()
void Collision::SetAABBMaxY (const int & tempIndex, const double & tempY) inline
Sets AABB MaxY.
Parameters
tempIndex - index of the AABB
tempY- max y of AABB
Returns
void
Definition at line 53 of file collision.h.
 {m_AABB.SetMaxY(tempIndex, tempY);}
SetAABBMaxZ()
void Collision::SetAABBMaxZ (const int & tempIndex, const double & tempZ) inline
Sets AABB MaxZ.
Parameters
tempIndex - index of the AABB
tempZ- max z of AABB
Returns
void
Definition at line 67 of file collision.h.
 {m_AABB.SetMaxZ(tempIndex, tempZ);}
SetAABBMinX()
void Collision::SetAABBMinX (const int & tempIndex, const double & tempX) inline
Sets AABB MinX.
Parameters
tempIndex - index of the AABB
tempX - min x of AABB
Returns
void
Definition at line 46 of file collision.h.
 {m_AABB.SetMinX(tempIndex, tempX);}
SetAABBMinY()
void Collision::SetAABBMinY (const int & tempIndex, const double & tempY) inline
Sets AABB MinY.
Parameters
tempIndex - index of the AABB
tempY- min y of AABB
Returns
void
Definition at line 60 of file collision.h.
 {m_AABB.SetMinY(tempIndex, tempY);}
SetAABBMinZ()
void Collision::SetAABBMinZ (const int & tempIndex, const double & tempZ) inline
Sets AABB MinZ.
Parameters
tempIndex - index of the AABB
tempZ- min z of AABB
Returns
void
Definition at line 74 of file collision.h.
 {m_AABB.SetMinZ(tempIndex, tempZ);}
SetNoBoundingBoxes()
void Collision::SetNoBoundingBoxes (const int & tempSize) inline
Sets number of bounding boxes.
Parameters
tempSize - number of AABB
Returns
void
Definition at line 92 of file collision.h.
 {m_AABB.SetNoBoundingBoxes(tempSize);}
References m_AABB, and AABB::SetNoBoundingBoxes().
Referenced by Camera::SetNoBoundingBoxes().
SetWorldX()
void Collision::SetWorldX (const double & tempX) inline
Sets world X of object.
Parameters
tempX - world x of AABB
Returns
void
Definition at line 80 of file collision.h.
 {m_worldSizeX = tempX;}
References m_worldSizeX.
SetWorldZ()
void Collision::SetWorldZ (const double & tempZ) inline
Sets world Z of object.
Parameters
tempZ - world z of AABB
Returns
void
Definition at line 86 of file collision.h.
 {m_worldSizeZ = tempZ;}
References m_worldSizeZ.
Member Data Documentation
m_AABB
AABB Collision::m_AABB private
Definition at line 154 of file collision.h.
Referenced by CreateLinkedList(), GetNoBoundingBoxes(), and SetNoBoundingBoxes().
m_list
AABBLinkedList Collision::m_list[4] private
Definition at line 157 of file collision.h.
m_listSize
int Collision::m_listSize[4] private
Definition at line 161 of file collision.h.
Referenced by CheckCollision(), and CreateLinkedList().
m_worldSizeX
double Collision::m_worldSizeX private
Definition at line 164 of file collision.h.
Referenced by SetWorldX().
m_worldSizeZ
double Collision::m_worldSizeZ private
Definition at line 165 of file collision.h.
Referenced by SetWorldZ().
The documentation for this class was generated from the following files:
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/collision.h
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/collision.cpp