ICT290 Assignment 1: AABBLinkedList Class Reference
AABBLinkedList Class Reference
Class that defines how the linked list for AABB'S works.
#include <AABBLinkedList.h>
Public Member Functions
AABBLinkedList ()
virtual ~AABBLinkedList ()
void Clear ()
Clears linked list and frees memory.
bool AddToStart (GLdouble maxX, GLdouble minX, GLdouble maxY, GLdouble minY, GLdouble maxZ, GLdouble minZ)
Adds a node to the start of the linked list.
void SetData (const int &ptrCount, const GLdouble maxX, const GLdouble minX, const GLdouble maxY, const GLdouble minY, const GLdouble maxZ, const GLdouble minZ)
Set the values of the node data.
GLdouble GetMaxX (int ptrCount)
Gets Max X of AABB.
GLdouble GetMinX (int ptrCount)
Gets Min X of AABB.
GLdouble GetMaxY (int ptrCount)
Gets Max Y of AABB.
GLdouble GetMinY (int ptrCount)
Gets Min Y of AABB.
GLdouble GetMaxZ (int ptrCount)
Gets Max Z of AABB.
GLdouble GetMinZ (int ptrCount)
Gets Min Z of AABB.
int GetListSize ()
Returns size of AABB list.
AABBNode * GetNext () const
Return the address of the link to the next node in the list.
AABBNode * GetFirst () const
// Return the address of the link to the first node in the list
Private Member Functions
void Delete (AABBNode *before)
Used to Clear Memory.
AABBLinkedList (const AABBLinkedList &ll)
AABBLinkedList & operator= (const AABBLinkedList &ll)
Private Attributes
AABBNode * m_first
pointer to first node in list
Detailed Description
Class that defines how the linked list for AABB'S works.
Author
Group Team No Name 2
Version
Date
14 Sep 20
Definition at line 29 of file AABBLinkedList.h.
Constructor & Destructor Documentation
AABBLinkedList() [1/2]
AABBLinkedList::AABBLinkedList () inline
Definition at line 33 of file AABBLinkedList.h.
 {m_first = new AABBNode;}
References m_first.
~AABBLinkedList()
virtual AABBLinkedList::~AABBLinkedList () inline virtual
Definition at line 35 of file AABBLinkedList.h.
 {Clear();}
References Clear().
AABBLinkedList() [2/2]
AABBLinkedList::AABBLinkedList (const AABBLinkedList & ll) inline private
Definition at line 141 of file AABBLinkedList.h.
 {};
Member Function Documentation
AddToStart()
bool AABBLinkedList::AddToStart (GLdouble maxX, GLdouble minX, GLdouble maxY, GLdouble minY, GLdouble maxZ, GLdouble minZ)
Adds a node to the start of the linked list.
Parameters
maxX - maximum x
minX - minimum x
maxY - maximum y
minY - minimum y
maxZ - maximum z
minZ - minimum z
Returns
bool
Definition at line 36 of file AABBLinkedList.cpp.
 {
     AABBNode *newNode;
     try
     {
         newNode = new AABBNode;
     }
     catch(...)
     {
         return false;
     }
     // add the value to the node
     newNode->SetData(maxX, minX, maxY, minY, maxZ, minZ);
     // set the address of the net node
     newNode->SetNext(m_first->GetNext());
     // reset the address of the first node
     m_first->SetNext(newNode);
     return true;
 }
References AABBNode::GetNext(), m_first, and AABBNode::SetNext().
Clear()
void AABBLinkedList::Clear ()
Clears linked list and frees memory.
Returns
void
Definition at line 13 of file AABBLinkedList.cpp.
 {
     AABBNode *ptr = m_first;
     while (ptr->GetNext() != NULL)
     // clear memory
     Delete(ptr);
 }
References Delete(), AABBNode::GetNext(), and m_first.
Referenced by ~AABBLinkedList().
Delete()
void AABBLinkedList::Delete (AABBNode * before) private
Used to Clear Memory.
Parameters
before - node before one to be deleted
Returns
void
Definition at line 25 of file AABBLinkedList.cpp.
 {
     AABBNode *temp = before->GetNext();
     before->SetNext(temp->GetNext());
     delete temp;
 }
References AABBNode::GetNext(), and AABBNode::SetNext().
Referenced by Clear().
GetFirst()
AABBNode* AABBLinkedList::GetFirst () const inline
// Return the address of the link to the first node in the list
Returns
AABBNode
Definition at line 126 of file AABBLinkedList.h.
 {return m_first;}
References m_first.
GetListSize()
int AABBLinkedList::GetListSize ()
Returns size of AABB list.
Returns
int
Definition at line 172 of file AABBLinkedList.cpp.
 {
     int tmpSize = 0;
     // count size of list
     for (AABBNode *ptr = (m_first); ptr->GetNext() != NULL; ptr = ptr->GetNext())
     {
         tmpSize++;
     }
     return tmpSize;
 }
References AABBNode::GetNext(), and m_first.
GetMaxX()
GLdouble AABBLinkedList::GetMaxX (int ptrCount)
Gets Max X of AABB.
Parameters
ptrCount - Pointer of AABB
Returns
GLdouble
Definition at line 61 of file AABBLinkedList.cpp.
 {
     AABBNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetMaxX();
     else
         return NULL;
 }
References AABBNode::GetNext(), and m_first.
GetMaxY()
GLdouble AABBLinkedList::GetMaxY (int ptrCount)
Gets Max Y of AABB.
Parameters
ptrCount - Pointer of AABB
Returns
GLdouble
Definition at line 92 of file AABBLinkedList.cpp.
 {
     AABBNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetMaxY();
     else
         return NULL;
 }
References AABBNode::GetNext(), and m_first.
GetMaxZ()
GLdouble AABBLinkedList::GetMaxZ (int ptrCount)
Gets Max Z of AABB.
Parameters
ptrCount - Pointer of AABB
Returns
GLdouble
Definition at line 124 of file AABBLinkedList.cpp.
 {
     AABBNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetMaxZ();
     else
         return NULL;
 }
References AABBNode::GetNext(), and m_first.
GetMinX()
GLdouble AABBLinkedList::GetMinX (int ptrCount)
Gets Min X of AABB.
Parameters
ptrCount - Pointer of AABB
Returns
GLdouble
Definition at line 76 of file AABBLinkedList.cpp.
 {
     AABBNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetMinX();
     else
         return NULL;
 }
References AABBNode::GetNext(), and m_first.
GetMinY()
GLdouble AABBLinkedList::GetMinY (int ptrCount)
Gets Min Y of AABB.
Parameters
ptrCount - Pointer of AABB
Returns
GLdouble
Definition at line 108 of file AABBLinkedList.cpp.
 {
     AABBNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetMinY();
     else
         return NULL;
 }
References AABBNode::GetNext(), and m_first.
GetMinZ()
GLdouble AABBLinkedList::GetMinZ (int ptrCount)
Gets Min Z of AABB.
Parameters
ptrCount - Pointer of AABB
Returns
GLdouble
Definition at line 140 of file AABBLinkedList.cpp.
 {
     AABBNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     if (ptr->GetNext() != NULL)
         return ptr->GetNext()->GetMinZ();
     else
         return NULL;
 }
References AABBNode::GetNext(), and m_first.
GetNext()
AABBNode* AABBLinkedList::GetNext () const inline
Return the address of the link to the next node in the list.
Returns
AABBNode
Definition at line 121 of file AABBLinkedList.h.
 {return m_first->GetNext();}
References AABBNode::GetNext(), and m_first.
operator=()
AABBLinkedList& AABBLinkedList::operator= (const AABBLinkedList & ll) inline private
Definition at line 142 of file AABBLinkedList.h.
 {};
SetData()
void AABBLinkedList::SetData (const int & ptrCount, const GLdouble maxX, const GLdouble minX, const GLdouble maxY, const GLdouble minY, const GLdouble maxZ, const GLdouble minZ)
Set the values of the node data.
Parameters
ptrCount - Pointer of AABB
maxX - maximum x
minX - minimum x
maxY - maximum y
minY - minimum y
maxZ - maximum z
minZ - minimum z
Returns
void
Definition at line 156 of file AABBLinkedList.cpp.
 {
     AABBNode *ptr = (m_first);
     for (int count = 0; count < ptrCount; count++)
     {
         ptr = ptr->GetNext();
     }
     ptr->GetNext()->SetData(maxX, minX, maxY, minY, maxZ, minZ);
 }
References AABBNode::GetNext(), and m_first.
Member Data Documentation
m_first
AABBNode* AABBLinkedList::m_first private
pointer to first node in list
Definition at line 132 of file AABBLinkedList.h.
Referenced by AABBLinkedList(), AddToStart(), Clear(), GetFirst(), GetListSize(), GetMaxX(), GetMaxY(), GetMaxZ(), GetMinX(), GetMinY(), GetMinZ(), GetNext(), and SetData().
The documentation for this class was generated from the following files:
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/AABBLinkedList.h
C:/Users/charl/OneDrive - Murdoch University/ICT290/Project/ict290/shayLearyALL/CAMPUS TOUR/AABBLinkedList.cpp